### PR TITLE
Database updates for new Setup implementation

### PR DESCRIPTION
**Pull request by klees**
Hi all (and especially @chfsx),

this is my current state of how the database update steps could look like in the [new implementation of the setup mechanics](https://github.com/ILIAS-eLearning/ILIAS/pull/1868). The final db-update steps do look very similar to the current db_update-files, a version for the tests can be viewed [here](https://github.com/klees/ILIAS/blob/trunk_setup/Services/Database/test/Setup/ilDatabaseUpdateStepsTest.php#L12).

They use the mechanism outlined in PR #1868, but make them more explicit (and easier to use) for the db-update case. The main difference is, that the steps are now wrapped in a class and that the available dependency (currently only `\ilDBInterface` is available!) for the steps is passed explicitly.

The possibility to have steps separated per component (as requested in [Setup Revision 2018](https://docu.ilias.de/goto_docu_wiki_wpage_4900_1357.html)) is implied, but the same mechanism could also be used for global steps. Dependencies of DB-update-steps (i.e. "execute this before that") can be expressed via [`ilDatabaseUpdateSteps::getAdditionalPreconditionsForStep`](https://github.com/klees/ILIAS/blob/trunk_setup/Services/Database/classes/Setup/class.ilDatabaseUpdateSteps.php#L61), but I expect most components to only depend on updates within themselves.

Also note, that this proposal only is supposed to deal with database updates (and not with the various other migrations and requests that are currently performed in the db_update-files). I will probably add an `InformUserObjective` (or something similar) for the things that are currently dealed with via `die`, while more complex migrations could simply be implemented as vanilla `Objective`s.

If this generell form for the updates is liked, I will open a PR to move the current db-updates to the new form.

Meanwhile, please have a look into this, ask questions, express doubts or raise concerns so I have feedback to iterate on this.

Thx!

### CODE REVIEW

**Comment by klees** [comment]
@matthiaskunkel I simply set this on the JF agenda to show publicly that this exists and that I'm looking for feedback.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 23 SEP 2019: Richard asks all developers to have a look at this PR and give feedback to Richard (who is currently working on the setup revision for ILIAS 6).

**Comment by matthiaskunkel** [comment]
Jour Fixe, 07 OCT 2019 : No feedback has been given until today. We understand this as a general agreement on Richard's suggesions and ask him to continue his development activities based on this PR.

**Comment by alex40724** [comment]
As menioned in the last JF I think it would reduce problems, if it is ensured that DB update steps are orderer by "ILIAS version".

**Comment by klees** [comment]
Dear colleagues,

I head a longer discussion with @chfsx about this and think the results are worth being noted here. I think Fabian brought up some concerns that some more of you might have had.

First of all: This proposal works for the current "one sequence of updates" as well as for the proposed ["updates per component"](https://docu.ilias.de/goto_docu_wiki_wpage_5889_1357.html). It just shows how we could encode database update steps for the new setup mechanism. It does not specify how (and if) components use that encoding, although that path is laid out via the [`Agent`s](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/Setup/Agent.php) that where part of [the initial proposal for the new setup mechanism](https://github.com/ILIAS-eLearning/ILIAS/pull/1868).

Second: This only shows how _updates_ will be encoded. There certainly is more stuff that currently is done in the db_update files: reloading the control structure, prompting admins with warnings, creating stuff for objects, moving files, ... @nhaagen already started to create [`Objective`s](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/Setup/Objective.php) for these purposes ([1](https://github.com/ILIAS-eLearning/ILIAS/pull/2187)) and we will provide more. But: We do not aim to provide the same freedom (basically: do everything) that the current db_update files provide.

Third: I certainly won't surprisingly replace the current db_update files one morning. Our (@nhaagen, mine) tactic currently is, to first move the current db_update files to the new format defined here and make sure the updates run. We kind of managed this on the CLI for updating 5.2 to trunk. "kind of" because we are fighting with lots and lots of hidden dependencies in the code that runs via the "db_update". We are looking to organize them more than it is currently the case. We will show this via PR so you have time to object. When this is done we will get back to the "updates for components"-thing.

Some random notes:
* The tracking of update steps that have run basically will work the same as in the current setup: store a number in the db. Most probably, different sequences of steps will be identified via their classname in the future if we allow components to have their own update steps. Renaming classes then will therefore be just as problematic as changing code in db update steps currently is.
* Maybe we could use some hash over classnames and methods to track which steps have been run.
* We (@chfsx, me) both considered the possibility to tag steps for versions (as @alex40724 suggests) a good idea.

If there are any further questions, feel free to ask them, even if this PR is merged. As mentioned, there also will be more PRs regarding the setup, which should give more opportunities to intervene.

@chfsx Feel free to correct or add stuff if I got anything wrong or anything is missing.

Best regards
@klees

**Comment by klees** [comment]
@chfsx I'll merge this, ok?

**Review by chfsx — APPROVED** [review]
@klees for me it's fine, thanks!

**Pull request merged**
