### PR TITLE
T&A: Fixes 0041214: Error message for malicious svg in File Upload Question

### PR DESCRIPTION
**Pull request by malaja11**
@thojou and @mbecker-databay will take care of this

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @malaja11, have you seen the message from @chfsx: https://mantis.ilias.de/view.php?id=37588#c104107 ? The Problem is that users right now get a whoops error message. 



2024-04-30-ixwb_Screenshot-


On normal installations, they need to ask an administrator, what the error message says if they upload such a SVG. This is fixed for the file upload with the new language variables: language variables upload_svg_rejection_message, upload_svg_rejection_message_base64, upload_svg_rejection_message_elements, upload_svg_rejection_message_script - 
I wish that you implement an error message box, which shows the correct error message with one of the new variables for the user. 

Thanks! 

CC @thojou ;)

**Comment by thojou** [comment]
Hey @dsstrassner, appreciate your feedback. I believe @malaja11's changes have already partly implemented the desired behavior. As you can see in the screenshot, a user-friendly message box is now displayed during a test pass.

image

From my debugging, I've found another scenario where the same exception occurs, specifically when uploading a malicious SVG file during question preview. I'll coordinate with @malaja11 to address these other instances where this exception isn't yet caught.

**Comment by dsstrassner** [comment]
My screenshot is from the question pool test preview of a file upload question. Sorry, that I did not test it in a test after this first whoops occurrence.

**Comment by malaja11** [comment]
Hey @dsstrassner, the implemented error message is now also shown in the question preview. I hope that all cases in which the exception is thrown are now covered.

CC @thojou

**Comment by dsstrassner** [comment]
> Hey @dsstrassner, the implemented error message is now also shown in the question preview. I hope that all cases in which the exception is thrown are now covered.
> 
> CC @thojou

Hi @malaja11 
I tested this today on a local ILIAS 9 installation. Now test and preview looks fine. Thank you for your patience and quick response!

If the code authorities are ok with the code, these PRs appear to be ready to merge ;-)

**Review by thojou — APPROVED** [review]
Hey @malaja11, your changes look good to me! 

You've also submitted pull requests for release_8 (#7441) and release_9 (#7443). The changes in release_9 (#7443) match those in this pull request, so we only need to merge either this branch (#7444) or (#7443), and then cherry-pick the changes to the other. 

The pull request for release_8 (#7441) also includes the missing validation, so it should be merged separately.

@mbecker-databay, @kergomard, could you please take a look and proceed with the merging? Thanks, @malaja11!

**Comment by mbecker-databay** [comment]
There are three tests failing on the added punctuation, when you put these back to work, I'll happily take this all in :)

**Comment by chfsx** [comment]
why are there any changes at all in the file `components/ILIAS/FileUpload/src/Processor/SVGBlacklistPreProcessor.php`.

for example, i see a typo, of course, but why the change in the punctuation? and... since `ILIAS/FileUpload` is now also affected by the PR, i would be happy if i were at least included as a reviewer?

just to clarify, the last question was directed at @mbecker-databay  or @thojou, who actually know this, nothing that @malaja11  should have known.  just so you're not confused :-)

**Comment by malaja11** [comment]
Hi @chfsx and @mbecker-databay,
I outsourced the changements in ILIAS/FileUpload into a new PR: https://github.com/ILIAS-eLearning/ILIAS/pull/7649,
so that this one can be merged and we can discuss about the punctuation in the seperate PR :)

**Pull request merged**
