### PR TITLE
Refactoring in Skill Service

### PR DESCRIPTION
**Pull request by tfamula**
Within the project "Continuous Refactoring Initiative“ there have been made improvements in the Skill Service. Mostly, the refactoring was made for classes within the `Personal` and `Profile` directory of the Skill Service. The changes include especially:

- using strict_types declaration (already done in https://github.com/ILIAS-eLearning/ILIAS/commit/230975de4f9d9ff79b4343a51ba4076ae51d5bce)
- avoiding static methods by using a service structure via DIC
- separating classes in repositories, DTOs, manager classes and gui classes
- replacing arrays with DTOs incl. factories
- unit tests for DTOs and factory service

### CODE REVIEW

**Comment by tfamula** [comment]
Hi @alex40724, @maxbecker, @mstuder,
in the context of the refactoring, I had to make some changes in the code of your components. There are no functional changes. In most cases, I just had to match the way how methods are called or the way how arrays are accessed. In some other cases, only renaming was done.
I would appreciate it if you could have a look at these few lines of your code and give me a green check mark if everything is fine for you. 
Thanks!

**Comment by kergomard** [comment]
Thank you very much for the improvements @tfamula .
Please bear with us: We will look at the changes in the code of the T&A once the big ILIAS 8 rush is over.

**Comment by oliversamoila** [comment]
Many thanks to you, @tfamula
I really didn't expect it so soon. ;)
I will make sure that we also get a review for the refactorings and corresponding feedback.

**Review by alex40724 — APPROVED** [review]
Thanks for reducing static calls and array use. I approve the changes for Container, COPage, Portfolio and Survey.

**Comment by tfamula** [comment]
Hi @kergomard 
thanks for the feedback. Of course I understand that the priority for T&A is somewhere else now.
I would like to go on with some developments in the Skill Management and would like to avoid that a lot of merge conflicts come up during the time. That's why I would like to merge this PR very soon. As already said in my previous comment, the very few changes in T&A are actually trivial (replacing static calls, replacing array usage, renaming).
I would like to merge the PR in the middle of next week. I would propose that if there will be any objections afterwards, you can of course come up to me.

**Comment by kergomard** [comment]
Hi @tfamula 
I would kindly ask you to not merge pull requests without the necessary approval. I would have looked at it today, as I felt it was important for you, but please give us the time we need to make a decision. If it was absolutely necessary to merge by Wednesday you could also have contacted me through discord or mail, to speed things up. Additionally, you could also propose a way to move the code fully into your responsibility, as it might not be in the right place right now. Thanks!
@kergomard

**Pull request merged**
