### PR TITLE
Proposal/9/zip unzip replacement

### PR DESCRIPTION
**Pull request by chfsx**
This is a part of #5172 and replaces the current implementations of zip/unzip in ilFileUtils

### CODE REVIEW

**Comment by alex40724** [comment]
@chfsx Looks great. Could you add some example consumer code in a readme?

**Comment by chfsx** [comment]
@alex40724 I am working on a general readme on how to work with files. I will also talk about ZIP, but I will tell you that you should not use it anymore. To create a ZIP, you don't need a directory in the file system that you can zip. You can do that all in memory and you don't need expensive copying processes and possible relicts in the file system. The documentation will therefore rather be: "Don't use it" together with a documentation how to make ZIPs in the future.

I have changed the PR a little bit, now there is also a UnitTest for Legacy-ZIP included

**Comment by chfsx** [comment]
@Amstutz I has to skin the following test in your component: https://github.com/ILIAS-eLearning/ILIAS/pull/5181/files#diff-3779baed56463a02084554a9828aa824093d505ecae2fe702eb2d3e7d45075adR122
With the changes Zipping/Unzipping is only possible in directories known to the `LegacyPathHelper`, there are Directories which can have User-Inputs. Your test tries zu Zip inside the ILIAS Code base which is now no longer possible for security reasons.

**Comment by Amstutz** [comment]
Hi @chfsx 

De-activating this test is fine for me, should be improved anyway. However, can you anticipate if this has side effects on the importing (genarating a zip ou of files of the customizing dir)/exporting (unpacking a skin from and moving files to the customizing dir) of skins?

thx for the work! highly appreciated.

**Comment by chfsx** [comment]
@Amstutz Customizing is one of the "allowed" directories, therefore this should work. i will test it an monday

**Comment by matthiaskunkel** [comment]
Jour Fixe, 06 MAR 2023 : We highly appreciate this suggestion - especially the how-to - and accept the PR for trunk.

**Pull request merged**
