### PR TITLE
fixed 24947: Deck of Card: IE11 Issue

### PR DESCRIPTION
**Pull request by alex40724**
https://mantis.ilias.de/view.php?id=24947

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM, thx @alex40724. I assume this leaves the rendering in other browsers intact, correct?

**Comment by alex40724** [comment]
@klees  I tested a similar screen to https://test54.ilias.de/goto.php?target=cat_53205&client_id=test54 on current Safari, Edge, Opera, Firefox and Chrome. Everything has been rendered ok.

**Comment by Amstutz** [comment]
Thx a lot for your fix!

**Comment by Amstutz** [comment]
promoted to trunk as well.

**Pull request merged**
