### PR TITLE
Add info messages for favourites and membership settings

### PR DESCRIPTION
**Pull request by iszmais**
This PR adds an message box to the dashboard settings if the specific setting of favourites or memberships are unfavorable for the dashboard.
https://mantis.ilias.de/view.php?id=32014

### CODE REVIEW

**Comment by iszmais** [comment]
This is still draft due to the fact that the affected settings are still missing.

@matthiaskunkel I would aprreciate if you may take a look at the translations if they fit your expectations. After your approval i will provide commits for ILIAS7 and trunk.

@alex40724 thx for the contribution of the setting `rep_favourites` . As far as i can see contrary to the depending Ticket Version this wasnt added to ILIAS6? Is this on purpose or just missing.

@smeyer-ilias I couldnt find the setting for the memberships atm. Could you provide this infomation for me?
If this is still WIP i would recommend calling the setting `rep_memberships` to match the given pattern of the already existing setting. Feel free to tell me if you disagree on that so i can change it inside this commit.

**Review by alex40724 — APPROVED** [review]

**Comment by iszmais** [comment]
@smeyer-ilias :bell:

**Comment by kergomard** [comment]
Hi @smeyer-ilias  

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the resources to look into it in detail.

Best regards!

**Comment by iszmais** [comment]
@smeyer-ilias 
Just a kindly reminder that this is still a part of a resolvement of a **prio 6 Ticket** that still awaits your feedback  or participation in any way.

**Review by lscharmer — APPROVED** [review]

**Pull request merged**
