### PR TITLE
orgu: #28535 add an activatable permission check for collection of or…

### PR DESCRIPTION
**Pull request by shecken**
…g units

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@mstuder  We stumbled upon this old PR in our TB meeting. Do you have any objections to merge this?

**Comment by chfsx** [comment]
Hi @mstuder 

this came up again in our last TB meeting on the 06-04-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by chfsx** [comment]
Hi @mstuder

this came up again in our last TB meeting on the 06-04-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by Amstutz** [comment]
Hi @mstuder

this came up again in our last TB meeting on the 10-08-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process? As far as we understand your current position, you will take care of your components, until another maintainer will be found.

Best regards!

**Comment by chfsx** [comment]
Hi @mstuder 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by mstuder** [comment]
thank you - I will merge this in the other branches to, this week!

**Pull request merged**
