### PR TITLE
Docs: Emphasize secure defaults in install.md

### PR DESCRIPTION
**Pull request by corro**
Emphasize some secure defaults:
* Enable mod_rewrite (required for WAC to work)
* Disable directory listing for ILIAS web root

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Thx @corro !

**Review by alex40724 — APPROVED** [review]
Thx!

**Comment by kergomard** [comment]
It might be good to emphasize this even more in the future, but this is a good first step to clarify the situation. Thx @corro !

**Review by mjansenDatabay — APPROVED** [review]

**Comment by alex40724** [comment]
Since three TB members have given an ok, I merged this.

**Pull request merged**
