### PR TITLE
Test export plugins cause error during ILIAS setup (42070)

### PR DESCRIPTION
**Pull request by fneumann**
Edit by @dsstrassner: Issue Link is https://mantis.ilias.de/view.php?id=42070

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @fneumann .
Ok, this actually is understandable even if I hate that we have to do this ;-) . As this is a bug-fix:
- Could you please link the corresponding mantis issue in the comment @fneumann (or create one, if there is none yet), so that we have a clean traceability. I will then take care of merging this.

Thanks again and best,
@kergomard

**Comment by dsstrassner** [comment]
Do we need the second review from @mbecker-databay because of some internal  Databay agreements? If not, please proceed @kergomard …

**Comment by kergomard** [comment]
Thank you very much for the  information @dsstrassner ! I will merge this, to have it off my plate. I don't see much of a reason not to.
Thanks again @fneumann for the PR.

**Comment by thojou** [comment]
Hey @dsstrassner,

I also looked into this and discussed the issue with @mjansenDatabay. As @kergomard mentioned, it seems there is no better solution available at this point. Thanks for merging.

**Pull request merged**
