### PR TITLE
Set return-type to what was mentioned in the original comment.

### PR DESCRIPTION
**Pull request by pascalseeland**
The original comment states that this function returns a bool. This PR makes setup work again.

### CODE REVIEW

**Comment by klees** [comment]
It's more contrived than that, I fear. This might return an array of errors:

```php
public function installLanguages(array $a_lang_keys, array $a_local_keys) : array
{
    // [...]

    $err_lang = array();

    // [...]

    return ($err_lang) ? $err_lang : true;
}
```

**Comment by pascalseeland** [comment]
Thanks for pointing it out. After having a second look at the code( it is as far as I can tell only called in ilLanguagesUpdatedObjective and ilLanguagesInstalledAndUpdatedObjective), I think there is no need to return anything from this function and in case of an error throw a RuntimeException. Even if there would be a failure, the Objective would still be achieved, as it never tested, if it failed.

I can provide an updated PR for this, if we agree on this way to solve the issue.

**Comment by klees** [comment]
> I can provide an updated PR for this, if we agree on this way to solve the issue.

This would be up to the maintainer of the service (@katringross) to decide. To me this sounds fine.

Best regards!

**Comment by katringross** [comment]
Hi @pascalseeland and @klees,

Thanks for following up this issue! @pascalseeland for me your suggestion makes sense too. Would be great If you provide a PR. 

Thanks Katrin

**Comment by katringross** [comment]
@pascalseeland und @klees for fixing https://mantis.ilias.de/view.php?id=31763#c77166 I merged this PR. As second step we will remove the return for the function.

**Pull request merged**
