### PR TITLE
UI, Form: 25041, unit tests

### PR DESCRIPTION
**Pull request by nhaagen**
unit tests for https://github.com/ILIAS-eLearning/ILIAS/pull/5255

### CODE REVIEW

**Comment by klees** [comment]
@Amstutz or @thibsy, would you please have another look here? Thanks!

**Comment by thibsy** [comment]
Hi @nhaagen

Thx a lot for adding the required testing to this PR. Also thx for your help in resolving the underlying issue.

While reviewing we stumbled upon the following two things:

Please change:
- [ ] Naming: Change `Form::getRequired()` to `Form::hasRequiredInputs()`. This works better on the form itself and is more concise in our opinion.

Question:
- [ ] Example: If possible, could you also provide an example of a form with at least one required field on the form example level. This PR is for ILIAS 7, but an example is not adding any risk to the productive release. Required is always a critical point for a11y conformance, therefore, it would be very useful to have such an example for easy testing (e.g. via testrail)?

Kind regards,
@thibsy and @amstutz

**Comment by nhaagen** [comment]
Screenshot from 2023-03-01 13-38-20

**Comment by thibsy** [comment]
Hi @nhaagen

Thanks for implementing the change and providing an example!

There are still a few tiny things, please change:

- [ ] Example: The UI examples should not contain the ILIAS license header, otherwise the documentation which is displayed in ILIAS will get rather crowded if there are several examples for one component.
- [ ] Comment: Please provide a brief comment above the example-function to explain what the example illustrates.
- [ ] Naming: Since you are adjusting the file anyways, we would also prefer it if the example had a more concise naming as well, like e.g. `form_with_required_input()` instead of just `required()`.

Afterwards this is good to merge.

Kind regards,
@thibsy and @Amstutz

**Comment by Amstutz** [comment]
Thx a  lot!

**Pull request merged**
