### PR TITLE
Fix/8/setup installation

### PR DESCRIPTION
**Pull request by chfsx**
There were several problem which made the installation of trunk fail.
@smeyer-ilias not sure if this is a feasible solution to have ilDBInterface injectable to ilTree

@mstuder or @d3r1w please have a look at the installation of employee-talks

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Related https://mantis.ilias.de/view.php?id=33382

**Comment by chfsx** [comment]
This is related to #4807

**Comment by chfsx** [comment]
Resolved conflicts in ilTree

**Comment by chfsx** [comment]
Since this is really a blocker (Setup not possible), @mstuder and @smeyer-ilias your soon feedback is needed, thanks a lot!

**Review by smeyer-ilias — APPROVED** [review]
Yes, LGTM. 
Regarding the dependency injection, I do not have a better solution in the moment.

**Comment by chfsx** [comment]
@smeyer-ilias thanks for your feedback!

I suggest to merge the PR on friday if there is no feedback from either @mstuder or @d3r1w, any objections?

**Comment by chfsx** [comment]
Since we have a release_8 branch since last friday, a Fix must be deployed wo release_8 AND trunk

**Comment by mstuder** [comment]
Hi @chfsx 

thank you for your proposal! I merged the suggestion of [daniwe4] - but I do not have any objections to your solution. If you like to merge it go on.

**Comment by chfsx** [comment]
@mstuder and @smeyer-ilias I will open a new PR since I think there are still some things wrong:
- Adding a new Admin-Node should not be done using a query but should use a ilTreeAdminNodeAddedObjective
- ilTree needs an option to inject a ilDBInterface-Instance
- we should get rid of these huge `ATTENTION: This is a total abomination. ....` dependency "mocking"
- ActiveRecord::updateDB() MUST not be used in core

**Pull request closed without merging**
