### PR TITLE
Remove permanent link input field of footer ILIAS8

### PR DESCRIPTION
**Pull request by lscharmer**
~Sister PR to #4811 for ILIAS8~
Sister PR to #5610 for ILIAS8

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @lscharmer 

I assign this back to you for the moment. I had a chat with Oliver on this. We are not yet sure, if we will merge this into the open beta. I asked Oliver to look into this, he will do after his vaccation.

Thx

**Comment by lscharmer** [comment]
After a discussion with Oliver and Michael we will add an API to show toast via JS (without a server interaction) and then to adjust this PR so a toast will be shown which informs the user that the link was copied to the clipboard.

This is the PR which provides the JS API: #5012

**Comment by lscharmer** [comment]
Update: This PR will probably be closed in the near future, because it will either **not** be implemented in ILIAS 8 or it will use another approach (this one: https://github.com/ILIAS-eLearning/ILIAS/pull/5301)

**Comment by klees** [comment]
Hi @lscharmer,

thanks a bunch!

Best wishes!

**Pull request merged**
