### PR TITLE
Fix typo in tpl.standard.html

### PR DESCRIPTION
**Pull request by Hadrian-II**
Fix typo in form enctype

### CODE REVIEW

**Comment by klees** [comment]
Hi @Hadrian-II,

thx for taking care of this. Please change the tests accordingly.

Best regards!

**Review by Amstutz — APPROVED** [review]
Thx a lot!

**Review by klees — CHANGES_REQUESTED** [review]
@Hadrian-II Please have a look at the tests again. You have missed one location.

Thanks!

**Comment by Hadrian-II** [comment]
Ok, now it passes. Note to self, there is nothing as just fixing a small typo :)

**Comment by klees** [comment]
Also picked to release_6.

Thanks @Hadrian-II!

**Pull request merged**
