### PR TITLE
[HUN] TinyMCE hun files and 4 modifications

### PR DESCRIPTION
**Pull request by KissDaniGH**

### CODE REVIEW

**Comment by chfsx** [comment]
@matthiaskunkel could you merge this since it's a language-PR. there are small changes needed in PHP-files, they seem to be ok. maybe crosscheck with alex since Tiny is in one of his components.

**Comment by matthiaskunkel** [comment]
It is a language related PR. But it affects a component that is not under my maintenance. I think it should be merged by a developer that knows more about the TinyMCE than me.

**Comment by alex40724** [comment]
If the translation will be maintained for future tiny versions, too, this is ok for me. I think we should ask Michael, too, since he takes care of the image upload plugin/patch.

**Comment by KissDaniGH** [comment]
official tinymce lang files are downloadable from tinymce.com, and I'll do the rest (creating, modifying ilias-specific files, testing, pulling). So no more need to do in the future versions than check & merge.

**Comment by mjansenDatabay** [comment]
This PR does not affect existing German or English translations, so this is OK for me.

**Pull request merged**
