### PR TITLE
#17215 - forum notification bug for forums inside of groups

### PR DESCRIPTION
**Pull request by gcomte**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Please check http://www.ilias.de/mantis/view.php?id=16840 before merging this pull request.

In my opinion the group object has to add participants by using ilParticipant or ilParticipants.

**Comment by smeyer-ilias** [comment]
Yes, and furthermore modules shouldn't call listeners directly. Instead raiseEvent for group should be called.

**Comment by smeyer-ilias** [comment]
I will push a fix for http://www.ilias.de/mantis/view.php?id=16840

**Comment by smeyer-ilias** [comment]
Anyway thanks for the pull request!

**Comment by gcomte** [comment]
Okay thank you for your feedback and the fixing. I will consider your points the next time.

**Pull request closed without merging**
