### PR TITLE
Cleanup of Services/Component

### PR DESCRIPTION
**Pull request by klees**
Hi everyone,

I made some more progress in cleaning up Services/Component. Besides some minor removals, I mostly moved code to locations that are more appropriate imo:

* I introduced an `ilPluginLanguage` in `Services/Language` that takes care about handling language variables. The class is now called from `ilPlugin` instead of having code that is language related almost exclusively in `ilPlugin`.
* I move `_getImagePath` from `ilPlugin` to `ilRepositoryObjectPlugin`, since the method is only used in the context of Repository Plugins.
* `ilClaimingPermissionHelper` is now located in Services/AccessControl, as it contains functionality more related to access control instead of plugins.

Also, i removed some stuff that is not required anymore:

* `ilPlugin::includeClass` and code that depends on it, since plugin classes are part of the classmap as of ILIAS 7. In this process, I removed methods that depended on that code.
* the tables `service_class` and `module_class` and code that fills these, since UICore (that was the exclusive user of that tables) is now artifact based as well.

I consider these changes to be of general interest, but I specifically like to get approval from the following maintainers:

* @katringross for the introduction of `ilPluginLanguage` in `Services/Language`
* @alex40724 for the move of the `_getImagePath` to `Services/Repository`
* @smeyer-ilias for the move of `ilClaimingPermissionHelper` to `Services/AccessControl`
* @thibsy because I used his UICore-DB-updates to finally remove the tables `service_class` and `module_class`. Also: we really don't need these anymore, right?

If there are any questions or concerns, feel free to ask or voice, as always.

Also, this fixes [#31905](https://mantis.ilias.de/view.php?id=31905).

Thanks for your cooperation!

### CODE REVIEW

**Review by thibsy — APPROVED** [review]
@klees the tables `service_class` and `module_class` class are not used by the UICore anymore. I did not remove them back then because I thought they were still being used in the component service somewhere =). LGTM!

**Review by katringross — APPROVED** [review]

**Comment by PurHur** [comment]
Will the autoloader with the classmap be updated if i install a plugin via the GUI instead of the setup tool, which builds the artifacts? Is it now possible to remove all the requires/includes at the current time?  

This is possible in ilias7 i dont know if ilias8 removed the plugin GUI

**Comment by klees** [comment]
@PurHur: No, the classmap and the artifacts will only be updated on the CLI. This is already the case with ILIAS 7, where some features (such as integration of plugins with the [new setup mechanism](https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/src/Setup/README.md)) will not work if the classmap is not updated.

With ILIAS  8, the information about the plugins themselves will [become part of an artifact](https://github.com/ILIAS-eLearning/ILIAS/pull/3778), so calling `composer install` (or `setup.php build-artifacts`) will become strictly mandatory after a plugin was added or removed from ILIAS.

I won't touch the install process for plugins on the GUI now (i.e. for ILIAS 8), but I'm certainly thinking about it. I will present my plans for `Services/Component` on the next Project Jour Fixe (sry, I do not have any documentation about that special JF that I could link) on the 21st Feb. Feel free to join, @mjansenDatabay could give more information about the how and when.

**Comment by PurHur** [comment]
If the GUI is not removed and classes arent included anymore there will be errors if someone installs a plugin via this way and probably the whole installation will be not accessible anymore, and you will have todo a manual composer install after that. Looks dangerous for me.

**Comment by klees** [comment]
@PurHur Could you elaborate a little? Gerne auch auf deutsch, falls das schneller geht =)

**Comment by PurHur** [comment]
Hallo Richard,

wenn du Lust und Zeit hast können wir gerne über meine Anmerkungen und Bedenken morgen (oder später) mal telefonieren. Es geht auch um den neuen PR von mir der diese Probleme hier lösen soll.

Viele Grüße
Andre

**Comment by klees** [comment]
@PurHur Würde 15:00 bei dir passen? Spricht für dich was dagegen, wenn wir @mjansenDatabay oder Oliver dazu bitten? Schick mir gerne eine Einladung.

**Comment by PurHur** [comment]
Ja das passt. Ich hole morgen am besten beide dazu wenn ich sie erreichen kann :) Top danke!
Die kennen dann auch deine E-Mail und schreiben dich an!

**Review by smeyer-ilias — APPROVED** [review]
Moving "ilClaimingPermissionHelper" to AccessControl is fine for me, thanks.

**Comment by klees** [comment]
@smeyer-ilias Thx!

**Review by alex40724 — APPROVED** [review]

**Pull request merged**
