### PR TITLE
Auth: Improve login attempts handling

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=37022

Will hoepfully also fix https://mantis.ilias.de/view.php?id=33773

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland ,

a detailed/profound review and feedback would be appreciated here.

Best regards,
Michael

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland,

a review is still highly appreciated.

Best regards,
Michael

**Comment by mjansenDatabay** [comment]
@chfsx Maybe you would like to have a look at the change in `ilAuthFrontendHTTP`, which is only used in the `WebDav` context.

**Review by chfsx — APPROVED** [review]
Thanks, the changes in `ilAuthFrontendHTTP` look good to me

**Comment by mjansenDatabay** [comment]
I'll merge this for `trunk` and pick this to ILIAS 10.

**Pull request merged**
