### PR TITLE
UI: fix Tooltip/CoreJS to find visible main element

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=39562

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @nhaagen 

This is almost impossible to review, due to all the whitespace changes. Can you directly push the whitespace changes, if according to guidelines, and only provide the changes here? 

This would make the changes much less difficult to spot. Thx.

Lg

**Comment by Amstutz** [comment]
Learned something new today:

image


Still, there are many unrelated changes. please ship them seperately.

**Comment by nhaagen** [comment]
Hi @Amstutz ,
I split up the changes into two commits, this is the actual change: https://github.com/ILIAS-eLearning/ILIAS/pull/6817/commits/21b2da05b2097b16bf0d380798e0f21e546b8db1

**Comment by Amstutz** [comment]
Thx lot, very helpful.

I understand the array cast. However, why did you replace: element.hasOwnProperty('hidden') ? What was wrong with that. The current solution looks a bit heavy handed...

Otherwise it is good to go.

thx.

**Comment by nhaagen** [comment]
Again, the linter forbade ;(
There is a [no-prototype-builtins - rule](https://eslint.org/docs/latest/rules/no-prototype-builtins) in eslint, apparently because considering all objects _really being_ prototypes is unreliable; also, the method might be injected/overwritten, e.g. by a JSON object.

**Pull request merged**
