### PR TITLE
remove old class stub - > fixing a classname collision

### PR DESCRIPTION
**Pull request by colin-kiegel**
pretty sure this is not in use.

if still needed please revert + rename class to ilSCORM2004SeqRule (instead of ..Template)

(one step closer to autoloading..)

### CODE REVIEW

**Comment by colin-kiegel** [comment]
@Uwe-Kohnle could you please have a look at this?

**Comment by chfsx** [comment]
@Uwe-Kohnle can you have a look at it and then merge the pull request? thanks a lot...

**Comment by matthiaskunkel** [comment]
Jour Fixe, August 15, 2016: Please contact Uwe Kohnle to discuss if this class can be removed. @Uwe: please have a look at this PR. We keep the PR open.

**Comment by klees** [comment]
This is not mergeable due to https://github.com/ILIAS-eLearning/ILIAS/commit/f06647ea95c12729e320ea31cc67442eae157b42 where the constructors were changed to newstyle constructors. So still seems to be a no brainer.

**Comment by Uwe-Kohnle** [comment]
Thanks

**Pull request closed without merging**
