### PR TITLE
Markdown clean-up

### PR DESCRIPTION
**Pull request by bogenschlag**
Did some Markdown clean-up in the template readme. Take it or leave it. 😉

### CODE REVIEW

**Comment by legionth** [comment]
I like it 👍 
Maybe a reference to https://tools.ietf.org/html/rfc2119 for the Keywords **must**, **should** etc. you use in this cleanup?

PSR has pretty good line in their descriptions (copied from [PSR-7](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md)):
```
The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.
```
What do you think?

**Comment by bogenschlag** [comment]
I didn’t have RFC compliance in mind when I cleaned this up. I just thought "Why the shouting?" … ¯\_(ツ)_/¯ 

But if there is a good reason for the shouting, we might keep it.

**Comment by klees** [comment]
Thx @bogenschlag. One but: Please use a line wrap after around 80 chars per line to improve readability.

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @bogenschlag 

First of all, thanks a lot for your improvements! Love to see people maintaining those docs.

Ill merge this and promote your changes also to trunk as soon as 
- [ ] the PSR keywords are changed back and 
- [ ] the 80 char line limit is kept. 

If you do not find to it, leave some remark and ill take care of it. 

Greetings and have a nice day

**Comment by bogenschlag** [comment]
Hey guys.

Thanks for the feedback. I have a "but", too, though:

I admit I have a real problem with hard-wrapping running (plain) text ("Fließtext"). IMHO that’s an absolute "no-go". And I don’t see how that improves readability (or anything) at all. (I concede that it might make sense for code maybe.) 

Also I explicitly "unwrapped" it because AFAIR it wasn’t even wrapped consequently either.

IMHO dynamic wrapping is the text editor’s/editor window’s job. And with a hard wrap you get ugly  "double-wraps" with narrower windows etc. that actually hinder readability. Apart from that it makes editing/revising a, well, pain in the lower back … 😉

2018-01-31 at 11 29

`¯\_(ツ)_/¯ `

**Comment by legionth** [comment]
In general: The 80 characters rule is pretty common rule through many projects. Wrapping may be the editors job, but not everybody uses an editor that understands Markdown and not everybody uses a big screen to develop or administrate the system. Even some editors don't break big lines. That is why this rule exists, so you don't limit your audience.

To be fair, I didn't found anything about the formatting and method of working with these documentation either. We really **should** write some rules down for documentation, with further explanation.

**Comment by Amstutz** [comment]
@legionth : Thanks for the feedback. 

I personally work with PHPStorms (as probably many others do). Any suggestions on how to achieve this with PHPStorms?

> We really should write some rules down for documentation, with further explanation.

+1. Any suggestions? I would be happy to adjust the corresponding docs guideline: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/documentation/docs-guidelines.md. However, I am personally lacking the expertise on this ;-)

**Comment by bogenschlag** [comment]
@legionth Hard-wrapping _text_ at 80 character might have been common in 1998 (and indeed back then I probably would have proposed somethings like that myself), but in 2018 it IMHO no longer is – and probably hasn’t been for years. Such rules stem from a time where display and terminal sized had dramatically less variety. Today such a mandatory hard-wrap does much more _for_ limiting your audience than against it.

Again, different rules quite probably make sense for code, but as someone who has been heavily _working_ with Markdown-formated plain _text_ for years I stand by my assessment that hard-wrapping that is not a good idea.

I’m willing to be convinced otherwise by arguments, but so far I haven’t heard a good one. 😌

**Comment by legionth** [comment]
@Amstutz Ah! There are documents about this thank you, I didn't found them:+1:. I think I will open several PRs the next couple of days with a few improvement suggestions to keep focus on this PR.

**Comment by klees** [comment]
@bogenschlag The 80 char length isn't implied by technical devices, but by readability considerations for text. Rules for code are derived from there. There are of course tools that insert line wraps on their own (your text editor) but there are many many tools that don't (this very webtool here, `more`, our browsers, ...).

**Comment by bogenschlag** [comment]
@klees Even `more` and `less` do some wrapping by default – but I admit that their default wrapping by characters instead of whole words is less than ideal for text.

GitHub and browsers, no, sorry – simply not true:

bildschirmfoto 2018-02-01 um 14 50 11

bildschirmfoto 2018-02-01 um 14 50 23

But, ok – if this really is consensus, have it your way. I’m going to amend the pull request.

I still feel that the 80 character default is arbitrary (why not 72 or 64 …?) and no longer appropriate. And again, actual _editing_ of hard-wrapped text is an IMHO _unnecessary_ pain in the, well, your know … 😌

**Comment by Amstutz** [comment]
To be honest, I never gave this much thought up to this point and my whole experience is from my tool chain alone (in which I the current solution works fine). However, bad to see other people struggling in using docs we worked quite hard for. Since I do not feel in the position to make a decision here, I put this on the JF to decide upon.

Question to JF: Do we want to apply the 80 char linebreak rule also for markdown files?

@bogenschlag: 

> Not sure this’ll motivate me a whole lot to do more work on ILIAS’ Markdown documentation in the future, though. 

That is kind of taking a gun to a fist fight, don't you think? This project needs every contributor there is, especially for markdown docs. We can not lose anybody. So let's give this a chance. As always, we will strife to find a solution that works as good as possible for as many as possible.

**Comment by bogenschlag** [comment]
It wasn’t meant as any kind of gun. But I’ve removed the remark for my comment. It was unnecessary, sorry.

**Comment by klees** [comment]
Hi @bogenschlag!

What I meant is this: how can I tell my browser to wrap lines after ~80 chars? How can I tell `more` to do so? How can I tell GitHub to do so? There are indeed tools that take line breaks we put in plain text files seriously. What you are showing there as GitHub-image isn't what I meant though, this already is a rendered version of the markdown. Click on `Files` in the PR to see what I was referring to. Your browser image imo is a good example for bad readability (rendered version not much better), which would be improved by some earlier line breaks. (Yes, I read docu in plain text formats and environments.)

We still don't need to turn this into a religious fight, so we might as well take any decision, because I also see the "No-Line-Wrapping"-party has its arguments. There even might be some tooling that does the formatting for us (there should be?). The 80 is of course arbitrary, could be 77 as well, but the general magnitude is supported by common layouter knowledge and some research as well (AFAIK).

Please keep contributing documentation and other stuff, even if there are pigheads like me that never refrain from a good argument.

Best regards!

**Comment by bogenschlag** [comment]
@klees It seems to me in the end neither one of us is going to convince the other. 😉 Of course what constitutes "good readability" will ultimately remain at least partly subjective. I _can_ see the point of the "pro-wrapping" argument of "command-line readability", but I also see the merits of "un-wrapped flexibility" both for reading and editing, ie. letting each user decide for her-/himself.

Therein lies ~~the~~ my answer to your question: I'd say you tell your browser to wrap the lines shorter/improve readability by simply resizing the window and/or making the text bigger (ctrl/cmd +) so that it suits your personal preferences. Also many dedicated Markdown editors will – by default – soft-wrap the lines even shorter, by the way. Both iA Writer and Ulysses at 64 for example. But this is also device-dependent. Try editing hard-wrapped text on a mobile device … (Yes, I sometimes do that – editors like iA Writer built around cloud-synced libraries actually make it quite feasible. 🙂)

But I’m all for letting this matter rest now. It surely is not _that_ important. And I do apologize for my on pigheadedness in these matters. I guess not only developers can have strong opinions about their tools and conventions … 😌

**Comment by matthiaskunkel** [comment]
Jour Fixe, 05 FEB 2018: We want to keep 80 character wide textes in README files for better readabilty in some editors. We will add this as a SHOULD rule to prevent further misunderstandings.

**Comment by Amstutz** [comment]
I adapted the according Readme to follow the JF decision: https://github.com/ILIAS-eLearning/ILIAS/pull/868/files.

@bogenschlag As far as I can see, this now follows the restriction. Thanks a lot for improving and also thx for triggering the discussion. Looking forward to more contribution :-)

**Pull request merged**
