### PR TITLE
Documentation for Repository Pattern

### PR DESCRIPTION
**Pull request by klees**
Last year we discussed the Repository Pattern and its potential usage in ILIAS in a VC-session with all interested ILIAS-developers.

This is the follow up to that discussion and the attempt to add some [documentation](https://github.com/ILIAS-eLearning/ILIAS/pull/1614/files#diff-7d547c3685adf2bab42654f84fb906c9R3), [examples](https://github.com/ILIAS-eLearning/ILIAS/pull/1614/files#diff-7d547c3685adf2bab42654f84fb906c9R229) and [conventions](https://github.com/ILIAS-eLearning/ILIAS/pull/1614/files#diff-7d547c3685adf2bab42654f84fb906c9R208) for the usage of the Repository Pattern to our shared wisdom. While I wrote down the content of my presentation at the VC, @rsheer was so kind to work on the examples and explore the design space a little further. If you need a (german) refresher of the VC you will find the protocol [here](https://edupad.ch/p/2018-11-14_Repository_Pattern).

Feel free to ask for clarification, changes, etc. or just look for mistakes and inconsitencies in our documentation and examples. @rsheer and I will give a small presentation of the PR on JF-2019-03-11 (if there is time) and hope that we will be able to agree on some usage patterns soon.

Best regards!

### CODE REVIEW

**Comment by alex40724** [comment]
Great! Thanks a lot for putting this together.

I have one main suggestion:

I would outfactor the `ilGeoLocation` object creation to a 
`ilGeoLocationFactory` and hand this factory over to the `ilGeoLocationRepository` via constructor dependency injection. The repos should not call `new il...` imo.

Edit: 

I think I understand why this happened. In the example there is a statement that the these data objects (e.g. ilGeoLocation) MUST have an ID. I would make this ID optional.

I think we might have the need to create these data objects in frontends (e.g. UI when reading a form or when reading from an import XML) pass them (without IDs) through some business logic classes and finally persist them using a repo object (which returns a "withId" version of it).

Otherwise we will end up sending lots of primities through several layers of code.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 11 MAR 2019 : Thank you very much for this proposal. We keep the discussion open on this page and add this topic to the next JF agenda again for final decision.

**Comment by rsheer** [comment]
Hi @alex40724 

First of all: Thanks a lot for your feedback! 
To be honest: It took me quite a lot of time to think about the Factory and the ID problems. In some parts, they are both kind of depend on each other. I am open for other ways to use this pattern and even happier, if we find a good solution to this two points. :-)

First of all I want to explain why I thought like this about the factory pattern: In my understanding of the factory pattern, it hides a part of the creation of an object from the client (in this case the repository) and returns an implementation of a given interface. This is in my opinion something, the repository is able to do too, since it also depends on an interface.

On one hand, I see the factories which can work only with the given data which the repository delivers. In this case, it seems more like an encapsulation/wrapper for the constructor. On the other hand, I see the factories which need more data than delivered from the repository. This data might be from an additional table in the database. To get this data, the factory would either use SQL itself, which would make the repository pattern useless, or get an additional repository to read this data from the database.

In the case of the factory, which gets more data from an additional repository, I see a mixture of different layers which seems wrong to me. And even worse, if the factory gets its data from its calling repository. This would create a circular dependency in which two objects call each other till the job is done.

The part with the ID is tricky. I agree with you, it could be possible to create objects without an id and maybe persist them later. I think this is more a question on how it should be done in ILIAS in general and less about the repository pattern itself. Both solutions have in my opinion its ups and downs. I already had problems with objects, which had an ID of NULL. On the other hand, I see the additional effort and complexity if only the repository is able to create objects. At the moment, i don't have a strong opinion on which way is better.

**Comment by klees** [comment]
Hi @rsheer!

About the IDs: Whether or not an object should have an ID IMO depends on how we want to compare objects: by equality or by identity (i.e. "Are they equal?" or "Are they the same?"). Typical things to be compared by equality are numbers, names or, in general, value-objects. Typical things to be compared by identity are users, posts, or in general, entities. To me this means that we won't be able to chose the one or the other in ILIAS in general, but rather need some idea when to chose the one or the other.

The creation of IDs could well be moved to factories if we just drop the idea that IDs need to be numbers that are incremented for each new object. We could use UUIDs and would get rid of the necessity to have a singular source for the IDs but instead could create them when required.

Best regards!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 25 MAR 2019 : We accept this pull request. Factories can be used with repositories as required. If anyone wants to expand the documentation in this regard we will be happy.

**Pull request merged**
