### PR TITLE
Kiosk Mode: Initialize ToC with label

### PR DESCRIPTION
**Pull request by nhaagen**
In order to display a root-node for the ToC _and label it_, the ToC itself needs to initialized with a string $label.
This changes the API of KioskModes's ControlBuilder, but I hope it's  not too late for that, yet ;)

### CODE REVIEW

**Comment by klees** [comment]
Hi @mjansenDatabay. You do not actually use this, right?

**Comment by klees** [comment]
This changes a public interface that people might actually rely on. Thus I added it to the JF agenda.

@nhaagen You require this because implementing the TOC over the `ilExplorer2GUI` requires a label on the top node, right?

Could we just set that to some standard value (e.g. "Table of Content") for now?

**Comment by mjansenDatabay** [comment]
@klees @nhaagen Yes, the `ContentPage` already uses the `ControlBuilder` (but not `tableOfContent`), see `trunk` branch.

**Comment by nhaagen** [comment]
@klees , it's more about the feature request calling for a dynamic title for the ToC.
See the first screen in https://docu.ilias.de/goto_docu_wiki_1357_Learning_Sequence_Object.html, 3.2.11 Learning Module (Kiosk Mode).

I'm afraid, that if we delay the change, it will be much more complicated and impact so many more implementations...

**Comment by matthiaskunkel** [comment]
Jour Fixe, 12 NOV 2018 : We accept this change of the public interface. Please commit it to trunk.

**Pull request merged**
