### PR TITLE
T&A: add metric to collect inconsistencies for #37759

### PR DESCRIPTION
**Pull request by klees**
Hi everyone,

in todays meeting of the T&A tech squad we decided to collect known inconsistency metrics for the database that arise during investigations of mantis tickets. This is the code to do so for [Mantis 37759](https://mantis.ilias.de/view.php?id=37759) (i hope...).

@mbecker-databay (or someone else who feels knowledgeable enough): Please look into my query, I hope I've understand the issue and the database correctly.

Kind regards!

### CODE REVIEW

**Comment by mbecker-databay** [comment]
I am not entirely sure if this one query catches them all.
For our purposes, this seems to bring the issue to light, we have an active and object data is gone.
There may be other effects, for example in object_reference and even more side-dishes in integrity, but I am fine with this one.

I will see to begin writing the "tutorialette" and leave this PR open for the time being, so we can review my text and this code side by side. Due to the regionality of the changes, I do not think we have to fear conflicts here.

In the mantis issue, as discussed, I will bring in an object-existence check and pull it up, the more general approach to fixing metered anomalies as per our agreement from the TechSquad in a more holistic approach.

**Comment by dsstrassner** [comment]
We discussed the status of this PR at today's TechSquad Meeting, and Max stated that he is on it. 
He looked at the available documentation and thinks that he could link to most of the information there. 

He will push the work on this task in the next weeks.

**Comment by dsstrassner** [comment]
Any updates on this @mbecker-databay?

**Comment by mbecker-databay** [comment]
I did in fact look into this, but I seriously have no meaningful addition because the base documentation is WAY better than I thought from reading other such pieces. I will merge this now.

**Pull request merged**
