### PR TITLE
T&A 41629: Fix handling of deleted global templates

### PR DESCRIPTION
**Pull request by lukas-heinrich**
Hi everyone,

this PR fixes an issue where the settings tab crashes when trying to access a deleted template. 

See: https://mantis.ilias.de/view.php?id=41629 

Looking forward to a review.
Best,
@lukas-heinrich

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @kergomard and @thojou, please discuss which one of you review this PR. 
Thanks and Best!
@dsstrassner

**Review by kergomard — CHANGES_REQUESTED** [review]
Thank you very much for the PR @lukas-heinrich !

This is partly Administration, so I ask @fneumann or @lscharmer  for a review.

In the part of the test:
- Please remove all html-tags you introduced in `ilObjTestSettingsGeneralGUI::getSettingsTemplateMessageHTML` and use the corresponding functions from the UI-Framework to generate the message and the link. The rest looks ok from where I stand.

Thanks again and best,
@kergomard

**Review by kergomard — APPROVED** [review]
Thank you very much @lukas-heinrich !

**Review by thojou — APPROVED** [review]

**Review by lscharmer — APPROVED** [review]

**Comment by kergomard** [comment]
Could you please fix the tests @lukas-heinrich , then I will merge as we have all thumb-ups we need.

This will be ILIAS 8 only and no cherry-picks are needed.

**Comment by kergomard** [comment]
Just in case you haven't seen it @lukas-heinrich : We now need one more little fix for the copyright ;-).

**Review by fneumann — APPROVED** [review]

**Comment by kergomard** [comment]
Thank you very much @lukas-heinrich !

**Comment by lukas-heinrich** [comment]
Thanks for the reviews!

I hope this PR gets squashed so no one ever sees this commit history again ;)

**Comment by kergomard** [comment]
Don't worry, it did ;-), ...and thanks again for all the work!

**Comment by rfcmaXi** [comment]
Thanks for the fix. The problem has been bothering us for a while. The solution seems to make a lot of sense to me and has already worked productively ;)

**Pull request merged**
