### PR TITLE
New Learning Progress Icons for Release 7

### PR DESCRIPTION
**Pull request by schmitz-ilias**
This PR introduces the new learning progress icons into release 7, implementing #4739, parts of #4845, and some fixes for the corresponding unit test into ilias 7.

### CODE REVIEW

**Review by smeyer-ilias — APPROVED** [review]
Thanks, @schmitz-ilias 
LGTM

**Comment by dsstrassner** [comment]
[Mantis JF Decision](https://mantis.ilias.de/view.php?id=31804#c79923)

**Review by smeyer-ilias — APPROVED** [review]

**Comment by smeyer-ilias** [comment]
@Amstutz Can you please check if the CSS changes are also fine for Release 7

**Review by Amstutz — APPROVED** [review]
CSS should work, wrote it myself. If any problems arise with the CSS for 7, you may assign them to me. ;-)

**Pull request merged**
