### PR TITLE
UI/Page - set viewport to max-scale=1

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=27835

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
I am on board with the request if:

- [x] Testing: We find a way to properly test it by some users. See: https://mantis.ilias.de/view.php?id=27835 

@klees : Since not everybody able to test is able to stamp out an environment running on the PR of nils, should we merge it and let it run for one day for the people to throughly look at it? Or do we provide some external point to test it?

@klees: I further know why no test case is failing here. Reminds me that we still have to look into better testing of the rendering (I am looking at you mustache task on @Amstutz 's desk).

**Review by Amstutz — APPROVED** [review]

**Comment by Amstutz** [comment]
@alex40724 thx for testing. @nhaagen thanks very much for fixing and providing the testing plattform. @klees feel free to merge as soon as approved by you.

**Comment by klees** [comment]
I've picked this to trunk.

**Comment by klees** [comment]
Thx all.

**Pull request merged**
