### PR TITLE
LTI, logout: ensure session-value during LTI-logout; 

### PR DESCRIPTION
**Pull request by nhaagen**
...the pageprovider relies on it

### CODE REVIEW

**Comment by eqsoft** [comment]
have to be merged also into release_6
@Uwe-Kohnle, @nhaagen: We should check multiple calls from lticonsumer with same user and different LTI objects. It seems that the stored session variables for the home entries in the menubar are confused. No idea yet, we have to dig deeper...

**Comment by nhaagen** [comment]
>stored session variables for the home entries
@eqsoft can you expand on that, please? which ones?

**Comment by eqsoft** [comment]
- I have two different LTI Objects "course" and "LM" in Consumer defined
- I first start the course: everything is fine (keep session open)
- Additionally starting the LM: MainMenu home entry and title in the MetaBar shows title from first session (LTI Course) and not LTI LM.
Maybe its a conceptional issue of the LTI session handling, we have to take a look into that

**Comment by eqsoft** [comment]
Maybe as you suggested the $screen_context_stack->current()->getAdditionalData() store might be a better place for that variables

**Comment by nhaagen** [comment]
I agree - the session-handling as well as the login/logout-sequence might profit from a little refactoring. But this is another topic (than GlobalScreen) altogether.

**Pull request merged**
