### PR TITLE
Dont use the language of the anonymous user in the anonymous area

### PR DESCRIPTION
**Pull request by PurHur**
Only use the user langugae if its not the anonymous user.

Probably this has a huge inpact on current ilias installations.

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724,
I assigned you as the implicit maintainer. I hope that's fine, if not please give the ticket to me.
Best Regards!

**Comment by klees** [comment]
Hi @PurHur!

This would mean that ILIAS would always be english for anonymous users, right? What is the current behaviour? Why would we want to change it?

Best regards!

**Comment by PurHur** [comment]
The behaviour now is that the language is always the language of the anonymous user.

With the Hotfix the language (in the html tag) will be set to the lang_default.

I added a commit. Then ilTemplate will use the current lang key in the global $lng object. The impact will be much bigger with this commit.

**Comment by alex40724** [comment]
@PurHur I do not get it. Setting the META_CONTENT_LANGUAGE always to 'en' for anonymous does not make much sense to me. Maybe you want to add the "&& !$ilUser->isAnonymous()" to the second if in line 664?

**Comment by PurHur** [comment]
You're totally right. I switched the lines. I will clean that up.

**Comment by PurHur** [comment]
Also i wonder why there is a hardcoded fallback for 'en'.
If english is not installed the correct fallback-language would be the lang of the anonymous user? Just curios.

**Comment by alex40724** [comment]
I checked this issue in 6 and will do so in 5.4 shortly.

**Comment by alex40724** [comment]
This is fixed in the current code.

**Pull request closed without merging**
