### PR TITLE
UI Components, Main Bar: Changed Purpose Description

### PR DESCRIPTION
**Pull request by Amstutz**
We (@klees , @yvseiler , @atoedt , @oliversamoila, @Amstutz ) discussed in the UI Clinic a request by (@atoedt and @oliversamoila) concerning the description of the Main Bar. Since there are numerous questions around the description, we decided to tackle one issue at the time and first discussed the purpose description. We believe to have found a much easier to understand and much shorter purpose description which we hereby propose.

Note that if the general feedback is positive, we are planning to tackle the composition and effect section as well and might even push forward to the Slate and Meta Bar entry.

### CODE REVIEW

**Review by yvseiler — APPROVED** [review]
Thank you @Amstutz for transferring our discussion into this PR. From my point of view there are no further comments on this. I am looking forward to the next steps.

**Comment by alex40724** [comment]
Dear @klees , @yvseiler , @atoedt , @oliversamoila, @Amstutz,

thanks for your efforts to clean up the Main Bar definition. A simplification of the description is much appreciated.

You removed the introduction of the tools and the tools section concepts. On the other hand the remaining documentation still contains references to the tools and the tools section, e.g. in the effect chapter or in Meta Bar definition. Imo we should not put the documentation into a state where concepts are referenced that are not introduced properly otherwise it might be hard to read and understand.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 07 DEC 2020: Thanks for this suggestion. It is already a good improvement of the rules. Please consider Alexander's latest comment and try to improve the PR accordingly. Feel free to present the PR again if you think it is ready to decide upon it.

**Comment by klees** [comment]
Hi @Amstutz,

I think we found some improvements in the group working on this, documented here:

https://docu.ilias.de/goto_docu_xpdl_8981.html

Would you include them? Feel free to call me via Skype if you want to have a look together.

Best regards!

**Comment by Amstutz** [comment]
Thx for the ping. Added the tools addition to the purpose section. IMO the revision of the composition section is not yet final, therefore I left it out FTM.

Joure Fixe: To celebrate intermediate successes, we like to get green light on the purpose section before moving on.

**Comment by kergomard** [comment]
Thx a lot to the whole group for all the work! I'm a little worried though that the sentence on the tools is not strong enough on the development of a coherent concept and thus cements a state that is slowly being seen by everybody as unsatisfactory. Could we maybe change this to:
"Currently Tools home functionality that could not be placed elsewhere and there is no sophisticated concept. We aim to develop a coherent concept as soon as possible and thus strive to keep the number of Tools low until this is achieved."

Thanks again and best!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 FEB 2021: We highly appreciate this suggestion and accept the PR for trunk.

**Pull request merged**
