### PR TITLE
LDAP: Fix accessing undefined array key "member"

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=38049#c96875

If approved, this must be cherry-picked to `trunk` (and maybe `release_9`) as well.

### CODE REVIEW

**Comment by pascalseeland** [comment]
@mjansenDatabay please rebase onto updated release8. That should get rid of the copyright issue

**Comment by mjansenDatabay** [comment]
@pascalseeland Please have a look at https://mantis.ilias.de/view.php?id=38363#c97055 . It seems this fix is not necessary.

**Comment by Dennis1993** [comment]
The problem seems to arise from something else. The real problem is that with PHP8 the LDAP limit is handled differently. Unfortunately I don't know how to fix this.

Theoretically, importing more than <LDAP limit> should not be possible with anyone using PHP8.

More information in the link from mjansenDatabay. I hope it can be fixed.

Thanks!

**Comment by mjansenDatabay** [comment]
IMO we don't need this PR anymore if https://github.com/ILIAS-eLearning/ILIAS/pull/6909 gets merged.

**Pull request closed without merging**
