### PR TITLE
Update language.md fixed typos

### PR DESCRIPTION
**Pull request by SaiAryan1784**

### CODE REVIEW

**Comment by chfsx** [comment]
@acgruber  may I pass this on to you for further examination? presumably the language maintainer will then be able to judge this conclusively.

**Comment by mjansenDatabay** [comment]
Hi @acgruber ,

this PR has been lying around for quite a while. Would you like to review this and (if you are happy with it) pass it to @matthiaskunkel as the language maintainer?

Thanks and best,
@mjansenDatabay

**Comment by acgruber** [comment]
Hi @mjansenDatabay,

Please excuse me somehow missing this notification. I will look into it asap. Thanks for the reminder!

Cheers
@acgruber

**Review by acgruber — APPROVED** [review]
Hi @matthiaskunkel,
I've reviewed this PR and the changes look fine for me. Ready to merge :)
Cheers,
Ann-Christin

**Comment by matthiaskunkel** [comment]
Thanks to @SaiAryan1784 for the improvement. Merged to Release_8. Will be cherry-picked to 9 and trunk as well.

**Comment by SaiAryan1784** [comment]
> Thanks to @SaiAryan1784 for the improvement. Merged to Release_8. Will be cherry-picked to 9 and trunk as well.

Will try to Contribute more in the project thanks (other than typos 😅).

**Pull request merged**
