### PR TITLE
UI/Filter: 38597, anchor position of il-popover-container

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=38597

### CODE REVIEW

**Comment by tfamula** [comment]
Hi @nhaagen,
thanks for the PR. The `Guidelines_SCSS-Coding.md` says in chapter "Hacks and Tweaks": 

> !important MUST NOT be used outside of this layer and SHOULD not be used here either.

But I guess that you considered this as only solution for this specific problem. For me, this is fine. But maybe @Amstutz or @catenglaender should decide here.

**Comment by nhaagen** [comment]
well, it's only "relative !important" ;)

**Comment by Amstutz** [comment]
@nhaagen , what @tfamula says ;-). Did you check with @catenglaender for an alternative? I guess we need to overwrite some inline js styling, right? if so, could be hard to find something better.

**Comment by Amstutz** [comment]
I believe to have found a fix without the relative important by fixing the popover js. Hopes it works, if not, we will fallback to this one here.

**Pull request closed without merging**
