### PR TITLE
Implemented a special char checker

### PR DESCRIPTION
**Pull request by catlauraherzog**
This tool checks the file within the given path for special control chars which are usually used by old printers. Sometimes these hidden characters like hidden spaces, tabs or newlines are added to the code accidentally.

It affects the travis tests.

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @lauraquellmalz,

thx a lot. Please have a look into Travis jobs. They are failing (which might be okay in general, due to already existing invisible whitespace), but there seems to be some problems with the permissions on the new script.

Best regards!

**Comment by catlauraherzog** [comment]
Updated the permissions of the files. Job failes as expected due to the occurance of control chars.

**Review by gvollbach — CHANGES_REQUESTED** [review]
Looks good so far, thx for the contribution!
But would it be possible to get rid of the `drölf` greps and use only one grep? Or do we need this explicit states for each case?

**Review by klees — CHANGES_REQUESTED** [review]
Hi @lauraquellmalz,

thanks so far, this is running now. Some more requests from my side:

* Please exclude the libs-folder. I do not think we need to check our dependencies in that regard.
* Please have a look into the current results for ./libs/composer/vendor/phpmailer/phpmailer/language/phpmailer.lang-eo.php. It seems there is some strangeness involved when multiple matches are found in one file: `see line(s) 7 8 9 , 20 , 23`.
* Please look into the identified locations _in our code_ and fix 'em in this PR so the tests succeed again.
* Also: answer to @gvollbach's comment please.

Thx!

**Comment by catlauraherzog** [comment]
Hey @gvollbach :-)

> Looks good so far, thx for the contribution!

Thank you!

> But would it be possible to get rid of the `drölf` greps and use only one grep? Or do we need this explicit states for each case?

We need these explicit states because grep is basically "dump". It just replies the lines with the special chars but due to several restrictions of the console we usually don't know which charackter it is. For instance: We only see this in the reply of grep: ���

This is not helpful if you search for a certain char. The most common is a u00A0-Char which is a null space somewhere in the code. But if you get an u200c additionally you just get the lines without the context for what charackter you are searching for.

Hope that helps.

@klees Thank you as well. Done your tasks. Due to the exclude of the libs folder we don't have any strange outputs anymore.

Best,
Laura

**Review by gvollbach — APPROVED** [review]

**Comment by gvollbach** [comment]
@lauraquellmalz 
Thanks for the clarification.

**Comment by klees** [comment]
Hi Jour Fixe,

we propose to include this white-space-checker in our CI-process and thereby deprecate invisible whitespace in our codebase.

Best regards!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 JAN 2020 : We highly appreciate this PR and accept it for trunk and release_6. Please merge and remove all bad invisible characters...

**Pull request merged**
