### PR TITLE
apply stripSlashes for user data import on desktop

### PR DESCRIPTION
**Pull request by fneumann**
A student can export personal data, inject JavaScript code in the profile or other fields and upload the data again. When the profile is viewed by another user, the code is executed. This may also happen for course administrators showing member list.

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @alex40724 Can you have a look at this PR? There is no Bug-Entry in Mantis since this is a security issue. Unfortunately, PR can't be deleted after merging. I will contact Github after merge.
@fneumann thanks for the PR, for future security issues please send them as e-mail to the security list. "bad-guys" could use this pull-request as a guide to compromise an ILIAS-Installation.
We will discuss how to handle security PR in the future

**Comment by chfsx** [comment]
I assigned @alex40724 since he's in the headers of the changed files. please reassign to me if wrong.

**Comment by fneumann** [comment]
I did not find the address of a security list on ilias.de, but in August I informed Alex dirctly about that issue since he is named in the feture wiki as contact person for the feature. This week I was reminded again by the person who discovered the issue.

**Comment by chfsx** [comment]
The mailing list is ilias-security@uni-koeln.de . I'll discuss the point that the address isn't really visible on ilias.de. thanks for the hint!

**Comment by alex40724** [comment]
Hi Fred,

thank you for the pull request. I will add a fix to 5.0/4.4/trunk, but reject these specific code changes, since ilUtil::stripSlashes is meant to be used to santize data from the UI in this case ilUtil::secureString() should be the better choice. I think as a quick fix we need only the changes in ilUserDataSet, since all other data will not be presented to other users. And we need a general solution for the imports here, something we should discuss at the JF.

**Comment by fneumann** [comment]
Hi Alex, thanks for the fix!

**Pull request closed without merging**
