### PR TITLE
Improvement of UI arrows

### PR DESCRIPTION
**Pull request by alinaappel**
We recommend standardizing the ILIAS arrow icons that display similar or identical functionality, aiming to create not only a more consistent overall appearance within the platform but also to improve the user experience.

### CODE REVIEW

**Comment by yvseiler** [comment]
Hi @alinaappel 
Thank you a lot for contributing to ILIAS and for preparing the analysis in the form of this concept paper PR. It provides a very focused and clear picture of the current situation. It also shows important recommendations for the revision of each group. Great work!

Please consider the following suggestions. You do not need to follow them, but please indicate shortly why you prefer to do otherwise:
- [ ] I would like to see a short “Conclusion” paragraph at the end of the paper that summarizes the recommendations once again and gives an outlook (next steps) on how these could be tackled. Among these, I see something like “Visual language: Define uniform visual language according to the recommendations”, “Embedding: Standardize embedding in the code, e.g. as an icon or glyph”.

If I can be of any help, please let me know.

kindly,
@yvseiler

**Comment by catenglaender** [comment]
Hi @alinaappel

What a fantastic paper! You really found some great places that would highly benefit from some tweaking and I personally would really like if we followed your recommendations. :slightly_smiling_face: :clap: 

Just a couple notes:

**recommendation for the sortation arrows**
* I would suggest to directly recommend the slim design, so we have a very actionable result

**accordion**
* this article presents some very surprising study findings that carets (downward arrows) actually test better than + and x. Against all expectations a user confusing the accordion head for a button/link seems to be rare in many cases: https://www.nngroup.com/articles/accordion-icons/
> Using a caret is definitely better than using no icon at all or a random icon in terms of conveying the expectation to stay on the page (and open an accordion).
Using an arrow or a plus is not better than using no signifier at all.

**conclusion**
I agree with @yvseiler that a conclusion paragraph discussing next steps and strategies could be the icing on the cake.

Seems like we are little by little replacing all Glyphicon Halfling Glyphs :laughing:

Great work! Very much appreciated!

Kind regards,
Ferdinand

**Comment by alinaappel** [comment]
Hello @yvseiler 

Thank you very much for your helpful feedback! I have implemented your suggestions and added a conclusion paragraph. In it, I have briefly mentioned the next steps and summarized the recommendations once again.

Regarding the topic of "Embedding" I am currently working internally on developing a possible procedure. I will add this point as soon as it is finalized.

If you notice anything else, please feel free to let me know. I would appreciate it!

Kind regards
Alina

**Comment by alinaappel** [comment]
Hello @catenglaender 

Thank you very much for your comment! I found very useful information in it for my documentation and have incorporated it into my paper, so it is more clear now where I suggest using the plus icon and where a caret is more useful.

Thank you! 

Kind regards
Alina

**Comment by matthiaskunkel** [comment]
Jour Fixe, 10 JUN 2024: Thank you so much for this very elaborated PR. We highly appreciate this PR and accept it for Release 10 / trunk.

**Comment by klees** [comment]
Thanks @alinaappel, much appreciated!

**Pull request merged**
