### PR TITLE
0024565: "No Permission Granted" for Learning Progress of objects out…

### PR DESCRIPTION
**Pull request by theodortruffer**
…side the activation date

### CODE REVIEW

**Comment by theodortruffer** [comment]
https://mantis.ilias.de/view.php?id=24565

The fix just takes the permission "read_learning_progress" out of the activation check. The "Learning Progress" tab of the object is still not accessible outside it's activation, I tested it.

**Comment by kergomard** [comment]
@smeyer-ilias: We stumbled upon this PR in our biweekly TB meeting. Could you please merge this PR or provide your objections? Thank you very much!

**Comment by Amstutz** [comment]
@smeyer-ilias  : Please provide some feedback to this PR. Note that you might reject this PR give some justification and close, ask for a feature request, ask for improvements or obviously also merge ;-)

**Comment by smeyer-ilias** [comment]
Thanks and sorry for the late repsonse.

**Pull request merged**
