### PR TITLE
use new emoticon font milos bug #25071

### PR DESCRIPTION
**Pull request by alex40724**
https://mantis.ilias.de/view.php?id=25071

### CODE REVIEW

**Comment by alex40724** [comment]
This PR is currently using the new font but the wrong codes. See Mantis Report.

**Comment by Amstutz** [comment]
What is the status of this, is this ready for a review/merge?

**Comment by Amstutz** [comment]
Any action required from my part? This is assigned to me, is this still correct?

**Comment by Amstutz** [comment]
I close this down, it still in draft state and I am unsure on how to proceed with this. If ready to be merged, you may reopen any time.

**Pull request closed without merging**
