### PR TITLE
DataCollection: Application for "Coding Authority" 

### PR DESCRIPTION
**Pull request by iszmais**
Dear @pascalseeland ,

as already announced through various channels i would like to apply for the coding authority within the DataCollection Component through this PR.

Pls consider my proposal and let me no if you have any concerns about it.

Greetings,
@iszmais

### CODE REVIEW

**Comment by klees** [comment]
Hi @iszmais,

did you already discuss this with @pascalseeland?

Kind regards!

**Comment by iszmais** [comment]
Hi @klees ,

yes, this was already considered 2 years ago since the last reassignment of this component and me as also @mjansenDatabay reached out to him recently to take action here.

Greetings,
@iszmais

**Comment by pascalseeland** [comment]
Hi @iszmais, this is fine with me. I guess this would need an approval from JF.

**Comment by mjansenDatabay** [comment]
> Hi @iszmais, this is fine with me. I guess this would need an approval from JF.

Hi @pascalseeland ,

from my understanding, you'll have to approve this first (what you kind of did above). Afterwards, @iszmais (or you) can write an email to the TB/PM (Update: ✅) and then we can finally announce this at the JF.

Best regards,
Michael

**Comment by iszmais** [comment]
@matthiaskunkel This is the PR you requested

**Comment by matthiaskunkel** [comment]
Jour Fixe, 13 MAY 2024: Final decision will be taken by TB and PM tomorrow.

**Comment by matthiaskunkel** [comment]
Change of authorities has been accepted by product manager and @pascalseeland as authority to (de-)assign authorities. No veto by TB.

**Pull request merged**
