### PR TITLE
CI: Make unit test runner more verbose and add failing criteria

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR changes our unit test configuration by:

1. Letting tests fail on "Deprecations" and "Notices"
2. Displaying details on tests with errors/warnings/deprecations/notices

### CODE REVIEW

**Comment by klees** [comment]
@nhaagen: Please fix the newly introduced issues here.

**Comment by mjansenDatabay** [comment]
> @nhaagen: Please fix the newly introduced issues here.

@klees Do you really mean @nhaagen, or me :smile: ? I introduced the line breaks for the sake of better readability (at least for me :smile:).

-- UPDATE --

I got it ^^. You meant the tests with errors. ^^

**Comment by nhaagen** [comment]
I think I was to fix the failing tests... 
https://github.com/mjansenDatabay/ILIAS/pull/26

**Comment by klees** [comment]
The failing test is caused by an issue with the CS-checker. So I'll merge this anyway.

Thanks for your efforts!

**Comment by mjansenDatabay** [comment]
Failed Test: https://mantis.ilias.de/view.php?id=41926

**Pull request merged**
