### PR TITLE
Review `Services/VirusScanner`

### PR DESCRIPTION
**Pull request by kergomard**
Hi @rschenk0 

Here are the results of the `Services/VirusScanner` review.

### Results

- [ ] The code style is PSR-2 + X compliant:_CS-Fixer changed two files_
- [x] No usage of $_GET / $_POST / $_REQUEST / $_SESSION: 
- [ ] There is a Unit Test Suite with at least one unit test:
- [ ] The unit tests pass
- [ ] External libraries are compatible with PHP 8 (if relevant): _Not relevant_
- [ ] The types are fully documented (PHPDoc) or explicit PHP types are used (type hints, return types, typed properties)

### Comments
- ilVirusScannerConfigStoredObjective line 52: It might be a good idea as $config is nullable to add a check for it and throw an explicit exception instead of potentially just letting it crash and burn.
- The component would be a good place to introduce declare strict_types. I see only two failing functions that are easily fixable: ilVirusScannerscanFileFromBuffer() and scanFileFromBuffer()

### Changes made in this PR:
- Fixed CS
- Scoped Constants
- Some additionnal fixes

Best regards,
@swiniker

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@swiniker / @gvollbach I added a new test suite for this component here: https://github.com/ILIAS-eLearning/ILIAS/pull/4339

**Comment by mjansenDatabay** [comment]
@swiniker I pushed some changes (https://github.com/ILIAS-eLearning/ILIAS/pull/4330/commits/3e7628a4a4c05b150189b41d75d3f746e3d457d7) to your review branch. IMO most issues are fixed now. I checked other setup agents and objectives (you mentioned `ilVirusScannerConfigStoredObjective`), but I did not find any agent who handles `null`.

@swiniker / @gvollbach / @rschenk0 : I also introduced `strict_types` for all related PHP classes, added the correct license header and improved most trivial PHP language issues my `PhpStorm` IDE suggested to change.

IMO this is ready to merge now (and don't forget to merge the `Test PR` #4339).

**Comment by kergomard** [comment]
Thank you very much @mjansenDatabay .
Concerning `ilVirusScannerConfigStoredObjective` in `ilVirusScannerSetupAgent` (big sorry for my wrong class reference above!): I understand the approach. I pointed it out because I personally get a  little nervous if it is explicitly stated that a parameter might be null, but I then go ahead and ignore that case in the code dealing with it.

On a side note: As I don't use `PhpStorm` these feedbacks on the reviews also help me to see better into the differences between the `PhpStorm ` inspection profile and phpstan.

**Comment by mjansenDatabay** [comment]
According to @rschenk0 I should merge this.

**Pull request merged**
