### PR TITLE
Move files from Services/Transformation to its only user

### PR DESCRIPTION
**Pull request by klees**
Hi @Uwe-Kohnle, hi @smeyer-ilias,

I was just looking into the call for bids regarding "Streamlining and Abandoning Legacy Services" and investigating `Services/Transformation`. Since Scorm2004 is the only user of classes from that service, it seems easy and appropriate to just move the classes there.

Best regards!

### CODE REVIEW

**Comment by kergomard** [comment]
@Uwe-Kohnle : We stumbled over this PR from March when we checked for old PRs at the meeting of the Technical Board yesterday. Could you please have a look at it and merge or give your reasons for not merging it. Thx!

**Comment by klees** [comment]
Hi @Uwe-Kohnle,

this came up again in our last TB meeting on the 12-07. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by Amstutz** [comment]
Hi @Uwe-Kohnle,

this came up again in our last TB meeting on the 12-01-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by Amstutz** [comment]
Hi @Uwe-Kohnle,

this came up again in our last TB meeting on the 23-02-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by smeyer-ilias** [comment]
Removing this service is absolutely fine for me. It was used for learning progress pdf generation in the past. But this is not in use anymore.

**Pull request merged**
