### PR TITLE
Cleanup bookmark links

### PR DESCRIPTION
**Pull request by pebosi**
Ilias SQL installation dump, has some old social bookmarks links in it.

### CODE REVIEW

**Comment by pebosi** [comment]
Icons removed...

**Comment by chfsx** [comment]
This pull-request will be discussed next JourFixe (see http://www.ilias.de/docu/goto_docu_wiki_wpage_1_1357.html). What's the concrete purpose of the PR, are those SocialBookmarks no longer needed in your opinion (abandoned feature) or aren't they working anymore (bug)? thanks for clarification.

**Comment by chfsx** [comment]
hi @pebosi 

please use the link to this pull-request when you open a feature-request. I close the PR, it's still available when filtering for closed PR.

thanks and best regards

**Comment by chfsx** [comment]
we decided to abandon the feature in http://www.ilias.de/docu/goto_docu_wiki_wpage_3798_1357.html since there is no maintainer for this service.

**Pull request closed without merging**
