### PR TITLE
Improvements and fixes for secure.md

### PR DESCRIPTION
**Pull request by corro**
This is a follow up to PR #1969 with some improvements and syntax/formatting fixes for the newly introduced security guideline `docs/configuration/secure.md`.

With regards to content, there is only one difference (see 8479c5a): if we use placeholders, they should be used consequently IMO.

### CODE REVIEW

**Comment by klees** [comment]
@mjansenDatabay Want to take this to the security group?

**Review by tmuellerdatabay — APPROVED** [review]
Thanks for the syntax upgrade.

**Comment by mjansenDatabay** [comment]
@klees Yes, I will contact them.

**Comment by corro** [comment]
@klees & @mjansenDatabay: I don't think this PR really security-related. There are no changes with regards to the content of the file, except 8479c5a, which is a very minor change IMO.

But if you insist, we can discuss this topic in the security group, which I'm part of too ;)

**Comment by klees** [comment]
@corro This is just a gentle attempt to make the security group take ownership for the doc... =)

**Comment by mjansenDatabay** [comment]
Merged after discussed this with the Security Group...

**Pull request merged**
