### PR TITLE
fallback for button-tests otherwise considered risky

### PR DESCRIPTION
**Pull request by nhaagen**
Mere cosmetics, but tests not permorming any assertions are considered "risky".

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

thx a lot for these improvements. Very considerate =)

Please consider this two suggestions. As always, you do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
* [x] In `test_render_button_with_aria_label`: shouldn't we just remove the conditional? Do we really have buttons that do not have an aria-label?
* [x] In `test_render_button_with_aria_checked`: The name should be changed to `test_render_button_with_aria_pressed`, right? Also: shouldn' we use `instanceof Engageable` here as criterion as well? Engageable buttons should indicate their state via aria-attribute, right?

Best regards!

**Review by Amstutz — APPROVED** [review]
@nhaagen Thanks for those improvements, IMO they may be since they make the status quo better. Nevertheless give a short feedback to @klees or even walk the extra mile if you believe it to be worth it. If done, you may merge directly to avoid any upcoming conflicts. Thx a lot!

**Comment by nhaagen** [comment]
Hi @klees, I addressed your points (and adjusted some templates/tests).
Please merge, if OK.
I think that the need for a HTML-Parser for the tests becomes more and more obvious....

**Comment by klees** [comment]
> I think that the need for a HTML-Parser for the tests becomes more and more obvious....

Yes. Or we should reconsider which tests for the rendering are required. Would you add an according entry for the roadmap in a new PR, please?

**Review by klees — APPROVED** [review]

**Pull request merged**
