### PR TITLE
Introduce CaptainHook as development dependency

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR will add https://github.com/CaptainHookPhp/captainhook as development dependency. It is a powerful tool which can be used to manage GIT hooks, e.g. for PHP linting, code-style checks and local unit test execution purposes.

It is based on a **central JSON configuration file**, so all ILIAS **developers can share the same GIT hook configuration and actions**. The configuration can (unike the GIT hooks themself, because of various reasons) be part of our code base.

CaptainHook can also be used (via the pre-commit hook) to validate and prepare commit messages by defining constraints (length, imperative mood for the subject, etc.).

~~Open Issue: https://github.com/CaptainHookPhp/captainhook/issues/60~~

If we want to **force** that all developers use the hooks we should use the CaptainHook composer-plugin instead.

```bash
composer require --dev captainhook/plugin-composer
```

----
**Current State / Proposed Shared Configuration:**

- [x] Local PHP Linting (on `pre-commit`)
- [x] PHP-CS-Fixer (on `pre-commit`), in `Dryrun/Reporting` mode
- [ ] The actions for the `commit-msg` hook are current **disabled**, but available in the configuration file.

The output for a failed `php-cs-fixer` check looks like:

```bash
(1:2026)$ git commit -m "A supid change"
No syntax errors detected

                  _______________________________________
                 /                                       \
                 | Avast! Hook execution failed!          |
                 |                                        |
                /  Yer git command did not go through!    | 
               /_                                         |  
       /(o)\     | For further details check the output   |
      /  ()/ /)  | or run CaptainHook in verbose or debug |
     /.;.))'".)  | mode.                                  |
     //////.-'   \_______________________________________/
=====))=))===()  
  ///'
 //
  '

======== Error details: Exception ==============================================
   1) trunk/Services/Mail/classes/class.ilObjMailAccess.php (single_blank_line_at_eof)
   2) trunk/Services/Mail/classes/class.ilObjMailGUI.php (concat_space, single_blank_line_at_eof)

Checked all files in 0.136 seconds, 18.000 MB memory used

Loaded config default from "./CI/PHP-CS-Fixer/code-format.php_cs".
Paths from configuration file have been overridden by paths provided as command arguments.
FF
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

```

----

**Important:** If the GIT hooks are installed once, changing branches could be an issue if `CaptainHook` is not installed or the `captainhook.json` file is missing in the branch just checked out.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@klees This tool could help to force the execution of unit tests locally before commit/push.

**Comment by Amstutz** [comment]
@mjansenDatabay Thanks. Could you throw in a few lines in the readme for tests, how to use this for developing. I would be heavily interested. Exactly today, I opened up a PR with a failing test, shame on me ;-)

**Comment by mjansenDatabay** [comment]
@Amstutz Before adding or extending README files, I suggest to discuss this PR with the @ILIAS-eLearning/technical-board (and maybe other interested developers).

We should try to see if our unstanding of it aligns and if we're all supportive and finding it valuable.

I could give a short presentation via Skype.

**Comment by mjansenDatabay** [comment]
07 JAN 2020: The TB will discuss this internally.

**Comment by mjansenDatabay** [comment]
Open Questions:
* Should we announce this via developers [at] lists [dot] ilias [dot] de?
* Is there any need for a documentation how to install this? It's just executing `libs/composer/vendor/bin/captainhook install`.

**Comment by alex40724** [comment]
> Open Questions:
> 
> * Should we announce this via developers [at] lists [dot] ilias [dot] de?
> * Is there any need for a documentation how to install this? It's just executing `libs/composer/vendor/bin/captainhook install`.

I think "yes" and "yes". Even if it's a one-liner, imo everything should be documented and linked in the main docs pages somewhere.

**Comment by mjansenDatabay** [comment]
I adde some changes to our existing `docs/development/git-hooks.md` README file.

**Pull request merged**
