### PR TITLE
T&A 41847: Fixes error when entering info screen on test

### PR DESCRIPTION
**Pull request by thojou**
This pull request addresses a bug where attempting to open the info tab from a test in the ILIAS trunk results in an error page.
This is related to the Mantis Ticket https://mantis.ilias.de/view.php?id=41847

### CODE REVIEW

**Comment by kergomard** [comment]
Hi @thojou 

Could you please move the constant to the test classes? This way we can merge this and be done with it.

Thank you very much for fixing this!

Best,
@kergomard

**Comment by dsstrassner** [comment]
@thojou: TechSquad 19 SEP 2024: Please proceed as wished by @kergomard.

**Comment by dsstrassner** [comment]
This error is quite annoying …

**Comment by kergomard** [comment]
Ok, I close this. We don't need the changes in InfoScreenGUI, as the summary-command is the default command. I picked and adapted here: https://github.com/ILIAS-eLearning/ILIAS/commit/c95fd31fa62d29da9715daee7cde536b2ed10a5c

The ImageMap-Question was broken before and is still broken after these changes. This is on my todo list.

**Pull request closed without merging**
