### PR TITLE
T&A, 0018463: rudimentary fix of archive export (with enabled anonymity)

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=18463
https://mantis.ilias.de/view.php?id=28195
https://mantis.ilias.de/view.php?id=29048

This PR is not a structural improvement, but a simple fix for non-anonymous exports and some errors on the way there.

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @nhaagen 

could you please do me the favor and resolve the conflicts, so directly afterwards @mbecker-databay could merge this for ILIAS 7 and cherry-pick this for ILIAS 8 and Trunk?

**Comment by dsstrassner** [comment]
Hi @mbecker-databay, 

Unfortunately, this PR is open quite a long time. This issue will create further failed tests in the actual test run, so please consider merging this in mannerly time. 
Could we do anything to help you with this one?

**Comment by dsstrassner** [comment]
@nhaagen will resolve the conflicts and afterward we will see, if we could merge this in a timely manner.

**Comment by kergomard** [comment]
I'm sorry @nhaagen : Might you be so kind and resolve the conflicts once more? I promise to then look at it asap so you don't need to do this a third time!

**Comment by dsstrassner** [comment]
@kergomard 🚀

**Comment by kergomard** [comment]
Thank you very much @nhaagen ! We are ready to merge and I will also cherry-pick back to 8, ...and apparently also 7.

**Pull request merged**
