### PR TITLE
Setup: add metric collector for db update steps

### PR DESCRIPTION
**Pull request by daniwe4**
Collect db update steps from different modules and services and add them to status command output.

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @daniwe4,

this looks fine already, but there is one change I still like to request. Let's use "Favor composition over inheritance" here and turn the `trait DatabaseStepHelper` into a full fledged `class DatabaseStepReader` that then is used by the two respective objectives. You can then write tests for the `DatabaseStepReader` once and simplify the tests for the objectives as well. This will turn out to be a lot simpler, I would expect.

Give me a call to discuss, as always.

Thanks!

**Comment by klees** [comment]
Hi @chfsx,

this LGTM. Please pick this up as maintainer of the database =)

Thanks!

**Comment by chfsx** [comment]
Hi @daniwe4 
Sorry for the late response!
I just checked your PR (and rebased it locally fist): while running a `php setup/cli.php update -y` I get errors like ` [ERROR] Call to undefined method ilMailDatabaseUpdateSteps::step_2()`. the class `ilMailDatabaseUpdateSteps` currently only has one step and the `step_2`does not exist. could you please have a look at this? thanks a lot!

**Comment by daniwe4** [comment]
Hi @chfsx,
thank you for the hint. I hopefully fixed the problem.

**Comment by chfsx** [comment]
Thanks a lot, works now like a charm :-)

**Pull request merged**
