### PR TITLE
Css squad branch

### PR DESCRIPTION
**Pull request by Amstutz**
Dear developers,

This PR is a follow up of: https://github.com/ILIAS-eLearning/ILIAS/pull/3189

As pointed out in the above PR, this is part of the ongoing Page Layout Revision III project. In this project we talked about various options to include improvements made in the santorini skin in ILIAS into the default ILIAS. One idea was to ship 2 distinct skins with the default ILIAS, however this idea was quickly discarded, since our maintenance workforce is scarcely enough to properly maintain one skin. Further, a lot of a11y improvements in santorini should also be shipped with the delos skin. So we decided to merge the two. However, while tackling this task in a special task force consisting of @ezenzen, @yvseiler and @Amstutz, we observed, that several quirks in the default skin, make it very hard and tiresome while merging. We decided to tackle the issue at it’s core and start cleaning up the mess. 

This PR contains our proposal of how to finally name and use the new color variables. Further it contains several small clean up tasks as well as fixes for issues around accessibility:

- 0029707: Contrast Errors (Tests failed): https://mantis.ilias.de/view.php?id=29707
- 0029724: Failed test: 2.4.3 und 2.4.7 Fokus ist gut sichtbar: https://mantis.ilias.de/view.php?id=29724
- 0029717: Failed test: 2.1.1a Tastaturbedienbarkeit - Metabar ohne Maus per Tab-Taste bedienbar: https://mantis.ilias.de/view.php?id=29717
- 0028939: Tools-Tile fails contrast requirements: https://mantis.ilias.de/view.php?id=28939
- 0028945: Focus outline is not visually agressive enough.: https://mantis.ilias.de/view.php?id=28945
- 0028942: Icons in Metabar lack contrast: https://mantis.ilias.de/view.php?id=28942
- 0028941: outlines of input fields in forms lack contrast: https://mantis.ilias.de/view.php?id=28941
- 0028956: ILIAS Delos Accessible Skin & Header: https://mantis.ilias.de/view.php?id=28956
- 0030113: Less Variables contradict the Less Guideline: https://mantis.ilias.de/view.php?id=30113
- 0030111: Redundant devmode less/css: https://mantis.ilias.de/view.php?id=30111
- 0030110: "Empty" less code should be removed: https://mantis.ilias.de/view.php?id=30110

Since many screens were examined for contrast errors as part of the CSS revision, this PR fixes many more contrast errors beyond the bug fixes. 

We aim to ship those changes with ILIAS 7 and trunk.

Since this is a rather large CSS change close to the release, we like the JF to greenlight this for ILIAS 7.
Thx
@ezenzen, @yvseiler and @amstutz

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 22 MAR 2021 : We highly appreciate this PR and accept it for trunk and release_7 as well. Thanks to all contributors. Please add a short notice to the release report of ILIAS that less variables have changed significantly.

**Comment by Amstutz** [comment]
Merged and also pushed down to 7.

**Comment by pschmitt77** [comment]
What is the reason for this changes (https://github.com/ILIAS-eLearning/ILIAS/pull/3240/commits/9340fa693a2c273f2fb60183e59e315125940338)? 

- Overwriting boostrap standart variables in the boostrap-variables.less file makes it harder to update bootstrap and is not necessary
- Why are core boostrap variables like "brand-primary" abstracted by ILIAS own variable names? Customizing gets harder as I have to learn the "ilias language" instead of applying bootstrap know how. It's hard to find help by googeling for "il-main-color".

In my point of view all customization should be done in ILIAS own files and not in the boostrap source. The abstraction (eg @brand-primary: @il-main-color;), if needed at all, can be done with a additional less file.

**Comment by Amstutz** [comment]
Hi @pschmitt77 

Thx for the Feedback. 

A detailed reasoning is provided here: https://github.com/ILIAS-eLearning/ILIAS/pull/3189 . 

In short: I think we aim exactly at what your pointing towards. So I guess we are on the same page on that. We want more independence from bootstrap. The wild mix of bootstrap variables and own custom ILIAS variables made it very hard to have an overview on side effects on changes. Therefore we factored them out of the variables.less file. Getting completely rid of them would be the ultimate goal but not yet possible since still used in countless places.

Thx.

**Comment by pschmitt77** [comment]
Hi @Amstutz 

Thanks for the link. 

I obvisouly confused "bootstrap-variables.less" with a bootstrap standart file - sorry for that! I would recomend to rename it as bootstrap comes with certain boostrap-[xyz].less files. We usualy call it "migration.less" in our projects to clarify its only temporary (or at least to goal is to use it only temporary :) )

Greetings, Pascal

**Pull request merged**
