### PR TITLE
Finder

### PR DESCRIPTION
**Pull request by mjansenDatabay**
A Symfony-like 'Finder' based on the ILIAS FileSystem abstraction.

### CODE REVIEW

**Comment by alex40724** [comment]
@chfsx We discussed this today in the TB meeting. @mjansenDatabay will provide more examples in the readme file in the next day. Please provide some feedback afterwards, even if this is "too complex" or "funding needed". Thanks.

**Comment by mjansenDatabay** [comment]
I revised the README file (in regards of the `Finder`). I hope this helps to understand the basic concept of this `FileSystem` addition.

I have no funding, so if funding is required, please close this PR.

**Review by chfsx — APPROVED** [review]
@mjansenDatabay many thanks for this very voluminous and extremely useful extension! I like it very much!
I can't review the PR in its entirety (especially all the iterators :-) ), but the general interfaces and classes look very good and I'll be happy to merge them. Could you imagine doing some kind of submaintainership for this part of the FileSystem service? So I could forward you e.g. tickets for it?

**Comment by mjansenDatabay** [comment]
Thanks for your review @chfsx 

> Could you imagine doing some kind of submaintainership for this part of the FileSystem service?

Yes, I could.

> So I could forward you e.g. tickets for it?

Yes, of course. I hereby announce my commitment to maintain this sub-component.

**Pull request merged**
