### PR TITLE
9/object/feature move timing settings

### PR DESCRIPTION
**Pull request by kergomard**
This PR implements https://docu.ilias.de/goto_docu_wiki_wpage_6059_1357.html .

@alex40724 : As discussed earlier, there is a small change in `ilObjContainerGUI` in the commit 94a552d9d543509a48879302867c52a66abb46c5 . I added you as a reviewer just so you are surely aware of this.

@mjansenDatabay : I needed to remove a variable declaration from `ilObjMailGUI` as I'm now using this variable myself. See a448beb1ce7e6ea0cb2700279c25fadff260b52b .

### CODE REVIEW

**Comment by kergomard** [comment]
Hi @thibsy 

I added you as a reviewer as you are maintainer of `UICore`. I could for the life of me not find the right place to render the modal. If I'm understanding this right, @nhaagen is already working on improvements for the modal-component, but until then, the changes in [this commit](https://github.com/ILIAS-eLearning/ILIAS/pull/6440/commits/9760a8476f1375ea302eb75261d87b1ef07d8800) were the only viable solution I could find. I have a second problem child there `{WEBDAV_MODAL}` and am more then willing to work on a solution for the both of them.

Additionally as far as I can see, `{LIGHTBOX}` can go. I will provide a PR.

Best,
@kergomard

**Review by thibsy — APPROVED** [review]
Hi @kergomard

Adding the modal there is fine by me. The goal will ultimately be to get rid of these templates altogether and replace them with UI components, where I don't think this will be an issue anymore.

Kind regards,
@thibsy

**Review by mjansenDatabay — APPROVED** [review]
Thx @kergomard , the changes in `Services/Mail` look good.

**Comment by kergomard** [comment]
Thank you all. I will merge this now.

**Pull request merged**
