### PR TITLE
[WIP] Feature/6/ui avatar implementation

### PR DESCRIPTION
**Pull request by chfsx**
This is the implementation branch of #2400.

it proposes 26 colors for the letter avatars, which are defined in the avatar.less. Shall we move them to variables less?

how about the rule which username gets which color. it's currently implemented as:
- the abbreviation are the first two letters of the username
- users with the same two letters of the username get the same color.

In ILIAS 5.4, the color had a relationship to the user-id. IMO, the UI-component should not know about the user id. but this would lead to two different colors for the UI-Component LetterAvatar and the old ilUserAvatarLetter. We should discuss this, I think :-)

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @fschmid

Thx for the implementation. Thanks for the examples. Looking nice.

Please answer the following question:
- [x] First two chars: The first two chars seem not ideal. E.g. if the user name is t.amstutz, abbreviation would be t., whereas ta would be much prettier. Do you agree? If this has always been like that, do not change. @Amstutz is gonna make a PR to propose this at some latter point in time then.
- [x] Color Variant Less: Why did you not use the il-extended-colors from the less variable file (See Section, extended Colors). They are designed to work together well. You have 9x5 Options along with a text color that does not violate any accessibility contrast ruling? Did you check all your colors for accessibility contrast?

Please make the following changes:
- [x] Color Variant Generation:  (ord($plit[0]) + ord($plit[1])) % 26; timeIs imo not good enough. There will be many dublicate colors, e.g. t.amstutz and t.sterki and t.gerber would all have the same color. Use `crc32($username) % self::NUM_COLORS` instead.
- [x] Split tpl.avatar.html into two files. This is easier to read and customize. E.g. `il-avatar-{MODE}` is an issue for designers.
- [x] Tests: Add Them.
- [x] Empty Lines: There are many empty lines added/removed in ilObjUser. This makes to actual change hard to spot. Get rid of them.
- [x] Docstrings: Please do not add docstrings above classes in the UI framework. We do not use them there.
- [x] Remove [`checkStringArg`](https://github.com/ILIAS-eLearning/ILIAS/pull/2447/files#diff-4c8af130356cc10a4cfdd858b41fb477R22). We have type hints now. Yay!
- [x] Line length: Please try to limit your lines to ~80 chars, especially in the KS entries. These are hard to read otherwise.
- [x] Rename `AbstractAvatar` to just `Avatar`. We don't use that Abstract` nomenclature in the UI framework.
- [x] `$plit` is supposed to be `$split`[here](https://github.com/ILIAS-eLearning/ILIAS/pull/2447/files#diff-c839b287997aca47ffa6a474aa9a60eeR18), right?
- [x] Rules: Please move the [rule regarding letter/picture-avatar](https://github.com/ILIAS-eLearning/ILIAS/pull/2447/files#diff-fc28788fb40be99397666ee147272631R22) to the rules section. There is a similar rule on the Letter Avatar. Phrase `Picture Avatar.usage.1` as a rule or remove it (clearly indicate the level of requirement by using MUST, SHOULD or MAY). 
- [x] The `effect` descriptions of Picture and Letter Avatar are identical. Please move them one layer up to avatar. Same goes for the `context` and the rule `responsiveness.1`. `accessibility.1` is duplicated on Avatar and Picture Avatar.

Thanks

@amstutz and @klees

**Comment by chfsx** [comment]
> First two chars: The first two chars seem not ideal. E.g. if the user name is t.amstutz, abbreviation would be t., whereas ta would be much prettier. Do you agree? If this has always been like that, do not change. @Amstutz is gonna make a PR to propose this at some latter point in time then.

As before, the set of rules is now also outside, as the calculation of the abbreviation requires a lot of information about the user, such as which parts of his/her profile he/she has published. All this logic is now outsourced to `ilUserAvatarResolver`.

> Color Variant Less: Why did you not use the il-extended-colors from the less variable file (See Section, extended Colors). They are designed to work together well. You have 9x5 Options along with a text color that does not violate any accessibility contrast ruling? Did you check all your colors for accessibility contrast?

Unfortunately, I can't use them, since JF has requested to use the same colors as in the old avatars (which in my opinion are not the Extended Colors).

> Color Variant Generation: (ord($plit[0]) + ord($plit[1])) % 26; timeIs imo not good enough. There will be many dublicate colors, e.g. t.amstutz and t.sterki and t.gerber would all have the same color. Use crc32($username) % self::NUM_COLORS instead.

Is adapted, also in the old implementation. Now you get the same color in both cases.

> Split tpl.avatar.html into two files. This is easier to read and customize. E.g. il-avatar-{MODE} is an issue for designers.

Done. There is a new rule every time, which I don't know ;-)

> Tests: Add Them.

Added

> Empty Lines: There are many empty lines added/removed in ilObjUser. This makes to actual change hard to spot. Get rid of them.

The PHPStorm Templates should be adjusted, so that you can use them. This is otherwise very annoying. I have now undo the changes manually.

> Docstrings: Please do not add docstrings above classes in the UI framework. We do not use them there.

Still no friend of this, because I like them (I know, not necessary). Done.

>  Remove checkStringArg. We have type hints now. Yay!

Done.

> Line length: Please try to limit your lines to ~80 chars, especially in the KS entries. These are hard to read otherwise.

I'll never get used to that, too. With the smallest adjustments you have to realign dozens of lines and YAML often has no fun with this. But well, rules are rules :-). Done

> Rename AbstractAvatar to just Avatar. We don't use that Abstract` nomenclature in the UI framework.

Done. Still find the PSR Naming Conventions the better ones: https://www.php-fig.org/bylaws/psr-naming-conventions/

Thanks foll the feedback and hints, tried to implement everything as you requested.

**Comment by chfsx** [comment]
there is currently a conflict i must resolve first

**Comment by chfsx** [comment]
hmm can't reopen the PR after recreation of branch :( i must open another-one

**Pull request closed without merging**
