### PR TITLE
PHP 8 Code Review Services Chart

### PR DESCRIPTION
**Pull request by katringross**
Hello @alex40724  ,

we completed the review of the Service/Chart component.

Results:

- [x] The code style is PSR-2 + X compliant
 No usage of $_GET / $_POST / $_REQUEST / $_SESSION: We found 7 usages of $_SESSION, 13 usages of $_GET and 40 usages of $_POST.
- [x] There is a Unit Test Suite with at least one unit test
- [x] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant)
- [x] There are no serious PhpStorm Code Inspection issues left
- [x] The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)
--

Please check our inline comments most of them might be just information reported by our inspection profile. You can use PHP8-Review when searching.

Best regards

@katringross

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
This PR contains changes for `Cache`, `Rating` and `Chart`.

@alex40724 

- [ ] A return type could be added in `\ilServicesChartSuite::suite`

**Comment by katringross** [comment]
@alex40724 and @mjansenDatabay sorry, I overlooked it for Cache and Chart. By mistake we added the commit for cache and rating here. Can you work with it? If not I will create a new PR.

**Review by alex40724 — CHANGES_REQUESTED** [review]
@katringross No, I need a new PR, since I already took care of the rating and cache issues. If I merge this one, I will have to do it again. So please provide a PR only containing the Chart changes.

**Comment by katringross** [comment]
I close this one, new PR: https://github.com/ILIAS-eLearning/ILIAS/pull/4304

**Pull request closed without merging**
