### PR TITLE
fixed bug #32128: Accordeon -vertical does not react after opening on…

### PR DESCRIPTION
**Pull request by alex40724**
…e panel

see https://mantis.ilias.de/view.php?id=32128

The general issue is: ILIAS does not support MathJax 3.

This might not be a full fix, see comments in mantis report.

### CODE REVIEW

**Review by mjansenDatabay — APPROVED** [review]

**Comment by fneumann** [comment]
I tested the fix and it works for the accordeon with MathJax3.  MathJax 3, however, is not yet supported by ILIAS 7. I added support for MathJax 3 in ILIAS 8 with an additional URL for the polyfill script required in https://www.mathjax.org/#gettingstarted. Merging this PR to the trunk of ILIAS 8 will certainly help there.

I don't know if MathJax 3 works fine without the polyfill in ILIAS 7. The MathJax page notes that "Some features from version 2 are still being ported to version 3. MathJax version 2 is still available, and you can continue to use that until version 3 includes the features that you need.". So there is no urgent need to move to MathJax 3 in ILIAS 7 and I don't see it as a real bug that ILIAS 6 and 7 does not yet suppot MathJax 3.

As a conclusion I would like to start support of MathJax 3 in ILIAS 8.

**Comment by fneumann** [comment]
@mbecker-databay do you agree with the test question related changes? They are all the same like in the accordeon and just check if the MathJax.hub class exists before it is used.

**Comment by dsstrassner** [comment]
@mbecker-databay What do you think? Could you agree to the changes?

**Comment by dsstrassner** [comment]
@mbecker-databay There is still the need for you to approve.

**Comment by kergomard** [comment]
Hi @mbecker-databay 

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the resources to look into it in detail.

Best regards!

**Review by kergomard — APPROVED** [review]
Thank you very much and sorry this didn't move for so long! This looks good to me and I approve the changes in the Test. Feel free to merge.

**Comment by alex40724** [comment]
@kergomard I am confused. In my understanding this needs approval by either @dsstrassner or @maxbecker as they are the only listed maintainers currently.

**Comment by kergomard** [comment]
We will formalize this in the near future as soon as the infrastructure for doing so is in place. I'm authorized to work on the code of the Test & Assessment and also to greenlight PRs like this one. There is a corresponding message by @dsstrassner somewhere.

**Comment by dsstrassner** [comment]
> We will formalize this in the near future as soon as the infrastructure for doing so is in place. I'm authorized to work on the code of the Test & Assessment and also to greenlight PRs like this one. There is a corresponding message by @dsstrassner somewhere.

This is correct. I authorized @kergomard within the [Additional Competences Guideline](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/maintenance.md#additional-competences) to handle PRs and Mantis Issues from the T&A.

**Comment by alex40724** [comment]
> > We will formalize this in the near future as soon as the infrastructure for doing so is in place. I'm authorized to work on the code of the Test & Assessment and also to greenlight PRs like this one. There is a corresponding message by @dsstrassner somewhere.

Where exactly?

> 
> This is correct. I authorized @kergomard within [Additional Competences Guideline](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/maintenance.md#additional-competences) to handle PRs and Mantis Issues from the T&A.

I don't find a corresponding message in this file. Where is it? How could developers know this?

**Comment by dsstrassner** [comment]
> > > We will formalize this in the near future as soon as the infrastructure for doing so is in place. I'm authorized to work on the code of the Test & Assessment and also to greenlight PRs like this one. There is a corresponding message by @dsstrassner somewhere.
> 
> Where exactly?
> 
> > This is correct. I authorized @kergomard within [Additional Competences Guideline](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/maintenance.md#additional-competences) to handle PRs and Mantis Issues from the T&A.
> 
> I don't find a corresponding message in this file. Where is it? How could developers know this?

I informed the Product Manager and the TB and this will be documented, as @kergomard stated, when the TB has informed the JF about the necessary infrastructure.

**Comment by alex40724** [comment]
@kergomard @dsstrassner @matthiaskunkel So developers are not yet informed. I am not sure what infrastructure is needed here. But why not simply adding a hint in the "Test & Assessment" section of the maintenance.md? This would avoid further confusion.

**Comment by kergomard** [comment]
Hi @alex40724 
I assign this to you. I think, as the changes related to tests and questions are ok with us, you can merge.
Thank you very much,
@kergomard

**Comment by alex40724** [comment]
@kergomard May I ask why this is assigned to me? This is a mathjax issue, the bug report is assigned to @fneumann, he is currently first maintainer of Mathjax. I initially assigned this to @fneumann.

**Comment by alex40724** [comment]
@dsstrassner You assigned @mbecker-databay as reviewer here, which is still pending. Please deassign, if this is not needed anymore.

**Comment by fneumann** [comment]
@alex40724 First of all many thanks for your PR. It solves the issue with mathjax 3 and worked well when I tested it. 
But the changed components are not maintained by me. So as far as I understood the procedure, I have for an approval by all affected maintainers before I can merge it, right?

**Comment by kergomard** [comment]
Hi @alex40724 
As @fneumann pointed out, none of the changed code is under his maintenance. The changed code is partly under the maintenance of @dsstrassner (this was reviewed by @kergomard and there is even an explicit approval of the review by @dsstrassner ). @mbecker-databay was there as an alternative review to the one done by @kergomard . I now removed you, @mbecker-databay as reviewer to make this explicit. I will do this in the future more explicitly.

The only additional code being changed is under your maintenance @alex40724 . You can give your explicit approval and assign me, if you prefer and I will merge, or you just merge yourself.

Thanks and best,
@kergomard

**Comment by alex40724** [comment]
@fneumann Yes, imo this is clearly related to your component, since it fixes a Mathjax bug. Unfortunately the Mathjax code is spread over multiple components. You might solve this differently, e.g. by somehow centralising this kind of code. @kergomard Since I wrote the PR myself, I don't see why I need to approve it, this does not make much sense to me. Of course the code change is ok for me.

**Comment by kergomard** [comment]
Ok, this has been going on for long enough and binding resources for nothing. I will merge it and then we will see.

Best,
@kergomard

**Pull request merged**
