### PR TITLE
UI: Proposal to Move to SASS with ITCSS-based Model

### PR DESCRIPTION
**Pull request by klees**
Hello everyone!

We like to present the first tangible results from the [Bootstrap 4/SASS working group](https://docu.ilias.de/goto_docu_grp_7484.html). We have met regularly since April 2019 to attempt to modernize our style code. We feel that we have come to some conclusions worth discussion in some larger circles and also worth some approval by the JF (or also rejection or change requests, of course).

We plan to proceed as follows:
* Announce the proposal on 2019-12-16 to give anyone time to scrutinize our results.
* Invite everyone to ask questions or express criticism on our [regular meeting on 2020-01-09 at 11:00](https://join.skype.com/naq6Ujj1wgl2) or via this PR.
* If nothing substantial comes up, discuss this proposal on the JF of 2020-01-20. Regroup otherwise.
* Move on according to the proposal.

If you like to join our discussion in general, you are of course welcome as well on our regular meetings.

Best regards!
@klees on behalf of @catkrahl , @tfamula, @Amstutz and @swiniker

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 16 DEC 2019 : Richard invited all interested users to read the proposal and participate at the next meeting of the SASS-group at [09 JAN 2020 at 11:00](https://join.skype.com/naq6Ujj1wgl2) in Skype (see above).

**Comment by klees** [comment]
Hi Jour Fixe,

we just waited in our call, but nobody (new) came and also nobody gave feedback in this PR. We would like to move on with this, but we are concerned that the implication of our proposal aren't fully understood by stakeholders and that questions and discussions will get out of hand on the JF. We still set the JF-label, but we would suggest to pause discussions and questions on the JF early on (if our concerns are valid) and move them to our next regular meeting (or another date).

Best regards!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 JAN 2020 : We highly appreciate this proposal and support its intention in general to abandon Bootstrap for the UI KS and to move from LESS to SASS. Nevertheless, some open issues still exist for legacy implementations that currently use Bootstrap elements and have no KS implementation yet to which they can be moved to. Therefore, discussing these issues and how to tackle legacy code still needs to be done in the next meetings.

**Comment by klees** [comment]
@Amstutz I would merge this, or do you see anything preventing that?

**Pull request merged**
