### PR TITLE
UI Repository Selector

### PR DESCRIPTION
**Pull request by Amstutz**
Proposal to add a new repository selector. Note that this is the first input component and the first selector component, those two families will be added with this PR as well.

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks for the PR! The examples now contain mockups, not the intended final code. Will we try to provide real example code before discussing this? I think the mockups could stay in the FW. Did you check (I am not sure if you are aware of it) any relation to the current filter implementation ideas from Richard and Fabian at https://github.com/chfsx/ILIAS/commit/e97898dd0c90d996ea5cdc9b401a3b0df8fe3e69 ? Will your $f->input()->selector() and their $f->text() be something of the same kind?

**Comment by alex40724** [comment]
One general challenge is, that the selector will need to invoke subsequent ajax calls for expanding/collapsing subtrees. These must be routed somehow to the selector again.

**Comment by Amstutz** [comment]
Thanks for the feedback. All that is asked for the discussion in the is the specification of the component in the factory and the interface. The interface of this one is incomplete, I am aware of that and that will surely be pointed out at the JF. However I found it hard to do, since I will not implement this myself. If you find time to add some parts, you are welcome to do so obviously.

As you point out, the mockups do not contain any reusable code. They are additionally added to simplify the discussion during the (showing what this component should do). You are right, that this might not be needed for most new elements, since they will probably introduced along with a new feature making use of it and therefore providing mockups in the corresponding FR. 

I discussed the raw idea of this shortly with Richard. He agrees with introducing an Input family. I guess text would also belong in there.

You are correct in pointing out the ajax difficulty. We have the same issue in other upcoming components as well (e.g. modals). Since we will not rework the whole ilctrl structure soon, we probably have to live with the known ajax patterns for the moment. Meaning, the tree will probably get some call back like function from the serverside (as link), in which the missing parts of the tree will be generated using again the same UI-Repository structure. The JS will then invoke this PHP functionality async on click and fill the result back into the DOM. Not sure if this is any good. But thats roughly the way I can think of.

**Comment by chfsx** [comment]
Thanks Timon for the PR, interestinf espeacially because it's coming with the same questions concerning JS and AJAX as we will have in Modals. 
@wanze the proposal for JS-bindings and AJAX-calls in modals should be as general as possible.

**Comment by chfsx** [comment]
@Amstutz this PR currently has conflicts

**Comment by Amstutz** [comment]
@alex40724 : will this be implemented for 5.3.? If not, I propose to close this, since it tends to be outdated.

**Comment by alex40724** [comment]
Not sure. I would prefer to wait before closing this, even if it needs updates.

**Comment by Amstutz** [comment]
TB: PR geschlossen, da outdated. Falls Projekt wieder aktuell, neuen PR erstellen.

**Pull request closed without merging**
