### PR TITLE
Init: Change password assistance info message when submitting form

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=38369

If approved, this has to be picked to `trunk` (and maybe also `release_9`) as well.

### CODE REVIEW

**Review by matthiaskunkel — CHANGES_REQUESTED** [review]
Hi @mjansenDatabay. Thanks for the improvement of the language files. Within the project for gendermainstreaming the German language file we got rid of the „Besucher“ in German with ILIAS 9. Therefore I ask you to modify the label as follows: „…, sofern ein ILIAS-Konto mit dem angegebenen Anmeldenamen und der E-Mail-Adresse existiert. …“ Thanks!!!

**Comment by mjansenDatabay** [comment]
@matthiaskunkel Done

**Comment by matthiaskunkel** [comment]
Thanks @mjansenDatabay. Will you merge this change to 9 and trunk as well? Thanks!

**Comment by mjansenDatabay** [comment]
@matthiaskunkel Done

**Pull request merged**
