### PR TITLE
UI, DataTable: add a LinkColumn

### PR DESCRIPTION
**Pull request by nhaagen**
Screenshot from 2023-10-24 17-30-20

### CODE REVIEW

**Comment by klees** [comment]
Hi @Amstutz and @thibsy,

please have a look into this. Code is almost trivial, the general addition was discussed in [the UI Clinic yesterday](https://docu.ilias.de/goto_docu_xpdl_13607.html). Would be nice if we could fasttrack this, we would need this addition to finish PR 6463.

Kind regards!

**Comment by tfamula** [comment]
@nhaagen Is there a reason why you removed the `LinkListing` afterwards?

**Comment by klees** [comment]
Hi @tfamula,

yes! From my POV these are supposed to be two different column types, as they seem to have different potential space requirements and hence formatting should be different. So I asked @nhaagen to remove the "Listing" part. If I understood our agreement on tuesday correctly, that type would be added by you, right? Could be a copy of this solution mostly, I guess.

Kind regards!

**Review by thibsy — CHANGES_REQUESTED** [review]
Hi @nhaagen

Thanks a lot for your contribution to the UI components!

About the concrete changes, please answer the following questions:

- [x] `Column` values: currently the only documentation we have on column values are through examples. I think this is sufficient for the moment, but we should provide some description on the column factory as well, so we can ease the lookup process. Could you create a short-term roadmap entry for this?

Please implement the following changes:

- [x] Examples I: please don't access dependencies of the global `$DIC` via array-keys and use the according type-hinted methods instead.
- [x] Examples II: please add the `string` type-hint to the function.

Kind regards,
@Amstutz & @thibsy

**Comment by klees** [comment]
@Amstutz @thibsy This is updated!

**Review by thibsy — APPROVED** [review]
Thx @nhaagen for implementing the changes. This LGTM now!

**Comment by thibsy** [comment]
Thx @tfamula for adding the JF label =). This needs to be announced at the upcoming JF of course.

**Comment by tfamula** [comment]
PR for LinkList: https://github.com/ILIAS-eLearning/ILIAS/pull/6482

**Comment by matthiaskunkel** [comment]
Jour Fixe, 30 OCT 2023 : We highly appreciate this suggestion and accept the PR for Trunk.

**Pull request merged**
