### PR TITLE
ks: main action for items

### PR DESCRIPTION
**Pull request by alex40724**
Follow up of https://github.com/ILIAS-eLearning/ILIAS/pull/6288

This adds a main action to KS items to provide a button for the most important action of an item.

This is needed to implement the feature https://docu.ilias.de/goto_docu_wiki_wpage_7444_1357.html

### CODE REVIEW

**Comment by alex40724** [comment]
@thibsy Tests are using mocks now instead. Link/Button HTML is replaced by Canonical.

**Review by thibsy — COMMENTED** [review]
Hi @alex40724

Thx a lot for implementing our suggestions! There is one minor thing left to do: 

- [ ] `ItemTest`: the renderer which is supplied with the mocked instance using a hash-code as canonical name will render only this hash instead, which allows us to perform the assertion like `assertTrue(str_contains($html, $hash_code));` instead of comparing the HTML structure with `assertHTMLEquals()`. This will allow us to modify said structure more easily in the future without adjusting too many unit-tests. Could you replace this check?
- [x] Copyright: I also noticed the checks currently fail because of malformed copyright license headers, please adjust them as well.

Afterwards this is ready to be merged now.

Kind regards,
@thibsy

**Comment by alex40724** [comment]
> Hi @alex40724
>     * [ ]  `ItemTest`: the renderer which is supplied with the mocked instance using a hash-code as canonical name will render only this hash instead, which allows us to perform the assertion like `assertTrue(str_contains($html, $hash_code));` instead of comparing the HTML structure with `assertHTMLEquals()`. This will allow us to modify said structure more easily in the future without adjusting too many unit-tests. Could you replace this check?

@thibsy  Thanks for the feedback, but I did that, as far as I understand the approach. Maybe you could be more specific.

The remaining assertHTMLEquals will test for the HTML of the item (which we want to test here, since this is an Item test) and it replaces the button/link HTML with the hash-code of the Button/Link. So it will check its position in the HTML, but it will not be influenced by HTML changes in buttons or links. So changes in Button or Link renderers will not affect this test, e.g.
```
<div class="il-item il-std-item ">
            <div class="il-item-title">Title</div>
            <div class="il-item-actions l-bar__container">
                <div class="l-bar__element">$expected_button_html
            </div>
            </div>
        </div>
```
All the HTML code is item specific, so it should be tested, `$expected_button_html` is the button hash (`$expected_button_html = md5(I\Component\Button\Standard::class);`). So the position is tested (and should) but not the button HTML. `str_contains` would only check for existence, but not for the correct position. Still changes in Button or Link renderers will not affect this test.

**Review by thibsy — APPROVED** [review]
Hi @alex40724

Thanks for your explanation. I can see your reasoning and will merge this PR now, since this was also merely a suggestion and using a hash-code is already a nice improvement. In the future we can ask ourselves, if a rendering test can be sufficiently covered by just a `str_contains()` check, to reduce redundancy if e.g. elements are always rendered in the same place. We must be careful not be too minimalistic though.

Kind regards
@thibsy

**Pull request merged**
