### PR TITLE
PHP 7.2: Changed assert() using strings (deprecated)

### PR DESCRIPTION
**Pull request by mjansenDatabay**
With PHP 7.2. assertions using strings as argument will emit an E_DEPRECATED .

- http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.assert-string-arg
- http://php.net/manual/en/function.assert.php

### CODE REVIEW

**Comment by klees** [comment]
Hi Michael, thanks a lot for this PR. I'm not sure if we want do do this right now. PHP 5.6 will  execute the code contained in the assertion, even if assertions are switched off. That is the reason why we chose that string-version, PHP won't execute anything then. That argument seems to be mostly academice, though, as we only have a small amount of assertions.
Best regards!

**Comment by mjansenDatabay** [comment]
We decided wo wait until the trunk is open for new features... Furthermore merging this PR depends on the decision whether we will further support PHP 5.x

**Comment by klees** [comment]
@mjansenDatabay and me talked about this and decided to leave this upon until a possible deprecation of PHP 5.6 for the next ILIAS is decided. We will create an according FR and bring it to discussion on some JF.

**Comment by klees** [comment]
Since PHP 5.6 won't be supported in ILIAS 5.4 anymore, I'm happy to merge this. Thx @mjansenDatabay!

**Pull request merged**
