### PR TITLE
Global Screen: Fix an issue where the 'Basic.js' file is included aft…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…er the 'dist/GS.js' and 'il.GS' is undefined

### CODE REVIEW

**Comment by chfsx** [comment]
Thanks a lot!

**Comment by mjansenDatabay** [comment]
Wow @chfsx :-)

**Comment by chfsx** [comment]
:D

**Comment by mjansenDatabay** [comment]
OK, this causes another issue, I'll fix this.

**Pull request merged**
