### PR TITLE
UI Components: Fix of 26259

### PR DESCRIPTION
**Pull request by Amstutz**
Proposal to fix the Add New Item Issue, see: https://mantis.ilias.de/view.php?id=26259

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @catkrahl , this PR is just to get the blessing of you for this fix, since it somewhat tackles the core of .il-layout-page-content. if you are fine with it, plz hit merge directly (of ping me back in case of insufficient perm).

**Comment by catkrahl** [comment]
Hi @Amstutz: sry, but the suggested solution will conflict with overflowing content in the main section. the overflow-property with the value "visible" will not force scrollbars in the main section with the class "il-layout-page-content". i think we have to find a different solution here...

**Comment by Amstutz** [comment]
damn it ;-) could overflow-x save us the day?

**Comment by catkrahl** [comment]
i tested all combinations, but nothing is working... i think the solution will be to have a responsive dropdown-menu which reacts to the varying space in the main section of the grid

**Comment by catkrahl** [comment]
imo the layering-concept in the grid is just working correctly, because it was intended that ALL of the content should be on a lower level than the maincontrols... except the dropdowns :( that is something we should rethink in the content revision, but doesn't the problem at the moment - i know! :(

**Comment by Amstutz** [comment]
well I do not have a strong opinion here, I just follow orders in this regard from the concept group ;-). IMO, making the content of the dropdown somewhat responsive seems to me personally the superior solution anyways. thx for the feedback.

**Pull request closed without merging**
