### PR TITLE
UI PresentationTable: 41643, revise and simplify expanding/collapsing of rows

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=41643

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM

**Comment by klees** [comment]
@nhaagen This would also apply to trunk, right?

**Comment by nhaagen** [comment]
> @nhaagen This would also apply to trunk, right?

yes, the differences are in the CSS for 8/9, i.e. LESS vs. SASS.

**Comment by Amstutz** [comment]
Picked manually due to conflicts in the delos.css.map

**Pull request closed without merging**
