### PR TITLE
TA: 30730, make MatchingQuestion sourceArea sticky

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=30730

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much  @nhaagen and sorry this took me so long!

Could you please fix the spacing [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6714/files#diff-fd8ea3febcb3753d26f543e007bddf981690e2aa6b3879314ad0ec6d4b85c97eR607) and I will then merge it as soon as @Amstutz gives me a green light.

I already added this to ILIAS 7 and 8 with: https://github.com/ILIAS-eLearning/ILIAS/commit/17f6599fa42bc79a1fb7e4d263a741a0ea033215

Thanks and best,
@kergomard

**Comment by dsstrassner** [comment]
Looking forward to this. Thanks to @nhaagen, @kergomard and at least @Amstutz ;-)

**Comment by kergomard** [comment]
Hi @nhaagen  and @Amstutz 

@nhaagen : Could you please fix the spacing and rebuild the CSS?
@Amstutz : Ok, if I then merge?

Thank you very much and best,
@kergomard

**Review by Amstutz — APPROVED** [review]

**Comment by kergomard** [comment]
Thank you all! Merged and picked to trunk.

**Pull request merged**
