### PR TITLE
Trunk LTI 001 - Adding dependencies & LTI Provider folder renaming

### PR DESCRIPTION
**Pull request by jcopado**
The composer.json file has been modified to include the php-jwt and LTI-PHP dependencies, required in the LTI module to stop including external libraries inside the module itself.

The LTI folder has been renamed to LTIProvider to maintain better consistency in component names.

### CODE REVIEW

**Comment by jcopado** [comment]
Work in progress :)

**Comment by jcopado** [comment]
Please, review :D

**Comment by mjansenDatabay** [comment]
Hi @jcopado ,

just one thought on this: If you want to make these dependencies explicit (which is good, thanks a lot) by adding them to the `composer.json` file, you should label this PR with the "JourFixe" tag and present it on Monday (last JF before the beta release of ILIAS 10.x).

See also: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/vendor/README.md

Best regards,
Michael

**Comment by matthiaskunkel** [comment]
Jour Fixe, 14 OCT 2024: Thanks for the PR. We accept the dependencies and renaming. But we prefer to split up the PR into three PRs, each dedicated to one subject: one for adding 'php-jwt', one for adding 'LTI-PHP' and one for renaming the 'LTI' directory to 'LTI Provider'. 
Concerning the two dependencies: please give a short explanation why you need them and add a short information about the status of mainenance of the libraries and which components in ILIAS use them (we assume LTI and LTI Consumer).
The new PRs can be merged to trunk before Coding Completed. No additional discussion in JF needed.

**Comment by dsstrassner** [comment]
hi @jcopado & @ZallaxDev with the merge of #8232 and #8220 and #8216, this PR could be closed?

**Pull request closed without merging**
