### PR TITLE
UI Dropdown: Added description and rule for empty dropdowns

### PR DESCRIPTION
**Pull request by Amstutz**
I promised to the JF to provide some additional description for the dropdown in case of empty dropdowns, see: https://github.com/ILIAS-eLearning/ILIAS/pull/1078.

This is it.

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM.

As a side note: The problem I initially expected to arise with the quite unusual "don't render if empty"-behaviour actually showed in real life. My colleague spent some time to figure out, why his dropdown wasn't included in the GUI just to find out that it was actually included but not rendered. I hope this will actually avoid that problem for other people, but honestly doubt that. People almost never read documentation.

**Comment by klees** [comment]
This fails tests due to formatting of the YAML-string. See "Checks"-tab, then click on "The Build" and on one job afterwards.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 27 AUG 2018 : Timon changed the rules according to the JF decision for PR1078.

**Comment by Amstutz** [comment]
Yes, the system with travis (and units tests as such) works! Nice to see. Thx everybody involved with travis catching helping catching this one and future ones.

The tests pass, @klees I think this is mergeable now. Won't do it myself, since this is my contribution.

**Pull request merged**
