### PR TITLE
Fix 37898: Use ilPropertyFromGUI to access post values

### PR DESCRIPTION
**Pull request by pascalseeland**
Fixes using the $_POST variables directly inside a deeply layered service.

https://mantis.ilias.de/view.php?id=37898

### CODE REVIEW

**Comment by pascalseeland** [comment]
Please check the changes to your module and merge, if you are the last reviewer. Thx

**Review by alex40724 — APPROVED** [review]

**Comment by chfsx** [comment]
@pascalseeland is that correct, that you can already use the new forms? because with ILIAS 9 we will have changed all setting forms to UI\Inputs.

**Comment by pascalseeland** [comment]
@chfsx yes, instead of [addSettingsToForm](https://github.com/ILIAS-eLearning/ILIAS/blob/aa2da4613651c8a9ccafd80cefcfa775555bd7cd/Services/WebServices/ECS/classes/class.ilECSObjectSettings.php#L126) you should be able to [getSettingsSection](https://github.com/ILIAS-eLearning/ILIAS/blob/aa2da4613651c8a9ccafd80cefcfa775555bd7cd/Services/WebServices/ECS/classes/class.ilECSObjectSettings.php#L196) from ilECSObjectSettings.

**Review by chfsx — APPROVED** [review]

**Comment by dsstrassner** [comment]
Hi @pascalseeland, when are you planning to merge this PR?

**Comment by pascalseeland** [comment]
@dsstrassner as soon as @smeyer-ilias approves the changes to his modules.

**Review by smeyer-ilias — APPROVED** [review]

**Comment by smeyer-ilias** [comment]
Thanks, @pascalseeland !

**Comment by dsstrassner** [comment]
> @dsstrassner as soon as @smeyer-ilias approves the changes to his modules.

So, the next days, that the pretesting can start? ;-)

**Comment by oliversamoila** [comment]
Hi. @pascalseeland 
If the PR fixes the named issue at https://mantis.ilias.de/view.php?id=37898, it would be helpful if the PR is linked in the Mantis ticket and the Mantis ticket represents this new status.

**Pull request merged**
