### PR TITLE
CSS: Table actions, fix #28414 Revised

### PR DESCRIPTION
**Pull request by Amstutz**
Thx for the feedback of @alex40724 in https://github.com/ILIAS-eLearning/ILIAS/pull/2739. Kudos for spotting the error.

There seemed to be some rebasing issue in the old PR, so I opened this new. Hope that is oke.

### CODE REVIEW

**Comment by Amstutz** [comment]
@alex40724 , fine with you if I merge this? This would resolve several rather annoying related issues.

**Review by alex40724 — APPROVED** [review]
Yes, thanks.

**Comment by catkrahl** [comment]
@Amstutz: there is something wrong in the stylecode for the responsive-table-class, why this fix is not working. the math-operation in the media-query should stand in brackets and only operate with numbers not with px. so the right expression should be: 
(@grid-float-breakpoint-max + 1)).
only this gives back the intended result of 769px after compiling on my local system! could be that the operation without brackets and  "+1px" only fails in my version of lessc?!
all the best CK

**Comment by Amstutz** [comment]
Thx @catkrahl for the feedback. Yes, the issue has been fixed here (see also discussion referenced in the mantis ticket referenced there): https://github.com/ILIAS-eLearning/ILIAS/commit/f6ee992fbde575e7f7b949a57e48d13964c2a0da#diff-b7e54a2a697227a83d63170b3971b007 .

However, this is also a lessc version issue. It those not seem an issue on the latest lessc version.

**Pull request merged**
