### PR TITLE
RFC: Mechanics for the Setup

### PR DESCRIPTION
**Pull request by klees**
Dear all!

I kindly request your comments, feedbacks and questions regarding these basic mechanics for the setup. I hereby propose to rebuild the setup around four basic abstractions:

* [**Config**](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-2a7764057fea4af5408b938985ae16d3) - Some options or configuration for the setup process that a user can or must set.
* [**Objective**](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-5ebc7eb1794c534269ee52453b57bca9) - Some desired state of the system that should be achieved via the setup process, maybe depending on other objectives as preconditions.
* [**Agent**](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-c28b50b130c9385a5bb27f949ad0c03f) - Some component performing parts of in the setup process is refered to as agent.
* [**Environment**](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-d56dd209f33d8a848bafe72798fa7dd1) - Some surrounding of the setup process which the objectives build and depend upon.

Please find further details in the [README.md](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-d0d013c3d488e60e1bd209724fa563ab). To show how these abstractions could be put into use, I started to implement a command line interpreter that installs the database. You may try to use it by creating an `install.json` like [this one](https://gist.github.com/klees/c5ca52a39e3d4be2dea600dc613ed07a) and call it via `php setup/cli.php install install.json`.

Please note, that the changes I propose here will move the real work of the setup to the components that actually want to or need to participate in the setup process. I will be happy to perform that refactoring, but also would transfer the maintainership of the resulting code to the respective components in that process. As a first step I would propose to hardcode that dependencies (like I did with the Database in the [cli.php](https://github.com/ILIAS-eLearning/ILIAS/pull/1868/files#diff-e72cbaeaa14c49839d7ee368b8c2854e), but probably collect them dynamically later on. I'm also looking to provide some simplified interface for components that only require database updates in the setup process.

My first target is to build a working setup for the command line with these new abstractions for ILIAS 6.0, then make the current setup GUI use these new abstractions and completely redesign it afterwards. This most probably won't happen for 6.0. I also prepared [respective feature request in the feature wiki](https://docu.ilias.de/goto.php?target=wiki_1357_Setup), but I'm looking to find an approach to consolidate the technical basis of the setup based on the current requirements first.

I'm looking forward to your questions, feedback and comments. Depending on the variety and amount of the feedback I might invite to a skype session, but I think we should try this asynchronous approach first.

Best regards!

### CODE REVIEW

**Comment by alex40724** [comment]
@klees Looks great. Thanks! We could use similar concepts for our "init" process, right?

**Comment by klees** [comment]
Thx @alex40724!

> We could use similar concepts for our "init" process, right?

Yes, I agree. I'm not sure if it needs to be that elaborate, though. The dependency injection container already provides a similar mechanism regarding dependencies of components. This might already be enough to spin up the system during init.

I did not use that mechanism for the setup because the setup seems to need more focus on and more elaboration of the single steps, while the steps are only single functions in the DIC.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 17 JUN 2019 : Richard gave a short overview about his development efforts for a new setup, especially for mechanisms to control dependencies during the setup. All maintainers are pleased to go through this PR and to post questions and comments asap.

**Comment by Amstutz** [comment]
Hi @klees 

Since you asked me today to perform a review on this, ill do so.

Special thanks for adding the readme.md in /setup and the tests. Espacially the nicely worked out readme really eased the understanding of this. 

Please answer the following questions:
- [x] Sympfony dep.: Why did you add the Symphony Dep. for CLI, is this really worth it?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [x] Php-Doc Comments: You mostly did not add them (except for the src folder), why? Probably add.
- [x] Todos: There are todos in your code. Any possibility to get rid of some more of them?

- [ ] Sympfony dep.: I did not fire php cli. I do not know symphony command, but from what I gather from InstallCommand I would need to do something like: `php ./iliasdir/cli —config=my_config`? Or is it: `php ./iliasdir/cli my_config`? Maybe add to your doc or at least point to the respective symphony doc.

Please implement the following changes:
- [x] symfony/console dep.: Add the approved-by and approved-date field, see: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/libs/composer#dependencies-for-production

 Please note, that I do not have any final say on this, since I do not maintain this component. The JF has given it’s oke, anyways.

kindly,
@amstutz

**Comment by klees** [comment]
Dear JF,

I forgot to explicitly ask for approval to include "symfony/console" in our project. May I do so?

Best regards!

**Comment by klees** [comment]
Hi @Amstutz,

thanks for looking into this, much appreciated!

> Sympfony dep.: Why did you add the Symphony Dep. for CLI, is this really worth it?

Yes, it is really worth it. It brings a lot of boilerplate, that we would need to write and maintain by ourselves otherwise, e.g. for...:

* ...defining and parsing of options and arguments.
* ...providing help for users based on the available command-definitions.
* ...creating nice and readable output with minimum effort.

Enough commercials =)

If we want to have a usable CLI-program (and not just some script) I don't see an alternative to include a library like this. I'm open for other suggestions, though. Note, that this is about boilerplate, not functionality, so I don't see us depend on that library too much.

> Php-Doc Comments: You mostly did not add them (except for the src folder), why? Probably add.

With the introduction of typehints (and increasing functionality of IDEs and such) I lately felt that we do not get to much additional value from adding Php-Docs in some (or even many?) cases. I mean: if I would add a Php-Doc to e.g. `ilDatabaseCreatedObjective::getLabel`, what would I even put in there that adds value to a reader? This is different for src, because we need to inform people what they need to implement and how. I might have missed some opportunity to in fact add value, though, and will look into this. Also my opinion might be controversial and I'm happy to see rebuttals.

> Todos: There are todos in your code. Any possibility to get rid of some more of them?

For two of them (in `ilDatabaseSetupAgent`) this depends on other components (PHP and Refinery). I'm not sure about variance in PHP, the Refinery should be ready soon. The metainformation for the app will follow soon. Note, that I wanted to show the model that I propose for the setup process. The implementation of a CLI-program for the setup certainly needs more than this PR contains, not only app-metadata.

> Maybe add to your doc or at least point to the respective symphony doc.

If you just type `php setup/cli.php` the programm will tell you the rest, or at least some of it (see your question about that dependency). But still, the CLI-program does deserve a docu in ILIAS as well. This is another thing that a CLI-programm will need. I will follow up on this soon, but most probably not in this PR.

> symfony/console dep.: Add the approved-by and approved-date field, see: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/libs/composer#dependencies-for-production

Yes. And even more important: ask the JF to approve the dependency. Thanks for pointing that out!

Best regards!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 01 JUL 2019 : We accept the introduction of the library "symfony/console" in trunk.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 01 JUL 2019 : We highly appreciate this PR and accept it for trunk.

**Pull request merged**
