### PR TITLE
removed static call of a nonstatic function

### PR DESCRIPTION
**Pull request by dkloepfer**

### CODE REVIEW

**Comment by dkloepfer** [comment]
Also belongs into 5.1

**Comment by klees** [comment]
@smeyer-ilias GitHub suggested you, or do we have some other maintainer for the setup?

**Comment by smeyer-ilias** [comment]
Current maintainer is Alex according to https://www.ilias.de/docu/goto_docu_pg_9985_42.html
But I feel responsible for these lines.

**Comment by smeyer-ilias** [comment]
Thank, merged.

**Pull request merged**
