### PR TITLE
Fix for Survery detailexport (#37733)

### PR DESCRIPTION
**Pull request by mdezi**
excel detail export didnt function when trying to export surverys containing freetext answers - tried to access an array without checking wether the array key is set.

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @mdezi for the PR!

I labeled it as 'improvement' as there is no Mantis-Issue for it, but it looks rather like a 'bugfix'. Please see our guidelines for PRs here: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/contributing.md#rules-for-contributors

Thanks again and best,
@kergomard

**Comment by alex40724** [comment]
@mdezi Thanks for the PR. Could you please provide a bug report according to the mentioned guidelines. Thanks.

**Comment by mdezi** [comment]
I had commented my changes in this ticket ( https://mantis.ilias.de/view.php?id=37733 ) as it describes a similar case with the same issue. Shall i make a new ticket for it instead?

**Comment by alex40724** [comment]
Thanks, this should be fixed in the meantime.

**Pull request closed without merging**
