### PR TITLE
Test&Assessment: Shortlist star flag icon and formatting - Mantis #32215

### PR DESCRIPTION
**Pull request by catenglaender**
Mantis Issue: https://mantis.ilias.de/view.php?id=32215

Is dependent on PR https://github.com/ILIAS-eLearning/ILIAS/pull/4156 and https://github.com/ILIAS-eLearning/ILIAS/pull/4157 which are included in first commit for reference and testing.

# Issue

* Marked star icon was placed below marked question title in shortlist, which makes it hard to see which question is marked and wastes a lot of space
* h3 tags in a menu list are not good accessibility practice for screen readers, because no actual content follows there.

# Changes

* Marked star icon in shortlist now appears next to the question title, which makes reading the list a lot easier.
* Shortlist uses just li tags instead of h3 tags, which was a problem for screen reader accessibility
* Font size of shortlist now comes from core delos.less

image

### CODE REVIEW

**Comment by dsstrassner** [comment]
Thanks a lot! You mean #4156 and #4157?

**Comment by catenglaender** [comment]
Yes, indeed. I corrected it in the PR description.

**Comment by dsstrassner** [comment]
hi @catenglaender!

We discussed this PR today @ TechSquad! 

For me as T&A maintainer, this is the right solution to the problem. This consent was missing in the PR until today.

@nhaagen will communication internally with you about the next steps.

**Comment by catenglaender** [comment]
To solve merge conflicts, this is now part of this PR: https://github.com/ILIAS-eLearning/ILIAS/pull/4792

**Pull request closed without merging**
