### PR TITLE
Trunk CI: adjust cs fixer to work with psr-12. See PR #4533.

### PR DESCRIPTION
**Pull request by daniwe4**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@daniwe4 This seems to be a (partly) duplicate of #4877

**Comment by klees** [comment]
I kindly asked @daniwe4 to start fresh, this is the result =) I'll close the other one.

**Comment by klees** [comment]
This does not include an automatic fix for the new rule regarding variable and property naming: "Names of properties and variables MUST be written in underscore-case."

I currently cannot find an according PHP-CS-Fixer rule to make this happen, so I'll take this 95% here...

**Comment by klees** [comment]
Picked to trunk and release_8.

**Pull request merged**
