### PR TITLE
Setup: Tiny changes

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Review by klees — COMMENTED** [review]
LGTM!

**Review by klees — APPROVED** [review]

**Review by chfsx — APPROVED** [review]
Thanks!

**Comment by klees** [comment]
@ILIAS-eLearning/technical-board Anybody else wants to have a look?

**Comment by alex40724** [comment]
+1 (trunk)

**Comment by Amstutz** [comment]
TB: We are fine with this PR, merge plz.

**Pull request merged**
