### PR TITLE
Administration: show more git information (origin-url and branch added)

### PR DESCRIPTION
**Pull request by jbraun-ilias**
@mjansenDatabay

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@jbraun-ilias Thanks for your contribution. Please add some information (which kind of GIT information is added here  -of course I can see this when reading the code) regarding the purpose of this change to the description field of this PR.

**Comment by jbraun-ilias** [comment]
origin-url and branch added

**Review by mjansenDatabay — APPROVED** [review]

**Comment by alex40724** [comment]
Thanks for the PR, sorry for letting you wait. For me this change is ok, but the JF should give ok, too.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 14 SEP 2020 : We accept this PR for trunk. Please merge.

**Pull request merged**
