### PR TITLE
WIP: GlobalScreen: Client-Side Notifications 

### PR DESCRIPTION
**Pull request by chfsx**
As mentioned in PR #2099, this PR contains the extensions for client-side notifications (required by the chat in ILIAS 6).

Note: This is not a general approach how to do client-side rendering in ILIAS or even bypass it. This mechanism is implemented due to the missing client-side rendering for the requirements of chat notifications. The discussion about client-side rendering will be conducted separately and should provide a general approach.

This part of the GlobalScreen service also contains TypeScript code. Work is already underway on this in a wide variety of places. This suggestion here is not to bypass this by any means or to deliver final concepts for the use of TypeScript in ILIAS. TypeScript was only used here to have a more understandable and secure structure in JS. We are already looking forward to the discussions about TypeScript.

@mjansenDatabay will take over from here and implement the UseCases in the chat notifications. 

This PR also contains all changes from #2099

### CODE REVIEW

**Comment by chfsx** [comment]
@mjansenDatabay this may get closed, isn't it?

**Comment by Amstutz** [comment]
IMO, yes.

**Comment by mjansenDatabay** [comment]
Yes @chfsx / @Amstutz

**Comment by Amstutz** [comment]
@mjansenDatabay You really must learn, how to block notifications, when your are not in office :-)

**Pull request closed without merging**
