### PR TITLE
sort langfiles

### PR DESCRIPTION
**Pull request by nhaagen**
Dear colleagues,
when dealing with translations, I find it somewhat cumbersome to align languages or keep track of related constants throughout the files.

A fairly minor step, that imo will help a lot in terms of clearness, though, is the simple alphabetical sortation of modules/constants.
This will not have any impact on programmatical mechanisms, and can be achieved quite simply
with linux commands:
(head -n 16 ilias_en.lang && tail ilias_en.lang -n +17 | sort ) > ilias_en.s.lang && mv ilias_en.s.lang ilias_en.lang

Please kindly consider, and best regards,
Nils

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Thx a lot @nhaagen . IMO we need an automatic mechanism for this, maybe a `pre-commit` hook which executes a script sorting the lines of all language files to be committed.
Otherwise there will be chaos again in a few weeks :-).

**Comment by matthiaskunkel** [comment]
Thanks, @nhaagen, from my side, too. Having an automatism as @mjansenDatabay suggests would be fine. But first we have to agree on the suggestion in general. I know some developers who prefer to have all new language entries at the bottom of the English and German language file as this makes it easier for them to handle all there branches. I'll add this suggestion to the JF agenda next Monday and ask the JF: "Do we want to have sorted language files or not?".

**Comment by nhaagen** [comment]
Would a hook like this be feasible?

for f in `ls *.lang`; do (head -n 16 $f && tail $f -n +17 | sort ) > tmp."$f" && mv tmp."$f" $f; done

**Comment by matthiaskunkel** [comment]
Jour Fixe, 23 AUG 2021: There is a clear vote for sorted language files. This might also prevent merge conflicts when committing language entries for different versions of ILIAS. We will continue the discussion how an automated process for sorting could look like.

**Comment by nhaagen** [comment]
I'm closing this in favor of #3575

**Pull request closed without merging**
