### PR TITLE
Fix/5 1/umask usage correction

### PR DESCRIPTION
**Pull request by d3r1w**
This pull request addresses the usage of the umask within ILIAS.
The following changes are made to address the discussed problem:

- Changed umask calls from 0000 to 0022
- Changed the mkdir calls permission to 0755

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
Thank you a lot for this fix! I can only approve the parts I messed up ;-), they seem fine.

**Comment by smeyer-ilias** [comment]
Some thoughts about a trunk change: 
Does anyone see problems with removing all ocurrences of umask() and chmod() in general?
I mention this because any manipulation of umask settings and direct chmod calls limits the possibilities of server administrators. One example:

Currently it is possible to initialize the directory permissions on the command line with 2775 (setting the SGID-Bit). If ILIAS creates directories with 755, the SGID information is lost for all newly created subdirectories. 

Furthermore a note from http://php.net/manual/en/function.umask.php:
"Avoid using this function in multithreaded webservers. It is better to change the file permissions with chmod() after creating the file. Using umask() can lead to unexpected behavior of concurrently running scripts and the webserver itself because they all use the same umask."

I think that even chmod is not required. The webserver-user and the group should have all permissions to read and write all files. If a webserver admin wants to reduce the permissions he can set a umask in the profile of the webserver user or in the apache envvars-configuration. But all this is not possible if ILIAS manipulates the permissions.

**Comment by Amstutz** [comment]
This is since some weeks now an open issue in TB discussions. A server admin complained about the way umask is used currently. I am no expert in this, but to me it seems we have to choose between many imperfect options, and that is the current proposal. However, thanks for your feedback and insight: @all: Should we discuss this in the upcoming JF on monday?

**Comment by matthiaskunkel** [comment]
Jour Fixe, September 11, 2017: We postpone the discussion to allow the TB to discuss this PR again.

**Pull request closed without merging**
