### PR TITLE
Feature orgu extension

### PR DESCRIPTION
**Pull request by otruffer**
Implementation of Org Unit Extensions as defined in: http://www.ilias.de/docu/goto_docu_wiki_wpage_4020_1357.html

Test Plugin:
https://git.studer-raimann.ch/otruffer/SimpleReport

### CODE REVIEW

**Comment by alex40724** [comment]
@fschmid: Did you check this code already? It would be good, if you could check it first and hand it over to me afterwards, since I do not have that much time currently. Please take a look especially at "seperation of concern" and related issues. E.g. ilPlugin should be a "general" code base and not include slot specific code.

**Comment by chfsx** [comment]
HI @alex40724 I'll have a look at it this afternoon

**Comment by chfsx** [comment]
@alex40724 we moved the RepObj/OrgExt specific code from ilPlugin to ilObjectPlugin.

**Comment by alex40724** [comment]
Looks ok for me now.

**Pull request merged**
