### PR TITLE
Fix/23298/trunk/save confirmation anonymous

### PR DESCRIPTION
**Pull request by chfsx**
Hi @alex40724 
For the Fix in https://mantis.ilias.de/view.php?id=23298 we need some adjustments in ilPropertyFormGUI. Fileuploads should be able to stay on a confirmation screen in DataCollection even if the the user is anonymous. therefore a change to the session id instead of the user id is needed.

feel free to give any feedback of if you need further explanation. thanks in advance!

### CODE REVIEW

**Comment by alex40724** [comment]
Hi @chfsx, 

Thanks for looking into this. I am not a big fan of the original code.

The user_id -> session_id move is definitely ok for me. I do not fully understand the changes related to the $reload arrays.

Please answer the following questions:
- [x]  Is writing into the $_FILES array unavoidable now?

In general the code change is ok for me. You may merge this, but please be available, if any issues arise due to this change. Otherwise I may revert this, if I do not find another way out. :-)

Best
Alex

**Comment by chfsx** [comment]
@theodortruffer could you have a look at this? Thanks!

**Comment by theodortruffer** [comment]
Hey @alex40724 

>  Is writing into the $_FILES array unavoidable now?

Yes, there seems to be no other way: The problem is that in almost any place where the ilFileInputGUI is used, the code directly accesses $_FILES instead of calling ilPropertyFormGUI::moveFileUpload (not sure why). 
So when you have a save confirmation or checkInput() fails, ilPropertyFormGUI stores the files as tempFiles on the disk and _re_stores them into a protected instance variable $reloaded_files. But since it is protected, it will only be found by using ilPropertyFormGUI::moveFileUpload - and $_FILES will be empty.

In ILIAS 5.3 I found 1 usage of ilPropertyFormGUI::moveFileUpload and 18+ files where $_FILES is accessed directly. 

I didn't like writing into $_FILES either, but I didn't see another way..

Thanks,
Theo

**Review by alex40724 — APPROVED** [review]
Ok, thanks for the explanation.

**Pull request merged**
