### PR TITLE
fixed 0028471: removed grid in print-styles

### PR DESCRIPTION
**Pull request by catkrahl**
This fixes the print styles for longer page content.

https://mantis.ilias.de/view.php?id=28713

### CODE REVIEW

**Comment by klees** [comment]
@Amstutz Looks plausible to me. Want to have a look?

**Comment by Amstutz** [comment]
Hi @catkrahl and @klees 

Thx a lot for this. The proposed solution resolves the issue with printing only the first page in FF. However, it introduces a new one by displaying dropzones in print view in the content pages of courses for admin. I look into it. Ill get back to you here.

Thx.

**Comment by Amstutz** [comment]
Seems like .ilFileDropTargetOverlay is suddenly shown, due to the new display block type for print view. Display Block is added inline per JS, so this will certainly solve the issue (in media print):

```
    .ilFileDropTargetOverlay{
      display: none !important;
    }
```

However, you might finde a way working around the `!important ` statement.

**Comment by catkrahl** [comment]
i found out the same solution and will update this PR... thx @Amstutz

**Comment by catkrahl** [comment]
@Amstutz: i removed all the relevant container-classes in the print-query. please have a look... now printing seem to work fine in FF without any droptargetoverlays...

**Comment by klees** [comment]
@Amstutz Are you on this? IMO we could merge this and apply it to release_6 as well. I do not like the `!important` but currently do not see a realistic and fast way to solve this more generally. Print style seems to be an angle we need to look at when thinking about SASS and KS elements, currently we are not very good in this department.

**Comment by Amstutz** [comment]
Yes on it, only thing left is compile to CSS, then this is ready for 6 and trunk.

**Comment by klees** [comment]
Also picked to release_6: https://github.com/ILIAS-eLearning/ILIAS/commit/569358bfcb473866a727a293e0404a9a3ac4f473

**Pull request merged**
