### PR TITLE
UI: add padding to legacy UI's form buttons positioned in the footer.…

### PR DESCRIPTION
**Pull request by lukastocker**
… (#39609) 

https://mantis.ilias.de/view.php?id=39609

### CODE REVIEW

**Comment by lukastocker** [comment]
Hi @Amstutz ,

please have a look at this PR. It works so far, but I am not 100% sure if it will have a negative impact on other legacy forms. Therefore I would love your input.

Greetings
Luka

**Comment by Amstutz** [comment]
@catenglaender mentioned, that he wanted to have a close look at this one. I forwarded it therefore to him, thx a lot!

**Comment by catenglaender** [comment]
We had a look at it today, this is indeed the correct way to do it! :slightly_smiling_face:  One more annoying padding gone! :tada:

(That cursed row outside of it styled with `.form-horizontal .form-group { margin: 0 }` though... we have to get rid of that in ILIAS 10 - it will break the look of all forms temporarily, but it's a good way to move this mess forward)

**Comment by Amstutz** [comment]
thx a lot!

**Pull request merged**
