### PR TITLE
T&A: BulkEdit Questions in Pool

### PR DESCRIPTION
**Pull request by nhaagen**
https://docu.ilias.de/go/wiki/wpage_8316_1357

adds bulk-editing for author, lifecycle and taxonomies to the question pool.
The Taxonomies are currently selected by ilTaxAssignInputGUIs, not the ilTaxSelectInputGUI, because the modals used in the selectors are not working.

### CODE REVIEW

**Comment by dsstrassner** [comment]
@nhaagen Did you provide the customer an installation for "Abnahme". If you are, please send me a login, and therefore I could have a look. Thanks!

**Comment by dsstrassner** [comment]
Hi @thojou could you please have a look on the code? Thanks!

**Review by dsstrassner — APPROVED** [review]
Hi @nhaagen, thanks for the PR. This looks fantastic from a user's view. 
After the merge of #7788, I could also test the function of bulk edit for all questions in a pool. But I have no doubt, that this will also work like a charm ;-)

Dear @thojou, please look at the code and review it.

**Comment by dsstrassner** [comment]
@nhaagen will adjust the PR accordingly to the discussion in the TechSquad today.

**Comment by nhaagen** [comment]
Updating data in transformation was deemed an antipattern, I'll adjust accordingly.

**Comment by nhaagen** [comment]
Hi @thojou,
please have another look.
Persistence is called seperatedly from tranformations now, 
with quite little impact on code structure.

Thanks and best regards

**Comment by dsstrassner** [comment]
@dsstrassner will check this later because of the test cases ;-)

**Comment by dsstrassner** [comment]
Test Cases are adapted. It is your turn @thojou!

**Comment by thojou** [comment]
Hi @nhaagen,

thanks for your changes. I merged this PR into trunk.

**Pull request merged**
