### PR TITLE
Administration: show more git information (origin-url and branch added)

### PR DESCRIPTION
**Pull request by jbraun-ilias**

### CODE REVIEW

**Comment by jbraun-ilias** [comment]
@mjansenDatabay

**Comment by mjansenDatabay** [comment]
@jbraun-ilias Thanks for your contribution. Please add some information (which kind of GIT information is added here -of course I can see this when reading the code-) regarding the purpose of this change to the description field of this PR.

**Comment by jbraun-ilias** [comment]
origin-url and branch added

**Review by mjansenDatabay — APPROVED** [review]

**Comment by mjansenDatabay** [comment]
We/The JourFixe accepted this for `trunk`, but not for our stable releases.

**Pull request closed without merging**
