### PR TITLE
UI: Data Table

### PR DESCRIPTION
**Pull request by nhaagen**
Dear colleagues,
this introduces a data table for the UI framework.  
The idea is to easily setup and use a table to display tabular data. The Data Table shall bring common ViewControls along (see #2540) and digest Requests. Also, Data handling and presentation are well separated. This is probably well expandable on the Presentation Table to the extend of a common Table-Interface, but this is a second or third step.. 
Please [see the example](https://github.com/ILIAS-eLearning/ILIAS/pull/2679/files#diff-da67b86bfcde546a13848a188b8970a2) to [get an idea off how to operate](https://github.com/ILIAS-eLearning/ILIAS/pull/2679/files#diff-3cd5007db3b37227ff61c805714a82c1) the table, and [find some rules here](https://github.com/ILIAS-eLearning/ILIAS/pull/2679/files#diff-488841fa74a3b3894b10afa09f10f507).

Please note that this is to describe the basic mechanics of a Data Table (or UI Tables in general). The Columns in this PR are most simple ones and of equally exemplary nature - e.g, adding an action-column should be quite easy. I'd consider this as an extension or follow-up, though, and would like to separate column types from this PR. There certainly are more...

Another point is the usage as tabular form - starting from checkboxes for row-selection, but then going really fast to ordering (dragging?), text-inputs in cells, etc. 
For this, I'd rather imagine a derivate of this table in the Form/Input section or maybe a different concept altogether.

Thanks for your kind consideration ;)

### CODE REVIEW

**Comment by klees** [comment]
@Amstutz I would show this on JF to gather some early feedback and raise awareness that this is happening. If you disagree and want to work on this without JF first, feel free to do so and remove the JF-label.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 27 APR 2020 : Richard asks all developers for feedback to this suggestion. PR will be presented in one of the upcoming Jour Fixe meetings.

**Comment by atoedt** [comment]
Hello, 
I was asked to look at this, but I cannot read code. Please gather the rules together for commenting. 
Please explain a little what this is good for. 

Tables in ILIAS contain interactive elements (Action-Dropdowns or Action links, Paths to objects, checkboxes for selection and so forth.) This is why I reckon that from an aria authoring perspective this [would be a grid](https://www.w3.org/TR/wai-aria-practices-1.2/#grid) with [examples](https://www.w3.org/TR/wai-aria-practices-1.2/examples/grid/dataGrids.html). 

However I cannot be sure of this because the PR is not digestable for me. 

best regards

Alexandra

**Comment by klees** [comment]
Hi @atoedt,

Thanks for the hint to aria-grid.

The [rules](https://github.com/ILIAS-eLearning/ILIAS/pull/2679/files#diff-488841fa74a3b3894b10afa09f10f507) are already linked in the [initial comment from @nhaagen](https://github.com/ILIAS-eLearning/ILIAS/pull/2679#issue-408528864). Also some explanation what this is good for: "The idea is to easily setup and use a table to display tabular data.". This explanation also goes in the `purpose`-section of the KS-entry, as practiced now for several years and linked in Nils' initial comment.

I offered to show you how to digest and interact with these kind of PRs personally on several occasions, but until now you did not catch up on this offer. For this reason I need to consider your comment that this "PR is not digestable" as simple trolling. **If anyone has problems understanding what's going on here and [the README of the UI Framework](https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-4/src/UI/README.md) does not help, [@Amstutz and I are available for further explanations](https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-4/src/UI/README.md#i-dont-understand-that-stuff-is-there-anyone-who-can-explain-it-to-me).** This offer has been accepted by various people now. There also are people in your very company that can help you with this stuff, if @Amstutz or I are not acceptable for any reason.

Best regards!

**Comment by maxbecker** [comment]
No detailed review but this looks compelling. I support. :)

**Comment by mjansenDatabay** [comment]
Thanks for this pull request :fireworks: 

As @atoedt already mentioned I am missing some interface to add an additional action column (basically a `Dropdown`) when comparing this to our current tables. Furthermore in most cases rows should be selectable, so the rows should be aware of a leading `Checkox` or `Radio Button` element.
All this components should be optional per row.

Maybe another requirement for a new table could be col and row spans, which are currently not addressed as well but sometimes used in our code base.

**Comment by nhaagen** [comment]
Thanks for your comments - I'll add some lines regarding actions/checkboxes in the description.

**Comment by klees** [comment]
Hi @mjansenDatabay,

thanks for the input!

Could you expand a little on what you would expect of row or col spans?

Regarding the actions: @nhaagen added a little explanation in the initial comment how we would like to proceed with interactivity. We think that "actions" (per row as well as multi) can be incorporated easily within the mechanic we propose, but didn't want to elaborate on that to keep this PR and the discussions manageable. The current usage of tables as tabular forms is out of scope of this PR (and our contract with Uni Bern) and we also feel that these would rather belong to the inputs or even should be reconsidered altogether.

Hope this helps!

Best regards

**Comment by atoedt** [comment]
Timon has talked me through this, thanks. 

Elaborating on my comment above:
- From an accessibility persective there is a huge difference between some tabular structure that is static (Data table) and absolutely not interactive and a tabular structure allowing for interaction (grid).  
- Please consider [Requirements for Reflow](https://www.w3.org/WAI/WCAG21/quickref/#reflow) which seems to be relevant to tabular structures.
- I did not manage to find a static table with zero interaction in ILIAS. In ILIAS we use tabular structures overwhelmingly with interactions. This may be a shortcoming of mine and maybe one can find the odd fully static data table somewhere. Did you find a fully static tabular structure somewhere? Please point me. It would help me to review the proposed rules with the actual place in the system where it is to be used.

**Comment by alex40724** [comment]
@nhaagen Thanks for the PR. For the mentioned purpose this looks very good, my main concerns are that "tabular forms is out of scope of this PR (and our contract with Uni Bern)". The last workshop I attended related to data tables was over a year ago and I am not sure what plan Uni Bern is following here. I remember there where main concerns about a) pagination and performance of large data tables and also using b) forms, especially checkboxes for multi actions. Both may interfere with the interface greatly imo. So it is hard to tell, if this interface will fit the main purposes of data tables in ILIAS or not just because it does not serve the most common use cases and I don't think that we want things look to differently depending on the use of a checkbox column and multi actions. In fact it might be that depending on permissions these columns/actions need to be available for the "same" view or not.

**Comment by Amstutz** [comment]
Note, I have to review this myself, I am not through with it yet. However, since Uni Bern is mentioned, here some thoughts.

@alex40724 , thanks a lot for the feedback. 

>  I am not sure what plan Uni Bern is following here. 

Tables and their usages in various scenarios turned out to be quite some "monster" in the sense, that they can do and actually almost anything. The plan of the Uni Bern is not start of with a really base concept of tables, with features everybody can agree on a table MUST have and a flawless handling of data. I believe that to be given here and hope others see it as that as well. Personally I really do think that this will need to be extended with at least multi actions in a further step. Also, this PR serves exactly for that.

So in short: The Master Plan is to work with our fellow devs. here towards a solution everybody feels confident to work with in future, so that we finally can get rid of the much treated current table implementation. No hidden agenda behind that ;-).

> Both may interfere with the interface greatly imo.

May you elaborate somewhat on that? Indeed I talked with @klees on possible options to extend this table. We believe it to be very open for action menus and somewhat open towards multi actions. Some adjustments might be necessary, but we hope them to be manageable. We do not believe this version of tables to be open towards inline editing (at least not how it is currently done with form fields). Is that an issue? We shortly brainstormed on the inline editing matter came up with some ideas, but I believe that is for another day.

I hope this answer helps.

@atoedt :
Thanks for the feedback. You finger tipp vs. the grid vs table question is important. Can you point us to some references. Maybe we really do need to revise the name of the table slightly.

**Comment by atoedt** [comment]
I linked to the grid resource in my above comment. The data table info resides in the same document.

**Comment by mjansenDatabay** [comment]
@klees Regarding Colspan/Rowspan: I am thinking about something like a `CombinedColumn` interface, maybe derived from `Column`.  This could have a `withColspan` mutator. When the respective renderer renders such a column, this column expands over two cells, like a merged cell in Excel oder a `<th colspan="2">foo bar</th>` /  `<td colspan="2">foo bar</td>` in a HTML table.
Maybe the `CombinedColumn` as an derived interface does not fit into the current approach proposed here (because the different column types, number, text ..., all already implement `Column` and we should not introduce more factory methods for the same types just for being able to get a xyz column, but as `CombinedColumn`), but this could be an indicator that something like a `ColumnLayout` could make sense here.

Colspans are used in every `Permission` table in the ILIAS repository.

Maybe there are also use cases for rowspans, when cells are combined/merged vertically.

**Comment by nhaagen** [comment]
The last commit adds accessibility-rules to the table.
Thank you, @atoedt, for bringing up the W3C-references for this.

As you can see, I also favored the grid-role over the table-role,
mainly because of the passage
"[..] each widget contained in a table is a separate stop in the page tab sequence. 
If the number of widgets is large, replacing the table with a grid can dramatically 
reduce the length of the page tab sequence [...]"
here: https://www.w3.org/TR/wai-aria-practices-1.2/#table.

This said, there are some implications following, which I hope to have phrased 
correctly and understandable in the a11y-rules.
Please also see the templates, since the attributes show up there.

Refraining from < table >-elements should also take the Requirements for Reflow (https://www.w3.org/WAI/WCAG21/quickref/#reflow) into account.

**Comment by klees** [comment]
Hi @mjansenDatabay,

thanks for the hint. The permission table seems to use the HTML-colspan-feature for something like "sub headlines" or "blocks". These span the complete width of the table to separate different blocks of data. A "subheadline" would be a nice addition indeed and could also be incorporated easily as a second constructor on the `RowFactory`. I would propose to not add it now but instead rename `RowFactory::map` to `RowFactory::standard` to have some name space for other kinds of rows, like `RowFactory::subheadline`. This most probably would imply that tables using sub headlines cannot per sorted or at least have a much more involved behavior when sorting.

Do you have other instances for the use of colspan? I kind of see that we would want to have them in something like headlines and we could look into ways how to incorporate them, but currently I have trouble understanding how we would want to use them for data in rows. There might be ways to align data on a grid that makes good use of colspans (=> excel) but using tables as a mere layouting mechanism is not what we target here. This is about listing similar shaped records (see [`purpose`](https://github.com/ILIAS-eLearning/ILIAS/pull/2679/files#diff-488841fa74a3b3894b10afa09f10f507R100)).

I'm also not sure if we would really want to expose 2-d grids for layouts. IMO these are in conflict with requirements for responsive designs that need to be solved by experts on a case to case basis (see the e.g. the page layout in ILIAS). I thus currently doubt that we would want to expose such layout mechanism on a public interface of the UI framework. It is a lot simpler to deal with responsive layout if we ask our consumers to declare semantics of the stuff they want to show and then figure out a good way to build layouts for different situations internally. This is what makes a `subheadline` very different from a `colspan`.

Hope this makes sense. This is a very interesting point you raised there.

Thanks!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 11 MAY 2020 : Richard gave a presentation of the PR. Parts of the concepts will still be elaborated (e.g. columns). We highly appreciate this suggestion and accept the PR for trunk. In case of questions please post them here or contact Richard.

**Comment by Amstutz** [comment]
I discussed that with @rklees today. Ill merge the current state to trunk to ease to further dev. in this subject. Note that the interface has been accepted by the JF. Further changes on the interface would need to be discussed in the JF again. Further note, that a complete review on the interface will follow.

**Pull request merged**
