### PR TITLE
Bugfix 0035599 (ILIAS 8): Multiple Choice Question negative points

### PR DESCRIPTION
**Pull request by fhelfer**
This fixes error message mentioned in https://mantis.ilias.de/view.php?id=35599

### CODE REVIEW

**Review by iszmais — CHANGES_REQUESTED** [review]
LGTM, just some minor Change Request:

Since the origin of the problem is cause by the negative $max due to the test result i would suggest to extend the already existing prove (!$max) to the (also type correct) version ($max <= 0.0) and remove the correction within the precentage.

**Review by iszmais — APPROVED** [review]

**Comment by kergomard** [comment]
Thank you very much @fhelfer and @iszmais for the review!
I've just one question :

- The two lines [1008 & 1009](https://github.com/ILIAS-eLearning/ILIAS/pull/5200/files#diff-4b4aef42f36e91bcdb2b976ad60cd259d8529fe8eee217a86faa364022d27b6dR1009) are just a very convoluted way of saying that $isFailed = !isPassed, right? I would suggest to make this explicit and change the line 1009 correspondingly.

Thanks and best,
@kergomard

**Comment by fhelfer** [comment]
> Thank you very much @fhelfer and @iszmais for the review! I've just one question :
> 
> * The two lines [1008 & 1009](https://github.com/ILIAS-eLearning/ILIAS/pull/5200/files#diff-4b4aef42f36e91bcdb2b976ad60cd259d8529fe8eee217a86faa364022d27b6dR1009) are just a very convoluted way of saying that $isFailed = !isPassed, right? I would suggest to make this explicit and change the line 1009 correspondingly.
> 
> Thanks and best, @kergomard

Removed line [1009](https://github.com/ILIAS-eLearning/ILIAS/pull/5200/files#diff-4b4aef42f36e91bcdb2b976ad60cd259d8529fe8eee217a86faa364022d27b6dR1008) (isFailed)

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

**Pull request merged**
