### PR TITLE
#16622 and #16960 

### PR DESCRIPTION
**Pull request by shecken**
#16622 added tabs in administration
#16960 enable custom icon for studyprogramme

### CODE REVIEW

**Comment by klees** [comment]
Hallo Fabian!

Stefan hat das für mich gefixt, daher mein PR? Oder siehst du das anders?

Beste Grüße!

**Comment by chfsx** [comment]
Hallo Richard, dachte ich mir auch, war nur nicht sicher, da Michael Autor der Files war. Aber dann ist alles klar! Beste Grüsse zurück

**Comment by alex40724** [comment]
ilObject should not contain object type specific implementations.

I know that there are container type checks and a file bug related check, but I would not like to pollute this class more with type specific code.

**Comment by klees** [comment]
Hi Alex,

thanks for your feedback! I thought it would be ok, as there already are object specific implementations (for cat, grp, crs, root, fold) in the method.
I currently see no other possibility to implement the custom icons for the study programme, so i guess it would be the best to discuss the issue on the next JF. Maybe i'm missing something.

Best regards!

**Comment by alex40724** [comment]
Yes, JF would be appropriate. Thanks.

My reasoning is
a) OO principle is that specific code should go to specific classes, not to its parent classes. I think this is obvious in this case.
b) If a code maintainer violates agains this rule in his/her own code, he/she is reponsible for the results (gets the bugs, needs to do future refactoring, ...)
c) If b) is the case, this does not mean that the maintainer has necessarily to accept the same kind of violations from other developers, since this would increase the effort of future maintainership. In this case it would mean I would have to accept all kind of type specific code in ilObject, since there are already violations against this rule. 

I am sure that there is a way to implement this feature without the violation of basic OO concepts.

**Comment by klees** [comment]
Hi Alex!

No object orientation there, just a plain old procedure namespaced in a class. The type specific implementations already present in the procedure witness that.

I think i just found another way, still not object oriented, but might work without modifications to _getIcon. We'll try.

Best regards

**Comment by shecken** [comment]
Implemented another way to get the custom item for study program.

@alex40724
Please have a look on 1e02441.

**Comment by alex40724** [comment]
Thanks, ilObject looks better now. Since the programmes are containers this makes sense to me. I should remove this array by some isContainer call to objDefition in the future.

**Pull request merged**
