### PR TITLE
[FIX] 22201: lucene index files

### PR DESCRIPTION
**Pull request by chfsx**

### CODE REVIEW

**Review by smeyer-ilias — COMMENTED** [review]
Thanks.
I guess this change will also work with older ILIAS versions (5.2, 5.1) ? 
So it is not necessary to install different ilServer versions for different release.

**Comment by chfsx** [comment]
I think so since it just assumes that version 1 is desired if no version or version 0 comes in the request

**Comment by chfsx** [comment]
It's the first time i built ilServer (using maven), I hope everything went right. But i started the new ilServer.jar and it worked (for indexing, did not test other functions of ilServer)

**Comment by smeyer-ilias** [comment]
Yes, everything works fine.

You can also build it on the command line with ant -f build.xml in directory:
Services/WebServices/RPC/lib

**Comment by dominikmebs** [comment]
@chfsx @smeyer-ilias good job 👍

**Pull request merged**
