### PR TITLE
KS Item with Audio Element (v2)

### PR DESCRIPTION
**Pull request by alex40724**
Follow-Up of https://github.com/ILIAS-eLearning/ILIAS/pull/4034

Changes made to the former PR:
- rebased
- withAudio -> withAudioPlayer
- use external audio in example

### CODE REVIEW

**Comment by alex40724** [comment]
@Amstutz @klees This is ready for a final review.

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @akill

Thx a lot for working in the review of the related PR. The changes are fine. 

Plz add:

- [x] Unit Tests: Add Unit tests for with/getAudioPlayer and rendering with audioPlayer

After this, the PR can be merged.
@klees and @amstutz

**Comment by alex40724** [comment]
@Amstutz Tests have been added https://github.com/ILIAS-eLearning/ILIAS/pull/4305/commits/98e0a1f09f898dad676618b459c327a28a7a56a8

**Comment by Amstutz** [comment]
Thx a lot!

**Pull request merged**
