### PR TITLE
implemented Divider

### PR DESCRIPTION
**Pull request by chfsx**
contrary to my statement at the last JF, the UI dividers (horizontally) can easily be integrated into the UI combined slates and the display is not that bad: 

Bildschirmfoto 2020-01-24 um 15 33 23

I therefore suggest to make the adjustment to the combined slate:
- https://github.com/ILIAS-eLearning/ILIAS/compare/release_6...studer-raimann:feature/6/supporting-mb-separators#diff-07d6dd43b6c5e279f9560f235f241a20R36

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @chfsx 

Nice to see. We should probably announce this at the upcoming JF (that we do keep the feature). Most of this tackles code under your maintainance. 

However for the UI Part add the following:

- [x] Public Interface: You implicitly change it. Make this more explicit by announcing the dividers in src/UI/Component/MainControls/Slate/Combined.php in the docs comment.
- [x] Description: Drop a sentence in the Combined slate descritpion mentioning that also dividers can be passed.
- [x] Unit Tests: Add a Unit test making sure, that a divider can be passed, is accepted and properly returned.
- [x] Example: Extend the existing example OR add a new one, showcasing a combined slate with a divider.

thx.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 03 FEB 2020 : We highly appreciate this PR and accept it for 6. Please give Timon a chance to review your latest changes and then merge this PR.

**Review by Amstutz — APPROVED** [review]
LGTM, thx a lot. 

@klees merge as soon as fine with you.

**Comment by chfsx** [comment]
ou sh** I did not see you mentioned @klees for merging! shall I revert it?

**Comment by klees** [comment]
Don't. I'll have a look, if there is anything you could well fix it afterwards.

**Pull request merged**
