### PR TITLE
php8 code review tagging

### PR DESCRIPTION
**Pull request by sailorsilv**
php8 code review Tagging

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
- [ ] Several type hints/declarations are missing: `\TagRelevanceTest::testTagRelevance` and `\ilTaggingGUI`

**Comment by alex40724** [comment]
Thanks for the PR!

**Comment by alex40724** [comment]
I fixed the remaining issues.

**Comment by mjansenDatabay** [comment]
@sailorsilv 

There are still obvious issues, see my fixes in: https://github.com/ILIAS-eLearning/ILIAS/commit/4065c1d66bde632b64a080efdbe31ee5483c29a7

All calls to `ilContainer_lookupContainerSetting` result in an error.

@alex40724 I added a further `TODO` in this commit, Please have a look.

<pre>
TypeError thrown with message "Argument 3 passed to ilContainer::_lookupContainerSetting() must be of the type string or null, bool given, called in /var/www/ilias/trunk/Services/Tagging/classes/class.ilTaggingClassificationProvider.php on line 83"

Stacktrace:
#14 TypeError in /var/www/ilias/trunk/Services/Container/classes/class.ilContainer.php:244
#13 ilContainer:_lookupContainerSetting in /var/www/ilias/trunk/Services/Tagging/classes/class.ilTaggingClassificationProvider.php:83
#12 ilTaggingClassificationProvider:isActive in /var/www/ilias/trunk/Services/Classification/classes/class.ilClassificationProvider.php:62
#11 ilClassificationProvider:getValidProviders in /var/www/ilias/trunk/Services/Container/classes/class.ilContainer.php:578
#10 ilContainer:isClassificationFilterActive in /var/www/ilias/trunk/Services/Container/classes/class.ilContainer.php:594
#9 ilContainer:filteredSubtree in /var/www/ilias/trunk/Services/Container/classes/class.ilContainerGUI.php:336
#8 ilContainerGUI:getContentGUI in /var/www/ilias/trunk/Services/Container/classes/class.ilContainerGUI.php:373
#7 ilContainerGUI:renderObject in /var/www/ilias/trunk/Modules/RootFolder/classes/class.ilObjRootFolderGUI.php:200
#6 ilObjRootFolderGUI:renderObject in /var/www/ilias/trunk/Modules/RootFolder/classes/class.ilObjRootFolderGUI.php:183
#5 ilObjRootFolderGUI:executeCommand in /var/www/ilias/trunk/Services/UICore/classes/class.ilCtrl.php:178
#4 ilCtrl:forwardCommand in /var/www/ilias/trunk/Services/Repository/classes/class.ilRepositoryGUI.php:236
#3 ilRepositoryGUI:show in /var/www/ilias/trunk/Services/Repository/classes/class.ilRepositoryGUI.php:216
#2 ilRepositoryGUI:executeCommand in /var/www/ilias/trunk/Services/UICore/classes/class.ilCtrl.php:178
#1 ilCtrl:forwardCommand in /var/www/ilias/trunk/Services/UICore/classes/class.ilCtrl.php:153
#0 ilCtrl:callBaseClass in /var/www/ilias/trunk/ilias.php:24
</pre>

**Pull request merged**
