### PR TITLE
[Fix 21451] Calendar: Today button disabled

### PR DESCRIPTION
**Pull request by xus**

### CODE REVIEW

**Comment by chfsx** [comment]
@xus and @Amstutz what's the current state of this PR, title says "changes needed".

**Comment by xus** [comment]
> @xus and @Amstutz what's the current state of this PR, title says "changes needed".

@Amstutz I changed the CSS of the UI Control View Section to get the same "disabled" "hover" effect than the UI Control View Mode.
If you agree with this change I will provide an example for the layout docu.

Regarding the "Today" button, it will be disabled if the displayed view has information about the current day.
I don't see anything else missing. 

screen shot 2018-11-16 at 12 38 29

**Comment by Amstutz** [comment]
@xus thanks for this proposal and sorry for letting this hang for so long. In the mean while we do have a (in my mind) very good solution for this state of the buttons, see: https://github.com/ILIAS-eLearning/ILIAS/pull/1311. However this will not be available for ILIAS ver. < 6.

@klees: would you be fine with using the fix of @xus for versions 5.3 and 5.4? I put that on the JF. I think it would be good to discuss this shortly with the rest of the devs. My vote for using this fix for 5.3 and 5.4 and use the solution from https://github.com/ILIAS-eLearning/ILIAS/pull/1311 in ILIAS 6 and above.

**Comment by klees** [comment]
@Amstutz Yes, I would be fine with that.

**Comment by Amstutz** [comment]
@xus thx a lot. I close this, since this is against trunk. However, plz merge this into 5.4 and 5.3, thx a lot (see comment above).

**Comment by xus** [comment]
Merged in 5.4 and 5.3. Thanks a lot

**Pull request closed without merging**
