### PR TITLE
UI Components: Interface for Notification Item and Notification Slate

### PR DESCRIPTION
**Pull request by Amstutz**
This PR proposes to introduce the required UI-Components for implementing: [FR](https://docu.ilias.de/goto_docu_wiki_wpage_5118_1357.html).

I propose the following two new components:

**Item -> Notification**:
As proposed already in the FR we implement a specialized version of the Item to display notifications in the list as shown in the mockups. The difference between the standard item as used e.g. in the Calendar List view is shown in the interface description. Most notably is the feature to aggregate Multiple Notification Items into one. Note that the behavior when clicking on the aggregate is very similar to the Dilldown Menu. However we did consider the drilldown behaviour here not as key characteristic here, but rather as implementation detail, that could change in the future or mix drilldown with regular List behavior (see e.g. nice to have note in linke FR).

**Main Controls -> Slate -> Notification**:
The Slate presenting the Notification is an already existing combined slate. The slates this Combined Slates Contains however are Notification Slates. They differ from Combination Slate in that they are accepting Notification Items as entries and in that they do not require an Icon.

Note that there are some slight differences from the mockup in the linked FR to the mockup bellow generated by using this interface. E.g. there are no links in the description (would be technically possible though), but directly on the title, to be more aligned with existing Items.

Further please have a close look an the following rule of the notification slates:
-  Every service that can send a notification SHOULD add an entry in the Notification Center.
- The displayed Notifications also SHOULD have a permanent place (mainly in Main Bar), somewhere where old messages shown as Notification Item can still be viewed, even if they are removed from the Notification Slate. Exceptions to this are the chat and the Background Tasks.

They are taken from the accepted [FR](https://docu.ilias.de/goto_docu_wiki_wpage_5118_1357.html), but might still be worth to be noted once more.

Further note, that if this FR does not contain the clientside logic for adding notifications such as provided in chat, see: src/GlobalScreen/Client

The following snippet provides an example using this interface and providing the mockup shown bellow:
```
public function getNotifications() : array
{
   //Creating a mail Notification Item
   $mail_icon = $this->ui_factory->symbol()->icon()->standard("mail","mail");
   $mail_title = $this->ui_factory->link()->standard("Inbox", "link_to_inbox");
   $mail_notification_item = $this->ui_factory->item()->notification($mail_title,$mail_icon)
      ->withDescription("You have 23 unread mails in your inbox")
      ->withProperties(["Time"=>"3 days ago"]);

   //Creating a badge Notification Item
   $badge_icon = $this->ui_factory->symbol()->icon()->standard("bdga","mail");
   $badge_title = $this->ui_factory->link()->standard("Badges", "link_to_achievement_badges");
   $badge_notification_item = $this->ui_factory->item()->notification($badge_title,$badge_icon)
      ->withDescription("You received 1 Badge.")
      ->withProperties(["Time"=>"2 days ago"]);

   //Some generic notification Items
   $generic_icon1 = $this->ui_factory->symbol()->icon()->standard("cal","generic");
   $generic_title1 = $this->ui_factory->link()->standard("Generic 1", "link_to_generic_repo");
   $generic_item1 = $this->ui_factory->item()->notification($generic_title1,$generic_icon1)
      ->withDescription("Some description.")
      ->withProperties(["Property 1"=>"Content 1","Property 2"=>"Content 2"])
      ->withActions(
         $this->ui_factory->dropdown()->standard([
            $this->ui_factory->button()->shy("Possible Action of this Item", "https://www.ilias.de"),
            $this->ui_factory->button()->shy("Other Possible Action of this Item", "https://www.github.com")
         ])
      );
   $generic_title2 = $this->ui_factory->link()->standard("Generic 2", "just_opens_the_list_of_aggregates");
   $generic_item2 = $this->ui_factory->item()->notification($generic_title2,$generic_icon1)
      ->withDescription("Some description describing the aggregates attached.")
      ->withProperties(["Property 1"=>"Content 1","Property 2"=>"Content 2"])
      ->withAggregateNotification([$generic_item1,$generic_item1]);

   $factory = $this->globalScreen()->notifications()->factory();
   $id = function (string $id) : IdentificationInterface {
      return $this->if->identifier($id);
   };

   //Now, one could fill the Notification Slates for those 3 Services (normally done by global screen)
   $mail_slate =  $this->ui_factory->mainControls()->slate()->notification("Mail",[$mail_notification_item]);
   $badge_slate =  $this->ui_factory->mainControls()->slate()->notification("Badge",[$badge_notification_item]);
   $generic_slate =  $this->ui_factory->mainControls()->slate()->notification("Generic",[
      $generic_item1,$generic_item2
   ]);

   //Add them to the center which is added to the top bar.
   $notification_center =  $this->ui_factory->mainControls()->slate()->combined("Notification Center",
      $this->ui_factory->symbol()->icon()->standard("notification","notification"))
      ->withAdditionalEntry($mail_slate)->withAdditionalEntry($badge_slate)->withAdditionalEntry($generic_slate);


   //Note that generating the slates is something, a developer does not need to take care of.
   //This is done by the global screen, see: src/GlobalScreen/Scope/Notification/README.md
   //So if one would need to offer those three new types of notification, one would need to
   //Offer a class implementing NotificationProvider by e.g. extending AbstractNotificationProvider and
   //implementing getNotifications like so (note slightly different from the version currently in trunk):
   $mail_group = $factory->standardGroup($id('mail_bucket_group'))->withTitle("Mail")
      ->addNotification($factory->standard($id('mail_bucket'))->withNotificationItem($mail_notification_item));

   $badge_group = $factory->standardGroup($id('badge_bucket_group'))->withTitle("Badges")
      ->addNotification($factory->standard($id('badge_bucket'))->withNotificationItem($badge_notification_item));

   $generic_group = $factory->standardGroup($id('generic_bucket_group'))->withTitle("Generic")
      ->addNotification($factory->standard($id('generic_bucket1'))->withNotificationItem($generic_item1))
      ->addNotification($factory->standard($id('generic_bucket2'))->withNotificationItem($generic_item2));

   return [
      $mail_group,
      $badge_group,
      $generic_group
   ];
}

```
image

### CODE REVIEW

**Comment by Amstutz** [comment]
@mjansenDatabay , I added you as reviewer, since you will be one of the main consumer, if you can have a short glimpse on this, it would be great, if not, no issue there.

@chfsx , I added you a reviewer, since I implicitly also propose to make a minor change in global screen, notification item, by directly passing the UI component instead of individual properties. Seems easier to understand and more flexible. Note that the example shown in the linked FR show-case the amount of flexibility needed here (IMO quite a lot). What do you think?

**Review by mjansenDatabay — APPROVED** [review]
@Amstutz LGTM! I have only two questions:

1. Currently a `NotificationProvider` implements `\ILIAS\GlobalScreen\Scope\Notification\Provider\NotificationProvider` and returns an array of `\ILIAS\GlobalScreen\Scope\Notification\Factory\StandardNotificationGroup` elements, containing 1 or many `\ILIAS\GlobalScreen\Scope\Notification\Factory\StandardNotification` elements.
If I understand this (and your comment addressing @chfsx) right, this has to be changed when this PR is merged. Instead of generating the array structure mentioned above, the concrete `NotificationProvider` will have to create UI elements directly. So **all existing** `NotificationProvider` instances have to be changed, right?
2. Will the implementation of this (or another, follup-up) PR contain any event handling on the client-side? To be more precisely: Will this (or an upcoming) PR handle a `click` event on the notification symbol, **and** will there be a minimum client-side interface to changing the `Counter` of the notification symbol.

**Comment by klees** [comment]
Hi @Amstutz,

thanks for working on these components, seems they are very important for ILIAS 6.

I understand that there is some pressure on this regarding the beta, but I nevertheless want to outline the issues I see with this proposal. In general I think the distinction between notifications as single things, collected in a `Slate` to be displayed somewhere is valuable. I'm not sure about the classification of `Notification`s as `Item`s, though, as outlined in the following. The notifications, on the other hand, could benefit from some further distinctions.

As always, I start with the questions:
- [x] What is the use-case for `Item\Notification::withAdditionalContent`?
- [x] How do `Item\Notification::withAggregateNotification` and `Item\Notification::withAdditionalContent` interact? Are they mutually exclusive? How is the content stacked? Do we really want to have both on one notification? Could it work to have a `Notification` (that has `withAdditionalContent`) and an additional `NotificationCollection` (without the additional content)?
- [x] The `Slate\Notification` must have a symbol (see interface of `Slate`). What should that be?

Please implement the following changes:
- [x] `Item\Notification::withAdditionalContent` seems to be waaaay to broad regarding the type of the parameter. Do we really want every `Component` to be includable here? Please at least describe which components may be included here.
- [x] Move `getLeadIcon` to Item. It seems to belong to his brother `withItem`.
- [x] You write `Note that Notifications only accept Icons as lead` in the comment on `getLeadIcon`. This won't be possible, because a Notification is an Item, which in turn has an interface that also accepts an image. To me this seems to be a hint that a `Notification` is not an `Item`. This already felt weird because `An item displays a unique entity within the system.`. Do we really want to see a notification as a unique entity within the system? For me it rather seems to be something quite minor which was uttered by unique entity. What, in turn, do we win by classifying a `Notification` as an `Item`? Changes in `Item` will need to be reflected in the `Notification` then.

As mentioned, I see that the time is short here. Nevertheless, I'm not happy with the situation regarding the classification of a `Notification` as an `Item`. Maybe this is just another instance of the the item vs. cards discussion already [outlined in our roadmap](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/ROADMAP.md#balance-or-unify-cards-and-items). I would hesitate to couple the `Notification`s to that problem to (via `Item`) and thus suggest to introduce them as a singular entity for the time being.

Maybe it will be easier to find a way forward via skype, though.

Best regards!

**Review by klees — CHANGES_REQUESTED** [review]
Argh, I'm always post my reviews as a simple comment (above).

**Review by chfsx — CHANGES_REQUESTED** [review]
@Amstutz thanks you for your suggestion and comments about the GS-Service. I didn't find any changes in GS, but I may have missed something.

I therefore refer to your question or suggestion to contact the UI component directly via the GS service. Unfortunately, I cannot support this idea.

The GS service intentionally works with an abstraction of the "items" that a provider can provide. One reason for this is that the individual components have no direct dependency on the UI component, but the abstraction also provides another output option in the longer term. The component should deliver a notification, not the appearance of a notification. Another reason is that this is the only way to make a translation of a "notification" into a "UI notification" centrally, which is very important for streamlining.

However, I would suggest that I only adjust the properties of a "notification" in the GS service as soon as the "UI notification" or its interface is finalized. How about that?

Translated with www.DeepL.com/Translator

**Comment by Amstutz** [comment]
Hi,

Thanks for all your feedback. 

First towards to comments of @chfsx and @mjansenDatabay :

@mjansen: 1. Yes this is what I did hint by the change of the Global Screen Interface. See also the question of fschmid.
@mjansenDatabay 2. Yes, but we need to get the server side questions out of the way first.

@chfsx : No, changes on the global screen are not part of this PR. I think those two things should be discussed seperately to allow the JF to make individual decisions. 

@chfsx 2 : I did notice this wrapping. I believe it to be good design to have the mentioned abstractions. However, those should be slim. IMO it is fine to have the Notification Groups and Items in the GS but then use the Components soon in order to not create a huge complexity and doubling of logic which can confuse while generating the entries. Note, those components are not yet bound to UI, since not rendered yet and IMO can be seen as kind of DTO's that are bound to the Notifications in the global screen sense. In my understanding there is no clear line between abstraction and no abstraction. There is this grey zone, where we need to decide, how far the global screen should be involved in e.g. notifications or just know, that there is something like notifications that are passed by the components specified by the KS. I do not prefer you solution, but can live with it. Is this your final conclusion? Note that there would remain the issue of having the additional unspecified content (e.g. the progress bar) that still would be passed in some kind of box.

**Comment by Amstutz** [comment]
@klees 

Thanks for the feedback, as always.

First concerning the questions:

> What is the use-case for Item\Notification::withAdditionalContent?

Yes, checkout the linked mockups. Most importantly, the progress bar which also has some JS related logic. This is used for the BG-Tasks. As often, it was not possible to find work force to shift all the needed UI components in one move. Progress bar is still missing. Also, I believe it not to be a bad pattern, to move such large components (as the notification concept) iteratively. We can put into the backlog, that we need the progress bar and should get rid of this withAdditionalContent ASAP all components are migrated.

>  How do Item\Notification::withAggregateNotification and Item\Notification::withAdditionalContent interact?

Not at all. Those are two completely different things. See Mockups in the FR. One is used to add things such as the progress bar, the other to add things such as Items to be shown in a Drilldown the aggregated Items.

> Are they mutually exclusive? 


Yes.

> How is the content stacked? 


Do you mean, where is the additional content displayed? This is an implementation detail, but according to the mocks in the FR, bellow that description. 

> Do we really want to have both on one notification? 


IMO, sadly yes for the moment. Except if we decide, that we do not need the progress bars for the moment.

> Could it work to have a Notification (that has withAdditionalContent) and an additional NotificationCollection (without the additional content)?


I am not sure if I understand the question. Do you mean can they exist next to each other? Yes.

>  The Slate\Notification must have a symbol (see interface of Slate). What should that be?


No it must not (see the factory and/or example). The Item however does need one.

>  Item\Notification::withAdditionalContent seems to be waaaay to broad regarding the type of the parameter. Do we really want every Component to be includable here? Please at least describe which components may be included here.


I could specify legacy here, maybe that would help to make the intention here. Would that help?

>  Move getLeadIcon to Item. It seems to belong to his brother withItem. You write Note that Notifications only accept Icons as lead in the comment on getLeadIcon. This won't be possible, because a Notification is an Item, which in turn has an interface that also accepts an image. To me this seems to be a hint that a Notification is not an Item. 


Or withItem to Standard Item and not the the abstract item ;-) In each case, there seems to be a typing issue. Yes. This is the reason, why getIcon is currently on Notification Item and getLead on Standard Item. Must be improved, check. My way forward would be to move withLead to Standard Item, would that be acceptable to you?

> This already felt weird because An item displays a unique entity within the system..  Do we really want to see a notification as a unique entity within the system? For me it rather seems to be something quite minor which was uttered by unique entity. What, in turn, do we win by classifying a Notification as an Item? Changes in Item will need to be reflected in the Notification then.


Tough one. Obviously I did understand the notifications as such, you did not. The shift would be technically easy. To me, there seems to be much logic that can be shared here. Further I do not like to have new entries in the top structure for every new component. To me this is just lazy when creating a taxonomy (declaring all things are different and do not share anything). IMO the better move would be to slightly open the definition of item and allowing the notification to find their place there. However, this seems to be a larger ongoing discussion. To me Notification Item is a good speaking name and fitting, can you live with it or do we really need to find an other place for it? If so, Ill need a proposal. "Notification" on top level IMO is not working.

@klees Does this answer help? Did I miss anything?

@everybody: Concerning the time pressure. You are right, but this is always the case. There is a deadline, things make it other do not. I willing to work hard on this one to make the deadline (I currently writing this on the beaches of sicily since it was simply not possible to get work force any where else for this). However, time pressure is no reason to accept bad solution. I am for iterative progress yes, but it must be progress. @everybody: Note that we identified this component early on as critical. There is a back up strategy here (live with the items in the meta bar as in 5.4). Would be sad, but we can not achieve more than we have the workforce for. However, I still see hope, that we can tackle this ;-)

**Comment by klees** [comment]
> We can put into the backlog, that we need the progress bar and should get rid of this withAdditionalContent ASAP all components are migrated.

:+1:

>> Could it work to have a Notification (that has withAdditionalContent) and an additional NotificationCollection (without the additional content)?

> I am not sure if I understand the question. Do you mean can they exist next to each other? Yes.

I would propose to have two kinds of notifications (`Notification` and `NotificationCollection`) where the further has `withAdditionalContent` and the latter doesn't. This would resolve the questions regarding stacking of additional content and sub-notifications. Currently, adding additional content would silently remove the sub-notifications, right?

>> The Slate\Notification must have a symbol (see interface of Slate). What should that be?

> No it must not (see the factory and/or example). The Item however does need one.

It indeed [must have a symbol](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/MainControls/Slate/Slate.php#L22) or you would break the interface. Doesn't mean the user needs to supply it, though.

> I could specify legacy here, maybe that would help to make the intention here. Would that help?

This and the backlog entry are totally fine.

Regarding the `Item`-discussion: I'm fine with your proposal to move `withLeadImage` (and maybe also `withLeadText`) to `Item\Standard`. Top-priority here currently for me is "not breaking interfaces". "Getting a good taxonomy" has second priority and yes, "everything is different" is the lazy way out here. "Sharing logic", though, seems to be a different concern (but also a valid one) that can well be taken care of orthogonal to the taxonomy.

The real problem here seems to be that super soft and broad "item"-term. Of course "Notification Item" makes sense, as well as just "Notification" or "Almost-Anything Item". An item just is something in a greater collection or maybe even just a "thingy". We currently connected it to the term "entity" in the UI-framework, which is a stronger term. To be "just something in a list" to me since is to weak to be an "item" because not everything in a list is an "entity". I still see value in that "entity" term, because these are the things our app really cares about and thus should get more visual weight then just "stuff in a list" (even if stuff has some internal id). Maybe the line we need to draw is somewhere between "just a thing in a list" and "a very important thing (in a list)" where we are missing the further currently and argue about the latter.

This is something we should clarify soon. A lot of data is presented in lists in ILIAS and if we want people to move their template code to the UI-framework "lists" and "items" will be important components.

Best regards!

**Comment by Amstutz** [comment]
> I would propose to have two kinds of notifications (Notification and NotificationCollection) where the further has withAdditionalContent and the latter doesn't. This would resolve the questions regarding stacking of additional content and sub-notifications. Currently, adding additional content would silently remove the sub-notifications, right?

No it would not. Those are two separate things. One just adds some additional HTML (Legacy Component) bellow the description, the other add Notification in a Drilldown Like manner. A Notification Item can have both.

> This is something we should clarify soon. A lot of data is presented in lists in ILIAS and if we want people to move their template code to the UI-framework "lists" and "items" will be important components.

+1, we need to wrap our heads around this. Ill send you a few possible dates in November.


To wrap it up for the JF:

- The question brought up by @chfsx concerning how this will be consumed is important, but not part of the PR. I'll propose, that we handle this in a skype session among intersted devs (@chfsx , @mjansenDatabay probably among them) Ill send an invitation.
- @Amstutz will clean up the Notification Item as proposed by @klees by move withLeadImage (and maybe also withLeadText) to Item\Standard
- We currently handle the Notification as Notification Item. @klees and @Amstutz agree, that his is not ideal. The problem ist the very broad item definition. That along with the issue that some Components are defined along layout (e.g. Cards, Deck) and others along their functionality (Round Trip Modal) and again others along their semantics (Workflow) is something @klees and @Amstutz need start to sort out.
- We need a decision, if we need both, Notification Item and Notification Item Collection.

@klees do you agree with the given wrap up?

**Comment by chfsx** [comment]
> * The question brought up by @chfsx concerning how this will be consumed is important, but not part of the PR. I'll propose, that we handle this in a skype session among intersted devs (@chfsx , @mjansenDatabay probably among them) Ill send an invitation.

I'm in, thanks for the suggestion. Since I can't participate in the JF this afternoon, here's my proposal on the subject: Skype session with the involved and my promise that I'll make the GS-side adjustments in time that will be needed to keep the behavior the same as in the other scopes.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 07 OCT 2019 : We highly appreciate the suggested interface and accept it for trunk.

**Comment by klees** [comment]
@Amstutz You are pushing this, right? Ping me if you need anything from me.

**Comment by Amstutz** [comment]
@klees : Yes I am on this. The implementation is almost done. I got into a little branching/merging/squashing/rebasing blood bath, due to the split of the implementation part of this into one Global Screen PR, a More Glyph PR, a JS Counter PR and a PR for the Implementation of this part. Note that I will probably close this one here and open a new one as soon as the implementation is complete. Note that the complete implementation of this has deps. towards to Counter JS PR and the More Glyph PR, so it would be great if we could merge this beforehand.

**Comment by Amstutz** [comment]
This PR has been superseeded by #2299, which also contains the implementation.

**Pull request closed without merging**
