### PR TITLE
switch from bower to npm

### PR DESCRIPTION
**Pull request by alex40724**
This PR suggests to move from bower to npm.

Why? Bower is deprecated and npm is doing the job so yarn would not be needed. npm is being used for all kind of other dev stuff already.

README at https://github.com/ILIAS-eLearning/ILIAS/pull/2667/files#diff-2bf22a30a6b2de672e6504bf2a274815

It includes a package.json with all our bower dependencies (except YUI, which we should get rid of). However I did not migrate the paths yet except for
"jquery": "^3.5.0"
"jquery-ui-dist": "^1.12.1"
"jquery-migrate": "^3.0.0"
"bootstrap": "3.3.7"

The nodes_modules directory is currently not included in the git repo.

> composer dump-autoload will trigger "npm -i"

I would migrate the paths and test the results for:

@geedmo/yamm3": "^1.1.0",
"maphilight": "^1.4.0",
"mediaelement": "4.2.16",
"owl.carousel": "git+https://github.com/OwlCarousel2/OwlCarousel2.git",
"qtip2": "^3.0.3",
"tinymce": "^4.6.7",
"jstree"
"yui"

CaT would take care of:
"ol": "^6.3.1"

@mjansenDatabay would take care of:
"jquery-outside-events": "^1.0.0",
"moment": "^2.24.0"

@chfsx would take care of:
    dropzone
    webui-popover
    bootstrap-tagsinput
    fine-uploader
    typeahead

These libs are remaining, but fall into distinct maintainerships imo:

"@andxor/jquery-ui-touch-punch-fix": "^1.0.2" (@mjansen, Databay)
"eonasdan-bootstrap-datetimepicker": "^4.17.47" (@smeyer-ilias, Leifos)
"jquery-dragster": "git+https://github.com/catmanjan/jquery-dragster.git" (KS Dropzone, @chfsx)
"jquery-mousewheel": "^3.1.13" (Services/Preview, @chfsx)
"nestable2": "^1.6.0", (ilMultipleNestedOrderingElementsInputGUI, @mjansenDatabay)
"pouchdb": "^7.2.1" (SCORM, @Uwe-Kohnle)

I will set candidates as assignees. Please leave comments if you support this and would migrate some of the libs and which.

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724,

thanks a lot for this push forward! We (CaT) will migrate Open Layers. Is there anything else you had in mind for us?

I have two question:
* Did you take the differences between npm and yarn into serious considerations? I did a super quick and shallow research, but this already unearthed two differences in the two that biased me towards yarn: [it seems to be better in reproducible builds and thus security](https://medium.com/@j.dumadag718/yarn-vs-npm-b2d58289fb9b) and [it seems to support bower](https://javascript.christmas/2019/10).
* Do we already know if all the packages we currently use are actually available via npm?

I think we should give the npm/yarn-question a bit more consideration, if you didn't do so already. I already know that my admin will hate the fact, that ILIAS even uses npm and I won't be able to tell him that it is just for the chat (that we do not use) anymore.

Best regards!

**Comment by alex40724** [comment]
> Hi @alex40724,
> 
> thanks a lot for this push forward! We (CaT) will migrate Open Layers. Is there anything else you had in mind for us?

Thanks, I really have not a good overview on who added what, since the "extra" metadata does not contain this info in lots of cases.
 
> I have two question:
> 
>     * Did you take the differences between npm and yarn into serious considerations? I did a super quick and shallow research, but this already unearthed two differences in the two that biased me towards yarn: [it seems to be better in reproducible builds and thus security](https://medium.com/@j.dumadag718/yarn-vs-npm-b2d58289fb9b) and [it seems to support bower](https://javascript.christmas/2019/10).

Since I do not have sufficient experience on my own I rely on external source like this blog post you mentioned, too https://javascript.christmas/2019/10

I got the feeling that npm had issues in the past but improved greately with the latest versions, so I would give it a try. Bower support is not an issue imo, since we replace Bower completely.

> 
>     * Do we already know if all the packages we currently use are actually available via npm?

Yes, see the packge.json in this PR. They are already all included if you install "nmp i". I just did not fix all the paths to the libs in the ILIAS source code (only for the basic jQuery and bootstrap stuff, see above).

> 
> I think we should give the npm/yarn-question a bit more consideration, if you didn't do so already. I already know that my admin will hate the fact, that ILIAS even uses npm and I won't be able to tell him that it is just for the chat (that we do not use) anymore.
>

I guess your admin hates node.js not necessarily npm. Yarn is using the npm ecosystem in the background, so we do not get rid of the npm dependency. Moreover, if we really experience issues with npm a migration to Yarn should be a no-brainer. But this would definitely add a second dependecy to the Yarn project.

Another option, if npm does still not reliably install the same lib versions, would be to include the node_modules dir in our repo and ship it directly (like we do with bower currently). In this case no npm would be needed on production systems, it would be a "dev dependency".

> Best regards!

**Comment by mjansenDatabay** [comment]
> I got the feeling that npm had issues in the past but improved greately with the latest versions, so I would give it a try.

That's exactly what our JavaScript devs told me. They switched to `yarn` and now back to `npm`.

**Comment by mjansenDatabay** [comment]
@alex40724 I'll pick `jquery-outside-events`. And if there is no volunteer for `moment`, I'll migrate this, too.

**Comment by fneumann** [comment]
No objection, but I can't pick a migration - sorry.

**Comment by klees** [comment]
@alex40724 Thx for the answer. So let's move on.

**Comment by chfsx** [comment]
I‘ll go for
- dropzone
- webui-popover
- bootstrap-tagsinput
- fine-uploader
- typeahead

**Comment by matthiaskunkel** [comment]
Jour Fixe, 27 APR 2020: We highly appreciate this PR and accept it for trunk. We prefer to have npm in the ILIAS repo. In a second step we could move all JS libraries out of the repo to keep it smaller.

**Pull request merged**
