### PR TITLE
Globa Screen/Main Menu: Show Repository Link and Seperator

### PR DESCRIPTION
**Pull request by Amstutz**
Fix of: https://mantis.ilias.de/view.php?id=26985

Note, not sure about the seperator as deactivated button. However, IMO we should fix soon, since this blocks other cases. Maybe we can abandon the seperators all together in the next JF, not sure if they make sense in the new concept anymore. @chfsx up to you.

### CODE REVIEW

**Review by chfsx — APPROVED** [review]
Thanks a lot!

**Comment by Amstutz** [comment]
As just discussed in the weekly, I removed the separator part of the PR. 

Note, I did not remove separators from the system completely, just from this PR.

**Comment by chfsx** [comment]
I squashed your commits and cherry-picked to release_6 as well

**Comment by Amstutz** [comment]
thx!

**Pull request merged**
