### PR TITLE
changed all indentation tabs to spaces

### PR DESCRIPTION
**Pull request by iszmais**
Algorithm:

replace "\n\t" with "\n    ".

replace "    \t" with "        ". repeat until no occurence found.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Thx @iszmais 

Please only modify `*.php` files and use the PSR-2 code style script instead.

**Comment by alex40724** [comment]
@mjansenDatabay Is there any click path from our main documentation to this script? I just saw that https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/coding-style.md does not link to it.

**Comment by mjansenDatabay** [comment]
@alex40724 See #2173

**Comment by alex40724** [comment]
@mjansenDatabay Thanks!

**Comment by mjansenDatabay** [comment]
I close this PR. Instead of creating one big PR, I suggest to create smaller PRs for each relevant component. Furthermore we should only apply a `PSR-2 + Additions` code formatting to `*.php` files, beause we have not guidelines for other filetypes, yet.

**Pull request closed without merging**
