### PR TITLE
Updated process security.md

### PR DESCRIPTION
**Pull request by fsesterh**
Since the security process has been finalized I've included some more detail in the security.md regarding the process. Most of it focuses on information we have an interest in people knowing before they contact us. I.e. to withhold the full disclosure until a fix is ready, to include steps to reproduce in the report etc.

### CODE REVIEW

**Comment by fsesterh** [comment]
@corro Please review, thanks.

**Review by corro — APPROVED** [review]
LGTM :+1:

**Comment by klees** [comment]
I assigned @mjansenDatabay and set the JF-label, since I had no better idea how a path to merge for this PR could look like. Feel free to disagree and comment here.

**Comment by mjansenDatabay** [comment]
LGTM! If the JF does not have any objections, this could be merged.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 JAN 2020 : We highly appreciate this improvement of the security.md. Please merge accordingly. In general, improving documents of the Security Group does not need an JF approval  as long as no fundamental changes in the setup of the security group are involved.

**Pull request merged**
