### PR TITLE
possible fix for mantis #33828

### PR DESCRIPTION
**Pull request by mglaubitz**

### CODE REVIEW

**Comment by Amstutz** [comment]
@mglaubitz , thx a lot!

**Comment by Amstutz** [comment]
@schmitz-ilias , maybe you want to look into this. AFAIK, @smeyer-ilias , is on vacation (soon).

**Comment by schmitz-ilias** [comment]
Looks good to me, thanks for fixing! (I don't have permission to merge though.)

**Comment by Amstutz** [comment]
I took the liberty to merge this, I hope this is fine. @schmitz-ilias : this does not need picking to trunk and 8, right? There this should be fixed.

**Comment by schmitz-ilias** [comment]
@Amstutz Yes, 7 should be sufficient. I can't test it because of other bugs in learning sequences, but just going by the code the same issue shouldn't come up in 8 and trunk.

**Pull request merged**
