### PR TITLE
PHP 8: Apply changes for first request

### PR DESCRIPTION
**Pull request by mjansenDatabay**
With this PR I would like to create awareness for the `Backward Incompatible Changes` of PHP 8. All this (in this PR) is required for requesting the login page via `http://localhost.php8-0/ilias/trunk/login.php?cmd=force_login` and getting a proper result. The public area repository page is also accessible (at least with my database state).

The main issues were:
- Attempting to read an undefined variable
- Attempting to read an undefined property
- !!! **Attempting to read an undefined array key** !!!
- Using `final private` methods (I already created some separate PRs for this)
- Using a `boolean` return type for the callback of `usort`.
- Required method/function parameters followed by optional parameters

### CODE REVIEW

**Review by chfsx — APPROVED** [review]
Hi @mjansenDatabay 
Thank you very much for this work! I reviewd
- Services/UICore/classes/MetaTemplate/PageContentGUI.php
- Services/UICore/classes/Screen/PageContentProvider.php
- Services/UICore/classes/class.ilCachedCtrl.php
- src/GlobalScreen/Scope/MainMenu/Collector/Map/Map.php
- src/GlobalScreen/Scope/MetaBar/Collector/MetaBarMainCollector.php
- src/GlobalScreen/ScreenContext/ContextRepository.php

LGTM!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 21 DEC 2020: Thanks to Michael for making us aware of this issue. The Technical Board will discuss this problem on its next meeting. Getting ILIAS compliant with ILIAS 8 will be an own project for ILIAS 8 that requires a lot of ressources. Compliance with ILIAS 7 is not realistic due to missing time before end of beta.

**Review by theodortruffer — APPROVED** [review]
No review necessary from my side.

**Review by smeyer-ilias — APPROVED** [review]
Thanks Michael! Looks good to me in my components.

**Comment by kergomard** [comment]
To move the PHP 8 compatibility forward the TB would like to merge this PR into trunk on February 9th 2021. We kindly ask all maintainers to look at the parts concerning them before this date. We would also kindly ask you to give some thought to what it will mean for you to make your code compatible with PHP 8.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 25 JAN 2021: We highly appreciate the TB's suggestion and accept the merge of this PR to trunk at the foreseen date. We ask all maintainers to give the requested feedback in time.

**Review by kergomard — APPROVED** [review]
Not much changed in the parts we feel responsible for. Thank you very much!

**Review by alex40724 — APPROVED** [review]
Thanks!

**Review by klees — APPROVED** [review]
Not much in here from me =) The change in `src/UI` is fine. Thanks!

**Review by rsheer — APPROVED** [review]
Thanks a lot for the PR!

**Comment by ghost** [comment]
https://github.com/ILIAS-eLearning/ILIAS/pull/3101 was merged - So I think it's ok for @mstuder in this PR too in Services/Component/classes/class.ilPluginAdmin.php

**Comment by kergomard** [comment]
Thank you @mjansenDatabay für the PR and everybody for having a look at it!

**Pull request merged**
