### PR TITLE
Changed ordering of KS-Entries

### PR DESCRIPTION
**Pull request by Amstutz**
Due to feedback from KS user, I propose to slightly change the ordering of the items on the first level. The current order is quite random, the new is grouping around possible interactions/week relations. This is intentionally implizit, since actual criteria on how to group things are used to build named families.

Old Order:
image

New Order:
image

This is no interface change. If no one objects, I will merge this in the beginning of next week.

### CODE REVIEW

**Comment by atoedt** [comment]
I second the motion. Clearly an improvement

**Comment by colin-kiegel** [comment]
At first sight this still looks quasi-random to me and I would still prefer alphabetic sorting.

I only need split second time to recognize/suspect alphabetic sorting, when it's there. But here I need at least one second of full concentration to discover some kind of sorting from small to large here. Usually I wouldn't stare long enough on a list like this and test assumptions about hidden sorting principles.

**Comment by matthiaskunkel** [comment]
I never understood the idea behind the old sorting - and to be honest - I did not assume there was one... But having one would be a step forward. I prefer a semantic sorting to an alphabetical one. Alphabetical sorting works fine when you know how the item is spelled you are looking for. But a lot of KS users are not that familiar with the KS labels. 

Nevertheless, why are Glyphs placed between Button and Link, while Icons are at first place?

**Comment by Amstutz** [comment]
@matthiaskunkel There was one, but probably worst possible: Ordering by date of creation ;-). 

> Nevertheless, why are Glyphs placed between Button and Link, while Icons are at first place?

Glyphs are interactive, Icons not. Icon are from an interaction perspective as trivial as it gets.

**Comment by matthiaskunkel** [comment]
@Amstutz That's always my preferred one ;-)

**Review by klees — COMMENTED** [review]
No opinion here, sry.

In general I would really like to have a tagging mechanism for the UI elements.

**Comment by Amstutz** [comment]
Thanks for all your feedback. A slight variation of this has been pushed to trunk.

**Pull request closed without merging**
