### PR TITLE
24902: Who is online tool does not show online status for Shibboleth Auth

### PR DESCRIPTION
**Pull request by alex40724**
https://mantis.ilias.de/view.php?id=24902

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 25 FEB 2019: PR highly appreciated and accepted, see related Mantis bug report. Please merge.

**Comment by Amstutz** [comment]
@alex40724 : Thanks a lot for this fix, I just tested this on a 5.3 installation with shibboleth enabled. Works like a charm. Thx.

**Comment by okaufman** [comment]
Will this PR be merged soon?

**Comment by alex40724** [comment]
Yes, it is now on top of my list.

**Pull request merged**
