### PR TITLE
UI/CombinedSlate: Add optional entry id for menu sub entries (ILIAS 7)

### PR DESCRIPTION
**Pull request by iszmais**
https://mantis.ilias.de/view.php?id=30469

### CODE REVIEW

**Comment by iszmais** [comment]
Hi @klees ,

i applied the changes to all 4 occurrences (+2 for the new test cases). 
But i already found 1 dynamic call (inside src/GlobalScreen/Scope/MetaBar/Collector/Renderer/TopParentItemRenderer.php) wich wasn't tracked by the file inspector. I guess the could be more possible occurrences.

Also the code inside the examples cant be updated easy caused by semantic discrepancies.
Contrary to 1 of your request which was to ensure unique ids, resulting in unique entries, most of the calls in the examples are ambiguous wich means they cant exist in inside the new requirements by concept.

Regards,
@iszmais

**Comment by iszmais** [comment]
@klees  / @Amstutz According to **JourFixe 19.04.2021** only the same changes like for ILIAS 6 (https://github.com/ILIAS-eLearning/ILIAS/pull/3278) will be applied. Other Requests to cleanup the code structure postponed to futhure PRs.

**Comment by iszmais** [comment]
@Amstutz 
Could you merge this PR, as @klees  will probably not be able to take action here for the time being?

**Comment by Amstutz** [comment]
Cherry picked from, https://github.com/ILIAS-eLearning/ILIAS/pull/3278, thx.

**Pull request closed without merging**
