### PR TITLE
Support PHP 7.1 with ILIAS 5.2

### PR DESCRIPTION
**Pull request by alex40724**
See JF Decision:
https://www.ilias.de/mantis/view.php?id=22487

TB can still veto this on its meeting at 7 Feb 2018.

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]

**Comment by mjansenDatabay** [comment]
Thx @alex40724 . I cherry-picked the 7.1.x setup fix (session related) yesterday.

**Review by chfsx — COMMENTED** [review]
Could we then drop 5.5.x instead?

**Comment by alex40724** [comment]
Drop 5.5.x for ILIAS 5.2? I am not sure about the implications. I think we should at least send a message to the admin list first and see if anyone objects.

**Comment by chfsx** [comment]
Yes maybe this would be a too hard change for a already released version.

**Comment by klees** [comment]
I would not drop the support for PHP 5.5 in ILIAS 5.2. This is a backward compatibility breaking move, that imo should not be done in patch releases.

**Pull request merged**
