### PR TITLE
PDF engine aware initialisation of MathJax

### PR DESCRIPTION
**Pull request by fneumann**
see Mantis #24570

Latex code is processed by the MathJax service for different content pieces separately. At the beginning of a PDF generation request the MathJax service has to be initialised to produce an output format (image or svg) for the formulas that can be treated by the chosen PDF rendering engine at the end of the request. 

When the MathJax service was introduced, this was done by ilPDFGeneration::prepareGeneration(), which initialises MathJax only for the TCPDF renderer and which is meanwhile deprecated. As a result, the latex formula are now presented wrongly in the PDFs generated by PhantomJS, e.g. in the PDF export of a Wiki where they are far too big. With the introduction of PhantomJS and a choice of PDF renderers for different purposes, the MathJax initialisation has to be done by the PDF renderer because only the renderer knows the needed format, dpi or zoom factor of latex images.

This pull request replaces all known usages of the deprecated ilPDFGeneration::prepareGeneration() by the new ilPDFGeneratorUtils::prepareGenerationRequest() which takes the service and rendering purposes as parameters and delegates the initialisation to the PDF renderer for that purpose. 

Additionally the chosen PDF renderer for the purpose Test/UserResult is now also respected by "Results by Question" in test statistics, by learning objective related test results, and by the preview of answers when a test pass is finished.

### CODE REVIEW

**Review by bheyser — APPROVED** [review]
Thank your for your changes. I am very fine with them. Especially fo the completion of passing a purpose i am very thankful.

From my Side: MERGE (!)

**Comment by klees** [comment]
AFAIK the leading change here is in the PDFGeneration, so I assigned this PR to @gvollbach

**Review by gvollbach — APPROVED** [review]
@fneumann lgtm, thanks again.

@alex40724 Any objections on your parts?

**Comment by alex40724** [comment]
Hi @fneumann, hi @gvollbach, 

@fneumann, thanks for your contribution. I fully support this.

@fneumann, @gvollbach: Please consider the creation of a README.md in the PDFGeneration service that collects the documentation know being available in the class file(s), e.g. "...Should be used to initialize the processing of latex code...". I think most consumers will not read this kind of information and may not make use of the service as expected.

kindly,
@alex40724

**Review by alex40724 — APPROVED** [review]

**Comment by fneumann** [comment]
Merged the PR, thanks for reviewing. 
@gvollbach: I agree with alex that a README for PDFGeneration service would be helpful, especially for those who want to add new rendering purposes.

**Pull request merged**
