### PR TITLE
Bring composer vendor-directory up to date.

### PR DESCRIPTION
**Pull request by klees**
In my understanding, deleting the composer vendor directory and then calling "composer install" should lead to the exact same vendor directory as before and therefore lead to no changes regarding git. Unfortunately this is not the case with the current state of the ILIAS composer vendor directory:
- two files where missing: vendor/geshi/geshi/.gitignore and vendor/ezyang/htmlpurifier/PATCHES.txt
- vendor/phpoffice/phpexcel contained files with windows line endings instead of unix lineendings as in the original

I therefore deleted the vendor folder and called composer install. Anyone objecting to pull this non-changes? Or did i miss anything?

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
I accidentally forgot to commit vendor/ezyang/htmlpurifier/PATCHES.txt .

**Comment by mjansenDatabay** [comment]
So, no objections ...

**Comment by chfsx** [comment]
no objections

**Comment by klees** [comment]
Hi @alex40724,

could you please have a look as well? You're the owner of geshi, Jörg is the owner of phpexcel, but he seems to be out of office for some time.

Best Regards!

**Comment by alex40724** [comment]
First of all, I do not object to commit these changes.

I do not have too much experience using composer. I think we are missing sime guidelines for this (or has anyone written them?). Up to now my opinion was that developers only update "their" libs. I had to install geshi "dev-master" since composer was unable (or I was not able) to install a proper stable version (I did not have these problems with getid3). My understanding of the version parameter is, that installs at a later time may update lib and include changes, depending on how you specify it.

So why should "install" not change code?

**Comment by klees** [comment]
Yes, Guidelines would be nice. Its on my backlog for some time now, just didn't get to it.

Regarding `composer install`: There are two files involved in `composer install`:
- composer.lock is owned by composer, stores the exact versions of libraries and therefore makes reproducible builds possible
- composer.json is owned by the developers, one can give bounds of versions here

If there is no composer.lock, composer uses the composer.json and tries to fetch a combination of packages fitting the bounds and being as up-to-date as possible. It then writes the exact versions of all installed packages in the composer.lock. There might be more packages in the *.lock as in the *.json, because some packages might have dependencies themselves, which are recorded as well. If there is a composer.lock, `composer install` uses the versions found in there, which should guarantee a reproducible build. In your case of geshi, the composer.lock should contain a hash of a git commit to make the build reproducible. The versions and hashes in composer.lock are only touched, when `composer update` is called.

**Comment by alex40724** [comment]
Thanks for clarifying this!

**Pull request merged**
