### PR TITLE
PSR-2 For src/UI folder

### PR DESCRIPTION
**Pull request by legionth**
This will adapt PSR-2 to the `src/UI` folder.

If you want I can split this PR into smaller PRs to make this more "reviewable".

### CODE REVIEW

**Comment by klees** [comment]
Thx. You did not do this manually, right? =)

**Comment by legionth** [comment]
:smirk:

No I used our `php-cs-fixer` (dev-dependency in compiser) with our configuration file in `./CI/PHP-CS-Fixer/code-format.php_cs` . Took 5 seconds ;)

**Review by klees — APPROVED** [review]
I trust the tool, no need to review =)

**Comment by Amstutz** [comment]
I think we should not merge this at the current state. there are several PR's open that would run into conflicts with this here. IMO, this is a job, @klees and I have to perform and somehow announced that before to avoid irritiation of devs of other branches.

**Comment by Amstutz** [comment]
However @legionth thx for bringing this up and push @klees and me to perform this necessary step. +1

**Pull request closed without merging**
