### PR TITLE
Allows custom positions to be imported.

### PR DESCRIPTION
**Pull request by CrawdadWarden**
Noticed that you could not import custom positioned users using the XML import, Unsure if this is the proper procedure or there should be a lookup in ilOrgUnitPosition to lookup by title but this is tested working on my development site.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Hi @mstuder 

we stumbled upon this PR in our TB meeting. If you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by chfsx** [comment]
Hi @mstuder

we stumbled upon this PR in our TB meeting. If you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by chfsx** [comment]
Hi @mstuder 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by mstuder** [comment]
thank you, i will merge this in ilias 7 and trunk this week also!

**Pull request merged**
