### PR TITLE
Feature/6/ui file input interfaces

### PR DESCRIPTION
**Pull request by chfsx**
This PR proposes the interface for a new UI input "File".
For the implementation we suggest the library Dropzone.js, because the currently used library will not be further developed and has to be replaced.

The input receives a title, a byline and an UploadHander. This is responsible for receiving the uploads, saving them and returning a file ID to the UI input. Background is the general storage mechanism that will come with ILIAS 7.

Files are immediately sent to the UploadHandler as soon as they are dragged into the drop zone. This solves the general problem with async requests associated with drag and drop uploads. The form can then be sent "normally" synchronously. The processing side can then use the file IDs supplied by the input.

Bildschirmfoto 2019-10-17 um 17 22 49

The background is the following feature request: https://docu.ilias.de/goto_docu_wiki_wpage_3993_1357.html

Please note that the UI element in ILIAS 6 is used exclusively for this feature and will only be equipped with more options later.

### CODE REVIEW

**Comment by chfsx** [comment]
Factory and description : https://github.com/ILIAS-eLearning/ILIAS/pull/2257/files#diff-2d8571e3a451f51b51f9868081f6f7e8R578

Interface: https://github.com/ILIAS-eLearning/ILIAS/pull/2257/files#diff-544cd9cda6d27bcf1beb3323c80daef9R10

**Comment by klees** [comment]
Hi @chfsx!

Thanks a lot for proposing this important but yet missing Input Field.

Of course we want to have this UI component and also the proposed mechanism (asynchronous upload) seems to be fine. We are really looking forward to you work on the File service.

Please answer the following questions:
- [x] Dropzone.js I: We see the reason to drop the currently used library. However, we do not like to run in similar issues in the near future. We like to see the many stars and forks, we are still worried about the many open issues and uncommented PRs. How do you judge this? Are there alternatives?
- [x] Dropzone.js II: What will be replaced by Dropzone.js? Does this replacement also target the UI component File Dropzone?
- [x] File Dropzone: Will File Dropzone be used internally? 
- [x] Missing Features: You write, that some options are missing. What do you have in mind? How do we make sure, that this will be shipped later? Also see our roadmap comment below.
- [x] Async I: What will happen with the file on the server if a user deletes it on the GUI?
- [x] Async II: What will happen with the file on the server if a user just closes the window?
- [x] Async III: What will happen if a user submits the form before the async upload of the file to the server has finished?
- [x] UploadHandler: We are not sure that we understand completely how this will be used or what work this will be performing (in the context of the UI-framework). Will the UI-framework use all methods of the UploadHandler? What will it do with `executeCommand` and `getResult`? Could you elaborate on this concept a little or show some code?
- [x] Accessability: Can this control be used by only using the keyboard?

Please consider the following suggestions. You do not need to follow these, but please indicate shortly why you prefer to do otherwise.
- [ ] HandlerResult: Use Data\Result for the ok/error part of that class and introduce a FileIdentifier for the rest.
- [ ] Size: Use Data\DataSize for the various file sizes. Maybe this class is missing a "toByte"-method and it also is certainly missing in the factory of the Data-library.
- [ ] Mimetype: Maybe it's worth the effort to implement this as a Data-type as well. This is used in other places as well, right?

Please implement the following changes:
- [x] Purpose: Really only one file, not multiple?
- [x] Composition: Be more specific: Is there a control to access the files through the OS file browser? What does the list of files contain (e.g. Titles, Descriptions, File Size, Type).
- [x] Effect: Be more specific: What happens if files are dropped on the zone, are they uploaded directly? Can they be removed? How can the file browser be accessed? 
- [x] Empty Rule: Remove the empty rule.
- [x] Roadmap: State what features are missing in this version and when and how they are intended to be implemented.
- [x] Context: The `context` is too broad, point to the use case given in the linked FR. Context should allow other devs to see this component in some productive use case.
- [x] Method Descriptions: Please provide descriptions for all methods of the interface. Especially `getUploadURL`, `executeCommand`, `getFileIdentifier` and therefore `getUploadHandler` are hard to comprehend. Also in `withMaxFileSize` and `withAcceptedMimeTypes` it could be worthwile to drop in a comment on the relation of those params to the system wide setting. Will they be overriden or is the dev always responsible to set them when using a `File Input`? Remove the typehints in the docstrings if they do not provide more information then the PHP-typehints.

If you feel the need to discuss stuff, feel free to contact us, as always.

Kindly,
@klees, @amstutz

**Comment by chfsx** [comment]
> Dropzone.js I: We see the reason to drop the currently used library. However, we do not like to run in similar issues in the near future. We like to see the many stars and forks, we are still worried about the many open issues and uncommented PRs. How do you judge this? Are there alternatives?

No matter how you search in this subject, Dropzone.js is mentioned. With 180'000 downloads per week (https://www.npmjs.com/package/dropzone), 14'600 stars and 3200 forks per week (https://github.com/enyo/dropzone) the library is widespread. It's true, however, that there are many Open Issues and that development has also become quiet in other respects.
A relatively up-to-date overview can be found here: https://bashooka.com/coding/20-javascript-libraries-to-manage-file-upload/
However, I also focused on the fact that the library does not have too many functions and above all too many implications for the UI.

Difficult to say if there are better alternatives.

> Dropzone.js II: What will be replaced by Dropzone.js? Does this replacement also target the UI component File Dropzone?

Nothing with this feature. However, the UI component Dropzone should use the same library with ILIAS 7 at the latest, because the development of the library used there was finished.
With ILIAS 6 we will not have the resources to change the UI drop zone.

> File Dropzone: Will File Dropzone be used internally?

No, see above.

> Missing Features: You write, that some options are missing. What do you have in mind? How do we make sure, that this will be shipped later? Also see our roadmap comment below.

Truly, the amount of features that this first implementation brings with it is very small. The background is surely that there is very little time left and the feature that will use the input as the only one in ILIAS 6 does not need any more functions.

But I have completed the roadmap and it looks like this:

--
General Dropzone functionality:
ILIAS 6 introduced a new library for drag & drop together with FileInput. This library was not used for all D&D users. This MUST be done and standardized with ILIAS 7.

With ILIAS 7, FileInput (or specific variants thereof) should have at least the following functions and properties:
- Upload several files at once
- Displaying existing files
- Restriction to file extensions
- Restriction to MimeTypes

With ILIAS 7 or later versions, FileInput (or specific variants thereof) can have the following functions and properties:
- Preview of uploaded images
- Crop functionality for images
--

How can we ensure that these will be delivered later? Not at all. But we can never do that.  It takes funding, a feature, time, etc. to do that. But I have an interest in doing this myself.

> Async I: What will happen with the file on the server if a user deletes it on the GUI?

I changed the UploadHandler more explicitly to an `ilCtrlAwareUploadHandler`. This handler has to return two URLs, one to process an upload and the other to delete an upload deleted in the GUI. The interface is now also better described. At the moment we only have ilCtrl to request an object that can be called via a request. Therefore this binding to ilCtrl.

> Async II: What will happen with the file on the server if a user just closes the window?

Unfortunately, this case cannot be covered at the moment. But since I will implement an `ilCtrlAwareUploadHandler` in the first step in connection with the new FileStorage, I will at least be able to identify such uploads. This will allow a cleanup process to clean up these orphaned files later.

> Async III: What will happen if a user submits the form before the async upload of the file to the server has finished?

I try to prevent this during the implementation, where the form buttons are inactive during this time.

> UploadHandler: We are not sure that we understand completely how this will be used or what work this will be performing (in the context of the UI-framework). Will the UI-framework use all methods of the UploadHandler? What will it do with executeCommand and getResult? Could you elaborate on this concept a little or show some code?

An UploadHandler should take over the processing of the uploads, the components that want to upload files can implement it themselves. In the medium term, there should be only one upload handler, one that writes to the new FileStorage.

I have extended the interface as mentioned above and described better what it is for. The UI service uses some of these methods to, for example, send the uploads to the correct URLs and also to know what to expect as an answer (HandlerResult).

> Accessability: Can this control be used by only using the keyboard?

Probably not, but I'm not a specialist in that either. For simple inputs like checkboxes etc. I think I have no problem with that, but here we are dealing with a more special one. If you could make your requirements more concrete, I would be happy. But if it fails at the end at this point, then I give up... =)

> Purpose: Really only one file, not multiple?

Like I said, right now, yes. But I want to expand this for ILIAS 7 in any case.

> Composition: Be more specific: Is there a control to access the files through the OS file browser? What does the list of files contain (e.g. Titles, Descriptions, File Size, Type).

Done.

> Effect: Be more specific: What happens if files are dropped on the zone, are they uploaded directly? Can they be removed? How can the file browser be accessed?

Done.

> Empty Rule: Remove the empty rule.

Done.

> Roadmap: State what features are missing in this version and when and how they are intended to be implemented.

Done. (in ROADMAP.md of the UI-Service?)

> Context: The context is too broad, point to the use case given in the linked FR. Context should allow other devs to see this component in some productive use case.

Done.

> Method Descriptions: Please provide descriptions for all methods of the interface. Especially getUploadURL, executeCommand, getFileIdentifier and therefore getUploadHandler are hard to comprehend. Also in withMaxFileSize and withAcceptedMimeTypes it could be worthwile to drop in a comment on the relation of those params to the system wide setting. Will they be overriden or is the dev always responsible to set them when using a File Input? Remove the typehints in the docstrings if they do not provide more information then the PHP-typehints.

I don't like it, but: Done. =)


Concernig your suggestions:

> HandlerResult: Use Data\Result for the ok/error part of that class and introduce a FileIdentifier for the rest.

definitely a good point, if I can find the time, I'll take it and come up to you with a PR.

> Size: Use Data\DataSize for the various file sizes. Maybe this class is missing a "toByte"-method and it also is certainly missing in the factory of the Data-library.

Also here, I hope I find the time and can do a PR.

> Mimetype: Maybe it's worth the effort to implement this as a Data-type as well. This is used in other places as well, right?

And here as well...

Thank you very much for your review, let me know what there is still to do.

**Comment by klees** [comment]
Hi @chfsx,

sry for getting back to you so late. We (@Amstutz and me) discussed the state of this PR yesterday and have two requests to make before we consider this JF ready.

For one, we are ok with pulling in the new dropzone-implementation, if you promise to look into the unification of the dropzone implementations for ILIAS 7. We would accept this state (having two same but different implementations) for the moment to get this input in return, but this certainly is something which needs to be resolved some time soon.

And second: Please split the `ilCtrlAwareUploadHandler` into two parts: one that contains the methods that the UI-framework really needs (which in our understanding would be `getUploadURL` and `getFileRemovalURL` only) and that is located in the UI-framework, the other that extends from that interface and is located in the FileUpload. We hope this clarifies further, which part of the interface is required by the UI and which is concern of the filesystem. We are also looking into releasing the UI-framework as a library some time in the future and thus would like to minimize dependencies on other components.

Is there anything more we need to discuss atm? Should we have a quick talk tomorrow via skype to gets this back on track soon?

Best regards!

**Comment by chfsx** [comment]
@klees we are all here at the moment: https://thecodinglove.com/when-there-are-only-a-few-days-left-before-the-deadline

no problem :-) I'll implement the desired changes asap and ping you back! Thanks a lot!

**Comment by alex40724** [comment]
Thanks for the PR! Is there any example how to use this on the consumer side? Especially how "the Upload and the Removal are handled correctly"?

**Comment by chfsx** [comment]
@alex40724 there will be a fully working example in the implementation, using a really small implementation of a general file-storage service

**Comment by matthiaskunkel** [comment]
Jour Fixe, 18 NOV 2019 : We highly appreciate this PR and accept it for ILIAS 6. Please merge to trunk.

**Comment by chfsx** [comment]
has been merged with #2347

**Pull request closed without merging**
