### PR TITLE
PHP8: some fixes

### PR DESCRIPTION
**Pull request by nhaagen**
Dear maintainers, 
please check and OK/comment on those changes.
These are patches on whoopses I ran into when creating new objects in the repository,
and I have to cherry-pick them every time I want to use the GUI :)
Thank you.

### CODE REVIEW

**Review by klees — APPROVED** [review]

**Review by alex40724 — APPROVED** [review]
Thanks for the fixes!

Personally I would prefer
`return $this->selected_column[$col] ?? false;`
instead of
`return array_key_exists($col, $this->selected_column) && $this->selected_column[$col];`

But it works boths ways.

**Comment by klees** [comment]
@alex40724 @nhaagen I totally agree. ``??`` is way easier to read IMO.

**Comment by Amstutz** [comment]
@klees : I opted for the contrary some month ago. However, I changed my mind / have been convinced otherwise and it seems to be common practice by now in ILIAS.

**Comment by nhaagen** [comment]
Wow, you are fast  - thank you. 
Added ?? and squashed the previous two commits.

**Review by smeyer-ilias — APPROVED** [review]
Thanks for fixing this.

**Pull request merged**
