### PR TITLE
Maintenance Changes

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Comment by alex40724** [comment]
How to proceed with Services/UI? Classic + Thomas? Coordinator? Any suggestions?

**Comment by mjansenDatabay** [comment]
@alex40724 : Could you please explain what exactly you mean by `Classic + Thomas` :-)?

Would you like to add @tfamula to the `./src/UI` coordinators or as maintainer for `Services/UI`?

**Comment by klees** [comment]
@ILIAS-eLearning/technical-board We should have had a look into this...

**Comment by alex40724** [comment]
I merged this, since it seems to reflect the status quo. The Services/UI question is still an open question though.

**Pull request merged**
