### PR TITLE
Remove/Abandon "Settings Template" feature

### PR DESCRIPTION
**Pull request by mBeym**
Removes the "Settings Template" feature based on https://docu.ilias.de/goto_docu_wiki_wpage_5288_1357.html

### CODE REVIEW

**Comment by mbecker-databay** [comment]
Thank you for the PR! Looks very comprehensive and it's a rare sight to see the language variables considered! Great job!

But I think you are removing a bit too much here:
- I am not sure the removal covers the Survey as well (maybe @dsstrassner has more insight on that matter)
- ...and IF you do not have to remove the settings templates from the survey, you must not drop the tables in the administration.
- I am very sure you do not like to remove didactic templates, that's a whole different beast.

Please look over these points once more, thanks a ton!

**Comment by mBeym** [comment]
> Thank you for the PR! Looks very comprehensive and it's a rare sight to see the language variables considered! Great job!
> 
> But I think you are removing a bit too much here:
> 
> * I am not sure the removal covers the Survey as well (maybe @dsstrassner has more insight on that matter)
> * ...and IF you do not have to remove the settings templates from the survey, you must not drop the tables in the administration.
> * I am very sure you do not like to remove didactic templates, that's a whole different beast.
> 
> Please look over these points once more, thanks a ton!

From the feature wiki:

`And finally: The removal of the settings templates for the Surveys have been accepted by the JF.
`

**Comment by mbecker-databay** [comment]
> > Thank you for the PR! Looks very comprehensive and it's a rare sight to see the language variables considered! Great job!
> > But I think you are removing a bit too much here:
> > 
> > * I am not sure the removal covers the Survey as well (maybe @dsstrassner has more insight on that matter)
> > * ...and IF you do not have to remove the settings templates from the survey, you must not drop the tables in the administration.
> > * I am very sure you do not like to remove didactic templates, that's a whole different beast.
> > 
> > Please look over these points once more, thanks a ton!
> 
> From the feature wiki:
> 
> `And finally: The removal of the settings templates for the Surveys have been accepted by the JF. `

Ok, that's great then (and I would - and have - missed that).
Still, there is a method for didactic templates deleted , which we need to have back, I think.

**Comment by dsstrassner** [comment]
I think originally, there was only 1 article to remove the settings templates from surveys and tests. [The article](https://docu.ilias.de/goto_docu_wiki_wpage_6253_1357.html) to remove the templates for surveys was accepted for ILIAS 8. 
I am unable to deliver more light into this than that ;-)

**Pull request merged**
