### PR TITLE
Update tcpdf library (For PHP 7.2 support)

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=26195

Exception in libs/composer/vendor/tecnickcom/tcpdf/tcpdf.php::16552
```
The each() function is deprecated. This message will be suppressed on further calls
```
Update the library seems to fix this

### CODE REVIEW

**Comment by ghost** [comment]
@gvollbach Current status?

**Comment by gvollbach** [comment]
@sragfw 
Thanks for the pull request and the reminder ;)

If this fixes a problem with PHP 7.2 it is ok for me, could you please resolve the conflict? I will then merge this.

**Comment by ghost** [comment]
Resolved

**Comment by gvollbach** [comment]
@sragfw Thx

**Comment by ghost** [comment]
@gvollbach Could you please fix this also for ILIAS 5.4, since ILIAS 5.4 also supports PHP 7.2?

**Pull request merged**
