### PR TITLE
9/object/feature move actions to ks

### PR DESCRIPTION
**Pull request by kergomard**
Hi @alex40724 , hi all

This PR proposes to remove asynchronous rendering of Actions in ObjectLists to be able to move the Actions to KS.
Rational:
* We don't use asynchronous rendering on the Dashboard at all and we already don't use asynchronous rendering in the Repository, if we show it in "Deck of Cards"-view. Thus the setting does already not do what it says it does.
* We have other methods to avoid high load in bigger `Containers` by setting the maximum amount of shown elements.
* The asynchronous rendering of actions is an accessibility issue.

Best,
@kergomard

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 18 SEP 2023 : We accept the suggested PR for trunk even it might come with performance problems in huge object lists. Please check if we can have a accessible version of the assynchronuous loading of actions in the KS Dropdown (as this might be the best way to prevent  a weaker performance.

**Comment by kergomard** [comment]
Hi all

Thank you very much to the Jour Fixe for the positive feedback!

After the discussions yesterday at the Jour Fixe and different discussions with stakeholders, I decided to postpone the merge of this PR until after the branch of ILIAS 9 is split up. This way we gain one year to improve the necessary checks to the point where we confident it will work for everybody.

Thus this PR will stay open for a little while longer.

Thank you very much and best,
@kergomard

**Comment by matthiaskunkel** [comment]
Hi @kergomard, shall we keep the JourFixe label to notify the community about your decision on the JF today? Or shall I remove it and you pick-up the issue again when there a news to tell about?

**Comment by kergomard** [comment]
Thanks @matthiaskunkel for the reminder. No, I think we should remove the JF label. I see this PR as accepted and the decision is documented in here, so: We just wait a little with the merge, no more information needed.

**Comment by kergomard** [comment]
As the branch for ILIAS 9 has been separated now, I merge this PR.

**Comment by alex40724** [comment]
@kergomard Could you please wait for the requested reviews? Codewise I am not happy with the changes, now I have two setup agents in the repository. This didn't get my top prio, since you decided to postpone it until beta and we have been busy to merge things for the release in the last weeks.

**Comment by kergomard** [comment]
@alex40724 : You were informed, when this would be merged. I couldn't wait longer, because the component revision would make it very hard for this to be rebased.

**Comment by alex40724** [comment]
@kergomard I have been asked for a review here and did not get any info that this would be obsolete. You postponed it and now it got high prio in two days after the branch has been created? This is super rude, sorry. We've been all busy with other things in the last weeks.

**Pull request merged**
