### PR TITLE
Help: KS Tooltip and HelpId as Attributes Integration

### PR DESCRIPTION
**Pull request by alex40724**
This is a follow up of https://github.com/ILIAS-eLearning/ILIAS/pull/6092

This PR is for documentation and discussion purposes. These changes should be merged to the trunk, but since the trunk is currently buggy and the features should be testable, this PR is against the release_9 branch.

It integrates  https://github.com/ILIAS-eLearning/ILIAS/pull/6092 and also the KS tooltips into the legacy tabs.

1) Open integration KS tooltips into the main menu

KS tooltips are currenlty supported by KS buttons and KS links. However the global screen service currently only allows to add modifications to symbols in the mainbar. We would need the global screen service to expose menu buttons and links similarly, to enable their modification (adding tooltips).

2) The integration into the legacy tabs is done by integrating KS links into the legacy tabs. This allows to attach KS tooltips. The JF needs to decide whether this is ok until we have a KS replacement of the legacy tabs.

Before merging this needs some code cleanup: removal of out-commented code and removal of unnecessary ilHelp calls in components.

### CODE REVIEW

**Comment by alex40724** [comment]
@chfsx I just added you as assignee, since afaik the fh dortmunds funds your implementation here. If this is not the case or if this is done, please left a note here. I currently set this on hold on my side.

**Comment by oliversamoila** [comment]
Hello @chfsx and @alex40724, 
can we expect an integration into the trunk before Coding Completed for ILIAS 10?

Best regards
@oliversamoila

**Comment by chfsx** [comment]
@alex40724 as you mentioned in a comment, there was the infrastructure missing to pass `Topics` to global screen items. This is now fixed, I added some lines to the README as well: https://github.com/ILIAS-eLearning/ILIAS/commit/7585f066bde83047a14dbc0a732c36f16d2d6851#diff-5e8e0cc7dc926b44aa31f7c0745cbf05c2989011ef8818b870d6b5156e2b7ea0R125

please not that currently buttons which trigger slates cannot render the tooltips, as soon as this issue is fixed or this PR is merged, this will work as well: https://mantis.ilias.de/view.php?id=42349 / https://github.com/ILIAS-eLearning/ILIAS/pull/8234

**Comment by chfsx** [comment]
And concerning your question: the dortmund part is now done in the mentioned PR and the implementation in GS. I deaasign myself from this PR here. FMPOV this solves your point 

> Open integration KS tooltips into the main menu

the other point is out of my scope,

> The integration into the legacy tabs is done by integrating KS links into the legacy tabs. This allows to attach KS tooltips. The JF needs to decide whether this is ok until we have a KS replacement of the legacy tabs.

You mentioned the JF here, maybe this is the way to go then.

**Comment by alex40724** [comment]
Merged manually. The JF already approved this PR, see decision here: https://docu.ilias.de/go/wiki/wpage_6926_1357

**Pull request closed without merging**
