### PR TITLE
UI: refactor DateTime's picker to HTML5 for accessibility.

### PR DESCRIPTION
**Pull request by lukastocker**
Also remove datetime-picker javascript from DateTime rendering.

Adjust DateTime tests.

**NOTE:**
Currently it's not possible to remove the bootstrap-datetimepicker.js files because the Button > Months still uses it: There's no Month-Picker for HTML5 until now - only a <input type="month".. /> but it's just functioning like a text input - so it's not a picker. Therefore the Button "Month" is still not accessible.

The duration.js file isn't needed anymore, because duration is now using the HTML5 types too.

### CODE REVIEW

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
@thibsy @Amstutz This LGMT, please have a look too.

**Review by thibsy — CHANGES_REQUESTED** [review]
Hi @lukastocker

Thanks a lot for your contribution to the UI components!

Please note that I have not looked at the changes in `Services/Forms` and `Modules/Test`, I only reviewed changes to the UI framework.

I've tried out the improved datetime input locally and found some issues, therefore please implement the following changes:

- [ ] Chrome Issue: I am using Google Chrome 116 myself, where I noticed an issue with the format, caused by the disabled input of the example: `The specified value "2023-09-27 11:00" does not conform to the required format, "yyyy-MM-dd"`. Could you look into this?
- [x] `Field\Renderer::renderDurationField()`: please remove the additional JavaScript code of the input, calling `il.UI.Input.duration.init`, which has been removed.
- [x] `Field\Renderer::renderDateTimeField()`: please revert [this change](https://github.com/ILIAS-eLearning/ILIAS/pull/6276/files#diff-f3892e7d92b0895c6b153d2f1754b755fc888a4b5199b1d4f8784a7344b81d5fR684). We still need to call `Renderer::bindJSandApplyId()`, otherwise `DateTime::withAdditionalOnLoadCode()` doesn't work anymore.
- [x] Example: there is a new [unused import](https://github.com/ILIAS-eLearning/ILIAS/pull/6276/files#diff-f39144158491586c4b11302127abc48fbb9a7284b84bf9175dff06051f988dbeR7) in the example, please remove it.

Kind regards,
@thibsy

**Comment by dsstrassner** [comment]
I added @kergomard for the Changes in Modules/Test as reviewer ;)

**Review by kergomard — APPROVED** [review]
Thank you very much for improving the picker!
Changes in Test LGTM.

**Comment by lukastocker** [comment]
> Hi @lukastocker
> 
> Thanks a lot for your contribution to the UI components!
> 
> Please note that I have not looked at the changes in `Services/Forms` and `Modules/Test`, I only reviewed changes to the UI framework.
> 
> I've tried out the improved datetime input locally and found some issues, therefore please implement the following changes:
> 
>     * [ ]  Chrome Issue: I am using Google Chrome 116 myself, where I noticed an issue with the format, caused by the disabled input of the example: `The specified value "2023-09-27 11:00" does not conform to the required format, "yyyy-MM-dd"`. Could you look into this?
> 
>     * [ ]  `Field\Renderer::renderDurationField()`: please remove the additional JavaScript code of the input, calling `il.UI.Input.duration.init`, which has been removed.
> 
>     * [ ]  `Field\Renderer::renderDateTimeField()`: please revert [this change](https://github.com/ILIAS-eLearning/ILIAS/pull/6276/files#diff-f3892e7d92b0895c6b153d2f1754b755fc888a4b5199b1d4f8784a7344b81d5fR684). We still need to call `Renderer::bindJSandApplyId()`, otherwise `DateTime::withAdditionalOnLoadCode()` doesn't work anymore.
> 
>     * [ ]  Example: there is a new [unused import](https://github.com/ILIAS-eLearning/ILIAS/pull/6276/files#diff-f39144158491586c4b11302127abc48fbb9a7284b84bf9175dff06051f988dbeR7) in the example, please remove it.
> 
> 
> Kind regards, @thibsy

Hi @thibsy ,

I just updated this PR with your requested changes. 

Greetings,
Luka

**Review by thibsy — CHANGES_REQUESTED** [review]
@lukastocker thx for implementing the changes so quickly!

There is still one minor thing I just noticed when looking over this again, please change:

- [ ] `Field\Renderer::registerResources()`: the `duration.js` which has been removed with this PR is still included in this method. Please remove the according line as well.

Afterwards this is IMO good to go. Thanks for improving our A11y!

Kind regards,
@thibsy

**Comment by oliversamoila** [comment]
Hello @tfamula , 
please have a look at this PR, which should be the basis for the integration of the Date(Time)Picker in the filter.
Best regards.

**Comment by lukastocker** [comment]
> @lukastocker thx for implementing the changes so quickly!
> 
> There is still one minor thing I just noticed when looking over this again, please change:
> 
>     * [ ]  `Field\Renderer::registerResources()`: the `duration.js` which has been removed with this PR is still included in this method. Please remove the according line as well.
> 
> 
> Afterwards this is IMO good to go. Thanks for improving our A11y!
> 
> Kind regards, @thibsy

Hello @thibsy ,

the duration.js reference is now removed. Thanks for checking throughout.

Kind regards,
Luka

**Review by thibsy — APPROVED** [review]

**Comment by thibsy** [comment]
Thx @lukastocker

Since `Services/Forms` is under implicit maintenance, I felt free to merge this now.

Kind regards,
@thibsy

**Pull request merged**
