### PR TITLE
T&A Feature: Centralized online status for Testpools

### PR DESCRIPTION
**Pull request by fhelfer**
Implementing FW: https://docu.ilias.de/goto_docu_wiki_wpage_7199_1357.html for TestPool

### CODE REVIEW

**Comment by dsstrassner** [comment]
@oliversamoila Du musst das abnehmen und dich um die Testcases kümmern!

**Review by kergomard — CHANGES_REQUESTED** [review]
Thank you very much @fhelfer for improving the settings of the Question Pool !

First: This review has only to do with form and not with function. It looks like this should work, but I did not test!

I would kindly ask you to make the following changes:
* Please don't use `new ilObjectPropertyIsOnline(true)` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-1cb659c07cfa02fb1a744e11d5b0cf83003aa4d4a493c7f0943005f089d4cfffR1585) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-070fc08d5f8b6333e1cc989789da909a4b817e419f7a7085cb144bb5c1affc05R46) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-070fc08d5f8b6333e1cc989789da909a4b817e419f7a7085cb144bb5c1affc05R211) but get it from the Object `$this->getObjectProperties()->getPropertyIsOnline()->withOnline()` should do the trick.
* Please remove [this static function](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-4c874363e848c32787e7eaa118b0ab131bec0e7711097bac22c1d0589be2d0daR711) completely. It is only used in `ilObjQuestionPoolListGUI` there you can access the ObjectProperties directly.
* Could you please move all namespaces to use statements [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-79341fc60c03ba53809fb097ae04d5d5a3e597a46a47406f01dd0fed78e926c2R51-L51).
* Could you please get the settings for title and description directly from `ilObject`? Please see `ilObjTestSettingsMainGUI` or the documentation in `ilObject` on how.

And then two non actionable feedbacks:
* [This here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-2f8d175f8c8a984af614e70d63a44dbb90090b276cd3f4e8b11b04e66d893671R51) is stretching the definition on what DB-Update-Steps should do pretty far, but I think, we can live with it.
* This here would be a great place for a repository, but this is not the right moment to ask for this.

Thank you very much again and best,
@kergomard

**Comment by oliversamoila** [comment]
Approval has been done. Documentation in the FeatureRequest has been done so far. TestCase follows.

Merging is up to you. Thank you all!

**Comment by fhelfer** [comment]
Thx for the feedback @kergomard,
i tried to implement all your annotations

Best, @fhelfer

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

Two last things (I will then quickly install, test and merge):
* You can remove the setting of Title and Description in the metadata [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-f19e48a32524b1e7edbe8a8125a5b8d7e321e7f54cbb90282fd8ef339c652fbaR125-R142). Metdata should be informed about changes, if it isn't (completely possible), then I need to fix that in ilObject.
* Could you please use array_keys for all form elements and access them through their keys instead of through `current()` e.g. [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-f19e48a32524b1e7edbe8a8125a5b8d7e321e7f54cbb90282fd8ef339c652fbaR120) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-f19e48a32524b1e7edbe8a8125a5b8d7e321e7f54cbb90282fd8ef339c652fbaR147).

Thank you very much and best,
@kergomard

**Comment by fhelfer** [comment]
Hi @kergomard,

> * You can remove the setting of Title and Description in the metadata [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6467/files#diff-f19e48a32524b1e7edbe8a8125a5b8d7e321e7f54cbb90282fd8ef339c652fbaR125-R142). Metdata should be informed about changes, if it isn't (completely possible), then I need to fix that in ilObject.

This does not seem to work. I have removed anyway. Maybe you can identify whats the problem there.
The PR is now ready for you to install and test

Best, @fhelfer

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

You are right, and I will take care of that in `ilObject`.

I merge this as it is.
Thanks again and best,
@kergomard

**Pull request merged**
