### PR TITLE
fix/25537/5-4/ilExcel_getCell

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=25537

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724 and @chfsx, I assigned you both since you are listed as implicit maintainers in that module. Please give a short note if you do not feel responsible.

**Comment by xus** [comment]
Hi,
Thank you @sragfw for this PR. 

I would like to propose a few changes to avoid side effects.
- I would like to use the new method [columnIndexAdjustment](https://github.com/ILIAS-eLearning/ILIAS/blob/8e27a7ff6e2e33fbb86a35bd0708973e2015866f/Services/Excel/classes/class.ilExcel.php#L616) to keep this column index stuff only in one place in the ilExcel adapter.

- Also, ilExerciseManagementCollectFilesJob.php has to be adapted. This [loop](https://github.com/ILIAS-eLearning/ILIAS/blob/8e27a7ff6e2e33fbb86a35bd0708973e2015866f/Modules/Exercise/classes/BackgroundTasks/class.ilExerciseManagementCollectFilesJob.php#L588) has to start by 0


-The following lines are also affected (I'm so sorry @theodortruffer ) :
The "+1" for the key is not needed anymore. 
https://github.com/ILIAS-eLearning/ILIAS/blob/8e27a7ff6e2e33fbb86a35bd0708973e2015866f/Modules/DataCollection/classes/Content/class.ilDclContentImporter.php#L217
and the last lines have to be removed to keep the previous state.
https://github.com/ILIAS-eLearning/ILIAS/blob/8e27a7ff6e2e33fbb86a35bd0708973e2015866f/Modules/DataCollection/classes/Content/class.ilDclContentImporter.php#L225 
just return $import_fields;
  
(mainly commit 80fb506ced550ab4e30b474f70273e496419c20a)

I will check if there is something missing to adapt and If @alex40724 , @chfsx consider I can provide another PR

**Comment by alex40724** [comment]
@xus OK thanks. Another PR would be fine for me.

**Comment by xus** [comment]
We continue the discussion in this [new PR](https://github.com/ILIAS-eLearning/ILIAS/pull/1900) which contains the commented changes. 
I close this PR.

**Pull request closed without merging**
