### PR TITLE
Cleanup, docu and refactoring in ilCtrl (rebased)

### PR DESCRIPTION
**Pull request by alex40724**
Follow up of 
https://github.com/ILIAS-eLearning/ILIAS/pull/615

Sorry for the strange commit message. The interactive rebasing took a while and in some step I seem to have not outcommented the correct lines...

### CODE REVIEW

**Comment by alex40724** [comment]
Not able to run final tests. Waiting on https://mantis.ilias.de/view.php?id=23876 to be fixed.

**Comment by alex40724** [comment]
@mjansenDatabay Ok, meanwhile there is a
$DIC->ctrl()->setTargetScript('saml.php');
call in ilStartUpGUI that relies on the availability of setTargetScript.

Any way to work around this. Otherwise I would keep this method and set the default to "ilias.php".

**Comment by mjansenDatabay** [comment]
We MUST use `saml.php` here because links generated in `\ilStartUpGUI::showSamlIdpSelection` MUST result in a request to `saml.php` with `ilContext::init(ilContext::CONTEXT_SAML);` being executed. Until this `Context Thing` in ILIAS is not revised, I cannot get rid of `$DIC->ctrl()->setTargetScript('saml.php');`. 

Of course I could add some `&action=saml` parameter to links targetting `ilias.php` and execute `ilContext::init(ilContext::CONTEXT_SAML);` if the value of the `action` query parameter eqals `saml`, but this is even more worse.

Or I could manipulate the return value of `ilCtrl::getLinkTarget` and replace `ilias.php` with `saml.php`, but I guess this is not an option :-). :-1:

**Comment by klees** [comment]
Hi @alex40724, the complete history of my previous PR is missing and the final commit message in this PR looks strange. Is this intentional?

**Comment by alex40724** [comment]
See my comment on top. I got rid of the conflicts in a squash/rebase procedure and in one of the steps the message was messed up. I live with that for now.

**Comment by alex40724** [comment]
Cherry picked, fixed at least the commit message.

**Pull request closed without merging**
