### PR TITLE
PluginSlot: Remove final from private method (ILIAS 7)

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=29378

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Duplicate of #3045

**Comment by ghost** [comment]
@mjansenDatabay Sorry, I didn't see your PR for ILIAS 7 too, because not linked in Mantis ticket

**Comment by ghost** [comment]
@mjansenDatabay Moment, your PR is for ILIAS 6, my PRs for ILIAS 7 and ILIAS 8, so all ok

**Comment by mjansenDatabay** [comment]
@sragfw You are right

**Pull request merged**
