### PR TITLE
UI Tree/Node: Add roadmap entry for node state persistence

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Comment by klees** [comment]
Hi @mjansenDatabay,

thanks fo adding this Roadmap-entry, much appreciated! Please add one (or more) sentences that explicitly tell, what we would like to achieve with the UI-framework regarding the persistence.

Best regards!

**Comment by Amstutz** [comment]
Hi @klees, 

How to we proceed here? It's been open for a while. Is persistance not something, some wrapper service should provide? E.g. located in Services/UI.

I propose to:
a) close this down due to inactivity
b) merge and drop some sentence that it remains an open question, where the centralized persistance layer should be located at and would be part of the problem.

both is fine with me.

greetings.

**Comment by klees** [comment]
I'd pick b) because this seems to be an issue for `Tree` users.

**Comment by Amstutz** [comment]
Done.

**Pull request merged**
