### PR TITLE
WIP feature RuleEngine

### PR DESCRIPTION
**Pull request by mstuder**
https://docu.ilias.de/goto_docu_wiki_wpage_5780_1357.html

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks for the PR. How does this relate to the Transformation/Refinery concepts?

**Comment by mjansenDatabay** [comment]
I also think parts of this could be strongly related to the `Refinery` and the `Transformation` strategies (already and in future) provided there, e.g. in `NumberHandler`, `IntegerHandler`, `ArrayHandler` ...

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 MAY 2019: Martin notified the JF about his plans for a rule engine and will discuss ideas and the relation to the transformation and refinery concepts with Michael and Richard, soo.

**Comment by kergomard** [comment]
Hi @mstuder 
This PR came up during our TB meeting yesterday and we wondered if you are still working on this or if it can be closed? Thank you very much for a quick reaction

**Comment by klees** [comment]
Send reminder to @mstuder today.

**Pull request closed without merging**
