### PR TITLE
(bugfix#30128): fixed container name, added rol_id to distinguish roles with same names

### PR DESCRIPTION
**Pull request by utesche**
The associated rol_id is enclosed in colons and prefixed to lookup list entries.  If the choosen (or typed) selection begins with such a word (digits enclosed in colons), it is used directly as the rol_id for the assignment.

Perhaps the list of current assignments should be tempered accordingly...  not included in this PR.

### CODE REVIEW

**Comment by kergomard** [comment]
Hi @smeyer-ilias 

we stumbled upon this PR in our TB meeting. If you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by chfsx** [comment]
Hi @smeyer-ilias 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by mjansenDatabay** [comment]
Hi @smeyer-ilias 

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias

As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by smeyer-ilias** [comment]
Sorry, for the delay.
I will check and test this PR after my vacation.

**Review by smeyer-ilias — COMMENTED** [review]
Thanks for your contribution.
I do not merge this PR since: 
- I'm not the maintainer of the LDAP-service.
- IMO this needs an more generic implementation since the local role search is used in other components like Shibboleth, ilUserStartingPoint, too.

**Comment by chfsx** [comment]
Dear PR, please accept my sincere apologies for not congratulating you on your 2nd birthday!

All joking aside... @pascalseeland can you give an assessment of whether you can look at this PR, whether it needs adjustments or how to proceed with it? thank you very much!

**Comment by klees** [comment]
Hi @pascalseeland

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the ressources to look into it in detail.

Best regards!

**Comment by nicoroeser** [comment]
Adding reverse pointer: see [comment](https://docu.ilias.de/goto.php?target=wiki_1357_Role_assignment_of_local_roles_for_OpenID_Connect_%28OIDC%29_Authentication#ilPageTocA127) dated 07 AUG 2023 by @utesche on a related matter, the [Role assignment of local roles for OpenID Connect (OIDC) Authentication](https://docu.ilias.de/goto.php?target=wiki_1357_Role_assignment_of_local_roles_for_OpenID_Connect_%28OIDC%29_Authentication).

**Comment by pascalseeland** [comment]
As mentioned in the bug report, I proposed a different approach to this issue.

**Pull request closed without merging**
