### PR TITLE
Setup: Create directories (fixes #27173)

### PR DESCRIPTION
**Pull request by nhaagen**
Create directories during setup.
https://mantis.ilias.de/view.php?id=27173

I used Setup/ilClient::create as a reference - but I'm not sure if all of the directories are still being used or to which Service/Module they really belong. Please correct me ;)

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

thanks for looking into this, this looks as if it should do what it is supposed to do. However, there seem to be a lot of duplication and cruft which I feel we should try to get rid of.

Please implement the following changes:
- [x] Implement a base class `ilFileSystemComponentDataDirectoryCreatedObjective` in `Services\FileSystem` that wraps around that duplicated mangling of names for data-directories. Base that class, in turn, on `ILIAS\Setup\DirectoryCreated`. Let that class have the precondition `ilFileSystemDirectoriesCreatedObjective.php`. It should be possible to remove all these specific classes for the different components and use the new class in the agents directly. This will remove like 50% of code, I guess.
- [x] There is to much of `l`in `ilForum_l_Directories...` (if we still need that class, anyway).

Call me, if there is anything you need to discuss. I will post the responsible maintainers afterwards.

Thx and best regards!

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Hi @mjansenDatabay, @alex40724, @smeyer-ilias  and @chfsx,

please have look here, we would like to add new `Objectives` for the setup in some component of you. Currently there seem to be some directories that ILIAS expects to be created in the initial setup process and that we had missed in the CLI setup so far. This PR adds according `Objective`s (and `Agent`s, where required) to the applicable components. To ease this progress we added a base class to `Services\FileSystem`, which @chfsx should check.

As always, feel free to give feedback, ask questions, contact me, disagree etc.

Thanks for your time and best regards!

**Review by chfsx — APPROVED** [review]
thank you very much, this def. LGTM!

**Review by mjansenDatabay — APPROVED** [review]
LGTM!

**Comment by klees** [comment]
@alex40724 @smeyer-ilias Could you please have a quick look here? Thx!

**Review by alex40724 — APPROVED** [review]
@nhaagen Great! I had some related bugs and started to create directories "on demand" in my code since in all cases additional subdirectories are created, too. Not sure what out "best practice" should be. This is fine, also the User related stuff, so this can be merged from our (Leifos) side imo.

**Comment by alex40724** [comment]
You just can hand over any "missing directory bugs" in my components directly to me.

**Review by smeyer-ilias — APPROVED** [review]
Thanks, looks good to me.

**Comment by klees** [comment]
@alex40724

> Not sure what out "best practice" should be.

With the ideas from @chfsx regarding the filesystem we seem to be heading in a direction where things like directories become opaque for consumer code anyway. So I guess at some point the filesystem service will be the only one actually creating directories, either during the setup or some other time.

**Pull request merged**
