### PR TITLE
UI, DataTable: do not order for one record

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=41513

### CODE REVIEW

**Comment by nhaagen** [comment]
Here's the fix for the failing test: https://github.com/ILIAS-eLearning/ILIAS/pull/7716

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

is this enough? Does this also remove the little arrows from the headers of the rows?

Kind regards!

**Comment by nhaagen** [comment]
> is this enough? Does this also remove the little arrows from the headers of the rows?

yes, the headers are built with the internal signal from the ViewControl.
if it's not there - which will be the case with a null-control  - the headers are rendered without any link:

https://github.com/ILIAS-eLearning/ILIAS/blob/1f47355707b6d7814fe663240ef860f90ee2f354/components/ILIAS/UI/src/Implementation/Component/Table/Renderer.php#L296

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
@Amstutz/@thibsy: This LGTM. Please have a look as well =)

Thanks!

**Comment by Amstutz** [comment]
@nhaagen

thx a lot for this neat improvement.

one detail:
- [x] $total_cout: make it mandatory in getViewControlOrdering

thx a lot,
@thibsy and @amstutz

**Comment by Amstutz** [comment]
thx a lot!

**Pull request merged**
