### PR TITLE
Proposal/update phpunit 5 7

### PR DESCRIPTION
**Pull request by chfsx**
- Updated the defined version of PHPUnit with 5.7.
- Replaced all deprecated getMock() with createMock()

Not sure if this need modification on ci.ilias.de, maybe @gvollbach can help.
I ran all Tests locally, everything fine besides all tests which uses the filesystem but this is not related to the changes here. We should refactor those test separately.

### CODE REVIEW

**Review by gvollbach — APPROVED** [review]
@chfsx
Looks good to me. I just checked this locally seems to work fine, big thanks for the work.
On the CI there is still an old phpunit 4.8.x for testing against PHP 5.5 which I would remove after this pull request is merged. Because after this we can only test against at least PHP 5.6, which would be fine for me.

**Comment by chfsx** [comment]
@gvollbach many thanks for checking this. I thinks it's correct to test against PHP 5.6 in trunk, see http://www.ilias.de/docu/goto_docu_wiki_wpage_4770_1357.html

**Comment by gvollbach** [comment]
@chfsx
I know, if PHP 5.6 wasn't a requirement, I would have said lets go directly to PHPUnit 6.1 but this would also require to change our tests to Namespaces. Because for example:
`PHPUnit_Framework_TestSuite`
under PHPUnit 6.1.x would be
`PHPUnit\Framework\TestSuite`
 
So PHP 5.6 and PHPUnit 5.7.x is ok for me.

**Comment by chfsx** [comment]
We tried with PHPUnit 6 which breaks a lot of tests (after migrating to namespaces) and marks a lot of "useless" tests.

**Comment by gvollbach** [comment]
Yeah this would be a slightly bigger project, and since we have to support 5.6.x this is the best compromise I think, I will configure the CI server accordingly to this changes so that this should not break the build if its is merged.

**Comment by chfsx** [comment]
Thank you a lot! As you might know I'm not really happy with the PHP 5.6 thingy, I'd rather drop the PHP 5 Support. We will have to migrate the test anyways. But at the current state PHPUnit 5.7 fits best

**Comment by gvollbach** [comment]
Yes I know. But since we are at this discussion anyway, could you have a look at your:
1) ilWACTokenTest::testFolderTokenWithSecondFile
Services/WebAccessChecker/test/Token/ilWACTokenTest.php:248

This is the last flaky test we have.

And I just configured the CI Server so that we are now testing the trunk against PHP 5.6, 7.0, 7.1 and HHVM with PHPUnit 5.7.20.

**Comment by chfsx** [comment]
I'l tackle the flacky-test directly in trunk! 

If there are no objections I'll merge this PR in a week

**Comment by matthiaskunkel** [comment]
Jour Fixe, June 19, 2017: Pull request is accepted. Please merge to trunk and update the DevGuide accordingly.

**Pull request merged**
