### PR TITLE
Implemented dicto into CI

### PR DESCRIPTION
**Pull request by catlauraherzog**
Implemented dicto into the CI-System. The results will be exported as csv so travis needs sqlite. The results will be automatically generated with the cronjob as @klees suggested.

### CODE REVIEW

**Review by klees — COMMENTED** [review]
Hi @lauraquellmalz,

maybe I am missing somethings huge here, but where do you read the *.csv's back into an sqlite-database for the next run of dicto?

Best regards!

**Review by gvollbach — APPROVED** [review]
The integration looks good to me. Please check the comment from Richard, which treats the functionality.

**Comment by catlauraherzog** [comment]
Hey @klees,

thanks for the information. I implemented the results database into the CI-Results for the use of the next runs of dicto.

Best,
Laura

**Comment by klees** [comment]
Hi @lauraquellmalz,

I close this, I think we need to reconsider here in the context of GitHub Actions and possible reporting improvements. Keep the branch, though, it contains good stuff imo.

Best regards!

**Pull request closed without merging**
