### PR TITLE
UI Filters (new branch)

### PR DESCRIPTION
**Pull request by tfamula**
This is the third PR for the Filters, which uses a new branch with a current trunk state and also solves all the conflicts from #1253.
#1253 is closed now and the final discussion/review will be continued here.

### CODE REVIEW

**Comment by klees** [comment]
Hi @tfamula,

do we still need the two older PRs (#1193, #1253) to be open? Will you ping me and @Amstutz if this is ready for review?

Best regards!

**Comment by tfamula** [comment]
Hi @Amstutz and @klees!
I tackled the points from our VC on 14 march 2019 (https://github.com/ILIAS-eLearning/ILIAS/pull/1253#issuecomment-472771658):

- Expanding and collapsing the filter is possible in all states of the filters now, activated and deactivated, on desktop and mobile. There is no longer full round-trip by doing this, because Ajax is used now.

- The task with the `getUpdateOnLoadCode` method is still open. I would really like to put this to the Roadmap for now. I would be very happy if we could merge the Filters like they are currently. After that, I will talk with @alex40724 and @Amstutz if this open task will be done by me, too.
Shall I write the entry for the Roadmap? Because in the minutes from 14 march we wrote that this will be done by by @klees if needed.

- Furthermore, I had to spent some time with the unit tests because of switching to a current trunk state, the PHPUnit8 migration and the changes in the Filter itself of course. 
I also figured out that some of the tests cannot be executed correctly due to `ilTemplate`. @xus told me that there are some problems with it in the trunk at the moment. This goes also for existing tests, you can e.g. have a look at the Forms. Nevertheless, I wanted to be finished with everything and decided to make a little detour to make the Filter tests ready. At 99%, the tests should pass when the ilTemplate-problem is solved ;-)

That's all from me. I hope you are happy with the Filters like they are now and look forward to a merge in the next days :-)

Many greetings

**Comment by Amstutz** [comment]
Hi @tfamula 

IMO, the points discussed and listed in #1253 have been taken care of. I also advocate to merge this soon. If more issues occur, we can handled them as bugs. I am also fine with handlinge getUpdateOnLoadCode as entry in the Roadmap. @klees as soon as you are fine with the PR, press the merge button to avoid upcoming conflicts.

Greetings,
Timon

**Comment by klees** [comment]
Hi @tfamula, 

I opened a PR for the roadmap-entry against your initial repo. I'm still not happy with this, since `Input` now advertises an API that it does not deliver. This will need to be fixed soon and I hope that you will be available for this. Please merge that PR and update the two conflicts, then I'll press the button.

Best regards!

**Pull request merged**
