### PR TITLE
TA: 41167, show number of requested hints in detailed results

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=41167

### CODE REVIEW

**Comment by dsstrassner** [comment]
Thank you so much for your swift response!

**Comment by dsstrassner** [comment]
hi @thojou and @mbecker-databay please review and merge. From my point of view, this looks good in the GUI.

**Review by thojou — APPROVED** [review]
I considered adding the new label and its corresponding value directly into the `$important_fields` array instead of creating a new variable. However, if we don't need to pass the new label into the `setImportantFields` method later on, this change seems suitable.

@mbecker-databay, could you also take a look and proceed with merging?

**Comment by thojou** [comment]
Hey @nhaagen ,

sorry for the slow response. I have know taken this PR and cherry-picked the changes into the trunk.

Thank you.

**Pull request merged**
