### PR TITLE
Introduction of new LP icons

### PR DESCRIPTION
**Pull request by schmitz-ilias**
This PR fixes [31804](https://mantis.ilias.de/view.php?id=31804) and [28832](https://mantis.ilias.de/view.php?id=28832) by introducing new icons for the learning progress status, and by implementing a new factory supplying both fully rendered icons and just the image paths to the icons.
The new icons are available in two variations, long and short, with long being the default. Hence, I only chose the short variant in views where limited space made it necessary, e.g. in TOCs and table headers. Further, in a few places slight changes to spacing in templates where necessary to accomodate the new icons.
Affected are the modules Course, DataCollection, Exercise, Forum, Group, LearningModule, LearningSequence, Portfolio, Scorm2004, ScormAicc and Wiki, the services Container, MyStaff and Tracking, as well as the delos css template. 

Please note that the version of the new icons included here is preliminary. The final version will be available in a few weeks, but will vary at most in the amount of whitespace around the icons. Additionally, due to some bugs in the trunk I was not able to access some of the views in ILIAS that include the icons (fields in data-collection tables of the type 'reference', course memberships in MyStaff, tracking tables of the SCORM modules, and results of learning objectives in info screens). Some adjustments to this implementations might thus be necessary in the upcoming weeks, but in return it will also benefit from the current testing phase.

### CODE REVIEW

**Review by alex40724 — APPROVED** [review]
Changes in
Modules/Exercise
Modules/LearningModule
Modules/Portfolio
Modules/Wiki
Services/Container
are fine for me. Thanks.

**Review by mjansenDatabay — APPROVED** [review]

**Review by yvseiler — APPROVED** [review]
This review comment here is limited to the icons mentioned in this PR (at the bottom under "Files changed"): The icons according to what Matthias Kunkel, Enrico Zenzen and Yvonne Seiler have created with icon designer Caroline Wanner. The distinction of status is based on the position of the status icon. The colour additionally helps colour-sighted people to distinguish, but is not the only characteristic.

If adjustments of the individual icons (e.g. size or position) are necessary, this can be done by replacing the icons while retaining the file names.

**Review by Amstutz — COMMENTED** [review]
Hi @schmitz-ilias 

Thx a lot and kudos for this commit. There is just one minor request from my part: 

- [x] Less Variable: can you use the @il-icon-size-small less variable for the icon height and calculate the width then from this size accordingly?

Other than that, I am fine with this. We also discussed this with the TB on how to proceed, since so many devs are involved here. We agreed that this can be merged if the System Styles Mantainer approves this, since this is in its core a change in the way the system Styles work. However, since much of the code also involves Tracking (especially ilLPStatusIcons class), this best also gets approval from @smeyer-ilias . So, IMO this can be merged as soon as the less variables change is performed, and @smeyer-ilias approves this as well.

Thank you very much!

**Comment by schmitz-ilias** [comment]
Hi @Amstutz, I just implemented your requested change on my local installation, and at least to my eyes the icons look a bit too bulky with @il-icon-size-small as their height. Would @il-icon-size-xsmall be alright as well?

**Review by smeyer-ilias — APPROVED** [review]
Thanks @schmitz-ilias All changes are fine for me

**Comment by Amstutz** [comment]
@schmitz-ilias , Yes.

**Comment by schmitz-ilias** [comment]
@Amstutz, is [this](https://github.com/ILIAS-eLearning/ILIAS/pull/4739/commits/ea3e81e0f9c1742546d134da8a5a30f4d7d20e52) what you had in mind?

**Comment by Amstutz** [comment]
Yes, thx a lot! Since @smeyer-ilias also approved this, I merge this. Thx a @schmitz-ilias for your contribution.

**Pull request merged**
