### PR TITLE
Docs: update member to security.md

### PR DESCRIPTION
**Pull request by QualitusHartwig**

### CODE REVIEW

**Comment by dsstrassner** [comment]
hi @acgruber  & @ILIAS-eLearning/technical-board, one question: do we always update these .mds on every ILIAS version or only on Trunk?

**Comment by acgruber** [comment]
Dear @ILIAS-eLearning/technical-board,
I would appreciate your advise on this matter. Please also see #8119 and #8120. I would tend to merge this to trunk only, since that is our main docu branch. Can you confirm? If yes, I'd proceed to merge the trunk-PR and close the two others.
Thanks and kind regards!

**Comment by mjansenDatabay** [comment]
Hi @acgruber,

first, thanks for caring.

> I would tend to merge this to trunk only, since that is our main docu branch. Can you confirm?

After a short discussion in the "Technical Board" we agree: The change should be merged into `trunk`, the other PRs can be closed.

Thanks in advance.

Best regards
Michael

**Comment by acgruber** [comment]
Thanks for the feedback, @mjansenDatabay! Will close this PR accordingly.

**Pull request closed without merging**
