### PR TITLE
25610 trunk

### PR DESCRIPTION
**Pull request by dkloepfer**

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724,

this will add an event to the ContainerReference. Please have a look.

Thx!

**Review by alex40724 — APPROVED** [review]

**Comment by alex40724** [comment]
@smeyer-ilias Fine for me, any objections?

**Comment by smeyer-ilias** [comment]
No objections from me. Can be merged.

**Comment by klees** [comment]
Merged this to trunk manually. Thx @dkloepfer

**Pull request closed without merging**
