### PR TITLE
(proposal fix 22214) Grid Calendar improvements

### PR DESCRIPTION
**Pull request by xus**
Improvements and fixes related to https://www.ilias.de/mantis/view.php?id=22214

### CODE REVIEW

**Comment by xus** [comment]
- [ ] Bug in Day and Week view: The div which contains the event must occupy all the space of the parent <td> it does not fill more than one row using google Chrome.

**Comment by xus** [comment]
This PR also fixes this another bug: https://www.ilias.de/mantis/view.php?id=22211

**Comment by alex40724** [comment]
Please provide the pull request against current 5.3 (one PR for all plugin issues, since they are related).

**Comment by xus** [comment]
PR for 5.3 -> https://github.com/ILIAS-eLearning/ILIAS/pull/795

**Comment by Amstutz** [comment]
This seem to take a different approach than the one for 5.3 (#795). Here still absolut positioning is used. To make things easier. Close this one and wait until we have accepted version for 5.3. Then directly promote this to trunk without additional PR (since it will be identical).

**Review by Amstutz — CHANGES_REQUESTED** [review]
Please close this one, it is out of date. #795 is to be discussed.

**Pull request closed without merging**
