### PR TITLE
Allow other php session cookie names for the session handling

### PR DESCRIPTION
**Pull request by amichelsdatabay**
e.g. multiple session in multiple clients

### CODE REVIEW

**Comment by chfsx** [comment]
@smeyer-ilias thats OK for our parts (DatCollection)

**Review by chfsx — APPROVED** [review]

**Comment by amichelsdatabay** [comment]
Hey @bheyser  guck mal. Nicht viel zum approven :)

**Comment by bheyser** [comment]
Approved changes within T&A files. Thx!

**Review by bheyser — APPROVED** [review]

**Comment by smeyer-ilias** [comment]
Thanks for this fix. 
I checked the trunk after the merge => no occurrences of PHPSESSID left.

**Pull request merged**
