### PR TITLE
replace imsglobal/lti with celtic/lti

### PR DESCRIPTION
**Pull request by Uwe-Kohnle**
replaced old imsglobal lib with celtic/lti (https://github.com/celtic-project/LTI-PHP/tree/support/v3);
Version 4 is not used  because of changes for LTI 1.3.

### CODE REVIEW

**Comment by Uwe-Kohnle** [comment]
The library from the ceLTIc project (http://celtic-project.org/) involves developers who previously developed the reference code for the standards organization IMS Global Learning Consortium (https://www.imsglobal.org/) (https://github.com/IMSGlobal/LTI-Tool-Provider-Library-PHP). I would like to highlight Stephen Vickers here (https://github.com/spvickers).
From the same house also a very popular TestTool comes: https://ltiapps.net/test/tc.php (see also https://lti.tools/saltire/).
The PHP library is widely used and takes into account, among other things, special features of Canvas and Moodle. From celtic-project there is also an implementation for Worpress.
The last update of https://github.com/celtic-project/LTI-PHP/tree/support/v3 was 17 days ago.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 21 DEC 2020 : We will postpone the decision about accepting this library to the next Jour Fixe and ask Uwe to give some details about the need and reliability of this library, esp. the middle-term and long-term strategy of this library and its need to change it, as well as the change situation when LTI 1.3 will be implemented. Is there any other library we could use? Is there a chance to substitute the lib by ILIAS core code?

**Comment by Uwe-Kohnle** [comment]
After consultation with Stefan Meyer, we propose a feasibility study to examine whether a LTI library to be included can be avoided with regard to LTI 1.1 and with regard to further developments towards LTI 1.3. Risks and costs are to be addressed in the process.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 11 JAN 2021 : We follow Uwes suggestion to make a feasibility study before deciding if we move to another library or implement an own one for LTI support. A decision is also related to the decision about moving to LTI 1.3 or not.

**Comment by mjansenDatabay** [comment]
Hi @Uwe-Kohnle 

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by chfsx** [comment]
Hi @Uwe-Kohnle

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by mjansenDatabay** [comment]
Hi @Uwe-Kohnle

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by chfsx** [comment]
Hi @Uwe-Kohnle 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by mjansenDatabay** [comment]
Hi @Uwe-Kohnle 

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by kergomard** [comment]
Hi @Uwe-Kohnle
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by Amstutz** [comment]
Hi @Uwe-Kohnle
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Pull request closed without merging**
