### PR TITLE
T&A, 39119: MultiSelect for Taxonomy Filter

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=39119
https://mantis.ilias.de/view.php?id=41532

Screenshot from 2024-06-03 14-52-03

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @nhaagen, 

sorry for the delay. I got an 

Whoops\Exception\ErrorException thrown with message "Undefined array key "lft""

Stacktrace:
#17 Whoops\Exception\ErrorException in /var/www/html/Modules/TestQuestionPool/classes/class.ilAssQuestionList.php:652
#16 ilErrorHandling:handlePreWhoops in /var/www/html/Modules/TestQuestionPool/classes/class.ilAssQuestionList.php:652
#15 ilAssQuestionList:loadTaxonomyAssignmentData in /var/www/html/Modules/TestQuestionPool/classes/class.ilAssQuestionList.php:583
#14 ilAssQuestionList:load in /var/www/html/Modules/TestQuestionPool/classes/QuestionTable.php:220
#13 QuestionTable:getTotalRowCount in /var/www/html/src/UI/Implementation/Component/Table/Data.php:400
#12 ILIAS\UI\Implementation\Component\Table\Data:applyViewControls in /var/www/html/src/UI/Implementation/Component/Table/Renderer.php:231
#11 ILIAS\UI\Implementation\Component\Table\Renderer:renderDataTable in /var/www/html/src/UI/Implementation/Component/Table/Renderer.php:48
#10 ILIAS\UI\Implementation\Component\Table\Renderer:render in /var/www/html/src/UI/Implementation/DefaultRenderer.php:60
#9 ILIAS\UI\Implementation\DefaultRenderer:render in /var/www/html/src/UI/Implementation/DefaultRenderer.php:56
#8 ILIAS\UI\Implementation\DefaultRenderer:render in /var/www/html/Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php:1942
#7 ilObjQuestionPoolGUI:getTable in /var/www/html/Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php:1288
#6 ilObjQuestionPoolGUI:questionsObject in /var/www/html/Modules/TestQuestionPool/classes/class.ilObjQuestionPoolGUI.php:577
#5 ilObjQuestionPoolGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:119
#4 ilCtrl:forwardCommand in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:243
#3 ilRepositoryGUI:show in /var/www/html/Services/Repository/classes/class.ilRepositoryGUI.php:223
#2 ilRepositoryGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:119
#1 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:92
#0 ilCtrl:callBaseClass in /var/www/html/ilias.php:24

after I imported an Question Pool with taxonomy in doil, select some nodes in the filter and deleted the nodes afterwards and tried to open the questions tab again ;-)

**Comment by dsstrassner** [comment]
Another Copy of this pool. Selected "Questions without assigned Taxonomy", but the filter does not filter the questions with taxonomies out: 

image

Selected Node "Fachspezifische Fragetypen", but got also another question without this node shown: 

image

Edit: got it: This "Fachspezifische Fragetypen" Node has 2 Sub-Nodes: "MINT" and "Sprachen"

Question Pool Export: 
[1718622465__4105__qpl_191594.zip](https://github.com/user-attachments/files/15866341/1718622465__4105__qpl_191594.zip)

**Comment by dsstrassner** [comment]
I created https://mantis.ilias.de/view.php?id=41533 to document the sub-node issue in the current implementation.

**Comment by nhaagen** [comment]
I updated the filter respecting all levels of the tax-tree as well as the representation of selected taxonomies.:

Screenshot from 2024-07-04 11-08-12

**Comment by dsstrassner** [comment]
Thanks, @nhaagen!
From my point of view, everything seems fine now. Please go on @thojou

**Comment by thojou** [comment]
Hey @nhaagen,

I took your PR and integrated the changes into trunk.

Thank you.

**Pull request merged**
