### PR TITLE
Administration: Add workaround for failing `Status` command

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=39355

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724,

I removed myself, since I'm not maintainer here. I'm available for discussions and questions, ofc, as always.

Cheers!

**Comment by alex40724** [comment]
@daniwe4 Not sure why, but I am not able to assign you as reviewer here. Could you have a look at this change please. Messing with the DIC does not seem to be a good way to deal with this.

**Comment by daniwe4** [comment]
Hi,
The workaround prevents the execution of two objectives that are actually the problem. 
These are:

 - class.ilDatabaseMetricsCollectedObjective.php
 - class.ilGlobalCacheMetricsCollectedObjective.php

For the former the solution is easy, see here 
https://github.com/daniwe4/ILIAS/blob/6df49ee7757ecf079e9ef0bc448cf207f51b7010/Services/Database/classes/Setup/class.ilDatabaseMetricsCollectedObjective.php#L146,
 but the latter requires a little more time. 
So a hotfix could be a TryFinally block around the code so that the objective doesn't break but also, it doesn't run correctly. See here:
https://github.com/daniwe4/ILIAS/blob/6df49ee7757ecf079e9ef0bc448cf207f51b7010/Services/GlobalCache/classes/Setup/class.ilGlobalCacheMetricsCollectedObjective.php#L49C1-L49C1

But the ilGlobalCacheMetricsCollectedObjective has to be updated to the new Cache implementation.

**Comment by klees** [comment]
I had a look into this, but I don't think this is the correct fix. Some status objectives seem to mess with the DIC, these should be fixed, not the call-side.

In general, DIC does not exist for code in the setup context and hence should not be used. I'll try to track down the offenders =)

**Comment by klees** [comment]
@daniwe4 is indeed right, `ilDatabaseMetricsCollectedObjective` and `ilGlobalCacheMetricsCollectedObjective` cause the problem.

**Comment by daniwe4** [comment]
@klees , yes, its right

**Review by klees — CHANGES_REQUESTED** [review]
I would suggest to close this and instead open tickets/PRs for the two offending objectives.

**Comment by alex40724** [comment]
Ok, I close.  The follow-ups seem to be
https://github.com/ILIAS-eLearning/ILIAS/pull/6870
and
https://github.com/ILIAS-eLearning/ILIAS/pull/6871

**Pull request closed without merging**
