### PR TITLE
TA fix Cloze and Longmenu Question Form Issues

### PR DESCRIPTION
**Pull request by Amstutz**
This form should be removed asap. Soooo many things could go wrong here. One small thing should be fixed with this PR, see: https://mantis.ilias.de/view.php?id=37130 and https://mantis.ilias.de/view.php?id=37081

### CODE REVIEW

**Comment by Amstutz** [comment]
Note test failings seem unrelated afais

**Comment by smeyer-ilias** [comment]
@Amstutz the test failings are fixed in R8

**Comment by kergomard** [comment]
Thank you very much @Amstutz for this PR!
And yes: This forms are generally speaking a bad idea built on top of other bad ideas and implementations.
One thing though: I don't believe this solves: https://mantis.ilias.de/view.php?id=37081
I still merge and cherry-pick to trunk.

**Comment by Amstutz** [comment]
I do believe it does. Maybe reload js cache.

**Pull request merged**
