### PR TITLE
KS: UI > Listing > CharacteristicValue

### PR DESCRIPTION
**Pull request by bheyser**
This PR is a followup for the [PR 2078](https://github.com/ILIAS-eLearning/ILIAS/pull/2078). It considers the conceptional discussion with @Amstutz and @klees that tooks place at skype.

This PR introduces a new ui component called characteristic value listing:
UI > Listing > CharacteristicValue

The component is to be used to present listings of label characteristic value doubles that need to be presented side by side.

It is more about presenting longer labels for short characteristic values than a short term that is described with a longer description. This is why we need this characteristic value listing as a rival to the descriptive listing.

The component comes as a new component family containing the following leafs:
UI > Listing > CharacteristicValue > Text

This leaf is at the moment the only choice. It allows text/text value pairs giving the most flexibility at the moment. In the future there might be other kinds of leafs for e.g. float values that automatically align to the decimal separator.

Example Usage:
```
function base()
{
    global $DIC; /* @var \ILIAS\DI\Container $DIC */
    $f = $DIC->ui()->factory();
    $r = $DIC->ui()->renderer();

    $items = [
        'Any Label for the First Item' => 'Item 1',
        'Another Label for the Second Item' => 'Item 2',
        'Third Item Comes as Component' => 'Item 3',
        'Fourth Item Comes as Component' => 'Item 4'
    ];

    $listing = $f->listing()->characteristicValue()->text($items);

    return $r->render($listing);
}
```
image

The component is relevant for the following (allready scheduled) feature requests:

Continuous Testing Mode Usability Improvement
https://docu.ilias.de/goto_docu_wiki_wpage_5089_1357.html
image

Extended Test and Item Statistics
https://docu.ilias.de/goto_docu_wiki_wpage_3529_1357.html
image

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
Hi @bheyser 

Thank you a lot for contributing to the UI Components. 
The proposed interface LGTM. Some minor details bellow. I recommend the JF to accept this.

Please implement the following changes:
- [ ] Improve Purpose desc: "Characteristic Value Listings are used to present characteristic values.“ is not very helpful. Expand to: „Characteristic value is understood here as a value to quantify or describe a state indicated by some key in listing“. 
- [ ] Rivals Description: Leave out, "It is to be used whenever the semantics of * a html descriptive listing is required that can be shown underneath."

Note that I will perform a review on the implementation as soon as the interface is accepted.

kindly,
@amstutz

**Comment by bheyser** [comment]
I changed the purpose and rival descriptions according to your suggestion @Amstutz ;-)

**Comment by matthiaskunkel** [comment]
Jour Fixe, 26 AUG 2019 : We highly appreciate this PR and accept it for ILIAS 6. Please merge to trunk.

**Comment by Amstutz** [comment]
Hi @bhyeser

Here follows the promised review of the implementation.

Thx for providing tests and examples.

Please implement the following changes:
- [ ] Strict Typing: use strictly typed params and return values wherever possible (e.g. public function render(Component $component, RendererInterface $default_renderer): **string**;
- [ ] Padding Variable: Use @padding-small-horizontal: instead of 5px for the padding in your less.

As soon as done and fine with @klees, this can be merged IMO.

kindly,
@amstutz

**Comment by Amstutz** [comment]
@bheyser , any update on this. Note that we intend to adopt the whole UI Compoents to PSR2 as soon as @klees is back on track. Merging will be difficult afterwards.

**Comment by bheyser** [comment]
Again, I am very sorry for the delay -.- I now have added type hints wherever possible.
I also made use of less variables padding-small/large-horizontal/vertical for all my paddings.

**Comment by klees** [comment]
Hi @bheyser, no problem. Please have a look into the tests. They fail... Thx!

**Comment by bheyser** [comment]
UI Kitchensink currently seems to need Fully Qualified ans Absolute Classnames regarding Namspaces when used in return types (perhaps also affects php docs, i dont know), since I removed ALL ...
- relative class names
- alias class names
... the Travis CI Checks passes.

**Pull request merged**
