### PR TITLE
PHP 8 Code Review PersonalWorkspace

### PR DESCRIPTION
**Pull request by katringross**
Hi @alex40724 ,

I completed the review of the Services/PersonalWorkspace component.

Results:

- [x] The code style is PSR-2 + X compliant
- [x] No usage of $_GET / $_POST / $_REQUEST / $_SESSION
- [x] There is a Unit Test Suite with at least one unit test
- [x] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant)
- [x] There are no serious PhpStorm Code Inspection issues left
- [ ] The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)
--
We fixed some trivial issues reported by our inspection profile. We marked some issues with comments, please search for PHP8-Review.

Actions needed:
- [ ] Please have a look at our comments.

Best regards,
@katringross

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@alex40724

- [ ] There are also some dynamically defined properties like `rbacsystem` in `ilObjPersonalWorkspaceSettingsGUI`. This is caused by the refactoring of `Services/Objects` and I noticed this kind of issue in many classes. The propery in the abstract base class `ilObjectGUI` is named `rbac_system` now.

**Comment by alex40724** [comment]
@mjansenDatabay @daniwe4 If non private member variables in upper classes are renamed, the developer has to rename all the instances in the derived classes. Otherwise the variables must not be renamed. Or am I wrong here? I mean this would be a lot of open ends otherwise.

This is the commit https://github.com/ILIAS-eLearning/ILIAS/commit/6726d26e

When I currently search for ->rbacsystem in ilObj*GUI classes I get 99 occurences. For >rbac_system I get 112 (I did not check review and admin). The ...ListGUI classes kept $rbacsystem, the ObjGUI went to $rbac_system. A number of classes still using $rbacsystem have been "fixed" in the meantime, meaning they have both members vars now. I know that the Object service was messed up to a certain extent before, but... we should agree on one naming here imo.

**Comment by mjansenDatabay** [comment]
@alex40724 / @daniwe4 

> If non private member variables in upper classes are renamed, the developer has to rename all the instances in the derived classes. 

Yes, this should be the case.

> When I currently search for ->rbacsystem in ilObj*GUI classes I get 99 occurences. For >rbac_system I get 112 (I did not check review and admin). The ...ListGUI classes kept $rbacsystem, the ObjGUI went to $rbac_system. A number of classes still using $rbacsystem have been "fixed" in the meantime, meaning they have both members vars now. I know that the Object service was messed up to a certain extent before, but... we should agree on one naming here imo.

Yes, this is a problem, and maybe the respective maintainers are not aware of the problem.

**Comment by daniwe4** [comment]
Hi @alex40724 and @mjansenDatabay,
maybe I went a little overboard with the renaming. I could create an extra PR by bringing the naming together again. In one direction or the other.

**Comment by mjansenDatabay** [comment]
@daniwe4 This would be great. Please be aware, some components already applied changes in regargs to your refactoring in `ilObject(GUI)` and removed 'local' `rbacsystem` member variables and instead use `rbac_system` (etc.) from the base class.

**Comment by alex40724** [comment]
@daniwe4 Thanks!

**Comment by alex40724** [comment]
@katringross Thanks for the PR. I will take care of the commented issues.

**Comment by alex40724** [comment]
Done

**Comment by daniwe4** [comment]
Hi @mjansenDatabay  and @alex40724 ,
i create a PR to hpefully fix the problems. https://github.com/ILIAS-eLearning/ILIAS/pull/4320

**Pull request merged**
