### PR TITLE
Unit Tests: PHPUnit 8 migration

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR fixes all incompatiblities with `PHPUnit 8`. Furthermore I added a `Travis CI` job for `PHP 7.3`. Both builds pass, but developers/maintainers should check the `risky` tests.

Dependencies changed:
* `"phpunit/phpunit": "^8.0",`
* `"phpunit/php-code-coverage": "^7.0",`
* `"mockery/mockery": "^1.2",`
* `"phpunit/php-token-stream": "^3.0",`

Supported PHP versions of PHPUnit: https://phpunit.de/supported-versions.html

### CODE REVIEW

**Review by bheyser — APPROVED** [review]
Approve for the changes in Test and Question Pool.
AND very thx for your work @mjansenDatabay  :)

**Review by klees — APPROVED** [review]
Hi @mjansenDatabay, thx a lot for your work here!!

**Review by legionth — APPROVED** [review]
Only reviewed https://github.com/ILIAS-eLearning/ILIAS/pull/1701

LGTM :+1:

**Review by alex40724 — APPROVED** [review]

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 APR 2019 : Thanks a lot to Michael for this pull request. We highly appreciate the changes and accept the PR for trunk.

**Pull request merged**
