### PR TITLE
Hotfix/trunk/join implode

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR fixes wrong `join()` and `implode()` calls.

This is similar to #2819 , but without distracted code formatting changes and higher coverage.

### CODE REVIEW

**Review by mbecker-databay — APPROVED** [review]
Looks good to me, thank you!

**Review by chfsx — APPROVED** [review]
LGTM in my files, thanks a lot!

**Comment by mjansenDatabay** [comment]
@alex40724 / @Uwe-Kohnle / @smeyer-ilias Any objections here?

**Review by smeyer-ilias — APPROVED** [review]
Thanks a lot.

**Review by alex40724 — APPROVED** [review]
Thanks!

**Pull request merged**
