### PR TITLE
Abandon Special Character Selector

### PR DESCRIPTION
**Pull request by fneumann**
Feature https://docu.ilias.de/goto.php?target=wiki_1357_Abandon_Special_Character_Selector 

Obssolete test cases:
C239 

New test cases (only for ILIAS 9 to check a correct removal):
C58212
C58213
C58214
C58215
C58216
C58217
C58218
C58219
C58220

### CODE REVIEW

**Review by alex40724 — APPROVED** [review]
Thanks!

**Review by kergomard — APPROVED** [review]
Thank you very much @fneumann 
Changes in Test and User look good to me!

I would ask you to update the Copyrights, though. Thanks!
Best,
Stephan

**Comment by fneumann** [comment]
As agreed in the today's TA TechSquad I will now merge the PR.

**Comment by oliversamoila** [comment]
Thank you very much @fneumann
Can we set the approval at https://docu.ilias.de/goto_docu_wiki_wpage_7230_1357.html due to the merge?

**Comment by fneumann** [comment]
I would say yes, but as it an order from Uni Bern, perhaps Timon @Amstutz would like to approve that the additional requirements (e.g. test cases) are fully met.

**Pull request merged**
