### PR TITLE
Update headlines.md fixed typo issues

### PR DESCRIPTION
**Pull request by SaiAryan1784**

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @acgruber may I assign this to you? The changes should be done in other branches (especially release_9 and trunk) as well.

**Comment by mjansenDatabay** [comment]
Hi @acgruber ,

this PR has been lying around for quite a while. Was it okay to assign the pull request to you?

Thanks and best,
@mjansenDatabay

**Comment by acgruber** [comment]
Hi @mjansenDatabay,

Please excuse me somehow missing this notification. I will look into it asap. Thanks for the reminder!

Cheers
@acgruber

**Comment by acgruber** [comment]
Hi @mjansenDatabay & @chfsx ,
This PR is ready to merge. Before I proceed: Is there a way to simultaneously add the changes to 9 and trunk or do I have to go for two additional PRs?
Thanks and cheers!

**Comment by mjansenDatabay** [comment]
@acgruber 

> Is there a way to simultaneously add the changes to 9 and trunk or do I have to go for two additional PRs?

Usually the maintainer is responsible to integrate the changes into the other release branches. AFAIK you don't have the permission to push to our repositories, right?

IMO we have two options:
Option 1) You create new PRs for the other release branches.
Option 2) Soneone cherry-picks the changes to the other release branches and pushes the commit without creation new PRs. I could do this for you.

**Comment by acgruber** [comment]
Thanks for the feedback, @mjansenDatabay! Let's go for option 2 then :) And should I merge this PR now or would you prefer to do this as well?

**Comment by mjansenDatabay** [comment]
@acgruber Yes, please merge the PR. I pick the commit to the other branches afterwards.

**Comment by acgruber** [comment]
Thanks to @SaiAryan1784 for the improvement. Merged to Release_8. Will be cherry-picked to other branches as well.

**Comment by mjansenDatabay** [comment]
Picked!

**Pull request merged**
