### PR TITLE
Trunk revert

### PR DESCRIPTION
**Pull request by chfsx**

### CODE REVIEW

**Comment by chfsx** [comment]
@ILIAS-eLearning/core-developers 

We had some problems in 7fe45d2 which removed a lot of changes in trunk. this PR reverts the merge 7fe45d2.

Please review the changes in your modules and check if this is the state you'd like to have. If everything is ok, we merge this and delete the brach trunk_revert and remove the lock from trunk.

**Comment by chfsx** [comment]
@Amstutz I added your changes from PR #265 again to this PR. So there's no need for another

**Comment by jluetzen-ilias** [comment]
Looks good to me.

**Comment by Amstutz** [comment]
@chfsx thank you.

**Comment by smeyer-ilias** [comment]
Looks good, thanks.

**Comment by alex40724** [comment]
Good for me also!

**Pull request merged**
