### PR TITLE
Review `Services/RTE`

### PR DESCRIPTION
**Pull request by kergomard**
Hi @mjansenDatabay 

Here are the results of the `Services/RTE` review.

### Results

- [x] The code style is PSR-2 + X compliant: _CS-Fixer made changes to 4 files_
- [x] No usage of $_GET / $_POST / $_REQUEST / $_SESSION
- [ ] There is a Unit Test Suite with at least one unit test: _There is no Suite yet_
- [ ] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant): _In as far as our own plugins for TinyMCE are concerned_
- [x] The types are fully documented (PHPDoc) or explicit PHP types are used (type hints, return types, typed properties)

### Changes made in this PR:
- Remove the tiny_mce_5_6_0-Folder as we now have a forked version of TinyMCE containing the plugin in our organization.
- Remove an, as far as I can see, unused constructor parameter.

Best regards,
@swiniker

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@swiniker Where did you find the super global variables? Your statement is: "_There are quite a few superglobals used, it is hard for me in a useful time frame to judge which ones are necessary in this context. I removed two accesses I was pretty sure we could easily get rid of._"

**Comment by kergomard** [comment]
My statement is gone! Big sorry, today I seem to screw up the clean up of my copy pasting big time!

**Comment by mjansenDatabay** [comment]
@swiniker I added a test suite and fixed the existing tests: https://github.com/ILIAS-eLearning/ILIAS/commit/44c6413c6aae12a2b42cbdef169db9bd67cda572

**Comment by mjansenDatabay** [comment]
Thx @swiniker for the changes in this PR.

**Pull request merged**
