### PR TITLE
Some improvment PHPDoc (@package, @author, @since, ...),  PHP7 types …

### PR DESCRIPTION
**Pull request by ghost**
…and use imports

### CODE REVIEW

**Comment by chfsx** [comment]
Mostly improvements in classes vom srag, LGTM. There are also changes in RBAC, @smeyer-ilias is that ok for you? I'd like to merge this after trunk is open again

**Comment by chfsx** [comment]
Just realized that Test are failing with these changes. @fwyss-srag could you please have a look at the UnitTests to make them run again? thanks!

**Review by chfsx — CHANGES_REQUESTED** [review]
- [x] Failing Tests

**Comment by ghost** [comment]
@chfsx @smeyer-ilias 
I didn't change anything on the unit tests.
I can run the unit tests succesfully

**Comment by ghost** [comment]
auswahl_003

**Comment by ghost** [comment]
Ok, I understand now, i need to run `run_tests.sh`

**Comment by klees** [comment]
Hi @sragfw and @chfsx, we had this PR on our TB-agenda today. Are there any news on this PR?

**Pull request closed without merging**
