### PR TITLE
WIP - Conceptual Discussion Feature/6 0/asq concept

### PR DESCRIPTION
**Pull request by mstuder**
With this pullrequest, I would like to show the possible implementation of the question service within ILIAS. With the paradigms CQRS / Eventsourcing and DDD.

I have removed so many files as possible. Nevertheless, there are a few. But you don't have to go through all of them. I tried hard to explain the whole process step by step with code examples:
https://github.com/ILIAS-eLearning/ILIAS/blob/7b261f43c6fe59938d72b84b270196089afbaa91/Services/AssessmentQuestion/docs/development/cqrs-and-event-sourcing-paradigm.md 

Best regards
Martin

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks for the PR. One Question:

How will the presistence layer of questions be organised (storage of all properties of questions). Will the event store replace the "normalised" version of the DB tables (tables like qpl_a_matching) or will these tables be kept and the event store holds only "historical" data or does the event store hold data on (current versions of) questions redundantly?

**Comment by mstuder** [comment]
Thanks for the question!

> How will the presistence layer of questions be organised (storage of all properties of questions). Will the event store replace the "normalised" version of the DB tables (tables like qpl_a_matching) or will these tables be kept and the event store holds only "historical" data or does the event store hold data on (current versions of) questions redundantly?

You can imagine the eventstore as the datamaster. But there's no latest version in form of a single row. The last version is the result of combining all events of the Aggregate Root. 

**Eventstore Example / Edit Side**
Database Table asq_qst_event_store

|event_id|aggregate_id|event_name|occured_on|event_body|
|---|---|---|---|---|
|233|abc-def|QuestionCretedEvent|2019-01-10 10:02|{}|
|234|abc-def |QuestionDataEvent|2019-01-10 10:03|{"title:" "MyQuestion", "description:" "abc"}|
|235|abc-def|QuestionSetOnlineEvent|2019-01-10 10:03|{"online:" 1}|
|236|abc-def|**QuestionPublishedNewRevision**|2019-01-10 10:10|{"revision": tzu-iop}|
|237|abc-def|QuestionDataEvent|2019-01-10 10:20|{"title:" "MyQuestion", "description:" "**i will never be on the query side of live ;-)**"}|
|238|abc-def|QuestionDataEvent|2019-01-10 10:22|{"title:" "MyQuestion", "description:" "xyz"}|
|241|abc-def |**QuestionPublishedNewRevision**|2019-01-10 10:30|{"revision": hui-bef}|

**Query Side / Read Side Example**
Database Table question_data (simplified example)

|question_id|questioni_uuid|revision_uuid|created|title|description|online|
|---|---|---|---|---|---|---|
|42|abc-def|tzu-iop|2019-01-10 10:10|MyQuestion|abc|1|
|96|abc-def|hui-bef|2019-01-10 10:30|MyQuestion|xyz|1|


We will have two (many) different Data Storages. 

One Data Storage per Aggregate Root for the events. This data storage we use at the editting side of for example a question.

Another / many other Data Tables for the Read / Query side of a question. Here we will have normal ("normalised") tables like qpl_a_matching. But in these tables we will never save all updates that happends on the eventstore. The event store will project his current state of a question as soon as a new revision is created. The revisioning is in charge of the consumer. Also on the read page revisions are immutable. A new revision means a new data row at the Read / Query side.

During the revision it will also be possible to write further data tables, e.g. aggregated data. Redundant data storage is one of the concepts that works best and without problems here.

You might think about filling the eventstore with new entries of the current state during a revision. This could be a snapshot for the ongoing work. Then you only have to go through the events from this point on to display them on the editing page.

Summary
* The event store holds all data of all changes and revisions
* The "normalised" tables holds the projected data (for each projection one separate row / data set) - in our case we will project by building a new revision. 

Please note: We read also from the event store.  The event store hast not to be "read protected" per concept.  We do that if we're editing a question. In this case we will not read from the "normalied" tables (read/query side). This can be confusing due to the terminology (write/command side - eventstore) and read/query side normalised tables.

**Comment by alex40724** [comment]
Thanks for the elaborated answer!

**Comment by kergomard** [comment]
Dear @mstuder,

thanks a lot for this smaller PR. This really helps to clarify, how you want to introduce the proposed patterns for the Assessment Question Service. Please note, that this PR still is very hard to review and it took every member of the TB considerable time to do so. Besides the size of the changes and the variety of patterns (which simply might not be reducible or divisible) we found a lot of open ends (like missing classes or implementations) in the PR. This led to a lot of open questions and lack of clarity. Also, this PR seems to show only some of the implications and complexities of proposed patterns. Your README helps a lot in this regard, but in the end, the truth is in the code here.


Since this is about the patterns you want to introduce in the service, we like to start by giving feedback regarding these.

**We support the introduction of UUIDs as IDs** instead of using database generated incremented IDs. This move will allow to decouple the persistence from the creation of objects.

**We do not object to introduce an *internal* command bus in the service.** Since we only see rudimentary pieces of the command bus and the implications of it for the implementation and structure of the service, we are not sure how this will impact the service. We understand how a command bus could help to structure and ease the implementation of services in general. If you feel that a command bus will help to solve problems in the Assessment Question Service, feel free to use it internally. We want to stress again, though, that a command bus is a major consideration for the Internal API Alignment team when thinking about a centralized API handling. Introducing a command bus here implies the possibility of at least two similar approaches (maybe on another architecturel layer). We expect you to refactor your `CommandBus`-related code accordingly if such concepts become part of the ILIAS core after the approval of the Internal API Alignment concept and if there is an intersection between the target layers of those. We gladly acknowledge that you already agreed to do so. Thanks! Also thanks for tackling this topic and sharing the acquired knowledge with the rest of the community in discussions such as this one.

**We strongly advise against the introduction of event sourcing while factoring out the Assessment Question Service from the T&A.** We do see that this approach could have a general value for the Assessment Question Service as well as for other components in ILIAS. We understand which new features of the Assessment Question Service could benefit from the approach. However, currently the absolut priority for the T&A (which we clearly communicated several times) is to factor out an Assessment Question Service from the T&A. We cannot see how the event sourcing works towards that goal. We also failed to find a traceable explanation why the introduction of event sourcing is imperative to make the implementation of the API as outlined in your/Björns proposal possible. Instead, **we are heavily concerned about the tremendous amount of additional complexity and hence sources for bugs and various other issues** (e.g. with performance) that this approach will invariably introduce. We are pretty sure, that this PR only shows a small part of the real complexity that will be involved with event sourcing. Currently the PR does not answer the following questions (among others):

* What will the normalized database scheme look like that will exist besides the event-sourced database?
* How will the data be moved from the event store to the normalized tables? When is the right moment in time for doing so?
* How will you deal with currently existing questions (incl. plugins) and how will they be migrated to the event-sourced database?
* How will the event sourcing mechanism deal with schema changes when the data is stored in json-strings?
* How will the event sourcing mechanism deal with binary data?
* Which additional features (regarding this PR) for the event sourcing are planed for ILIAS 6.0? The normalization, e.g., currently is not included here?

All answers to these questions will introduce new complexity. We think the approach could very well be considered when the Assessment Question Service moves on after it is separated from the rest of the T&A, but we feel that this separation alone introduces enough difficulties for now. 

**We strongly advise against the introduction of CQRS.** We see the general value of that approach, but we also see that there are considerable downsides too (see e.g. [Martin Fowler](https://martinfowler.com/bliki/CQRS.html)). We currently do not feel that CQRS is a good fit for the Assessment Question Service or the system in general, considering the pros and cons of the approach. As always, this is up for debate in general, but we do not think that the seperation of an Assessment Question Service from the T&A is a good place for this debate. Further, it is hard to see how this pattern is really show cased in the PR, as we cannot see different models for read and write. In the current state of the work, we can't tell which parts of the PR are really about CQRS as we see a mix of many patterns and details of the implementation. Maybe it's just best to drop the label 'CQRS' and focus on the concrete requirements of the Assessment Question Service and the implementation. Same as for event sourcing, we do not see a tangible explanation, why the implementation of the target APIs of the service is only possible or even just considerably simplified when using CQRS and **we are deeply concerned about the complexities that CQRS will introduce now and in the future for every involved party.** We see how the new feature [Item Statistics](https://docu.ilias.de/goto_docu_wiki_wpage_5321_1357.html) could lead to the idea to introduce CQRS but, again, we clearly prioritized the separation of the Assessment Question Service from the rest of the T&A over new features. We propose that you consider a [Reporting Database](https://martinfowler.com/bliki/ReportingDatabase.html) as a simpler alternative to CQRS. This could also be introduced after the separation.

 **We definitely see that we as a community should investigate DDD further, consider ideas as well as processes and try to learn lessons from DDD. Thanks for bringing it up.** You are implementing DDD by introducing entities, services, application as e.g. presented in "Domain Driven Design in PHP" by Buenosvinos. However, note that Buenosvinos and others also describe DDD as an approach to design a system in a close cooperation between domain experts and developers by creating and documenting a shared model, the ubiquitous language. The implementation then uses certain techniques to implement that language, but the approach itself is not about the implementation only but also about the design process. It is no problem, though, that this design process was not followed for the separation of the Assessment Question Service, as there already exist requirements and models and there certainly was no time to go through an intense iterative DDD process.

Regarding the other content of the PR, we want to add the following suggestions and requirements:

* Please use dependency injection instead of static method calls. The massive use of static method calls indicates a lack of code organisation and structure.
* We strongly recommend to introduce automated tests. This will be simplified by introducing dependency injection.
* Use the mandatory [PSR-2 (+X) ILIAS Coding Style](https://github.com/ILIAS-eLearning/ILIAS/pull/1838/files).
* Add return types and type hinting where possible.

**We want to restate publicly, that we just try to play our role as advisory body for the maintainers and the product manager here. Ultimately it is up to you as maintainers now to decide how to go on with this (also concerning the question of whether to use or not to use CQRS and Event Sourcing).** We are trying hard to find a course of action that allows for a consensual way forward here. To balance your agency as maintainers with our deep concerns regarding your proposal, we propose the following measures:

* Create a branch in the public ILIAS-repo where everyone (we, your customers, other developers, ...) can see the current state of the implementation. This will increase transparency and also clarify where we stand in terms of functionality and general progress. We realized that we currently do not understand how far you really have progressed in the separation of the Assessment Question Service which might influence our assessment of the situation.
* Ask Matthias to create a test-installation for that branch that people can access. It will help to alleviate our concerns if we could see your concepts in action. This will also allow everyone to test the new implementation to make sure that bugs are found early and to show that your proposal in fact works despite our reservations. This will also allow to go on with ILIAS 6.0 without the changes for the assessment question service if our concerns turn out to be warranted.
* Both measures will require a transparent and ongoing communication on your side to manage expectations towards the current state of the implementation.
* **Important:** Note, that the branch can only be merged to the trunk when approved by your customers. The TB is among these customers as the sponsor of the initial concept for the separation of the service. Note also, that there are other improvements of and investments in ILIAS 6.0 at stake here as well. We will not agree to merge any state of the branch that puts these other improvements and investments at an unknown or uncontrollable risk. 

We hope that we clearly and unambiguously pointed out where and why we are concerned about the patterns you want to introduce here. Please, don't hesitate to ask for clarifications, if we didn't succeed as well as we thought. We might be wrong, but we cannot see how this can further be decide based on some abstract discussion at this point. Please appreciate our concerns, however you may decide to go on. We do not try to stop you for no good reason, but we have a responsibility towards the whole system, given by the by-laws of the ILIAS society.

We are looking forward to our meeting and hope we find a way forward together.

Kind regards,
the Technical Board

**Comment by Amstutz** [comment]
We are not sure, what the relation to: https://github.com/ILIAS-eLearning/ILIAS/pull/2121 is? We guess that this one here can be closed, correct?

**Comment by mstuder** [comment]
This pull request was used to discuss new technological approaches within the assessment question service. The concrete development you find under https://github.com/ILIAS-eLearning/ILIAS/pull/2121

**Pull request closed without merging**
