### PR TITLE
Chat: Changed documentation in regards of supported versions for ILIAS 5.4.x

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
Thanks a lot. 

Note: Some plugins (e.g. Etherpad) also depend on node. On several installation, e.g. Etherpad runs on the same server as e.g. the chat. However, I guess this will at least be not an issue for etherpad: https://github.com/ether/etherpad-lite. Maybe announce it on the dev list? Or shortly announce in the next JF.

**Review by klees — COMMENTED** [review]
No opinion from my side here. NodeJS is suspicious to me anyway.

**Comment by alex40724** [comment]
+1

**Comment by Amstutz** [comment]
TB: Merge plz.

**Pull request merged**
