### PR TITLE
fix 25474 II

### PR DESCRIPTION
**Pull request by Amstutz**
Update of #1850, for fixing: https://mantis.ilias.de/view.php?id=25474

### CODE REVIEW

**Comment by chfsx** [comment]
Sorry but I can't decide if this fixes all issues just by looking at it, I suggest to merge und I will fix some other places in the GlobalScreen where this was used.

BTW: PHPStorm has a great way to changes such thing with a lot o magic ;-)

**Review by chfsx — APPROVED** [review]
As I already mentioned I'm quite sure these are not all locations where this was used :-) I'll have a look at it myself but merge this first

**Comment by klees** [comment]
Isn't it the parallel development which causes the problems here?

**Comment by chfsx** [comment]
> Isn't it the parallel development which causes the problems here?

Which one?

**Comment by klees** [comment]
Symbol and global screen =)

**Comment by chfsx** [comment]
My last changes in GS were yesterday, so this may be

**Comment by klees** [comment]
This is awesome: We are working so fast and so cooperative at the same time that we in fact have these problems =)

**Comment by Amstutz** [comment]
Since @chfsx approved this, I guess it is oke to merge and make the trunk (at least partly) workable again.

**Pull request merged**
