### PR TITLE
Abandon Item Analysis Export for Pure Single Choice Tests

### PR DESCRIPTION
**Pull request by tbongers-cat**
https://docu.ilias.de/goto.php?target=wiki_wpage_7491_1357

### CODE REVIEW

**Comment by klees** [comment]
@dsstrassner Can we help to move this further?

**Comment by dsstrassner** [comment]
> @dsstrassner Can we help to move this further?

I think we need a rebase from @tbongers-cat and then @kergomard is good to go and merge?

**Comment by dsstrassner** [comment]
Thanks a bunch @tbongers-cat 
  

Whenever it suits you @kergomard 🥰

**Comment by tbongers-cat** [comment]
Rebased and copyrights fixed =)
This should be quite easy to check now, since the test export has been refactored in the meantime and the abandoned option is not used anymore.

**Comment by kergomard** [comment]
Thank you very much @tbongers-cat !
The removed code does not seem to do anything anymore anyway, apart from saving a checkbox and retrieving it.
I merge now.
Best,
@kergomard

**Pull request merged**
