### PR TITLE
[Fix 21451] Today button with engaged state

### PR DESCRIPTION
**Pull request by xus**
Further discussion about this PR in this bug report:
https://mantis.ilias.de/view.php?id=21451

### CODE REVIEW

**Review by Amstutz — COMMENTED** [review]
Hi @xus

Thank you a lot for fixing the linked bug. Note that this is not code I maintain, final say about this has @smeyer-ilias. However, I'll give some feedback, since I am directly involved.

I agree with all of it, however, stumbled about the following question:
- [x] Why is the link only set if not today? If I understood @klees right, a clicked on engaged today would reload the page even though it already is engaged. For this the link would be needed. I think this does make sense. Note that this is a question, I do not have a strong opinion on this. I also observed, that many pages indeed to not set any action on controls with an engaged like state.

kindly,
@Amstutz

**Comment by klees** [comment]
@Amstutz @xus Just to be sure you understand me correctly: I *as a user* would expect the "Today"-Button to reload the page.

This of course would require an action on the button, which should work regarding the UI component.

**Comment by xus** [comment]
I totally agree with you @klees @Amstutz . I removed the action in my last commit because I thought that no redirection had to be performed as we have in 5.3 and 5.4 using the "withUnabailableAction" method.
But since the "withUnabailableAction" was a temporary solution I also think that now the link has to be here. Actually, it is my personal preference.
I will add the link again. 
Thanks

**Comment by xus** [comment]
Hi @klees @Amstutz @smeyer-ilias 

If there are no objection or questions, this PR can be merged when considered.

**Comment by klees** [comment]
Hi @xus,

I do not consider myself responsible to merge this, I'm not the maintainer of the Calendar!

So: I am out =)

**Comment by Amstutz** [comment]
As initially stated (see comment above) this calendar internal. I can give my opinion on it (as valid for all PR) but do not have any decision or even merging powers here ;-). @smeyer-ilias : I guess this could be merged if you believe it to be good.

**Comment by Amstutz** [comment]
Ping, IMO this should be merge soon. @smeyer-ilias ready for merging? @xus attention there is a conflict needing to be resolved.

**Comment by alex40724** [comment]
@smeyer-ilias This seems to be part of the trunk already since June. I think you could close this, right?

**Comment by mjansenDatabay** [comment]
@smeyer-ilias Any update on this? Please provide feedback/ask questions, close the PR, or merge it.

**Comment by smeyer-ilias** [comment]
This is already part of the main release.

**Pull request closed without merging**
