### PR TITLE
[FIX]: Mantis 0018712

### PR DESCRIPTION
**Pull request by theodortruffer**

### CODE REVIEW

**Comment by theodortruffer** [comment]
@klees 
Can you have a look at that? The StudyProgramme didn't update it's LP to 'complete' when a user completed the CourseReference inside the StudyProgramme.

**Comment by klees** [comment]
Hi Theodor!

Do you have a mantis report that is fixed by this?

Please use tab for indentation.

Thx!

**Comment by theodortruffer** [comment]
No I haven't found a report for this and I didn't create one since this seemed to solve the problem. Do you need one with a description for reproducing the problem?

**Comment by klees** [comment]
I would at least like to understand the problem, before i merge this =)

**Comment by theodortruffer** [comment]
Oh sure ^^. I reproduced it with a simple setup: Create a SP 'x ' -> create another SP 'y' inside SP 'x' -> create a Course Reference with some Learning Progress determinating objects inside 'y'. 
In the LP-Administration, activate that the LP is visible in objects lists.

When a user completes the Course Reference, the SP 'y' still has a grey/yellow Learning Progress, although the Course Reference is green. The upper SP 'x' is also complete/green.

So I refreshed the LPStatus on completion. Is this somehow understandable? :)

**Comment by matthiaskunkel** [comment]
Sorry for intervening in your discussion - but shouldn't we always create Mantis reports if we found a bug? We create lists of fixed bugs for every new published release. And I think it is an important information for users when a certain problem has been solved.

**Comment by klees** [comment]
@matthiaskunkel You're indeed correct. You're interventions are always welcome =)

**Comment by theodortruffer** [comment]
There you go: http://www.ilias.de/mantis/view.php?id=18712

**Comment by klees** [comment]
Thank you Theo, seems to be correct. As far as i understand, ilLPWrapper::_refreshStatus has the semantic: "Hey ILIAS, i have new LP Statuses for this object and that users, please fetch them from me.", which i could call as often as i like, even if LP did not in fact change.

Could you please use tabs for indentation instead spaces, i'll merge then.

**Pull request merged**
