### PR TITLE
[fix] for missing language entry

### PR DESCRIPTION
**Pull request by kunzeus**
Replace hard coded text with ILIAS  language entry

### CODE REVIEW

**Comment by kunzeus** [comment]
Also in ILIAS 7

**Comment by dsstrassner** [comment]
Thanks a bunch @kunzeus. 

Fixes https://mantis.ilias.de/view.php?id=35548

**Comment by kergomard** [comment]
Thank you very much @kunzeus !
I would have a little change request, though:
- Would you please be so kind as to change the name of the language-variable to 'tst_player_answer_saved_and_locked'. From where I stand the important information is the 'and locked' part and it should not be used if an answer is just saved.

**Comment by mbecker-databay** [comment]
I had a faint memory the length of the identifier was important to look at due to the db field very short, but I see in current versions that it's set as varchar(200), so I second @kergomard s wish.

**Comment by kunzeus** [comment]
Sorry for the wait, I was on sick leave.

**Comment by kergomard** [comment]
Thank you very much @kunzeus ! I hope you are feeling well again. Will merge and cherry-pick to 8 and 7.

**Pull request merged**
