### PR TITLE
LearningSequence, adapt to GlobalScreen

### PR DESCRIPTION
**Pull request by nhaagen**
- extend Mainbar/Metabar with "withClearedEntries" to remove all entries
- move curriculum into slate
- move exit-control into metabar
- render content using layoutprovider/modifications
- cleanup template

https://docu.ilias.de/goto_docu_wiki_wpage_6070_1357.html

### CODE REVIEW

**Comment by klees** [comment]
Dear JF,

I added this, because we propose to add methods to clear all entries to the [Mainbar](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-5c7ddb1f728800a5ec75b9baeacf6d14R305) and the [Metabar](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-f1c2792b0b63a71a672f042574909d1fR97).

Regards!

**Review by klees — CHANGES_REQUESTED** [review]
Dear @nhaagen,

thanks for working on this. I'm really happy we lost so much ad-hoc code in favor of something more structured!

Please implement the following changes:

- [x] Clean up `ilLSViewLayoutProvider::isInterestedInContexts`. It looks as if something was just forgotten.
- [x] Use guard clauses/early return [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R56), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R74), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R92) [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R105) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R118). With guard clauses I mean: do `if(!condition) { return; } what_you_really_want_to_do...` instead of `if (condition) { what_you_really_want_to_do... } else { return; }`. Or put differently: eliminate uniteresting cases or edge cases early on by returning or throwing, then do the interesting stuff. This tends to remove indentation and also make the code more approachable. Thx!
- [x] Use `\ilLanguage` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-496ad40167c44a01c8469ba68fa73c1eR41) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-496ad40167c44a01c8469ba68fa73c1eR60) instead of hardcoded strings.
- [x] Add the changes on the `MainBar` and the `MetaBar` at the public interface of these two classes as well. How would we be knowing that they exist [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2318/files#diff-b03de869ef0c22d00e4df24f8fdb8710R60) otherwise?

Best regards!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 18 NOV 2019 : We highly appreciate this suggestion and accept the PR for ILIAS 6. This implementation won't show the help glyph as decided in the discussion about the 'clean screens' for the entire ILIAS. In case, this is seen as a problem in the future we have to pick up the topic again.

**Comment by nhaagen** [comment]
Dear @klees ,
thank you for going through this PR. 
I adressed the issues and this is good to go, I think.

**Comment by klees** [comment]
Merged as d674f7f557ee4317f3668b640b044269489363f3 and 6a554d9749ca0c3212d87ee3ab95d6cd8551c65c with minor changes. Thx @nhaagen.

**Pull request closed without merging**
