### PR TITLE
#31476: Make User Defined Tags Work in Blog

### PR DESCRIPTION
**Pull request by klees**
Hi @Amstutz, hi @alex40724,

there have been multiple issues with user defined tags for the Tag Input Field. These changes should fix them. However, the plot for a rework of the form internals thickens (see Roadmap) and the JS integration of tagify (an probably before) looks, hmm, messy. So there are certainly more things to be improved with the Tag Input Field.

Best regards!

### CODE REVIEW

**Review by alex40724 — APPROVED** [review]

**Comment by alex40724** [comment]
Looks good to me. Thanks.

**Review by Amstutz — APPROVED** [review]
LGTM, tomorrow is JF and there is some change on the interface, we should quickly announce and then Ill merge.

**Comment by Amstutz** [comment]
Involves Issue: https://mantis.ilias.de/view.php?id=31476

**Comment by matthiaskunkel** [comment]
Jour Fixe, 18 OCT 2021 : We highly appreciate this suggestion and accept the PR for ILIAS 7 and trunk.

**Pull request merged**
