### PR TITLE
#0037963 : php8 compatibility studyprogram event listener

### PR DESCRIPTION
**Pull request by sroenchen**
Adding implicit type cast to prevent hard error

### CODE REVIEW

**Comment by klees** [comment]
@sroenchen Thanks a bunch. If you have time, please have a look into the failing test. It's just an incorrect copyright... I'll get to this myself by afternoon.

**Comment by sroenchen** [comment]
@klees I'd love to rectify the issue, but am not really sure how to. 
The Account being fresh and all, I thought any copyright settings etc would be copied while forking.
Do you have any pointers for me?

**Comment by klees** [comment]
On it. Thanks for looking into it. We currently have some rectification effort regarding copyrights going on, but I just found out that we didn't not document this very well. Will fix both...

**Comment by klees** [comment]
Merged manually: 7a90d04850bd2837da6a12682397b015e9ce9a28 Thanks!

**Comment by klees** [comment]
And picked to trunk.

**Pull request closed without merging**
