### PR TITLE
Orgu: 36658, tolerate deleted users and mark inactive

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=36658

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

this will probably work, but I think we should go a little bit deeper with the fix.

After all, this is an inconsistency in the database. We should not fail without any chance for help, I agree here. But: This fixes just one location where this could fail. There might be even more locations in the code, where we assume that users indeed exist if they are assigned. 

So I propose that we instead add a named objective that rectifies the database in that regard: look for users that do not exist anymore in the assignment table, delete the according entries.

I bet this will come in handy some time again...

Thanks!

**Comment by nhaagen** [comment]
This will not tolerate deleted users anymore;
run php setup/setup.php achieve orgunit.removeDeletedUsersFromOrgUnits to rectify the DB.

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Picked to trunk.

**Comment by klees** [comment]
Picked to trunk.

**Pull request merged**
