### PR TITLE
[FIX] 20462: correct behaviour of ilDBPdo when dropping tables

### PR DESCRIPTION
**Pull request by chfsx**

### CODE REVIEW

**Comment by alex40724** [comment]
This does not seem to drop sequences of the table automatically. I am not sure if this should happen (like in the past) or not.

**Comment by chfsx** [comment]
I'd feel better when @smeyer-ilias could implement the deletion of the tables, I don't like to delete tables of other maintainers ;)

**Comment by smeyer-ilias** [comment]
@Fabian: I guess nobody expected, that you delete the specific tables mentioned in the bug report. There is nothing to do on your side. 
Alex meant: The sequence table (for mysql "mytable_seq") is not automatically deleted when using dropTable("mytable") in the current implementation.

**Comment by chfsx** [comment]
Oh sorry, I just misread the post. The PR here restores the bavavour and the parameters of the old dropTable() but I will check this again.

**Comment by alex40724** [comment]
I think I misread the code in this PR. @chfsx I think it all looks good now.

**Pull request merged**
