### PR TITLE
0037524: 404-Error bei Lautstärkeänderung in einer Frage - 404 error when changing volume in a testquestion, status "editing"

### PR DESCRIPTION
**Pull request by PurHur**
Probably fixes https://mantis.ilias.de/view.php?id=37524#c94252

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @PurHur for the PR! I merged the PR here https://github.com/ILIAS-eLearning/ILIAS/pull/6089 instead.

Best,
@kergomard

**Comment by PurHur** [comment]
Note that the #focus achor is still an error in javascript actions.

**Comment by Rillke** [comment]
@PurHur 

> Note that the #focus achor is still an error in javascript actions.

Can you elaborate on that and eventually provide a PR?

**Comment by PurHur** [comment]
The line i fixed appends #focus to links. But if the link starts with javascript: is should not be appended since #focus is not valid js (it would be an undefined token/variable):

image

This is the PR that fixes this. Since the other fix fixes the eventhandling this does currently have no known error but its still wrong.

**Pull request closed without merging**
