### PR TITLE
#24747 use unix timestamps to store learning sequence avaliability period

### PR DESCRIPTION
**Pull request by dkloepfer**

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @dkloepfer!

You silently removed the possibility that the availability might be `null`. This is required to allow to express, that there is indeed no availability. Please restore that possibility.

Thx!

**Comment by dkloepfer** [comment]
> Hi @dkloepfer!
> 
> You silently removed the possibility that the availability might be `null`. This is required to allow to express, that there is indeed no availability. Please restore that possibility.
> 
> Thx!

@klees This is not quite true. I've replaced null with a numeric 0, which represents "No Date given".

**Comment by dkloepfer** [comment]
@klees OK, how about now?

**Comment by klees** [comment]
Merged to trunk as well.

**Pull request merged**
