### PR TITLE
[FIX] 0036179: Failed test: Prüfungsblatt (optional/obligatorisch) - …

### PR DESCRIPTION
**Pull request by chfsx**
…Byte vs Megabyte

@klees may you have a look at this? Not the solution we want for the future, but maybe for the moment. background is https://mantis.ilias.de/view.php?id=36179 which you already know. thanks in advance!

most crucial part is here: https://github.com/ILIAS-eLearning/ILIAS/compare/release_8...srsolutionsag:ILIAS:fix/0036179/8/size-formatting?expand=1#diff-f3892e7d92b0895c6b153d2f1754b755fc888a4b5199b1d4f8784a7344b81d5fR849

### CODE REVIEW

**Review by klees — APPROVED** [review]
Hi @chfsx,

looks as if this shows how the constructor of `DataSize` is really odd and the formatting also needs improvement =)

Thanks!

**Comment by chfsx** [comment]
ngngngngngngn 😩 https://github.com/ILIAS-eLearning/ILIAS/actions/runs/4064782181/jobs/6998618003#step:5:639
I will have a look at the tests first, sorry

**Comment by chfsx** [comment]
I updated to PR to use `HumandReadable` from PR #5516 which should be discussed and merged before

**Comment by chfsx** [comment]
This PR contains https://github.com/ILIAS-eLearning/ILIAS/pull/5516 as well

**Comment by chfsx** [comment]
@klees I rebased this PR now, feel free to merge

**Comment by klees** [comment]
Thanks a bunch! :kissing_heart:

**Comment by klees** [comment]
Picked to trunk.

**Pull request merged**
