### PR TITLE
Taxonomy: Fixed counting non array

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Comment by alex40724** [comment]
@mjansenDatabay 

Thanks!

Any bugs occuring due to this, do we need this in other branches?

**Comment by mjansenDatabay** [comment]
No, just a PHP WARNING with PHP >= 7.2.x

**Comment by mjansenDatabay** [comment]
Damn, okay. Thanks for your hint/question @alex40724 .

According to the documentation we support PHP 7.2.x in ILIAS v. 5.4.x. So if we want to fix PHP WARNINGS, we have to cherry-pick this to stable branches supporting PHP 7.2.x.

**Comment by alex40724** [comment]
Ok, as I see you already picked this to 5.4. Thanks.

**Pull request merged**
