### PR TITLE
PRG: Userdata in Assignment Table and Export of Members/Assignments

### PR DESCRIPTION
**Pull request by nhaagen**
Features:
https://docu.ilias.de/goto_docu_wiki_wpage_6958_1357.html
https://docu.ilias.de/goto_docu_wiki_wpage_7749_1357.html

### CODE REVIEW

**Comment by klees** [comment]
Dear @kergomard,

look into the changes [here](Modules/StudyProgramme/classes/Setup/ilStudyProgrammeUDFDefinitionUpdateSteps.php) and in `Services/User`?

Kind regards!

**Comment by klees** [comment]
Hi @smeyer-ilias,

you are listed as implicit maintainer for Services/PrivacySecurity. Want to have a look here? I'm not sure how much you feel responsible here and would greenlight the changes myself if you are ok. Or does @kergomard understand the changed files to be a part of `Services/User`?

Kind regards!

**Review by kergomard — COMMENTED** [review]
Thank you very much for this PR @nhaagen !

This looks fine with me. I've just a few trivial formatting issues:
* Please add a space after the cast [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6449/files#diff-a11f93800f8b26d384ed76b2f4a11f640b49e9a33795ba13241e0712e68bb582R646).
* Please fix the formatting [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6449/files#diff-a11f93800f8b26d384ed76b2f4a11f640b49e9a33795ba13241e0712e68bb582R720)
* Could we [check this strictly](https://github.com/ILIAS-eLearning/ILIAS/pull/6449/files#diff-83334f7d4fe55536a99c03a29c0f7e87885b5b104d5f826dd1dbbd657786e704R228) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6449/files#diff-f4039d02e12a8249f2372cfe892804a804359e9d6dfd737f3211cffde70e8e3bR136), please.
* Could  you please remove this empty line [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6449/files#diff-83334f7d4fe55536a99c03a29c0f7e87885b5b104d5f826dd1dbbd657786e704R538)

Thanks again and best,
@kergomard

**Review by kergomard — APPROVED** [review]
Thank you very much this now is fine with me!

**Pull request merged**
