### PR TITLE
T&A 24969: Conceptual issue with (de)activating public comments in pools

### PR DESCRIPTION
**Pull request by matheuszych**
The read and write access to QuestionPool comments is not checked properly and this should resolve that.

[Mantis: 24969](https://mantis.ilias.de/view.php?id=24969)

### CODE REVIEW

**Review by thojou — CHANGES_REQUESTED** [review]
Hey @matheuszych,

As discussed, we should handle the custom checkAccess within the T&A Modules without modifying the central Notes Service.

- [x] Rework the access check for comments to be managed within the T&A module

Thanks!

**Comment by matheuszych** [comment]
@thojou I believe this should be a more appropriate approach.

**Review by thojou — APPROVED** [review]

**Comment by dsstrassner** [comment]
Will try to look into it this Weekend.

**Review by dsstrassner — APPROVED** [review]
For me, the changes seem appropriate in PR.

**Review by oliversamoila — APPROVED** [review]
I have looked at this along explanations and demonstration video in https://mantis.ilias.de/view.php?id=24969#c106506 and thank you for the changes.

**Comment by thojou** [comment]
Hey @matheuszych,

i took your PR and cherry-picked the changes into trunk.

Thank you!

**Pull request merged**
