### PR TITLE
PHP 8: Review `src/Data`

### PR DESCRIPTION
**Pull request by playamongthestars**
Dear @klees 

I completed the review of the `src/Data` component.

Results:

- [ ] The code style is `PSR-2 + X` compliant
- [x] No usage of `$_GET` / `$_POST` / `$_REQUEST` / `$_SESSION`
- [x] There is a `Unit Test Suite` with at least one unit test
- [x] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant)
- [x] There are no serious `PhpStorm Code Inspection` issues left
- [ ] The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)

Best regards,
Nadia

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@nmatuschek 

- [x] Please fix the tests
- [x] Please remove the unnecessary changes in PHPDocs

**Comment by mjansenDatabay** [comment]
@nmatuschek The tests still fail ...

**Comment by mjansenDatabay** [comment]
@nmatuschek 

- I fixed the unit tests
- I changed the access modifier of some constants from `public` to `private`

@klees  Addionally to the applied changes by @nmatuschek ...

- I fixed the order of arguments in `tests/Data/URITest.php`, so there are a lot of changes
- I used the most appropriate assertion for testing `RegEx`
- I removed some redundant `PhpDoc` comments
- I added some `PhpDoc` comments for arrays to specify the shape of the array (list, map, ...)
- I optimized some return statements by using the `??` operator

**Comment by klees** [comment]
@mjansenDatabay Thanks a lot!

**Pull request merged**
