### PR TITLE
Fix/0022866/trunk/component service other globals than dic bug

### PR DESCRIPTION
**Pull request by chfsx**
This is for https://www.ilias.de/mantis/view.php?id=22866

@alex40724 most of those classes belong to you, could you have a look at this?

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks +1. But this now under your maintainership, right?

**Comment by chfsx** [comment]
This is not clear, I think. For the plugin-stuff, yes. But there are also things like ilModule or ilService

**Comment by alex40724** [comment]
Ok, I see. I think it will be difficult to have these mixed responsibilities in this directory. Would you prefer to take these classes, too. Or separate them from the plugin related stuff in another directory?

**Comment by chfsx** [comment]
I'm not so keen to have these classes, to be honest. I suggest to split this up.

**Pull request merged**
