### PR TITLE
T&A: fix for 22409

### PR DESCRIPTION
**Pull request by okaufman**
Fixes https://mantis.ilias.de/view.php?id=22409
I added a check to see if there are any obligatory questions present in the test before adding the text "You filled out all compulsory questions." in the final message.

I made a new function to make it easier to read.

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @okaufman : Sadly this Mantis-Issue has accumulated a lot of cruft during its long existence and the important sentence  from  @dsstrassner got hidden in the middle (https://mantis.ilias.de/view.php?id=22409#c75361). Your fix would fix the original report, but actually on the way people agreed that the whole sentence can go, independent of the setting. Would you be so kind and update the PR accordingly? Thanks a lot!

**Comment by kergomard** [comment]
...and now Jens had a very good point:
The Information might not be Null, if the test has been ended automatically. I will see with @dsstrassner  and we will need to give this a little bit more thought. Sorry for the back and forth!

**Comment by dsstrassner** [comment]
We talked about this in our TechSquad Meeting today, and I also spoke with HJ Lauener. 
We agreed to only let the sentence to, as fix for this Mantis Issue. Also, we (HJL & I) agreed to abandon this feature / setting with ILIAS 10. (see [Discord](https://discord.com/channels/819582183290437642/1022408960302653481/1035117888048205854).
Dear @okaufman would you do me the favor, to adjust your PR to this decision. 
Afterwards, @kergomard will merge the PR to ILIAS 7 and cherry-pick to ILIAS 8 and trunk

**Comment by kergomard** [comment]
Thank you very much @okaufman . Will merge and cherry-pick.

**Pull request merged**
