### PR TITLE
StudyProgramme: Add fix for Mantis issue 26291

### PR DESCRIPTION
**Pull request by mjansenDatabay**

### CODE REVIEW

**Comment by klees** [comment]
Thx @mjansenDatabay!

This indeed looks plausible and I certainly am convinced that you tested this before PRing it. But currently I fail to see the cause for the problem and thus also do not understand how this code solves it. Could you enlighten me a little? Are there any specific questions you like to discuss with me?

**Comment by mjansenDatabay** [comment]
Yes, I have tested this. We will do some further tests (that's why I created this PR as a draft).

The problem was:

- With your latest commit (in regards of this SP topic), you changed the structure from a nested `Array of Objects` structure to a `Flat Array` structure by only pushing the DOM IDs on a stack, see: https://github.com/ILIAS-eLearning/ILIAS/commit/ad8c420f83099eebc4bfa1ef09379be717114b2f#diff-7c8824b600415b391df62d51e969dcc8R198 . This array did not include any hierarchy information at all.
- On the server-side, you modified the code (https://github.com/ILIAS-eLearning/ILIAS/commit/ad8c420f83099eebc4bfa1ef09379be717114b2f#diff-f3b2aa5d04c2d1da3f1194a0a13f9528R238) to be aware of the `Flat Array` structure. You did not change the algorithm (base on recursion and parent-child-relations) of `\ilObjStudyProgrammeTreeGUI::storeTreeOrder`, so all elements got the root study programme as their new parent object. Even PhpStorm complains about the **undefined** `$node` variable :-).

**Comment by mjansenDatabay** [comment]
Feel free to merge!

**Comment by klees** [comment]
Hi @mjansenDatabay,

I merged this manually:

https://github.com/ILIAS-eLearning/ILIAS/commit/3b0752d298c7d9fa42d52166c75a1f7ec21b3278
https://github.com/ILIAS-eLearning/ILIAS/commit/7ccad40aa6f7d1517eacaa8bd3854af4371b96db

Thanks!

**Comment by mjansenDatabay** [comment]
Okay, so this can be closed @klees ?

**Comment by klees** [comment]
Ah, yes. Thx for the reminder.

**Pull request closed without merging**
