### PR TITLE
0031283: removed language from setup

### PR DESCRIPTION
**Pull request by c-knof**

### CODE REVIEW

**Comment by katringross** [comment]
Hi @klees, like you and @matthiaskunkel suggested I decided to remove the language config from setup. Only en will be installed as default language.

**Review by katringross — APPROVED** [review]

**Review by klees — APPROVED** [review]

**Review by klees — COMMENTED** [review]
Hi @katringross,

I think `\ilLanguageSetupConfig` can be removed now.

Best regards!

**Comment by katringross** [comment]
@klees can you please review this PR again, since we removed all config related parts from the language setup code and fixed the failing tests for language. We added the license header too where we had to.

thanks a lot!

**Comment by klees** [comment]
Hi @katringross,

I removed myself from the PR as this only touches code under your maintenance.

Is there anything specific that you want me to look into?

Best regards!

**Pull request merged**
