### PR TITLE
Update ilias_bg.lang

### PR DESCRIPTION
**Pull request by bistrekov**
Update of the Bulgarian language file - 30112021

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @bistrekov 
Thanks for this contribution! The maintainer of the language files will have a look at this. My question: there seem to be a lot of changes (13,999 additions, 14,006 deletions), did you sort the items by alphabet or something like that?

**Comment by bistrekov** [comment]
Well, I suppose this file was not touched for a long time. Or my workflow was not right.
I did the following: I've exported all enties from a fresh ILIAS 6 installation, did the adjustments on that global lang file, and then copied the result into the ilias_bg.land file on my local ILIAS repository. Most likely the sorting was done during the export/download of the file from the ILIAS installation.

**Comment by chfsx** [comment]
> Well, I suppose this file was not touched for a long time.

could be the reason ;-) @matthiaskunkel will have a look at this! thanks a lot!

**Comment by matthiaskunkel** [comment]
Thanks @bistrekov for updating the Bulgarian language file. File hasn't been touched for a long time. Any additional updates are heartly welcome. Number of changes relies on the sorting of lines (now alphabetically, before not). Everything's fine.

**Comment by bistrekov** [comment]
Thank you, @matthiaskunkel!
I will keep working on updates. The intention is to get it translated up to 90% in the next week to two. 
Cheers,
Lyubo

**Pull request merged**
