### PR TITLE
UI Input: getUpdateOnLoadCode for all Inputs (and some more associated things)

### PR DESCRIPTION
**Pull request by tfamula**
Hi @Amstutz and @klees!
This PR implements the entry in the Roadmap of the UI-Framework regarding the `getUpdateOnLoadCode` and `OnUpdate` stuff coming from the Filters (see also https://github.com/ILIAS-eLearning/ILIAS/pull/1735#issuecomment-483672114). This PR does a little bit more than that. The following points are included:

- Implementation of (almost*) every task from the Roadmap (see also comment at the bottom)

- `Numeric` and `MultiSelect` are Filter Inputs now. `Tag` was also added temporarily (to save these changes in Github), but removed for now due to ugly rendering within Filters.

- The implementation of `OnUpdate` for Forms were temporarily made (to save these changes in Github and for testing purposes), but removed for now due to a missing use case for `OnUpdate` within Forms. As soon as one exists, https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559 can be copied/cherry-picked and completed with the implementation of the use case in `form.js`

Open Tasks: 

- [x] Check if any tests are failing

*@klees: I did not implemented the third bullet point in the Roadmap because it makes no sense IMO.

> The usage of the method should be moved from the (specific) Container\Filter\Renderer to the (general) Field\Renderer to make OnUpdate apply everywhere.

I understand your intention here, but I think you overlooked the relation between Filter and Input. The method `withOnUpdate` must be used in the Renderer of the Filter because we must call `getUpdateSignal` for the Filter here to use the data we get from the Input. The same goes for the Form.

### CODE REVIEW

**Comment by klees** [comment]
Hi @tfamula,

you might be correct and I might be missing something, but let me try once again (and bare with me)...

So [`Input::withOnUpdate`](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Implementation/Component/Input/Field/Input.php#L488) is available on every input regardless of the container it is embedded in. So users will expect that this trigger (?) also works in the `Form Container`. This, in turn, led me to expect that some code similar to [this here](https://github.com/ILIAS-eLearning/ILIAS/blob/b8a2a3a203d8fb5bab988849ab43616be7379551/src/UI/Implementation/Component/Button/Renderer.php#L163), that actually turns triggers and signals into javascript, must be present in the `Renderer` of `Field` to make the update-trigger work regardless of the `Container` it is. But I can't find that code. This in turn led me think that the update-trigger in fact does not work in the `Form Container`. I found some code that deals with the update-trigger in the  `Renderer` of `Filter Container`, which in turn led me to believe that the javascript code for the `Field`s is created there in fact. On closer inspection I'm not sure about this anymore, though. So my original question (or requirement, however my confusion will be resolved) is: Does the Update-Signal work in the `Form Container`. And as follow up: Why? You might be in a better place to answer these questions though, I'm just confused atm. Does at least my question make some sense?

This might show once again that this Signal-Triggerer-Stuff and its implementation is just confusing and we need a better model or at least naming, though.

Thx for your stamina!

**Comment by tfamula** [comment]
Hi @klees,
to answer your question, please also take a look a look at the third bullet point in the description of the PR. I made https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559 to demonstrate how this OnUpdate-Stuff for Forms will look like in the future. Because we have no proper use case at the moment, I removed this code in the next commit. That's why you cannot find it under "Files changed" in this PR.
On the one hand, in https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559, we have [`setSignals`](https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559#diff-b4ae02bf34c6e4ce03fb9c92d0376778R64) for the Input Field where you can find the `withAdditionalOnLoadCode` part, similar to the Button example in your comment. You find the same code from the method in [`FilterContextRenderer::renderInputField`](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Implementation/Component/Input/Field/FilterContextRenderer.php#L182). We need this duplication because we have separate Renderers for Filter and Forms.
On the other hand, there is [`registerSignals`](https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559#diff-79e45d112128287b42f6ab6436c48224R58) for the Form. You can find there another `withAdditionalOnLoadCode`, which listens to changes in the Input Field. In the [JS-function](https://github.com/ILIAS-eLearning/ILIAS/commit/45980f3fdcb7200a6a5a1abc1d59c5e23085e559#diff-8cb856d0c5bc80710d3e8cbd2d34dc55R17), I put only a simple console.log() for testing purposes because a proper use case is missing at the moment, like I said before. For Filters, we already have one, see [here](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/templates/js/Input/Container/filter.js#L146).

> This in turn led me think that the update-trigger in fact does not work in the Form Container.

So you are right, the update stuff does not work in the Forms yet. We must find a useful case for them. But actually, this was not part of the Roadmap entry.

> So Input::withOnUpdate is available on every input regardless of the container it is embedded in.

This is not quite correct. It is `getUpdateOnLoadCode` which is available on every Input. `withOnUpdate` is theoretically available  for every Container instead.

I hope this is more comprehensible now. Do not hesitate to ask if something is still unclear. But please consider that sometimes the Signal-Triggerer-magic is confusing to me, too :smile:

**Comment by klees** [comment]
@tfamula Thanks for the explanation Thomas! This helped a lot to (again) understand this complicated situation.

I do not agree totally, though:

> This is not quite correct. It is getUpdateOnLoadCode which is available on every Input. withOnUpdate is theoretically available for every Container instead.

`withOnUpdate` is indeed available on every input (internally): see [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1933/files#diff-48267845b56fb4a2b62352167f358f9cR473). So we still have the situation that we seem to provide some functionality that simply does not work in some situation without notification. So at some point, someone will try to use this method for whatever reason and then will spend some potentially long time to figure out what is wrong just to find out that we provided a method that just isn't implemented completely.

What will happen then? Maybe the person already handed in some offer that was based on the fact, that `withOnUpdate` works as expected just to find out she needs to put in extra work not accounted for. Or he will expect @Amstutz and or me to implement it. Maybe we'll just get a bug report. We will need to remember this conversation here then. I hope we do, because if not it will be one of us figuring out why this does not work. I'll be disappointed of myself, then. Solving this problem is indeed the intention of the roadmap entry, which also outlines the required actions (imo).

This boils down to: We should not promise functionality and then not deliver it. If this is not possible for whatever reason, we should at least tell loud and clear that we cannot provide the promised functionality.

I can indeed think of a use case, though. Updating the word-count of a textarea.

Even more strange, `getUpdateOnLoadCode` is available on the [public interface](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/Input/Field/Input.php#L176), but what would I want to do with this method as a consumer? The more useful `withOnUpdate` and `appendOnUpdate` are missing on the public interface, though, and I currently cannot find a definition of them the justifies the `@inheritdoc` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1933/files#diff-48267845b56fb4a2b62352167f358f9cR471).

> But please consider that sometimes the Signal-Triggerer-magic is confusing to me, too 

Yes, it certainly is. We will need to change it.

I'm still not very happy with the situation here, but huge parts of this might stem from this complicated trigger/signal-stuff in conjunction with the equally complicated js-stuff. All in all, this PR seems to improve the situation, thanks for this. We still need to solve the issue that we promise functionality but not deliver it.

If for some reason it is not possible to make `OnUpdate` work in every context (i.e. Filter and Form, currently) we at least need to notify our users that this does not work. To make this happen we should put a big-fat "ATTENTION" section at the definition of `withOnUpdate` and `appendOnUpdate` and throw an exception if someone tries to use these methods in the context of the Form.

I'm sorry that I need to be so persistent with this and I see that you put in a lot of effort to solve the situation, thanks for that. But delivering a supreme UX for devs to me is very important for the UI-framework and delivering what is promised for me is essential there.

**Comment by Amstutz** [comment]
@tfamula thanks a lot for the PR and for staying with us for so long on this matter!

I strongly believe, that the point of @klees is valid:

> This boils down to: We should not promise functionality and then not deliver it. If this is not possible for whatever reason, we should at least tell loud and clear that we cannot provide the promised functionality.

@tfamula do you see any possibility to fulfill that promise within this PR?

**Comment by tfamula** [comment]
Hi @klees and @Amstutz 
Thank you for pointing out the problem here. It is completely valid! Of course, we should not promise functionality and then not deliver it. In general, the desired functionality was always there, I was just unable to see the wood for the trees :laughing: The problem was, it was not working properly or just partly. I did the following things:
-  I analysed conflicts in some Components and detected / solved conflicts with other existing Javascript stuff. To make everything work, i.e. existing code and the new OnUpdate-code, I had to make some improvements in the [Renderer](https://github.com/ILIAS-eLearning/ILIAS/pull/1933/files#diff-b4ae02bf34c6e4ce03fb9c92d0376778) of the Input Field and also in some templates regarding the ID handling.
- I implemented `getUpdateOnLoadCode()` for the Inputs `DateTime` and `Duration` because they were merged in the meantime. I also tried to make them already to `FilterInput`s as a side benefit. But unfortunately, I had to give up for now due to some difficulties with the rendering within the Filter, especially for `Duration`.
- I removed Signal-related code for the `Form` (which I used for easier testing) because we do not need the `Form` as a `Triggerable` like the `Filter`. If there will be a use case for this in the future, it can be added again without any problems. 

To point out the most important thing: **The promised functionality works now**. You can use `withOnUpdate` and `appendOnUpdate` with every Input (as well as Input Groups to affect multiple Inputs at once). `Input` can have the role of a `Triggerer` now. A very easy example for a `Triggerable` could be a Modal. By extending an Input with `->withOnUpdate($modal->getShowSignal())`, a Modal window would show up when making a change in an Input field. We can also use the OnUpdate-event now for things which are more useful, like changing the current behaviour of updating the word count of a `Textarea` and transfer it to the new `OnUpdate` way (as mentioned by @klees).



I hope everything is clear now :smile: I (again) learned a lot about Signals / Javascript within the UI Framework (and I fear that was not the last time).
Please tell me if you are okay with the PR now, so I can check the unit tests before we merge this.



PS: @klees Some explanations especially for you:

> Even more strange, getUpdateOnLoadCode is available on the public interface, but what would I want to do with this method as a consumer?

IMO, we put `getUpdateOnLoadCode` into the interface to "force new inputs to implement this method properly" (see Roadmap). Because we also need this method to make `OnUpdate` work properly, we should leave it as it is.

> The more useful withOnUpdate and appendOnUpdate are missing on the public interface

IMO, these methods are implemented like other Events. The interface `OnUpdateable` can be found "globally", like `Clickable`, `Hoverable` and so on. We do not declare the methods `withXYZ` and `appendXYZ` in the specific interfaces of the components a second time, but extend the "global" interfaces instead, see [here](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/Input/Field/Input.php#L31) for Input. In the implemenation part, we then of course need these methods, see [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1933/files#diff-48267845b56fb4a2b62352167f358f9cR432).

**Comment by alex40724** [comment]
@tfamula Thanks a lot. To me this all looks great. @Amstutz Do you think we can merge this after fixing the tests, or would you like to wait for @klees ?

**Comment by Amstutz** [comment]
This looks fine to me, the only thing left is fixing the tests. I would like to have a short thumbs up from @klees before merging. @klees All fine with you?

@tfamula thanks a lot for your endurance on this one!

**Review by Amstutz — APPROVED** [review]

**Comment by Amstutz** [comment]
@klees any update on this?

**Review by klees — APPROVED** [review]
Hi @tfamula,

thanks for the hard work, this looks very good now. I'm sorry that you had to wait so long for that feedback.

Please fix the tests and solve the (probably new) conflicts and then ping @Amstutz or @klees to push the merge button.

Thanks!

**Comment by tfamula** [comment]
Hi @Amstutz and @klees,
The tests are fixed and the conflicts are solved! I would be very grateful if one of you could hit the the Merge button in the course of this week (especially because of the announced shift to PSR2 in the UI Framework on the 9 September)

**Comment by Amstutz** [comment]
thx a lot

**Comment by tfamula** [comment]
@alex40724 Merged!

**Pull request merged**
