### PR TITLE
ModeInfo/UI Demo: fix example for modeinfo

### PR DESCRIPTION
**Pull request by nhaagen**
fixes the example for ModeInfo; also, the button was _very_ unobstrusive.

### CODE REVIEW

**Comment by Amstutz** [comment]
Thx for improving the example.

what exactly was broken? note that tests are failing atm.

**Comment by nhaagen** [comment]
Links to the fullscreen were not working (script-url was changed), and the page was rendering without CSS/JS.
Checks failed due to the horrible $_GET-access. Now it's something with the footer?!

**Comment by nhaagen** [comment]
Sorry about the fuss; I found some more issues, basically all examples rendering a full page. 
This now should fix links and responses by using refinery, requestwrapper and ilCtrl over script-names and server-globals.

**Comment by Amstutz** [comment]
Looking much better know, thx a lot for improving this!

**Pull request merged**
