### PR TITLE
Extended Maintainer Documentation

### PR DESCRIPTION
**Pull request by alex40724**
This PR extends to maintainance documentation to clarify the process of becoming a maintainer and how companies can be mentioned in maintainerships.

### CODE REVIEW

**Comment by atoedt** [comment]
plural is companies

**Comment by alex40724** [comment]
@atoedt ... but there is no use of a plural in this text !?

**Comment by matthiaskunkel** [comment]
Jour Fixe, 17 FEB 2020 : We highly appreciate this suggestion and accept the textual modification for all branches.

**Comment by alex40724** [comment]
Merged to trunk, 6 and 5.4

**Pull request merged**
