### PR TITLE
Test Assessment Design Tickets - PR collection of Mantis #32213 #32215 #32214 #32184

### PR DESCRIPTION
**Pull request by catenglaender**
To solve merge conflicts, this PR combines the Test Assessment PRs #4157 #4159 #4162 #4164 on top of a more recent release_7 branch.

These PRs address design issues and tweaks in CSS and HTML. Because of refactoring code into new files, some php code was also changed.

Links to all Mantis Issues:
Responsive Split View for question shortlist - https://mantis.ilias.de/view.php?id=32213
Star icon for marked questions as favorites - https://mantis.ilias.de/view.php?id=32215
Remaining time alert box - https://mantis.ilias.de/view.php?id=32214
Missing bottom navigation - https://mantis.ilias.de/view.php?id=32184

ILIAS 7 instance for testing: https://dev.cate-tms.de/fetajuly

There is one public test assessment on the top level of the repository that can be accessed without being logged in. If you require an admin login, just message me on Discord.

### CODE REVIEW

**Comment by dsstrassner** [comment]
Big thanks @catenglaender. As requested by @Amstutz: For me as T&A maintainer, these are the right solutions for the issues.

**Review by Amstutz — APPROVED** [review]
@catenglaender 

Many big thx and hugs! Special thx for moving the css to the correct place. To however who might be reading this and asking, why we accept CSS changes here, that violates all kind of guidelins; @catenglaender just moved this to the correct place and did not refactor all of the CSS code in this step. Extracting all color values here and replacing them with less variables as an example would need to be done in a further iteration.

The DOM changes are looking good, however, they need to be tested on the GUI as well. @dsstrassner Can you do that, as soon as we have a installation for testing. As soon as this is done, @mbecker-databay can imo merge this.

**Review by mbecker-databay — APPROVED** [review]
This looks good to me, thank you very much for your work on this.
Unless there are any findings in the UI Tests, it's good to be merged.

**Comment by catenglaender** [comment]
ILIAS 7 instance for testing: https://dev.cate-tms.de/fetajuly

There is one public test assessment on the top level of the repository that can be accessed without being logged in. If you require an admin login, just message me on Discord.

**Review by dsstrassner — APPROVED** [review]
The issues described in the Mantis Reports are fixed with this PR. I checked the provided test plattform.

**Pull request merged**
