### PR TITLE
UI: adjust position of infoscreen profile infos. (#38151)

### PR DESCRIPTION
**Pull request by lukastocker**
https://mantis.ilias.de/view.php?id=38151

### CODE REVIEW

**Comment by lukastocker** [comment]
Der Test läuft derzeit auf Grund von [diesem Commit](https://github.com/ILIAS-eLearning/ILIAS/commit/244ad9cae6158142ca4c58db0c5e7dca24375935) nicht durch.

**Comment by Amstutz** [comment]
Hi @lukastocker 

Thx for proposing this. However, I have not such a good feeling by resolving that with padding here. AFAIK those values are styled by the col-sm-8 col-md-9 col-lg-10 classes. Why seem they not to be working here?

@catenglaender : Opinion from your side?

**Comment by lukastocker** [comment]
Hi @Amstutz ,

@catenglaender and myself had a discussion today about this implementation. I updated this PR with the new implementation - therefore I am assigning this back to you.

The offset was commented out as it was only used for the infoscreen profile template. We avoid a lot of extra code now.

Kind regards
Luka

**Comment by Amstutz** [comment]
Hi @lukastocker 

- [ ] There will also be a mixin `make-col-offset` this might not be used anymore. Probably delete this as well. 
- [ ] Delete the out commented lines and the selectors surrounding it. We should and will not use this anymore.

thx.

**Comment by lukastocker** [comment]
> Hi @lukastocker
> 
>     * [ ]  There will also be a mixin `make-col-offset` this might not be used anymore. Probably delete this as well.
> 
>     * [ ]  Delete the out commented lines and the selectors surrounding it. We should and will not use this anymore.
> 
> 
> thx.

Hi @Amstutz ,

as reviewed with you I deleted every mixin, include, selector and comment regarding "offset". Please have a look to the changes.

Kind regards,
Luka

**Comment by Amstutz** [comment]
thx a lot!

**Pull request merged**
