### PR TITLE
[WIP] [Refinery] Implementation of kindlyTo transformations

### PR DESCRIPTION
**Pull request by legionth**
This is the first version for a possible version of `kindlyTo` transformations.

This is an addition to the previously merged refinery (#1707).
As @klees mentioned this is needs some love and discussion before it can be merged into the trunk.

The original concept for the whole refinery can be found [here](/docs/documentation/input-processing.md).

Our original intention for this version was to design the kindly to transformation close to the PHP default behavior of the [type juggeling](https://www.php.net/manual/de/language.types.type-juggling.php).
In a discussion with @klees @mjansenDatabay and @legionth we came to the conclusion that this is not the desired behavior we want to have here.
Example: A `string` "false" or "true" should be interpreted by the `KindlyTo\BooleanTransformation` as the boolean equivalent.
However an optimal solution is currently under work. As mentioned in #1707 we have to take of corner case like scientific and similar notations.

A big part of the discussion can be found in the original PR #1707 (some parts were discussed via a conference call).

Feel free to give us feedback on this early/first version :+1:

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@alex40724 This PR adds the `Secret Sauce` :smile:  and makes the `Refinery` (more) usable, e.g. for form handling and other consumers, where we don't know much about the input. Maybe you are interested in providing feedback here.

**Comment by alex40724** [comment]
@mjansenDatabay Thank you for pointing me to this PR. And thanks to everyone who contributed to this so far. As mentioned in our telephone call I am still missing the ultimative final way for developers to make this useful especially for the very common case of handling input parameters.
I somehow lost the discussion on the "syntactic sugar" part. But I understand that this was not part of the contract yet.

**Review by klees — COMMENTED** [review]
I guess we need an approach to somehow have a structured discussion with all developers about this. I would propose, we do the following:

* Create an edupad, containing the initial problem description and a list of the kindlyTo-implementations we are looking for.
* Add the current proposals for implementations to that list.
* Add tasks to that edupad:
    * Propose alternative implementations.
    * Comment on the proposed implementations.
* Then: write a mail to the dev-list with the invitation to participate and a doodle for a vc for the actual decision-making.
* Have the VC around ~4 weeks later.
* Weigh the options per transformation on the vc. We might not necessarily nned to pick one or the other option there, one and the other might also be a possibility.

I would take care to create the edupad, write the e-mail and organize the vc if @mjansen and @legionth are fine with this approval.

**Comment by mjansenDatabay** [comment]
@klees :rocket: We are fine with this!

**Comment by alex40724** [comment]
@klees @mjansenDatabay Could you please give a short status update on this?

**Comment by klees** [comment]
AFAIK we may just close this, the code won't be gone even if it's closed. We'll have a meeting regarding the kindlyTo-transformations on 02-27 at 10:00 via Skype. Please contact @nhaagen or me.

**Comment by mjansenDatabay** [comment]
I agree, closed!

**Pull request closed without merging**
