### PR TITLE
Mail: Remove legacy migration for mail templates

### PR DESCRIPTION
**Pull request by iszmais**
Removing of legacy migration inside the mail.

Softly depends on https://github.com/ILIAS-eLearning/ILIAS/pull/7926

### CODE REVIEW

**Comment by iszmais** [comment]
@kergomard conceptionaly i would strongly assume that this also affects the similar migration inside the user service.

Feel free to approve or to correct me on that.

**Review by mjansenDatabay — CHANGES_REQUESTED** [review]
Thx @iszmais , please create a separate PR for the "User" component.

**Comment by iszmais** [comment]
@mjansenDatabay I split the parts for review purposes.

However, since this is conceptionally entwined, I would suggest merging both PRs in dependency to another.

Greetings,
@iszmais

**Review by mjansenDatabay — APPROVED** [review]
LGTM!

**Pull request merged**
