### PR TITLE
TA: 37915, get autosave-answers by pass and display in manual scoring

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=37915

Screenshot from 2023-12-12 16-22-36
Screenshot from 2023-12-12 15-50-04

### CODE REVIEW

**Comment by dsstrassner** [comment]
This PR also changes the authorization of answers and reverts a JF decision. So, we need to wait until the JF approves this change.
Thanks again @nhaagen!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 JAN 2024: We follow the suggestion of the 1st maintainer and remove the decision for the Mantis bug report #28561. Related PR 6788 is accepted for ILIAS 8, 9 and trunk.

**Comment by kergomard** [comment]
Thank you very much for the PR @nhaagen ! I added a text to the results output, that shows the second box contains an autosave. Not exactly beautiful programming, but does the trick for the moment. See: https://github.com/ILIAS-eLearning/ILIAS/commit/c40a319b7216e70923e7266b7d73ff0dd642292d. Merged and ported to ILIAS 8 and trunk.

**Comment by jweber-unibe** [comment]
A quick retest shows the original issue to be resolved for ILIAS 9 – but not so for ILIAS 8 ... 🤔😶

**Comment by kergomard** [comment]
I added the autocorrect value to ILIAS 8 with https://github.com/ILIAS-eLearning/ILIAS/commit/1c43de7888b61a9a8b58cf67613518827a0c80a2. This is not the same behaviour as it was in ILIAS 7 where the solution was NOT shown for participants, but it is now the same behaviour as in ILIAS 9.

**Comment by kergomard** [comment]
> A quick retest shows the original issue to be resolved for ILIAS 9 – but not so for ILIAS 8 ... 🤔😶

Could you, @jweber-unibe maybe provide me an example and a path for reproduction? I cannot reproduce this on ILIAS 8 and the code looks sound.

Best,
@kergomard

**Comment by dsstrassner** [comment]
> > A quick retest shows the original issue to be resolved for ILIAS 9 – but not so for ILIAS 8 ... 🤔😶
> 
> Could you, @jweber-unibe maybe provide me an example and a path for reproduction? I cannot reproduce this on ILIAS 8 and the code looks sound.
> 
> Best, @kergomard

I think @jweber-unibe means the Ghost-Attempts. See steps for reproduction in [Mantis](https://mantis.ilias.de/view.php?id=39458)

**Pull request merged**
