### PR TITLE
Learning History Service

### PR DESCRIPTION
**Pull request by alex40724**
Feature:
https://docu.ilias.de/goto_docu_wiki_wpage_4954_1357.html

README:
https://github.com/ILIAS-eLearning/ILIAS/blob/a3707371d986c16ff19f0e9891b1b9e2909dcb5a/Services/LearningHistory/README.md

Abstract base class:
https://github.com/ILIAS-eLearning/ILIAS/blob/a3707371d986c16ff19f0e9891b1b9e2909dcb5a/Services/LearningHistory/interfaces/class.ilAbstractLearningHistoryProvider.php

Interface class:
https://github.com/ILIAS-eLearning/ILIAS/blob/a3707371d986c16ff19f0e9891b1b9e2909dcb5a/Services/LearningHistory/interfaces/interface.ilLearningHistoryProvider.php

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 OCT 2018 : We highly appreciate this PR and accept it for 5.4.

**Comment by mjansenDatabay** [comment]
@legionth

**Comment by legionth** [comment]
I think this is great feature and will make a lot of things easier for the user :+1: . I think an event-driven approach would fit a bit better here. Instead of collect data via registered providers, an event listener could be added. This listener could listen on defined events, these events could provide all information you need for the display in the learning history.

E.g.:
```php
$ilAppEventHandler->raise(
    'Services/LearningHistory',
    'new_entry',
    array(
        'achievetext' => 'congratz!',
        'achievetext_in_text' => 'congratz!',
        'icon_path' => '/some/icon/path/icon.jpeg',
        'timestamp' => time(),
        'obj_id' => 600,
        'ref_id' => 1200,
    )
);

```

This would also mean less configuration for maintainers and would be easier to be replaced in the future.

@alex40724 what do you think about this?

**Comment by klees** [comment]
Hi @legionth, could you elaborate a little more on your assessment regarding the benefits of events vs. collector? Thx!

**Comment by legionth** [comment]
Of course @klees ! Using collection mechanism means we have to define classes for each component and somehow register them. In this special case it would mean **extend** from the base class "ilAbstractLearningHistoryProvider" and **implement** the interface "ilLearningHistoryProvider". Furthermore the developers has to add the new provider to the "ilLearningHistoryProviderFactory".
Based on these `ilAbstractLearningHistoryProvider::getEntries()` can be called in certain intervalls to receive new entries. This means also to differ between old entries and new entries.

Using an event instead means that only the relevant data will be send without creating new classes. The event could be emitted directly after every data is completed, which means we have more "real-time" approach here. This depends(of course) on the event processing component, the "real-time" MAY be lost here.
But maintainers don't have to maintain new classes or the adding to the factory. This service MAY also be in *no need* for an interval approach. The data could be processed soon after the event appears. 

I don't want to block this feature, because my feature also depends on it:smiley:
Maybe @alex40724 says it would be to much work right now to adapt this concept, this would also be fine by me :+1:.
I just wanted to consider this possibility while this is in an early stage.

**Comment by legionth** [comment]
Let me know what you think about this :+1:

**Comment by alex40724** [comment]
I do not persist the data in any way. This is all realtime. Consumers give their realtime data. I asks consumers everytime I display this view. This means consumers should be able to give this data with a performant database query, which should not be a big issue. Consumers are also responsible to historise their own data (the name of this service is due to the naming in the user interface, not because it stores this data).

Events would completely decouple the data from the consumers. What if an error produces too much of these events? Which component could fix this? How is user language dependency realised if I would persist this data (even lang keys may not be valid anymore)? This hard coded icon path may also not work anymore with an upcoming release.

**Comment by legionth** [comment]
These are IMO all solvable problems, that must be answered of course.

Here are my "ad-hoc" thoughts on this:

* **What if an error produces too much of these events? Which component could fix this?**
The event emitting service is responsible to fix these problems. This event could be an abstraction of an `SQL-Delete`.
This problem could also exists in the current approach because of invalid duplicated entries in the database. This would mean i need to delete these entries via e.g. a database update step.

* **How is user language dependency realised if I would persist this data (even lang keys may not be valid anymore)?**
Using an `update`-event that could change. This event could be an abstraction of an `SQL-Update`.

* **This hard coded icon path may also not work anymore with an upcoming release.**
Same as I explained before via an update-event.

But I see you are not a fan of this approach, this is why I would avoid further discussions for "time-saving" reasons.

**Comment by alex40724** [comment]
Yes, I am not a fan of producing data redundancy. The event based interface might be easier but becomes more obscure, too. A developer might just forget so send this "update the icon path" events when a designer comes with a new icon. Developers tend to grep the code for the old path and change it. But if this is stored in some services db tables, the developers might just overlook this. Same for lang keys.

Beside data redundancy I am also not a big fan of using event based interfaces internally, since this one raise() method is very weak when it comes to typisation. There is no real "definition" of an interface here imo.

**Comment by alex40724** [comment]
This has been merged.

**Pull request closed without merging**
