### PR TITLE
DateTime: Remove manipulations of global default timezone (except in …

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…Services/Calendar)

This PR removes all global/default timezone manipulations (except those in `Services/Calendar`) from our code base.

It is related to https://mantis.ilias.de/view.php?id=26951

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@chfsx / @maxbecker : Please check the changes I made in your components. All changes except the [`hearbeat`](https://github.com/ILIAS-eLearning/ILIAS/pull/2423/files#diff-6139df5afa7e4ffe8c0b09297f0b95e2) related one are covered with unit tests.

**Review by mbecker-databay — APPROVED** [review]
#lgtm :) Thank you!

**Review by chfsx — APPROVED** [review]
Thanks @mjansenDatabay! the parts in BGT and FS are perfectly fine for me, thanks for the investigation!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 06 JAN 2020: PR highly appreciated. Thanks for merging.

**Pull request merged**
