### PR TITLE
UI/Symbol/Icon/Standard - Introduction of missing Glyphs

### PR DESCRIPTION
**Pull request by ezenzen**
This PR offers new glyphs that are needed in the page editor and for removing the ilGlyphGUI.

These Glyphs will be inserted into the KitchenSink. The glyphs bulletlist, numberedlist, listindent and listoutdent are needed for the page editor. With the introduction of the filter glyph, even the last glyph from the ilGlyphGUI can be replaced by a KS element and the ilGlyphGUI can be removed soon.

With this PR the following adjustments are made:

- Description of the KS article Symbol > Glyph
- 5 new Glyphs

Feedback is warmly welcome.

### CODE REVIEW

**Comment by ezenzen** [comment]
**Glyphs to be introduced**
Glyph

**Comment by ezenzen** [comment]
**Example for a KS entry**
Screenshot_2020-10-23 ILIAS Documentation(1)

**Comment by klees** [comment]
Hi @ezenzen 

Congrats to this second neat PR in such short time! Special thanks for the screenshots and examples.

The descriptions seem fine to us, however we have not been participating closely in the Page Editor Revision discussions and expect someone of this working group to join the discussion in case of disagreement. The description of the Filter Glyph seems to fit its job.

This PR can be discussed at the upcoming JF. 

Note, before merging we need to adapt tests/UI/Component/Symbol/Glyph/GlyphTest.php somewhat to also test the new Glyphs. Contact @Amstutz if we can assist you with this.

Thx
@Amstutz and @klees

**Comment by matthiaskunkel** [comment]
Jour Fixe, 26 OCT 2020: We highly appreciate this suggestion and accept the PR for ILIAS 7.

**Comment by Amstutz** [comment]
@ezenzen Thx a lot. As pointed out, there are some tests yet missing. However, while looking out to fill those in, I observed some room for improvement for the glyph tests in general. Since no tests are failing I merge this but will create a new PR, adding the missing tests along with a general improvement of the way we test the glyphs.

Thx to everybody involved!

**Pull request merged**
