### PR TITLE
8/bugfix/long menu javascript

### PR DESCRIPTION
**Pull request by gvollbach**
Fixed broken Javascript for LongMenu Question

### CODE REVIEW

**Comment by gvollbach** [comment]
Copyright checks are failing, since your php classes, do not have the correct copyright header.

**Comment by kergomard** [comment]
@mbecker-databay, @dsstrassner : If it is ok with you, I will take care of this issue, while fixing the other issues in the Longmenu-Question, as I'm also renaming the files a bit. A PR should follow shortly. I would keep this PR open for the time being as a reminder and take the responsibility to close it. You can assign it to me.

**Comment by dsstrassner** [comment]
> @mbecker-databay, @dsstrassner : If it is ok with you, I will take care of this issue, while fixing the other issues in the Longmenu-Question, as I'm also renaming the files a bit. A PR should follow shortly. I would keep this PR open for the time being as a reminder and take the responsibility to close it. You can assign it to me.

This is fine for me. I reassign this to you @swiniker. I will leave my assignment due to the TechSquad protocol.

**Comment by dsstrassner** [comment]
As discussed at today's TechSquad Meeting #4600 / #4626 will be merged after @kergomard vacation. (Or closed)

**Comment by kergomard** [comment]
Thank you very much for this PR @gvollbach and sorry it took me so long to get back to you. 
We were in the process of completely rebuilding the Javascript for the LongMenu-Question (See: #4626) and after that it got lost in my queue.
I think all the issues you tackle in this PR are fixed by now.
Sorry again and best,
@kergomard

**Pull request closed without merging**
