### PR TITLE
Form: Fix  restore condition on upload rebuild

### PR DESCRIPTION
**Pull request by iszmais**
https://mantis.ilias.de/view.php?id=40787

This is an additional Fix to https://github.com/ILIAS-eLearning/ILIAS/pull/7194 which refactors the first two condition cases and adds the missing third one.

### CODE REVIEW

**Comment by iszmais** [comment]
To give everybody an option to propose their interest in this PR, I will leave this withing the shepherds until 29.08.2024.
Everybody is encouraged to take actions here without any further required consultation.

If no one has claimed the PR until then, @mbecker-databay and @fhelfer will provide a review for it, since both where already involved in the initial fix.

Greetings,
@iszmais

**Comment by iszmais** [comment]
@fhelfer @mbecker-databay 

Since noone has state interest here feel free to add your review.

Thanks
@iszmais

**Comment by Amstutz** [comment]
Hi @iszmais 

Thx a lot, this seems to related to rather urgent DC PR, and we would be happy for a merge.

@mbecker-databay , I see that you are assigned here, if you are willing to click merge here, Ill gladly share the blame with you, if any rains down on you after merging.

**Comment by mbecker-databay** [comment]
I don't know why I was assigned, but I can surely look at this.
Oliver let me know, too.

**Comment by mbecker-databay** [comment]
This looks good to me. Please provide additional PRs for other relevant release-versions if necessary.

**Review by mbecker-databay — COMMENTED** [review]
Looks good to me.

**Comment by iszmais** [comment]
@mbecker-databay Thank you!

I provided the same changes for ILIAS 9 and Trunk in:
https://github.com/ILIAS-eLearning/ILIAS/pull/8048
https://github.com/ILIAS-eLearning/ILIAS/pull/8049

Greetings,
@iszmais

**Pull request merged**
