### PR TITLE
T&A #0035463 (trunk): Same name in Test export 

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=35463#c88384

### CODE REVIEW

**Comment by fhelfer** [comment]
adds to #5225 , because issue was still not resolved

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

I have one little request again, sorry:

- [ ] Could you please reduce the amount of `strtolower()` needed? I would think we need exactly one.

**Comment by fhelfer** [comment]
> Thank you very much @fhelfer !
> 
> I have one little request again, sorry:
> 
> * [ ]  Could you please reduce the amount of `strtolower()` needed? I would think we need exactly one.

@kergomard  less strtolower, new variable to keep original username for sheet naming

**Comment by kergomard** [comment]
Thanks again @fhelfer !

**Pull request merged**
