### PR TITLE
LTI LearningModule bugfixes and improvements

### PR DESCRIPTION
**Pull request by eqsoft**
- switch to LTI\MainMenu class in LTI-Mode
- adding inline css variable into tpl.page_new.html and tpl.page_fullscreen.html. @Alex: Please take a look at this if it is really needed. It is taken from tpl.main.html and has nothing to do with LTI

### CODE REVIEW

**Comment by alex40724** [comment]
Please refer a corresponding mantis bug report.

**Comment by Amstutz** [comment]
On behalf of the TB we close this report due to the following reasons:
- There is a mix between bugfix and improvement
- There are multiple fixes involved
- There are no clear bugreports indicated

See https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/documentation/contributing.md#rules-for-contributors for further information.

Nevertheless thank you for your contribution. Just split this into multiple PRs and properly comment.

**Comment by alex40724** [comment]
@Stefan: If this gets a corresponding bug report it should be ok. I do not see any improvements aspects here. The inline css is not needed by my code.

**Comment by alex40724** [comment]
So what I would need:
- The bug report. Then put the bug number in the title of the PR. Then we can reopen this pull report and tag it as bug related.

For the code:
- please remove the inline css stuff
- Please hide LTI internals (e.g. session names) from the consumer code. Since it seems to be unavoidable that the learning module gets some knowledge about the lti service at all in the current state, it should use a proper interface at least.

Something like

$lti_service = some factory call.
if ($lti_service->isActive())
{
  $ilMainMenu = $lti_service->getMainMenuInstance();
}

would be fine for me for now.

**Pull request closed without merging**
