### PR TITLE
Refinery: Adding the newly introduced identity transformation to the factory

### PR DESCRIPTION
**Pull request by Amstutz**
See title.

### CODE REVIEW

**Comment by klees** [comment]
Tests have been broken before...

**Comment by mjansenDatabay** [comment]
Before this PR?

**Comment by klees** [comment]
Yes... Weren't they?

**Comment by mjansenDatabay** [comment]
Yes, but because of the SCORM/CmiXapi code, not because of Refinery related code :-). I interpreted `before` as: We need this PR to make the Refinery work :-).

**Comment by klees** [comment]
No, the refinery works just fine =)

**Pull request merged**
