### PR TITLE
#25693: changes the getEmployees function to use the new OrgUnit fetch methods.

### PR DESCRIPTION
**Pull request by CrawdadWarden**
(Stolen directly from this commit in 5.4 https://github.com/ILIAS-eLearning/ILIAS/commit/7d40ae0a58247040030ab129357b79a32cf6db42)

### CODE REVIEW

**Comment by CrawdadWarden** [comment]
Sorry, I should have mentioned I opened a bug report for this (0025693).

**Comment by klees** [comment]
@CrawdadWarden Don't worry.

**Comment by klees** [comment]
Hi @mstuder,

could you have a look and give some feedback here?

Best regards!

**Comment by kergomard** [comment]
@mstuder: Sorry to bug you again with this, but we stumbled upon this PR in our biweekly TB meeting when we went through the old PRs. And this one will have its one year anniversary quite soon! Could you please merge it or provide your objections?

**Comment by mstuder** [comment]
Thx for contributing!!! With ILIAS 5.4 and ILIAS 6.0 we have fixed this behavior.

**Comment by CrawdadWarden** [comment]
I took the fix from 5.4, as I'm moving our LMS to 5.4 in the next week this isn't an issue but I'm curious when maintenance **ends** on the 5.3 branch as I still see commits being made to it and I believe that this is still broken functionality in 5.3 (in terms of showing the correct staff in the org unit view.)

**Pull request closed without merging**
