### PR TITLE
Forum: Hotfix for Mantis issue 28765

### PR DESCRIPTION
**Pull request by mjansenDatabay**
Mantis Issue: https://mantis.ilias.de/view.php?id=28765

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@Amstutz / @yvseiler FYI

**Comment by Amstutz** [comment]
Hi @mjansenDatabay 

Thx a lot. I just ran this script on a testinstallation with around 65k threads. Everything went smoothly, I did around 10 random checks of well populated threads. The tree is shown nicely afterwards posts as well. 

However I observed two things:

- [ ] answering on previously existing post does not seem to work, new posts are always attached to the very bottom.
- [ ] There seems to be an issue with the following query:
```
        $query = '
            UPDATE frm_posts_tree
            SET 
                parent_pos = CASE WHEN parent_pos = %s THEN %s ELSE parent_pos END, 
                rgt = rgt + %s,
                lft = lft + %s,
            WHERE lft >= %s AND rgt <= %s AND thr_fk = %s 
        ';
```
Is the "," before WHERE really needed? Further it seemst to be possible that $source_parent filling the first %s can be null and therefore making the query invalid. I had to slightly adapt with:

```
        if(!$source_parent){
            $source_parent = "0";
            $GLOBALS['ilLog']->warning("source parent has been 0, manualy set to 0!");
        }

```

However, I have no clue why this was possible, I only had one such case.

**Comment by mjansenDatabay** [comment]
@Amstutz : Argh, you were to fast 😁. I fixed some issues in the meantime. Maybe your testinstallion thread trees are now even more corrupted than before 🤣. You should restore it from a backup. I will contact you if it our internal tests are successful tomorrow.

**Comment by Amstutz** [comment]
No issue, just give me a nudge as soon as I should perform another go.

**Pull request merged**
