### PR TITLE
PHP 7.2 compatibility ILIAS 5.3 - part 2

### PR DESCRIPTION
**Pull request by ManfredKellermann**
Some more code changes in ILIAS 5.3 regarding PHP 7.2 compatibility.

### CODE REVIEW

**Comment by klees** [comment]
Dear all, I hope I picked the right assignees, this contains changes in various modules.

**Comment by alex40724** [comment]
@ManfredKellermann First of all, thank you very much for your support and this PR. It might seem to be a small issue but these kind of PRs are not in line with out guidelines and this create issues when being processed, see https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-4/docs/documentation/contributing.md

PRs should be minimal (not adress multiple issues) and changes that fix a bug should come with a bug report.

Having no bug report will not inform admins of other installations about these bugs and their fixes. If they experience they same bug they might open an additional report.

This PR (also your previous one) adresses issues in multiple components. I kindly ask you to open separate PRs in the future in this case. The handling becomes difficult, since multiple maintainers share responsibility. GitHub makes it easy for us to discuss the initial merge here, but only one person can do this merge and this person will be responsibility to merge this to other release branches as well. And these merges can become quite difficult to handle when they result in conflicts (in components under the responsibility of other maintainers).

Thanks and best regards

**Comment by alex40724** [comment]
@smeyer-ilias @bheyser Could you please review the changes in your components? I will try to merge this up to the other branches and hope that I will not get any conflicts like last time.

I had a short look at the IL_NO_LICENSE fix. This constant is used in another class as well, which might result in another bug. This is code originally of @fneumann. The feature has been abandonded with 5.4.

**Comment by ManfredKellermann** [comment]
@alex40724: Thanks for the info, I'm not so familiar with the development process.
Bug reports are missing, because they are improvements and no bugs (ILIAS 5.3 officially only supports up to PHP 7.1).
And probably this was the last pull request in this matter, I didn't find any more bugs. In our installations many features are switched off (competencies, badges, study programs,...).

Regards

**Review by bheyser — APPROVED** [review]
Changes in my components does look good to me ;) Approved and THX (!)

**Comment by ManfredKellermann** [comment]
Is there any chance that the remaining 7 code changes will become part of version 5.3.17 (assClozeTestGUI and ilObjectListGUI are already done in 5.3.16)?
Thanks and regards
Manfred

**Comment by alex40724** [comment]
@smeyer-ilias Could you please check the changes in ilCopyWizardOptions. Thanks.

**Pull request closed without merging**
