### PR TITLE
Test Bugfix #0041637: Course Certificates aren't issued in the language of the receiving user in any case (month names)

### PR DESCRIPTION
**Pull request by fhelfer**
references and depends on merge of https://github.com/ILIAS-eLearning/ILIAS/pull/7758

### CODE REVIEW

**Comment by dsstrassner** [comment]
hi @mjansenDatabay, I assume we wait for #7759?

**Comment by mjansenDatabay** [comment]
@dsstrassner Yes, all these PRs depend on #7759

**Comment by mjansenDatabay** [comment]
All relevant/ref. PRs have been merged, so this can be merged as well (after @fhelfer resolved the conflict here).

**Comment by dsstrassner** [comment]
@kergomard will you be so kind.

**Comment by kergomard** [comment]
Thank you very much for the PR @fhelfer 

Could you please remove the [`use ilObjUser`](https://github.com/ILIAS-eLearning/ILIAS/pull/7764/files#diff-8d41a0eb00eb0480cba96318ee40459ad3c0894bdd72a83545ff94bd695c2821R23) and fix the test, I will then merge.

Thanks and best,
@kergomard

**Comment by fhelfer** [comment]
> Thank you very much for the PR @fhelfer
> 
> Could you please remove the [`use ilObjUser`](https://github.com/ILIAS-eLearning/ILIAS/pull/7764/files#diff-8d41a0eb00eb0480cba96318ee40459ad3c0894bdd72a83545ff94bd695c2821R23) and fix the test, I will then merge.
> 
> Thanks and best, @kergomard

Done

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

**Pull request merged**
