### PR TITLE
LS/Membership: configure mail-notifications in administration (fixes 26294)

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=26294

### CODE REVIEW

**Comment by klees** [comment]
@nhaagen Could you please update the lang-files?

**Review by klees — APPROVED** [review]
LGTM

**Comment by klees** [comment]
@alex40724 Could you please have a look here? Is this how it supposed to be done?

**Review by alex40724 — APPROVED** [review]
Changes in Services/Adminstration are ok to me. @smeyer-ilias did the course/group notification thing afaik.

**Review by smeyer-ilias — APPROVED** [review]
LGTM

**Comment by klees** [comment]
@nhaagen Please rebase this again. Sry....

**Pull request merged**
