### PR TITLE
Bugfix/release 8/ta/35306

### PR DESCRIPTION
**Pull request by mBeym**
Mantis ticket: https://mantis.ilias.de/view.php?id=35306
Fixes issues in the test question `Content for Recapitulation` by merging changes made by @nhaagen in the `trunk` branch.

### CODE REVIEW

**Comment by kergomard** [comment]
@mBeym : Thank you very much for your PR. But I will close it, as these changes where only ment for trunk. See: 
https://github.com/ILIAS-eLearning/ILIAS/pull/4587#issuecomment-1134581824
Please feel free, to reopen, if you see this differently.

**Comment by mBeym** [comment]
@kergomard I'll change the pull request to only fix the issue from the ticket. It looks like I can't reopen the pull request though

**Comment by mBeym** [comment]
@kergomard Fixed. Please review again :)

**Comment by kergomard** [comment]
Thank you very much @mBeym and sorry to keep you waiting!

One quick question:

- We are sure we don't need [this](https://github.com/ILIAS-eLearning/ILIAS/pull/5195/files#diff-4b4aef42f36e91bcdb2b976ad60cd259d8529fe8eee217a86faa364022d27b6dL1926) `ilRTE::_replaceMediaObjectImageSrc($row["value"], 1)`, right?

Thanks and best,
@kergomard

**Comment by mBeym** [comment]
@kergomard Good catch.

I added it back :)

**Comment by kergomard** [comment]
Thank you @mBeym !

**Pull request merged**
