### PR TITLE
Setup: Tree trunk_30847 add tree to setup

### PR DESCRIPTION
**Pull request by daniwe4**
- ensure tree is in environment during setup

### CODE REVIEW

**Review by klees — COMMENTED** [review]
Hi @daniwe4,

LGTM, thanks for looking into this. I don't think we actually need the agent, though, because I just doesn't do anything. The objective could be used by other objectives as a precondition, no agent needed. Please delete it.

Thanks!

**Comment by klees** [comment]
Hi @smeyer-ilias,

I assigned this to you as the maintainer of `Services/Tree`. We found that some migrations or objectives will need a tree to work correctly, so we propose to add this objective to the service to make that dependency expressible.

Best regards!

**Comment by chfsx** [comment]
Hi @smeyer-ilias 

this came up again in our last TB meeting on the 19-10-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process? 

Best regards!

**Comment by daniwe4** [comment]
SetupAgent is deleted.

**Review by klees — APPROVED** [review]

**Comment by chfsx** [comment]
Hi @smeyer-ilias 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by klees** [comment]
@smeyer-ilias This would be extremely helpful to move the code in `Services/Migration` to `Objectives` as agreed upon in the PHP8-Working-Group. Could you look into this soon? Is there anything we can do to accelerate this?

**Comment by mjansenDatabay** [comment]
Hi @smeyer-ilias 

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by Amstutz** [comment]
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

**Comment by kergomard** [comment]
Dear @smeyer-ilias 
While checking on old open PRs in the frame of our Technical Board Meeting we stumbled over this one that is getting a little long in the tooth. Could you please either close it with an explanation, give feedback or ask @daniwe4  to resolve the conflicts and merge? Thank you very much!
@kergomard in the name of the TB

**Comment by chfsx** [comment]
Hi @smeyer-ilias 

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the ressources to look into it in detail.

Best regards!

**Comment by alex40724** [comment]
We understand the requirement to have the tree available in the setup, but we close this PR.

The major issue are the many workarounds in the initEnvironment function. E.g. the logger availability might just be a separate objective. In general the ilTree class should have a proper dependency injection for all the things that are added via DIC here. It is quite hard to estimate if all these workarounds really work properly, e.g. the user object, or if not something crucial is missing.

We are hoping to find a new maintainer for the tree component that finds the time to take care of this properly in the near future.

**Pull request closed without merging**
