### PR TITLE
Fix/25040/trunk/fix/dicto

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=25040

### CODE REVIEW

**Comment by ghost** [comment]
I can't say, if the dicto rule is crorrect, bacause I had newer used the ILIAS Dicto. At least, if I run ILIAS Dicto, it gives no violation, if I add an foreignObject tag again in a svg file, but it should

**Comment by klees** [comment]
Hi @sragfw,

if this gives no violation when you add the tag this is bad and the rule does not work as intended =)

Try:
```
SVGFiles = Files with name:".*[.]svg"
```
If I remember correctly, dicto adds the delimiters for start and end itself: https://github.com/lechimp-p/dicto.php/blob/master/src/Regexp.php#L52

Also `.` is everything, but you are expecting a real dot `[.]` as delimiter in front of svg.

Hope this helps, feel free to come ping me if you have further questions.

Best regards!

**Comment by klees** [comment]
Yeah, this looks better. Did it do the trick?

**Comment by ghost** [comment]
@klees
Thanks for the hint regarding `.` , it was a fault of me.
But even if `.svg` files will not be ignored in `config.yaml`, unfortunately it not works

**Comment by ghost** [comment]
@klees 
Is this also correct `SVGFiles cannot contain text: "<foreignObject"`?

**Comment by klees** [comment]
Looks fine to me. This basically the same as `IliasTemplateFiles cannot contain text: "<script"`. Did you check if this does actually find script-tags in templates? Does dicto actually index the files you want to be checked?

**Comment by ghost** [comment]
No, `IliasTemplateFiles cannot contain text: "<script"` works also not.
Yes, the svg and the html file were indexed

**Comment by ghost** [comment]
...
NOTICE: Running analysis...
INFO: checking: WholeIliasCodebase cannot invoke TriggerError
INFO: checking: WholeIliasCodebase cannot invoke ExitOrDie
INFO: checking: WholeIliasCodebase cannot invoke SetErrorOrExceptionHandler
INFO: checking: WholeIliasCodebase cannot invoke Eval
INFO: checking: WholeIliasCodebase cannot depend on ErrorSuppressor
INFO: checking: GUIClasses cannot depend on IlDB
INFO: checking: only GUIClasses can depend on IlTabs
INFO: checking: only GUIClasses can depend on IlTemplate
INFO: checking: WholeIliasCodebase cannot invoke RaiseError
INFO: checking: IliasTemplateFiles cannot contain text "<script"
INFO: checking: IliasTemplateFiles cannot contain text "javascript\s*:"
INFO: checking: IliasTemplateFiles cannot contain text "on(blur|change|click|dblclick|focus|keydown|keypress|keyup|load|mousemove|mouseup|mousedown|mouseenter|mouseleave|mouseout|mouseover|mousewheel|resize|select|submit|unload|wheel|scroll)"
INFO: checking: WholeIliasCodebaseExceptInitialisation cannot depend on GlobalsExceptDIC
INFO: checking: WholeIliasCodebase cannot depend on IsDependencyAvailableMethod
INFO: checking: WholeIliasCodebase cannot depend on GetMessageHTML
INFO: checking: WholeIliasCodebaseExceptIlUtil cannot depend on SetOnScreenMessage
INFO: checking: WholeIliasCodebase cannot depend on GetSystemMessageHTML
INFO: checking: WholeIliasCodebase cannot depend on GetSpecial
INFO: checking: SVGFiles cannot contain text "<foreignObject"
NOTICE: Analysis took 2.2730319499969 seconds to run.
execution time:    32.535182952881s
peak memory usage: 50.581.304 byte

**Comment by ghost** [comment]
...
INFO: indexing: templates/default/images/icon_crs.svg
...
INFO: indexing: templates/default/tpl.error.html
...

**Comment by ghost** [comment]
I add `<script>alert("test");</script>` to `templates/default/tpl.error.html`

**Comment by ghost** [comment]
I add `<foreignObject></foreignObject>` to `templates/default/images/icon_crs.svg`

**Comment by klees** [comment]
Hi @sragfw,

I checked out the "script"-rule yesterday and it works like intended. Is it possible that you just ran `dicto analyze` without creating a report afterwards? `analyze` just runs the analysis and puts the result in the database defined in the config-file. You need to create reports from that data to see the violations.

You might want to add a report as such to your config:
```
name: "total"
class: "TotalPerRule"
target: "php://stdout"
config:
template: "total_per_rule"
source_url: "https://github.com/ILIAS-eLearning/ILIAS/blob/{COMMIT}/{FILE}#L{LINE}"
```
and temporarily remove all rules your are not interested in from your rule file. Then you could `dicto report total $config_file` to see a list of all existing violations of your rules.

Does this help? If not: feel free to get back to me, maybe contact me via skype if you like.

Best regards!

**Comment by ghost** [comment]
@klees 
Thanks, now it works like desired, after I ran the `report` command :)

**Comment by matthiaskunkel** [comment]
Jour Fixe, 07 MAY 2019 : We highly appreciate this PR and accept it for currently maintained versions and trunk.

**Pull request merged**
