### PR TITLE
Advanced Metadata: Search patch

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This patch was implemented by @jluetzen-ilias in a customer's project. I was asked to create a pull request for these changes because there are plugins (CourseSearch, written bei Leifos) which rely on this patch.

This should be also applied for 5.2.x and 5.1.x

### CODE REVIEW

**Comment by klees** [comment]
Hi @mjansenDatabay, is there a ticket that is solved by this PR? Or is this an improvement? Or neither a bug nor an improvement.

**Comment by mjansenDatabay** [comment]
It is an improvement of the current "API" (only optional parameters being introduced/handled) of this service to let plugins use it for the purpose of searching objects.

The code was developed by Leifos and targets a Leifos maintenance. I was asked by Norbert to create this PR.

**Comment by alex40724** [comment]
I think Stefan should judge on this (as metadata maintainer). But the introduction of new parameters (even if they are optional) is not a pure refactoring or performance improvement. It adds new functionality, right?

**Comment by mjansenDatabay** [comment]
@alex40724 Yes, @jluetzen-ilias used this patch to prevent the rendering of form section headers and to exclude certain items (passed as a whitelist).

This does not change the current core behaviour, but enables plugins to use the service.

**Comment by nbromberger** [comment]
I highly appreciate this little adaptation. It is up to you to decide.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 04 DEC 2017: Stefan will have a look at the PR and merge it to trunk or close it according to his analysis.

**Comment by smeyer-ilias** [comment]
Yes, this PR does not break the current core behaviour, but it changes the method searchSubObjects which now returns objects or subobjects depending on the input parameters. I would prefer different methods for these cases.

**Pull request closed without merging**
