### PR TITLE
Docs: Accessibility Process

### PR DESCRIPTION
**Pull request by klees**
Hello everyone!

We hereby like to propose this document describing an accessibility process for the development of ILIAS. The current version is based on work done by @Amstutz and me in our capacity as UI coordinators. This basis has been improved and specified a lot by the SIG Accessibility, before it finally was brought to the attention of the Technical Board. Thanks a lot for the effort that the SIG put into the document and processes.

This version was revised by the Technical Board and adjusted to various other improvements of our processes, such as the expert groups.

We want to discuss and approve this paper on the JF soon and are looking for feedback. Feel free to comment here, to [write an email](mailto:tb@lists.ilias.de) or to voice your opinion on the next JF.

Best regards!

### CODE REVIEW

**Comment by atoedt** [comment]
Hello, please note that the SIG did not have time to deliberate this PR, yet. It would be much apprectiated if an "Accessibility section" would be adopted to the feature requests for ILIAS 8. 
kind regards 

Alexandra

**Comment by matthiaskunkel** [comment]
Jour Fixe, 22 FEB 2021: Richard and Timon ask for feedback and comments to this PR. It should be discussed and decided on the next Jour Fixe.

**Comment by atoedt** [comment]
Please postpone the Jour Fixe discussion until the SIG Accessibility had the opportunity to discuss in a meeting. Last meeting we did not manage to process all our agenda items and did not discuss the suggestion. 
We will discuss this suggestion on March, 17.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 MAR 2021: Following the request of the SIG Accessibility to postpone the discussion until the SIG had a chance to discuss this suggestion, we schedule the discussion now to 22 MAR 2021.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 22 MAR 2021 : Because the SIG Accessibility hadn't the time for a final discussion of this PR, we postpone the decision to the next JF at 19 APR 2021 for the last time. Please add all alternative suggestions to this PR in time so we can all be prepared for the JF discussion then.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 19 APR 2021: We highly appreciate this suggestion and accept the PR for ILIAS 8 / trunk. According to the process documentation we will extend the FW template and add a section for Accessibility. This will also be done for all FW requests for 8 that will be presented for decision for the next JF. 
This is a first version of the process documentation. Please help us to make it even better by providing related PR.

**Comment by Amstutz** [comment]
As decided in the JF yesterday, the TB merged this today. Thx to everybody involved in the discussion. Further proposals for changes are welcome to be handed in as PR to trunk.

**Pull request merged**
