### PR TITLE
Test: Add certificate indicator/link

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=37056

If approved and picked to `release_8` and `trunk`, please add the missing type hints, return types and property type declarations.

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @mjansenDatabay?
What is the status of this PR? Is there anything to decide or to review?

**Comment by mjansenDatabay** [comment]
@dsstrassner This is currently "on hold", because the effort is quite high to implement the "_When should the user be allowed to see the download link?_"-part in a **right** way in container lists/tiles for many tests on one page. I already put this on out internal backlog. Of course we can decide to close this.

**Comment by kergomard** [comment]
Hi @mjansenDatabay  and @dsstrassner 
I found this when going through the old PRs for the TB. I would personally suggest to close this as it is still for ILIAS 7 and to reopen a new one for ILIAS 8 or above when you get around to it.

Thank you very much and best,
@kergomard

**Comment by dsstrassner** [comment]
I will be happy when a new PR for ILIAS 8 and then ILIAS 9 is released. Thanks for the reminder @kergomard.
Thanks for the effort @mjansenDatabay ;)

**Pull request closed without merging**
