### PR TITLE
Feature 5 1 web access checker redesign

### PR DESCRIPTION
**Pull request by michherren**
This pull request is for a last review of the Web-Access-Checker. Please do not merge -> there is a db-update-step which needs to be added before. This request will be merged on the 21.08.15.

### CODE REVIEW

**Comment by alex40724** [comment]
I had a look at the code, especially the changes in my components. What is still missing is a better way to make the media object code modular, but this is something I need to do in the future. Two general points:
- The WAC comes with a ilHTTP helper class. I think this should go either to a HTTP service or be renamed to ilWACHTTP, if it is not intended to be re-used.
- There is an access_denied.png which should be a svg. No idea what the mp4 is for...

But overall the code looks good to me, thanks!

**Comment by jluetzen-ilias** [comment]
-- sorry german only --

Der neue WAC unterstützt aktuell "nur" Workspace-Blogs und Portfolios.
Es fehlen aber Repository-Blogs und Portfolio-Templates (prtt).

Dies wurde beim alten WebAccessChecker (/sec/-Version) über die Methoden in ilFileSystemStorageWebAccessChecker abgebildet:
- ilBlogWebAccessChecker::isValidPath()
- ilPortfolioWebAccessChecker::isValidPath()
  überschreiben für Workspace-Blogs und Portfolios (prtf) die Grundfunktionalität aus der Basis-Klasse.

Wobei ich mir aktuell gar nicht sicher bin, ob es für Portfolio-Templates so bisher alles korrekt funktioniert hat...

**Comment by michherren** [comment]
thanks for the feedback. 

@alex40724 I will forward the feedback about the renaming and the png to fabian. I think the access-denied-video is there to send the browser the expected file-type. This might be important, when a video-player-page is already loaded and then the access-checker denies.

@jluetzen-ilias As far as I could check, this permissions should be covered through the new WAC

**Comment by alex40724** [comment]
Wow, now this is in the trunk and I get lots of bugs. I reviewed the code, but did anybody test the functionality or approve this? Or address Jörgs issues before putting into the trunk? Feature wiki says "not approved" an "no test cases"... Usually when you write test cases you do some basic checks if the functionality is not completeley broken.

**Pull request merged**
