### PR TITLE
Fix for 33852

### PR DESCRIPTION
**Pull request by rfalkenstein**
Hi @schmitz-ilias , this should solve https://mantis.ilias.de/view.php?id=33852. Please have a look at it and check if this needs to be merged in release_8 and trunk, too.

### CODE REVIEW

**Comment by schmitz-ilias** [comment]
Hi @rob0403 , I can't replicate the error locally, but your change looks good, thanks for fixing! This does not need to be merged to R8 and trunk.

**Comment by rfalkenstein** [comment]
Hi @schmitz-ilias , you can check on test7.ilias.de

**Comment by schmitz-ilias** [comment]
Finally figured out how to reproduce what is happening, and I can confirm that your fix indeed works, @rob0403 . Thanks! (But I don't have permission to merge.)

**Comment by Amstutz** [comment]
Again, I take the liberty to merge this, since this is Icon Change related. I hope this is fine. @schmitz-ilias can you provide the PRs for Trunk and 8 if necessary.

**Pull request merged**
