### PR TITLE
UI Tooltip

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR adds a `Tooltip` component to the UI framework.

This component has been (initially) created with the help of @colin-kiegel and @legionth during the `UI Framework Hands On` workshop (organized by @tfamula and @nhaagen) of the 31st ILIAS Development Conference in Cologne.

We suggest to add the following JS dependency to the ILIAS codebase: https://atomiks.github.io/tippyjs/

Furthermore we suggest to introduce [Yarn](https://yarnpkg.com) for JS dependency management. A `README.md` can be found [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1777/files#diff-316bdf48777d6b8c2162641b79ebb27d).

Rules/descriptions can be found [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1777/files#diff-0c3b34e8901a0a9c29aec05f17067584R843) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1777/files#diff-d68a47c6aa3e99367685b450b3730cd5R18). Feel free to contribute better descriptions/rules.

Finally, thx to my beloved wife for letting me contribute this/these piece(s) of code on `Good Friday` ❤️ 😄 🥚 🐰 

# Screenshots
Tooltip Example Screenshot
Tooltip Example Screenshot

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @mjansenDatabay 

Thanks a lot for the PR. Unfortunately I did not find the time to look over this an perform a review before the JF. I am sure we can discuss this during the next upcoming JF.

Greetings

**Comment by klees** [comment]
Hi @mjansenDatabay, just a quick ping: I started looking into this, but most probably won't finish today. I try to finish my review by thursday.

**Comment by klees** [comment]
Hi @mjansenDatabay (and collaborators)!

Thank you a lot for contributing to the UI-framework.

It's really nice to see a collaborative work here, so shout out as well to @colin-kiegel and @legionth. This looks very solid from a technical perspective, but I think we need to work a little on semantics.

Please answer the following questions:
- [x] Why did you introduce yarn? I suppose it's because bower cannot install tippy.js? I'm starting to get really confused about all this js-dependency-managers. Did you investigate if we could move the other js-dependencies to yarn as well?
- [x] Did you look into using `Popover` to implement the tooltip? Why did you decide to introduce the new dependency instead of just using the implementation of `Popover`? I think `Listing Popover` does just that to implement `Tag Input Field`.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly
why you prefer to do otherwise:
- [x] Change from `prompt` to `overlay` (or maybe something else) [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1777/files#diff-d68a47c6aa3e99367685b450b3730cd5R23). `Prompt` seems to be the wrong term here, since `Tool Tips` don't want any user input.
- [ ] Please structure the inside of the tooltip a bit more. This currently is restricted by a rule, but I wonder if we require additional components inside the tooltip at all. Why not just take a text? Or maybe a title, a text and a list of links?
- [x] Make `Tooltip` a child of popover. Consider just adding `Tooltip` there, instead of introduction `Standard Tooltip` which would suggest other forms of tooltips. 

Please implement the following changes:
- [x] Please remove "Standard Tooltips are used to display other components." in the purpose. I doubt that this is the real purpose, it's rather how tooltips are supposed to work. The next sentence ("Tooltips should give the users additional information about a displayed component.") is a lot better purpose imo.
- [x] Please remove that meta-info about `@package` and `@author` in the docstrings and the generic documentation from PHPStorm ([`Interface Standard`](https://github.com/ILIAS-eLearning/ILIAS/pull/1777/files#diff-6e64113e9561562bb0af49ce74cb76a0R8)) as well. We don't do this in the UI-framework (and I also doubt it adds any valuable information).
- [x] Rename "placement" to "position" to match the wording of the popovers.
- [x] Adjust the placement options for the tooltip to match those of the popovers. We feel that devs cannot really decide on a placement such as "top", "bottom", "left", "right" and decided to use "vertical", "horizontal" and "auto" instead. Have a look [here](https://github.com/ILIAS-eLearning/ILIAS/pull/454) about that discussion. 

I consider it important to work out the relationship to popovers a little more and most possibly merge the two. You added a rival to popovers (which is very nice!) to draw a line between them, but I think that distinction could well be made for a `Tooltip Popover` and a `Standard Popover`. I also feel like "popover" vs. "tooltip" is rather a wording issue than a real functional difference. "Popover" talks about the how, while "tooltip" is about the why. I think having both in a different hierarchy will confuse people in the long run, and it certainly spawned some of my questions in this review.

Feel free to contact me and @Amstutz to schedule a discussion in skype if you feel we need one.
 
Best regards!
@klees

**Comment by mjansenDatabay** [comment]
> Why did you introduce yarn? I suppose it's because bower cannot install tippy.js? I'm starting to get really confused about all this js-dependency-managers. Did you investigate if we could move the other js-dependencies to yarn as well?

Yes, I introduced `Yarn` because `bower` did not provide a usable package with built JS files (only `TypeScript`) for `tippy.js`. Furtheremore `bower` is **dead**, so I provided a complete `README.md` how JS dependencies could be managed via `Yarn`.
I did not investigate whether or not all current JS dependencies can be managed via `Yarn`.

**Comment by Amstutz** [comment]
@mjansenDatabay : I did perform a complete review yet, however, I agree with the most points @klees pointed out. However, as @alex40724 points out in: https://mantis.ilias.de/view.php?id=24359#c60893, you did that in some spare time without any funding. Your contribution is large and mostly perfectly fine, many thx. 

Would it be oke if we (Bern) take it from here and refine it to make the last steps? If so, I would close this PR and open a new one as soon as done (based on your branch). Obviously, if you still have some resources to continue here, we would applaude. I am afraid you can not earn more respect here, you've pretty much maxed out this attribute in the last few weeks ;-)

**Comment by mjansenDatabay** [comment]
@Amstutz : It would be OK if you take it from here and create a new PR based on my work.

Of course I could do some minor changes (PHPDocs, descriptions/rules, renaming of `Placement` to `Position`).
But I do not have the time (for discussions and implementation) to merge the complete code into (or with) the `Popover` component/concept.

**Comment by alex40724** [comment]
@mjansenDatabay: Thanks for the Yarn investigation, I also think we need to get rid of bower better sooner than later. Yarn is using the npm registry. Everything is already there except jquery-dragster (not sure if we still need this). Adding dependencies to git repos is also possible, see https://yarnpkg.com/lang/en/docs/cli/add/

**Comment by mjansenDatabay** [comment]
> Adjust the placement options for the tooltip to match those of the popovers. We feel that devs cannot really decide on a placement such as "top", "bottom", "left", "right" and decided to use "vertical", "horizontal" and "auto" instead. Have a look here about that discussion.

I just implemented a default 'auto' positioning for tooltips, similar to the `Popover` component. Nevertheless I kept the `top`/`left`/`right`/`bottom` options in favor of explicit `vertical` and `horizontal` positioning options (which are also **not** supported by `tippy.js`).

> Please structure the inside of the tooltip a bit more. This currently is restricted by a rule, but I wonder if we require additional components inside the tooltip at all. Why not just take a text? Or maybe a title, a text and a list of links?

In our opinion the `Tooltip` contents should not have a defined structure. For instance in contrast to the `Popover` it must not (in our opinion) have a title.
In most usage scenarios a `Tooltip` will only have text (a simple `string`?), often with some basic `HTML` markup. But do we really want to limit this by providing slots for e.g. a `List` rendered below the text? If you have a strong opinion or requirements here, we could of course implement these.

**Comment by mjansenDatabay** [comment]
I think all desired changes except a merge into the `Popover` component have been addressed with my latest commits (or comments).

One sentence why the `Tooltip` component is **not** a child or part of the `Popover` component, yet: You are right, merging these two components makes somehow sense. Had this been demanded/mentioned as a **hard requirement** (more clearly) during the `UI Framework Hands On` workshop, we would most probably have gone this way.  We were inspired by the segregation of `Tooltip` and `Popover` components in `Bootstrap 4`. As often, this is maybe not black/white or 1/0 thinking/deciding at the end.

**Comment by Amstutz** [comment]
@okaufman will finalise this an provide a new PR, thx for everybody involved so far.

**Comment by Amstutz** [comment]
Note, I put the Yarn vs. Bower, next step on the TB again, special thx also on your work there.

**Comment by Amstutz** [comment]
Note, as most probably have noticed, sadly, we (Uni Bern) never found the time to finish up to work here. If anybody is interested in performing a follow up and work in remaining details, feel free to do so. Note that we are currently much further advanced in the JS discussion, then a year ago. See: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/development/js . 

Feel free to contact @amstutz or @klees in case of questions.

**Pull request closed without merging**
