### PR TITLE
FILE: Fixed #23096

### PR DESCRIPTION
**Pull request by ralfzeit**
https://www.ilias.de/mantis/view.php?id=23096

Fixed bug with cyrillic filename

_______.pdf -> История.pdf

### CODE REVIEW

**Comment by klees** [comment]
Hi @ralfzeit, is there a ticket [in our bugtracker](https://mantis.ilias.de) for this issue?

**Comment by ralfzeit** [comment]
@klees, no

**Comment by Amstutz** [comment]
Hi @ralfzeit then please create one, since this is required for this PR to be handled and maybe merged as bugfix. See [contributing.md](https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-3/docs/documentation/contributing.md#rules-for-contributors):

> If your PR contains a bugfix please reference the number of the mantis ticket in the title 12345 - To many spaces, link the ticket in the description and label the ticket with bugfix. You may make one PR per affected branch.

**Comment by ralfzeit** [comment]
Hi @Amstutz. Thank you for help.

https://www.ilias.de/mantis/view.php?id=23096

**Comment by klees** [comment]
@ralfzeit Thx!

@alex40724 @chfsx I assigned you both since I'm not sure who is responsible for that code in `ilUtil` right now.

**Comment by chfsx** [comment]
Hi @ralfzeit 

We discussed your changes here and in #1065. Changing the behavior of `returnASCIIFileName()` is no solution since it should do what is says: returning a ASCII compatible filename. Therefore we close the two PRs and would like to move the discussion to the mantis-ticket until we see a solution for your issue.

best regards!

**Pull request closed without merging**
