### PR TITLE
Raise error after session logout

### PR DESCRIPTION
**Pull request by iszmais**
https://mantis.ilias.de/view.php?id=36185

This also provides messages for login and startuppages, even if a deleted session leads to them.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
The solution is similar to the one proposed by @kergomard for `release_7`, which I merged yesterday: https://github.com/ILIAS-eLearning/ILIAS/pull/4870 . In `release_8` (and above), the specific issue @kergomard fixed is not relevant  (anymore). But if there are still issues with the `MessageBox` elements on the login page, we should maybe implement this session based approach. It is still kinda ugly that we'll have to do it this way.

Please keep in mind that you'll have to involve @pascalseeland for the changes in `ilStartupGUI` (and also me as 2nd coordinator, which you already did :-)).

**Comment by iszmais** [comment]
@mjansenDatabay thx for the info!

i reverted my changes on the startupGUI @kergomard solutions should do the trick too.

Therefore this is still ready for merge, but the the desired result of the mantis ticket still awaits the cherry pick of #4870 into ILIAS 8 and trunk.

**Comment by iszmais** [comment]
UPDATE: Still awaits that fix https://github.com/ILIAS-eLearning/ILIAS/pull/4870 by @kergomard

**Comment by kergomard** [comment]
Sorry for the long wait: Cherry-pick for ILIAS8 is here: #5625

**Review by lscharmer — APPROVED** [review]

**Comment by iszmais** [comment]
@mjansenDatabay This is ready to merge if it gets your approval

**Comment by iszmais** [comment]
Im not sure why i not initialy did that but i changed the redirect to a static force login since thats seems the most reasonable process of that error.

Further i tested some other cases of expired/lost session with and without referers on their behaviour which all seem to work good now, except one case:
- When a session is deleted (e.g. when i remove cookies from my browser and reload) no Error message is shown due to the fact that the erro cant linked to any call without an proper identifier. Im not sure if this is solvable (if it is even a problem) but when thats the case this most likely has to be solved inside the startupGUI imo. 

@mjansenDatabay @lscharmer Please leave me a feedback if you disagree on any of that.

**Comment by mjansenDatabay** [comment]
The solution should be fine @iszmais

**Pull request merged**
