### PR TITLE
0021941: Failed test: globale Rolle mit "Visible und Read auf die Administration" anlegen und testen

### PR DESCRIPTION
**Pull request by bseglias**
https://www.ilias.de/mantis/view.php?id=21941

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, 05 FEB 2018: Please assign the related maintainers to the proposed code changes and give them the opportunity to check the PR. In general, we highly appreciate a bug fix for this problem.

**Comment by chfsx** [comment]
Hi all, as discussed during the last JF @bseglias search the files for the author-infos and I added them as reviewers. There are also files with author-infos for people no longer in the community.

**Comment by chfsx** [comment]
The PR brings bugfixes concerning this Testcase: http://testrail.ilias.de/index.php?/tests/view/24748

Especially: Removing Buttons and Action-Menues when the user only have read-access to the administration-node. This should be tackled in all tabs and subtabs of the nodes. Feel free to approve or reject your parts, we will remove the rejected parts from the PR of fix them if only small changes. Thanks a lot!

**Comment by chfsx** [comment]
@bseglias I opened a new PR for trunk here: #1180

**Pull request closed without merging**
