### PR TITLE
DI: use DIC in setup

### PR DESCRIPTION
**Pull request by klees**

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724,

please have a look.

Merci!

**Comment by alex40724** [comment]
I don't object this step in general, but would like to get some other opinions how we should proceed with the setup.

It would need a general refactoring and a "real" maintainer for the future, to me the setup is basically heritage from other developers. I think Fabian was interested, at least if he would be able to get some funding.

**Comment by klees** [comment]
Hi Alex,

i totally understand and agree. We would be interested in the Setup as well, but i'm sure Fabian and me will find a solution.

Regards!

**Comment by chfsx** [comment]
yes, we're both interested in refactoring the setup. maybe not before 5.3 but there will be a solution. for the current PR I think we have to go this way until there's a better solution

**Comment by mjansenDatabay** [comment]
@klees: Seems wo work fine (but I didn't test the changes in ./setup/sql/dbupdate.php).

**Comment by mjansenDatabay** [comment]
OK, I found one issue (I will soon provide the steps to reproduce):

Fatal Error: ilSettings object instantiated without DB initialisation.

Steps to Reproduce:
1. Login to setup
2. Click on "List of Clients"
3. Click on "Details"
4. Click on "List of Clients" again

**Comment by chfsx** [comment]
@mjansenDatabay Does this appear on the Client-list? I saw this issue before the DIC migration, after reloading the page it disappears (which is quite spooky)... this bug relates to the implementation of PDO into ilClient and i'll have a look at it

**Comment by mjansenDatabay** [comment]
@chfsx Yes, it appears on the client list.
@klees: This is not related to your changes. The error also occurs after I reverted your changes on my local installation.

**Comment by alex40724** [comment]
The ./setup/sql/dbupdate.php related changes are 10 year old update steps. I doubt that anyone will run them again.

**Pull request merged**
