### PR TITLE
App: Support PHP 8.3

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR adds the support for PHP 8.3 (and drops the PHP 8.1) for the next ILIAS major release (ILIAS 10) by ...

* ... modifying the installation documentation
* ... adjusting versions in our `composer.json` file (I upgaded the dependencies by using PHP 8.2 as the lower version)
* ... changing the configuration for our GitHub CI pipeline configuration files

Required and Supported Software ILIAS 10: https://docu.ilias.de/goto_docu_wiki_wpage_8125_1357.html

### CODE REVIEW

**Comment by alex40724** [comment]
@mjansenDatabay Thanks for trying. To bad that the deps don't support this yet.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 27 NOV 2023 : We highly appreciate this suggestion and accept the PR for trunk.

**Comment by kergomard** [comment]
Hi @mjansenDatabay 

This go stuck somewhere on the way, right? May I kindly ask you to either merge or close?

Thank you very much and best,
@kergomard in the name of the TB

**Comment by mjansenDatabay** [comment]
@kergomard I would like to wait until the new `composer.json` is provided by #7141

**Comment by kergomard** [comment]
You are right! Completely missed the connection, sorry!

**Comment by iszmais** [comment]
@kergomard @alex40724 ,

does one of you have interest in being a shepherd for this PR?

Otherwise one of my colleagues and myself would offer ourselves to take that responsibility, but of course we would appreciate external verification above that.

Greetings,
@iszmais

**Comment by matthiaskunkel** [comment]
Hello @iszmais ,
It might be the best way to get this PR quickly to trunk if you ask your colleagues. Stephan and Alexander seem to be too busy. We should not loose more time. Thanks!
Best regards, @matthiaskunkel

**Review by iszmais — APPROVED** [review]

**Comment by iszmais** [comment]
LGTM

as soon as @lscharmer approves i will merge this into trunk.

@mjansenDatabay This is just for trunk, right? Or are their some similar adaption for ILIAS 9 (and PHP 8.2),too?

Greetings,
@iszmais

**Comment by mjansenDatabay** [comment]
Yes, for `trunk` only ...

**Review by lscharmer — APPROVED** [review]
LGTM 👍🏿

**Pull request merged**
