### PR TITLE
T&A 41611: Fix regex for gaps in cloze questions in learning modules

### PR DESCRIPTION
**Pull request by malaja11**
https://mantis.ilias.de/view.php?id=41611

As suggested, I replaced the old regex with the one used for cloze questions in Tests.

cc @thojou

### CODE REVIEW

**Comment by dsstrassner** [comment]
Is also needed for ILIAS 8, according to the mantis report.

**Comment by thojou** [comment]
Hey @Uwe-Kohnle,

@malaja11's changes are in the Scorm2004 Module. Could you please check if we can adjust the regex as proposed?

Thanks so much!

**Comment by dsstrassner** [comment]
Hi @Uwe-Kohnle, any updates on this?

**Comment by dsstrassner** [comment]
Hi @Uwe-Kohnle, is there any chance, that you Merge or at least accept this PR until the next JourFixe on September 16th?

**Comment by dsstrassner** [comment]
@Uwe-Kohnle We will merge this end of the week. Okay?

**Comment by iljalukin** [comment]
Hi all, any news on this? Is there any issue, why this can't be merged?

**Comment by dsstrassner** [comment]
hi @malaja11 & @thojou maybe the conflicts could be quick resolved and afterwards the PR merged?

**Comment by malaja11** [comment]
Hi @dsstrassner I resolved the conflict

**Comment by thojou** [comment]
Hey @malaja11,

thanks for resolving the conflicts. I've finally merged the changes into release_9 and also cherry-picked them into release_10 and trunk.

Best,
@thojou

**Comment by thojou** [comment]
In Addition, i also cherry-picked the changes backwards to release_8.

**Comment by dsstrassner** [comment]
Thanks @malaja11 & @thojou!

**Pull request merged**
