### PR TITLE
UI: adjust status counter in metabar. (#37998)

### PR DESCRIPTION
**Pull request by lukastocker**
[Mantis Ticket 37998](https://mantis.ilias.de/view.php?id=37998)

### CODE REVIEW

**Comment by klees** [comment]
@catenglaender Does not feel right, pixel-based positioning... Please advise...

**Comment by lukastocker** [comment]
Hi @catenglaender ,
please review especially with https://github.com/ILIAS-eLearning/ILIAS/pull/6568 also in mind.

**Comment by lukastocker** [comment]
Hi @Amstutz ,

this PR - including the newly pushed changes - was discussed and tested live on my local instance with @catenglaender today.
As these changes also fixes the counter notification issues, the PR https://github.com/ILIAS-eLearning/ILIAS/pull/6568 can be closed.
You can merge these changes if you're also okay with this implementation.

Kind regards
Luka

**Review by catenglaender — COMMENTED** [review]
I like this new solution a lot. It's much more clear now that the font size controls the position of the badges and no further adjustment of the top and bottom pixel values is necessary.

**Comment by catenglaender** [comment]
I think this is good to go.
How do we proceed with these? @Amstutz, do you merge these tickets and pick them to trunk? Or what should the process be?

**Comment by Amstutz** [comment]
@catenglaender thx a lot for the feedback. Yes, I'll merge this, compile the CSS, and probably manually pick the changes to truck. If cherry-pick partly works, ill cherry-pick to keep @lukastocker as the contributor of this improvement...

**Pull request merged**
