### PR TITLE
Forum Bugfix #0036483: Latest articles links not working

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=36483

@mjansenDatabay There are other solutions maybe we can discuss this sometime

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Thx @fhelfer . The question is: Why does it work in ILIAS 7? Maybe changes should be applied to the news component, not to the forum. If it works in ILIAS 7 without this special news handling in the forum, I suspect the root of all evil is located in the news component.

**Comment by fhelfer** [comment]
@mjansen It seems to be because of ilCtrl getNextClass Changes,
https://github.com/ILIAS-eLearning/ILIAS/blob/cbce4a6a80e9c43359ebd35f702a15dd3ecb3ae7/Services/Object/classes/class.ilObjectGUI.php#L1449
this has to be `$this->ctrl->getNextClass($this)` in order to work as in ilias7

**Comment by mjansenDatabay** [comment]
If approved, this has to be picked to `release_8` as well.

**Comment by mjansenDatabay** [comment]
@kergomard Since this change affects `ilObjectGUI`, I added you as the assigne here. The issue seems to be caused by `ilCtrl` changes, most probably caused by the `ilCtrl` revision by @thibsy . Maybe Thibeau has an idea why the behaviour changed so that `$this` has to be passed in ILIAS >= 8.x.

**Comment by kergomard** [comment]
@thibsy : Yes, I would be very glad to have a second opinion on this, as I'm unsure if this can have side-effects. I will merge and cherry-pick thereafter.

**Comment by thibsy** [comment]
Hi @mjansenDatabay and @kergomard

Sorry it took a while, but I finally managed to look into this.

I looked into the behaviour of `ilCtrl::getHTML()` and recognized the issue to be an `ilCtrl` bug.
Hence I close this PR, but thanks for looking into it anyways.

Kind regards!

**Pull request closed without merging**
