### PR TITLE
NPM: Add MathJax

### PR DESCRIPTION
**Pull request by fneumann**
This PR adds `mathjax` as NPM dependency.

Usage:

- Page editor: text content
- Forum: thread, post, reply
- Survey: introductory message, final statement
- Test Questions: question text, feedback, hints
- Cloze Question: cloze text
- Kprim Question: answers
- Matching Question: terms, definitions
- SC Question: answers
- MC Question: answers
- Ordering Question: answers

Wrapped By:
- components/ILIAS/UI/resources/js/MathJax/mathjax.js 
if PR [Stramline LatexUsage](https://github.com/ILIAS-eLearning/ILIAS/pull/8256) is merged.

Reasoning:

See Feature Request [Streamline Latex Usage](https://docu.ilias.de/go/wiki/wpage_5614_1357)

MathJax is currently added as third-party software.  It is configured with a URL in the ILIAS administration. That allows ILIAS administrators to adapt their MathJax support, but they need the MathJax CDN or must maintain a local copy themselves. This makes it difficult to compare installations and reproduce errors in the ILIAS test installation. Updates in the case of security problems are the responsibility of local administrators. With MathJax as an npm dependency, this gets much more predictable.

Furthermore, ILIAS components that export HTML content can include MathJax in their exported archives instead of linking it from a CDN.

Maintenance:

MathJax is the de-facto standard for rendering LaTeX on web pages. It is supported by strong partners (IEEE, Elsevier). It is actively developed. In the last month, six pull requests have been merged.

Links:

NPM: https://www.npmjs.com/package/mathjax
GitHub: https://github.com/mathjax
Documentation: https://www.mathjax.org

### CODE REVIEW

**Comment by klees** [comment]
Hi @fneumann,

since this is in `Draft`-status, I assign you for the time being.

Kind regards!

**Comment by fneumann** [comment]
Hi @rklees,

I changed the status to "Open" and suggested it for discussion at the JF at 11.11.2024:
https://docu.ilias.de/go/dcl/5316/67_65_11760

Who should be the reviewer of it?

**Comment by mjansenDatabay** [comment]
> Hi @rklees,
> 
> I changed the status to "Open" and suggested it for discussion at the JF at 11.11.2024: https://docu.ilias.de/go/dcl/5316/67_65_11760
> 
> Who should be the reviewer of it?

No one, you just present this at the upcoming JourFixe.

**Comment by matthiaskunkel** [comment]
Is this a dependency of ILIAS 11 / trunk? Or is it still for 10?

**Comment by fneumann** [comment]
This is for 11 / trunk, since the feature that will use it will be discussed for 11.

**Comment by kergomard** [comment]
Hi Fred
Just to be sure: You need to update this PR to provide the changes against `package_new.js` to make sure that this change becomes part of ILIAS 11.

Thank you very much and best,
@kergomard

**Comment by fneumann** [comment]
Updated for ILIAS 11 by https://github.com/ILIAS-eLearning/ILIAS/pull/8615

**Pull request closed without merging**
