### PR TITLE
Setup: #41940, named objective to reset failed db-steps

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=41940

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM.

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

I didn't look close enough the first time. I think the `DELETE` statement will reset _all_ steps for a class that has failed steps. It should only reset the failed steps.

Since you're on this anyway: Please change the name of the objective to `resetFailedSteps`.

Thanks!

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Hi @chfsx,

as database code authority, would you please have a look into this. Ping me if this is ok for you. I can do cherry-picks then...

Thanks!

**Review by chfsx — APPROVED** [review]
This looks good to me as wenn, thanks a lot. I merge this to release_8 (squashed) and can pick it to the newer branches as well.

**Pull request merged**
