### PR TITLE
Fixed language log to lang service

### PR DESCRIPTION
**Pull request by smeyer-ilias**
This PR moves the language logging from the root logger to a  new lang-Service logger.

### CODE REVIEW

**Comment by smeyer-ilias** [comment]
Could also be merged to 5.4.

**Comment by mjansenDatabay** [comment]
@smeyer-ilias Maybe an ilCtrl reload step should be added here.

**Comment by fneumann** [comment]
@smeyer-ilias mjansen is right - a reload in the dbupdate would be needed to add the language services to the log_components. This must especially be included in the hotfixes if the fix is merged to 5.4.

All other changes are straightforward to me. You may merge them directly.

**Comment by Amstutz** [comment]
Hi @smeyer-ilias 

Any Update on this?

**Comment by Amstutz** [comment]
Hi @fneumann ,

Any hope that there will be a decision before the upcoming release?

Kindly, the TB

**Comment by mjansenDatabay** [comment]
@smeyer-ilias : Could you please add the missing database update step and merge this PR?

**Pull request merged**
