### PR TITLE
#24395 Recursive orgus staff view

### PR DESCRIPTION
**Pull request by dkloepfer**

### CODE REVIEW

**Comment by alex40724** [comment]
@mstuder Since this is quite old, could you provide some feedback, please?

**Comment by kergomard** [comment]
@mstuder: Sorry to bug you again with this, but we stumbled upon this PR in our biweekly TB meeting when we went through the old PRs. Could you please merge it or provide your objections?

**Comment by Amstutz** [comment]
@mstuder : Please provide some feedback to this PR. Note that you might reject this PR give some justification and close, ask for a feature request, ask for improvements or obviously also merge ;-)

**Comment by mjansenDatabay** [comment]
@mstuder Could you please provide any feedback here?

**Comment by alex40724** [comment]
@mstuder Could you please provide some feedback for this PR? Thanks.

**Comment by klees** [comment]
Send reminder to @mstuder today.

**Comment by kergomard** [comment]
@mstuder: Sorry to bug you again with this, but we stumbled upon this PR in our biweekly TB meeting when we went through the old PRs. And this one has had its one year anniversary quite a while back! Could you please merge it or provide your objections?

**Comment by mstuder** [comment]
two years later.... !!THANK YOU!! i reanabled the list with ilias 6. thank you very very much for contribution, sorry my late response:
https://github.com/ILIAS-eLearning/ILIAS/commit/2d1c242e910cd527b49524fe241515cf8f83d2df

best regards
martin

**Pull request closed without merging**
