### PR TITLE
Fix 28340: Highlighting Main Menu entries when they get focus

### PR DESCRIPTION
**Pull request by tfamula**
This should fix [28340](https://mantis.ilias.de/view.php?id=28340)
@alex40724 You are listed as an implicit maintainer for Main Menu beside @chfsx as first maintainer. Is it enough when you have a look at this?

### CODE REVIEW

**Comment by alex40724** [comment]
For me this is ok, but usually the first maintainer should check this.

@chfsx Is it ok if I merge this?

**Review by chfsx — APPROVED** [review]
@alex40724 I'm happy with this change in general, but there are a lot of (color-short-syntax) changes in delos. I have no big steaks in this and I think this comes from different less-versions we all are using. For me it's fine!

**Comment by Amstutz** [comment]
plz do not merge this. there 600+ changes in delos.css. Only provide the changes provided by the changes in less.

**Comment by tfamula** [comment]
Can somebody explain to me how to deal with the changes in `delos.css`? If I only consider the `delos.less` from Main Menu, the changes in the general `delos.css` would be missing, see [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2734/files#diff-b7e54a2a697227a83d63170b3971b007R12953). Wouldn't this be a problem?

**Comment by alex40724** [comment]
@Amstutz Why is this an issue now? This is done regularly be developers due to different less versions:

One way...
https://github.com/ILIAS-eLearning/ILIAS/commit/6b0df5cd07810f3a4ff9ebfcac738bd1a3e9cc7c#diff-b7e54a2a697227a83d63170b3971b007

And the other way...
https://github.com/ILIAS-eLearning/ILIAS/commit/47faaa23262fe25fb50ae3d4b402116877ea0490#diff-b7e54a2a697227a83d63170b3971b007

**Comment by Amstutz** [comment]
sry, that this slipped through while merging a PR. sry for that. Note, this is somewhat tends to be looked over when reviewing since it is minified, I know it happened in the past:
image

Thx for @chfsx for spotting it in this case.

However, don't you think this is a really big issue for all kind of scenarios that we should avoid? you could run into all kind of merge/cherry pick issues like this. I really try hard since quite some time to avoid exactly that. It is tedius since it really depends on the lessc version and I did end up selecting by line by line the ones I like to commit because I did not have to right lessc version at hand. 

So please answer, do you believe it to be an issue? Then please fix. If you observe a weak moment of mine committing css like that or of anybody else, please ask me or whoever to correct. IMO this is what collaboration is all about and why we perform such reviews. 

If you believe this to be oke, well I really am tired on investing much that much time in such consistency discussions, be my guest merge it. I can handle the few merge conflicts since I do not have that many branches.

**Comment by alex40724** [comment]
@Amstutz  I was just witnessing that this file went in both directions regulary, this is why I thought "it does not matter". I personally had never an issue with this up to now.

However, I consulted the less rules again and we have a clear rule for this "Shortforms MUST be used in less and CSS. E.g. `#efe`, instead of `#eeffee`. * Only use lowercase for color codes in less and CSS. E.g. `#efe`, instead of `#EFE`."

So this makes it clear for me, this change should not be committed. Is this something configurable in less (I did not find anything) or is this just "using the correct less version"?

@tfamula I think updating your less version should improve this.

**Comment by tfamula** [comment]
I updated the delos.css by using the latest version of less (3.11.2). There are still (other) changes beside the changes coming from delos.less in Main Menu. I think the reason for this is that the newest version of less was published yesterday and the current state should be up-to-date. IMO we should merge it like it is now.

**Comment by Amstutz** [comment]
Thanks for sharing the result of the latest less version. I am completely fine with using this as the new default. However, lets just do this in a seperate PR, so other devs can follow by reading the commit message, why the CSS switched again. Since I currently more or less maintain CSS in my role as second maintainer, I just did that (see my three commits linked above). So this should be fine for merging as soon as rebased. If not, ping me.

In general, I believe PRs should only contain changes, they announce by title/linked tickets and description to make changes traceable. I am perfectly aware, that I failed to do that in the past in several commits. However If we agree that this is a good pattern, then I look forward of being corrected myself in that matter in reviews in future.

**Comment by tfamula** [comment]
Thanks @Amstutz! I totally agree with your pattern. The digression in this PR was really useful for me because the question how to deal with these delos.css issues were concerning me for a longer time and I had not found an answer for it.

PR is ready for merging now!

**Comment by Amstutz** [comment]
@chfsx this is good for rebase and merge from my point of view. thx @tfamula .

**Comment by chfsx** [comment]
Thanks a lot to all of you

**Pull request merged**
