### PR TITLE
Chatroom (ILIAS 9): Remove private rooms

### PR DESCRIPTION
**Pull request by lscharmer**
This PR removes the private rooms for the chatroom.

Feature Wiki: https://docu.ilias.de/goto_docu_wiki_wpage_7333_1357.html

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@lscharmer Can you please remove all language filed related changes except for `de` and `en`?

**Comment by lscharmer** [comment]
@mjansenDatabay
> @lscharmer Can you please remove all language filed related changes except for `de` and `en`?

Why :o Who will translated them instead?

**Comment by lscharmer** [comment]
> @lscharmer Can you please remove all language filed related changes except for `de` and `en`?

@mjansenDatabay I removed them.

**Comment by mjansenDatabay** [comment]
Thx @lscharmer , could you please fix the conflicts?

**Review by mjansenDatabay — CHANGES_REQUESTED** [review]
Thx @lscharmer , could you please fix the conflicts?

**Comment by lscharmer** [comment]
@mjansenDatabay Yes

**Comment by lscharmer** [comment]
@mjansenDatabay Conflicts are resolved.

**Review by mjansenDatabay — APPROVED** [review]

**Pull request merged**
