### PR TITLE
UI: DataTable #37493, make action-ids optional

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=37493

ids for the actions are no longer mandatory

### CODE REVIEW

**Comment by klees** [comment]
Hi @nhaagen,

do we currently need that id for anything?

Best wishes!

**Comment by nhaagen** [comment]
No, the id is really optional. all strings are within the action itself, and there is no reference to the array key.

**Comment by klees** [comment]
Ok, so I guess we should drop them.

**Comment by tfamula** [comment]
@nhaagen When there is no action-id for an action, then `DataRow::withDisabledAction` will not work for this action, right? Because you have to pass the action-id as parameter here. Or did I understand something wrong?

**Comment by klees** [comment]
@tfamula This seems to be right. Currently we have only dropped the `$action_id` in the example and made it possible to use integer ids as well. So technically, your use case should still work. Don't know if we have improved regarding comprehensibility, though. Thanks for the hint!

**Pull request merged**
