### PR TITLE
[FIX] duplicate modal.js

### PR DESCRIPTION
**Pull request by chfsx**
@klees this is a proposal to solve the issue with two `\ILIAS\Component\Resource\ComponentJS` with target `assets/js/modal.js`

### CODE REVIEW

**Comment by chfsx** [comment]
I have not been able to change the calls to LegacyModal.js, because i can no longer distinguish between the new and old ones. but maybe you still have the status from before the changeover so that you can easily adapt it.

**Comment by klees** [comment]
Is there anything wrong with this? :thinking:

```
$ grep -r Modal.js .
./components/ILIAS/Test/classes/class.ilTestScoringByQuestionsGUI.php:        $this->tpl->addJavascript('assets/js/Modal.js');
./components/ILIAS/DataCollection/classes/class.ilObjDataCollectionGUI.php:        $this->tpl->addJavaScript("assets/js/Modal.js");
./components/ILIAS/OnScreenChat/classes/class.ilOnScreenChatGUI.php:            $page->addJavascript('assets/js/Modal.js');
./components/ILIAS/UIComponent/Explorer2/classes/class.ilExplorerSelectInputGUI.php:        $this->global_tpl->addJavascript("asserts/js/Modal.js");
./components/ILIAS/UIComponent/UIComponent.php:            new Component\Resource\ComponentJS($this, "Modal.js");
./components/ILIAS/UIComponent/Modal/classes/class.ilModalGUI.php:        $tpl->addJavaScript("assets/js/Modal.js");
```

**Comment by klees** [comment]
Merged as: https://github.com/ILIAS-eLearning/ILIAS/commit/aebb1b27993042d08b79c946d8ca6afb3be6b340

**Comment by klees** [comment]
Thanks!

**Pull request closed without merging**
