### PR TITLE
Memberships: Fix recipient selection for subscribers

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=28144

If approved, this should be cherry-picked/applied for `release_8` and `trunk` as well.

### CODE REVIEW

**Comment by dsstrassner** [comment]
@smeyer-ilias Could you please merge this fix before the Release of ILIAS 7.19?

If not, please state why not?

**Comment by dsstrassner** [comment]
Hello @smeyer-ilias!
Regrettably, this Bug fix didn't make it into Release 7.19. So, some ILIAS users in my institution are really unhappy. 

Could you please inform @mjansen and me, if there is anything wrong with the fix or the approach to resolving this old issue?

What could we do, that you merge this PR before the release of ILIAS 7.20?

**Comment by dsstrassner** [comment]
Dear JF, 
how do we proceed with this? 

I have contacted @smeyer and @fwolf before the Release of ILIAS 7.19, to merge this bug fix before the release. This does not happen. 

Questions, why this PR is not merged yet or if anything is wrong with the fix, are not answered. 

I kindly ask to merge this Pull Request to release_7 and apply also to release_8 and trunk.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 03 APR 2023: Stefan will have a look at the PR as soon as possible.

**Comment by smeyer-ilias** [comment]
Thanks @mjansenDatabay  for fixing this.

**Pull request merged**
