### PR TITLE
Scripts: Improve Test Discovery, Make them Run!

### PR DESCRIPTION
**Pull request by klees**
Hello everyone,

this simplifies the discovery of PHPUnit-tests and also makes all tests run again:

* You can simply put files that match `^[^.]+Test\.php$` into the `/tests`-folder of your component, the script will discover them automatically.
* If you want more control, you may use suites named `^[^.]+Suite\.php$`, also within your `/tests`-folder.

I'm still looking for a good place to document this, docs/development/unit-test-usage.md might be a good place, but I did not find a good location until now. If someone nows of another place, feel free to propose it.

While implementing this I discovered a lot of paths that depended on the CWD and made them relative to the file they are used in.

I will leave this open for recognition and inspection until tomorrow in the afternoon, and merge then. The stuff is editorial imo. If any maintainer wants to have a longer look please ping me until then.

Thanks!

### CODE REVIEW

**Comment by klees** [comment]
Ping @chfsx, @mjansenDatabay, @Amstutz, @dsstrassner, @kergomard

**Comment by kergomard** [comment]
Thank you very much @klees for the improvement and the heads up! LGTM.

**Review by chfsx — APPROVED** [review]
Thanks a lot!

**Review by mjansenDatabay — APPROVED** [review]
Thx a lot @klees !

**Pull request merged**
