### PR TITLE
Templating: local cache for file content

### PR DESCRIPTION
**Pull request by shecken**
We would like to introduce a local cache for loaded file contents. Ambition is to speed up the template engine.

### CODE REVIEW

**Comment by klees** [comment]
This would be great to speed up the templating, especially in the case where a template is used multiple times. This will be the case more often, when the new UI framework is used.

**Comment by Amstutz** [comment]
I like this request and agree with richard, that the I/O operations tremendously slow down the work of the template engine if the same template is used multiple times.

**Comment by chfsx** [comment]
TemplateEngine is still one of the top classes when profiling. every small improvement is welcomed! +1

**Comment by Amstutz** [comment]
@alex40724 can this be merged?

**Comment by alex40724** [comment]
@Amstutz I think we agreed that #245 would be even better, but the discussion is still open there.

**Comment by alex40724** [comment]
I close this, please leave your comments in #245

**Pull request closed without merging**
