### PR TITLE
RBAC: Fix Access to Unsubscribe

### PR DESCRIPTION
**Pull request by kergomard**
This is a fix for: https://mantis.ilias.de/view.php?id=32243

There is a very small change in `ilObjCourseGUI` [here](https://github.com/ILIAS-eLearning/ILIAS/compare/release_7...kergomard:7/rbac/fix_32243?expand=1#diff-8da1c98f27b56173df010d944f536db9c9cacf72703bd9de2403efb1a0904c23R2711). Sorry for the many changes in `ilObjCourseGUI`, but they are necessary for the checks to pass.

@schmitz-ilias :  I added you as reviewer, too, as you reacted in the Mantis-Issue. I would just expect one of you two to review and assume that you coordinated internally.

Thank you very much and best,
@kergomard

### CODE REVIEW

**Comment by kergomard** [comment]
Hi @smeyer-ilias and @schmitz-ilias 
Any chance to get a feedback here until the end of the week, latest?
There is just one line changed concerning you: https://github.com/ILIAS-eLearning/ILIAS/pull/6514/files#diff-8da1c98f27b56173df010d944f536db9c9cacf72703bd9de2403efb1a0904c23R2711

Thank you very much and best,
@kergomard

**Comment by smeyer-ilias** [comment]
Hi @kergomard, as mentioned yesterday: due to vacation I've had no time to review this PR. I will check the issue during next week.

**Comment by kergomard** [comment]
Hi @smeyer-ilias 

The last week has come and gone. Please provide a feedback until Friday latest, thanks.

Best,
@kergomard

**Review by smeyer-ilias — APPROVED** [review]
Thanks for fixing this. 
In combination with the AccessControl changes, this fixes the issue.

**Comment by kergomard** [comment]
Thank you very much for the feedback @smeyer-ilias ! I merge and pick to ILIAS 8, ILIAS 9, and trunk.

**Pull request merged**
