### PR TITLE
Travis CI: Add PHP 7.4 snapshot to build matrix

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR will add the PHP 7.4 snapshot to our Travis CI build matrix.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
So beside the PHP 7.4 deprecations reported (and already fixed with #2106, #2105, #2103) in our code base, there are ugly deprecation issues with the current versions of the following composer dependencies:

* Mockery
* PHPUnit

**Review by gvollbach — APPROVED** [review]
@mjansenDatabay 
Looks fine to me, but before we merge this we should at least get rid of the errors.

**Comment by mjansenDatabay** [comment]
27 AUG 2019: According to TB decision, this PR should be merged after #2106, #2105, #2103 have been merged.

**Comment by mjansenDatabay** [comment]
Current State:

- Waiting for a new composer package of https://packagist.org/packages/ezyang/htmlpurifier

**Comment by mjansenDatabay** [comment]
Current State:

- ezyang/htmlpurifier updated, only one (not related to this update) failing test left

**Comment by mjansenDatabay** [comment]
:shipit: Now we are ready for PHP 7.4 testing @ILIAS-eLearning/technical-board / @gvollbach

**Pull request merged**
