### PR TITLE
Remove duplicate Unicode lib (keeping the newer version + relocate)

### PR DESCRIPTION
**Pull request by colin-kiegel**
ok .. this looks a bit like a mess, but what I did is simple:

There were two unicode libraries present (almost identical)
- Modules/Wiki/mediawiki/normal (new version)
- include/Unicode

I moved the new version of mediawiki to include/Unicode and changed all references to point to the new location. Again to avoid classname collisions.

### CODE REVIEW

**Comment by alex40724** [comment]
But this results in patching the (old) mediawiki code, which we should not do. This code should be untouched and being kept local. Especially creating a dependency from third party code into our own code seems to be a bad idea.

**Comment by colin-kiegel** [comment]
Ok, I understand. The problem is that both files define a class with identical name. That will definitely be a problem if both files are included within the same request. Luckily that does not seem to happen so far. But it is definitely an issue when switching to autoloading of classes (the autoloader will have no means to determine which version to include).

My intention is to remove all ambiguous class definitions within the complete codebase of ILIAS, general options are:
- namespaces: seems difficult to introduce (there are conversion scripts around)
- renaming: should be less invasive
- removing/merging duplicates: whenever possible seems to be the best option

As a last resort, it might be possible to somehow _completely exclude_ some classes from autoloading and to rely on manual include. But that would not be very satisfying... Do we have good alternatives in this case? Upgrading the mediawiki code? Why not using the Unicode-lib from mediawiki?

If you could point me in the right direction I will try to update this PR accordingly. :-)

**Comment by alex40724** [comment]
I am not sure what you are up to. There has been no decision of using any auto loading concept in ILIAS yet, and if so, we may end up with something like PSR-4. Or do you intend to load a full class map with every request? Or looking paths up for each one? This should be discussed in the JF and refactoring should be based on JF decisions...

**Comment by colin-kiegel** [comment]
When you search for "optimized autoloader" you get results telling to use classmaps instead of pure PSR-0/4. classmaps are also the quickest approach to introduce autoloading - because they don't require PSR-0/4. You can still implement PSR-0/4 _and_ use classmaps.

Autoloading is on the agenda for 5.1 http://www.ilias.de/docu/goto_docu_wiki_wpage_3520_1357.html

While writing this Feature Wiki Article I also made an analysis which parts of ILIAS need to be changed to make it work. These pull requests are in fact part of this feature wiki ticket (I did not mention it - sorry). But some of these pull requests should be relevant even without the goal to use autoloading. I agree, that this specific PR is not an easy one.

**Comment by alex40724** [comment]
I personally would like to have a decision on this PR. I will put it on the JF agenda. Either we move forward with autoloading, or we decide to patch the mediawiki code or we just close the PR.

**Comment by chfsx** [comment]
hi @alex40724, any news on this one?

**Comment by alex40724** [comment]
Yes, we will patch the mediawiki code with 5.2 as part of the PHP7 efforts. I keep it open until I we are done with it.

**Comment by matthiaskunkel** [comment]
Postponed to next Jour Fixe when Alex will participate again.

**Comment by alex40724** [comment]
updated pr and merged to trunk

**Pull request merged**
