### PR TITLE
Server-Side MathJax Rendering

### PR DESCRIPTION
**Pull request by fneumann**
Server-Side MathJax Rendering
see http://www.ilias.de/docu/goto.php?target=wiki_1357_Server-Side_MathJax_Rendering

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
A great step forward, esp. for the PDF generation and HTML exports.

**Comment by alex40724** [comment]
I approve all the changes in my and Jörgs components. However in my opinion the main implementation should be moved out of the "Utilities" directory into a proper subdirectory and build a new service with a responsible maintainer.

**Comment by bheyser** [comment]
Green Light for my Components

**Comment by jluetzen-ilias** [comment]
This has already been committed separately yesterday?
https://github.com/ILIAS-eLearning/ILIAS/commit/d11e7e6a78cdd178a344c9cf891222cea3965dda

**Comment by alex40724** [comment]
I guess this PR just can be closed.

**Comment by matthiaskunkel** [comment]
Hello Fred, I guess you can close this PR because you already committed the code.

**Comment by fneumann** [comment]
Oh yes, it's already committed.

**Pull request closed without merging**
