### PR TITLE
Object: Fix Copying from Search

### PR DESCRIPTION
**Pull request by kergomard**
See: https://mantis.ilias.de/view.php?id=37364

Part of this is also necessary for ILIAS 7 as it breaks there, too.

### CODE REVIEW

**Comment by kergomard** [comment]
I assign you @alex40724 as you answered in the Mantis-Issue

**Comment by kergomard** [comment]
hHi @alex40724 and @smeyer-ilias 
Could one of you maybe have a look at this so I can close the corresponding issue soon.
Thank you very much and best,
@kergomard

**Review by alex40724 — APPROVED** [review]
Thanks. This can be merged.

**Comment by kergomard** [comment]
Thank you very much for the feedback @alex40724 . Then I merge.

**Pull request merged**
