### PR TITLE
Feature/6.0/ui datatables

### PR DESCRIPTION
**Pull request by mstuder**
With this pull request we like to discuss and introduce a new kitchen sink element Data Table:
https://docu.ilias.de/goto_docu_wiki_wpage_5938_1357.html

### CODE REVIEW

**Comment by klees** [comment]
Hi @mstuder,

is this urgent? Neither I nor Timon will be able to review this until the next JF on monday.

Best regards!

**Comment by mstuder** [comment]
Hi @klees 

Thx for your prompt reaction!! No it's not urgent. Sorry for the jf label. Take your time.

Best regards
Martin

**Comment by mstuder** [comment]
@klees / @Amstutz 
Please let us know if we should reduce the pullrequest, so that only the intrefaces can be seen and in a first step we only discuss the interfaces.

**Comment by klees** [comment]
Hi @mstuder!

Thank's for tackling this extremly hard problem!

First and foremost: This PR is extremely hard to understand and review. It is big and is missing descriptions and explanations completely. You seem to introduce a lot of new concepts (`DataFetcher`, `Formater`, `Format`, ...) without any explanation, neither in the description of the PR, nor inline in the code. Please take some time to at least describe what is what and how things relate to each other in cases like this in the future. It took me some time to figure that stuff out. There is a huge ROI on good explanations in PRs. You already understand the concepts and write down explanations once, while every reviewer needs to understand them again when explanations are not provided.

From what I think I understood, some approaches you use here are different from all other UI-components (e.g. have a consumer facing `Formater` that is supposed to return strings) and are also different from the sibling of the `Data Table`, the `Presentation Table` (e.g. in the handling of view controls). This might all well be justified, but again, it is hard to understand why, because explanations are missing.

From what I understand currently, this PR is a good base for a further discussion, but not ready to be introduced to the trunk. I hope this will become clear when you look into my questions, suggestions and change requests. The areas where this needs to be improved that I already see are:

* the `Formatter`/the export to formats other then HTML
* interface to the component, especially in comparison to the `Presentation Table` as well as to other UI components
* relation to the `Filter` UI component

On the other hand, there seems to be stuff in here, that to me points in good direction:

* definition of the shape of the table via columns
* introduction of a facility to fetch data (instead of using arrays)

This all means, that this is not some complete review where you just need to tick the boxes to pass, but instead is my stance on how I currently see your proposal and a definite invitation to a further discussion.

Please answer the following questions:
- [ ] As far as I remember, we agreed to use the same pattern as for the `Presentation Table`, i.e. setting a closure that creates a row from some data and passing the data separately. This looks rather different. Why is that? We could of course improve on that pattern, as we already agreed upon, e.g. by using some facility that fetches data instead of just passing some records (as we discussed and you proposed here). But we should try to maintain a similar interface to both tables as far as possible. Please point out which of the new concepts introduced here you feel should be applied to the `Presentation Table` as well and why you chose to not use others (as, e.g. the environment).
- [ ] What are these `Data` and `RowData` classes supposed to do? `Data` just looks like a glorified array, while I do not understand `RowData` at all atm.
- [ ] Why do the `Setting`s return a `Pagination` instead of using `withViewControls` like the Presentation Table does?
- [ ] How does this proposal relate to the new `Filter`s from the UI-framework?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] Do no attach the key of the columns to the `Column`s themselves, rather use keys from the array that contain the columns for that purpose. Currently nothing stops me from assigning the same key twice. A PHP-array already guarantees that every key is only used once. From a similar perspective, "default sort" seems to be property of the table, not an individual column.
- [ ] Use flags for the boolean properties of the columns, I would expect that to make the creation of tables a lot more readable when it comes to columns.

Please implement the following changes:
- [x] Remove `data.php` from the PR. It is created by the [artifact builder](https://github.com/ILIAS-eLearning/ILIAS/pull/2123) during `composer install`.
- [x] Move the language-variables to the "ui"-module.
- [ ] Add descriptions to your interfaces, classes and methods. I don't think that every method, interface or class needs a detailed description, but currently I see none. Since the datatable seems to introduce a lot of concepts currently unknown in the UI-framework, comments are important to understand what's supposed to do what. On the other hand, if your are able to typehint return-types or parameters, please do not duplicate that information as docstrings if you provide no additional information.
- [ ] Do not use `Container` as a dependency. `Container` basically could contain anything, i.e. this type hint does not add any valuable information. Depend on what you really require, e.g. `DefaultFormater` in `Column`.
- [ ] Add a factory-method for `Column`.
- [ ] Remove the `Formatter`. In the context of the UI-framework, `Renderer`s are supposed to translate UI-components to strings, currently I see no reason why we should introduce a new thingy that produces strings as well. On the other hand I am missing a conceptualisation of a row (and most probably cells as well) as UI components.
- [ ] We do not want to have static or global dependencies if not strictly required. You need to us `ilUtil` because somehow delivering PDF/CSV/XLSX-export should be solved by the UI-framework, also you use the DIC directly a lot. We need to find another solution here.

Currently I would not advise to take this proposal to the JF. Instead I would propose that we schedule a discussion on the areas pointed out above to improve on this proposal.  Currently I would hesitate to push this for ILIAS 6 but instead would propose to take it slow with this very important component to iron out the issues I pointed out. Most developers would not use this for 6 anyway (because they should already mostly completed coding).

Still I see this to be moving in the right direction and again thank you for your effort!

Best regards!
@klees

**Review by klees — CHANGES_REQUESTED** [review]
:point_up: :man_facepalming:

**Comment by klees** [comment]
Hi @mstuder and @Amstutz,

can we close this?

Best regards!

**Comment by klees** [comment]
Sry, fat finger...

**Comment by Amstutz** [comment]
Since there has been no feedback for several month and no invitation to any further discussion, we should close this IMO. New suggestions on how to proceed with tables are appreciated.

**Pull request closed without merging**
