### PR TITLE
Update composer.lock after release v8.1

### PR DESCRIPTION
**Pull request by fwolf-ilias**
Dear @ILIAS-eLearning/technical-board,
This PR updates all dependencies after release v8.1.

**Composer Notices:**
```
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/twig-configurable-i18n is abandoned, you should avoid using it. No replacement was suggested.
Package technosophos/libris is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
```

### CODE REVIEW

**Comment by fwolf-ilias** [comment]
Mh die checks laufen fehl, da stimmt noch irgendwas nicht. Ich schaue mir das morgen nochmal an.

**Comment by fwolf-ilias** [comment]
There is an issue with the newest PHPUnit  version 9.6.7, which triggers the warning below. So either this unit test should be fixed or phpunit's version has to be 8.*.

```
 1) ilObjUserPasswordTest::testExceptionIsRaisedIfPasswordManagerIsCreatedWithoutValidFactory
Expecting E_ERROR and E_USER_ERROR is deprecated and will no longer be possible in PHPUnit 10.
```

**Comment by mjansenDatabay** [comment]
@kergomard I'll provide: https://github.com/ILIAS-eLearning/ILIAS/pull/5888

**Comment by kergomard** [comment]
Thank you very much  @fwolf-ilias  and @mjansenDatabay ! I merge.

**Pull request merged**
