### PR TITLE
Make fillJS and fillCSS identical

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=23878

### CODE REVIEW

**Comment by ghost** [comment]
Sorry for the reformat of code

**Comment by ghost** [comment]
Changes was in 
- addJavaScript
- addCss
- addInlineCss
- fillJavaScriptFiles
- fillJavascriptFile
- fillCssFiles
- fillInlineCss
- resetJavascript
- resetCss

**Comment by alex40724** [comment]
I added @klees and @Amstutz to the list of reviewers, since they are currently leading the rewrite of ilTemplate which will be merged to trunk shortly.

**Comment by ghost** [comment]
OK
I will look what is still needed after the merge of refactoring of ilTemplate
Maybe it is aleready made

**Comment by klees** [comment]
Hi everybody, I did not change any functionality of `ilTemplate` that is required by anyone (at least I tried), so no, this would not be covered by the refactoring. However, this seems to make changes in a lot of places, so I would be glad if you not merge this before the ilTemplate-Refactoring, because the according PR most probably won't be mergeable afterwards.

**Comment by ghost** [comment]
I create a new PR after merge the refactoring of ilTemplate

**Pull request closed without merging**
