### PR TITLE
Fix mb37641: An error occurred while exporting the language file

### PR DESCRIPTION
**Pull request by c-knof**

### CODE REVIEW

**Comment by klees** [comment]
Hi @c-knof,

is there a mantis-ticket associated with this?

Kind regards!

**Comment by c-knof** [comment]
yes, it is: https://mantis.ilias.de/view.php?id=37641

**Comment by klees** [comment]
@c-knof Please [reference the mantis ticket](https://github.com/ILIAS-eLearning/ILIAS/blob/release_8/docs/development/contributing.md#rules-for-contributors) if you fix one. We'll set the according tag to the PR then. Thanks =)

**Comment by klees** [comment]
Now I see you did :sweat_smile:. Just didn't notice the abbreviation. I parse "mb" as "multibyte" :smile:

**Comment by dsstrassner** [comment]
> @c-knof Please [reference the mantis ticket](https://github.com/ILIAS-eLearning/ILIAS/blob/release_8/docs/development/contributing.md#rules-for-contributors) if you fix one. We'll set the according tag to the PR then. Thanks =)

Always good, to link the Issue in the first comment. This will help the Label-Setters ;-)

**Pull request merged**
