### PR TITLE
TA, 36269: write points for matchingPairs during question corrections

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=36269

### CODE REVIEW

**Comment by nicoroeser** [comment]
@nhaagen , out of curiosity: why do you create a clone and then replace the object with it? Couldn’t the pairs just be loaded into the _current_ object?

(I have not tested nor deeply thought about this, only skimmed your commit. Please forgive me if I am missing something.)

**Comment by nhaagen** [comment]
@nicoroeser , I did not see a method in assMatchingQuestion to actually _set_ a well configured pair.
There are methods to (newly) create them, based on information I would have to retrieve anyways. 
So, instead of taking the pairs apart and have them rebuild, I thought cloning and changing the relevant aspect the easier way.
Maybe, I'm also so used to do this due to repo-pattern stuff, that this is my standard approach ;)

**Comment by mbecker-databay** [comment]
> 

withFunctionalCreep(); 

...but the dude abides... or are there objections?

**Comment by kergomard** [comment]
No objections from my side.

**Pull request merged**
