### PR TITLE
Fix 28339: Change fixed alt text for Logo to language variable

### PR DESCRIPTION
**Pull request by tfamula**
This should fix [28339](https://mantis.ilias.de/view.php?id=28339)
@alex40724 I assign this to you because you are implicit maintainer of "Main Menu" and "Init". There is also a change in a template file of `LTI`. I don't understand the meaning of this template, because it looks more or less like a duplicate from `tpl.main_menu.html` in `MainMenu`. Do I have to assign @Uwe-Kohnle for this change, too?

### CODE REVIEW

**Comment by alex40724** [comment]
@Uwe-Kohnle @chfsx For me the changes are ok. Can I merge this?

**Review by chfsx — APPROVED** [review]
Yes, thanks a lot!

**Comment by tfamula** [comment]
I also added @smeyer-ilias as reviewer, because he is first maintainer of `Init`

**Review by smeyer-ilias — APPROVED** [review]
Thanks Thomas. 
LGTM. Please can you create a PR for release 6, too, since this needs changes in ilMainMenuGUI.php

**Comment by tfamula** [comment]
> Thanks Thomas.
> LGTM. Please can you create a PR for release 6, too, since this needs changes in ilMainMenuGUI.php

IMO, these changes are not needed for release 6 because the UI element "Standard Page" is used there. The logo is placed there as UI element "Image".

**Comment by alex40724** [comment]
@tfamula The changes are ok. Please resolve the conflicts in the lang file and commit this to 5.4.

**Pull request merged**
