### PR TITLE
Fix typo: comparing instead of assigning

### PR DESCRIPTION
**Pull request by AppChecker**
This possible defect found by [AppChecker](http://cnpo.ru/en/solutions/appchecker.php)

### CODE REVIEW

**Comment by chfsx** [comment]
@Uwe-Kohnle any news on this? Please try to have a look at your pull requests more frequent

**Comment by klees** [comment]
@Uwe-Kohnle This ticket had its first birthday recently. Even though it was created by a bot, the content clearly looks as if there either is a hidden bug or some code that is not required anymore.

**Comment by chfsx** [comment]
@Uwe-Kohnle could you please have a look at this PR?

**Review by Uwe-Kohnle — APPROVED** [review]
Thanks

**Comment by smeyer-ilias** [comment]
Thanks, it's ok for me.

**Comment by Amstutz** [comment]
Since everybody seems happy with this, i'll merge.

**Pull request merged**
