### PR TITLE
Registration: Prevent multiple assignments for same domain (ILIAS >= 8.x)

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=29273

If approved, this has to be picked to `trunk` as well.

### CODE REVIEW

**Comment by oliversamoila** [comment]
Hallo @pascalseeland 
könntest du hierzu noch eine Rückmeldung geben?
Besten Dank und viele Grüße.

**Comment by oliversamoila** [comment]
Hello @pascalseeland, please give us feedback on this PR.

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland, any objections to merge/pick this?

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland ,

the Technical Board regularly monitors PRs with no recent activities. This PR has been lying around for quite a while. Please merge as soon as you are ready or provide feedback.

Best regards,
@mjansenDatabay

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland , do you have any objections?

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland ,

I would like to merge this within the next week. Any feedback is highly appreciated.

Best regards,
Michael

**Pull request merged**
