### PR TITLE
UI Button with aria-labels proposal

### PR DESCRIPTION
**Pull request by xus**
Proposal to add aria-label and arial-checked HTML arguments in the UI Button. This arguments are needed for others UI elements like viewcontrol or tags.

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Thanks @xus. I approve that in general. However, please add a sentence in the rules accessibility section about when this label is needed.

**Review by Amstutz — APPROVED** [review]

**Comment by klees** [comment]
Hi @xus,
thanks for the changes, much appreciated. Unfortunately your changes made some tests fail, have a look at our [CI](ci.ilias.de). If you need help to find the appropriate screen that tells you what broke I'll be happy to help. Also: could you implement tests that show that the button indeed renders the aria-labels with the values that were set?
Thanks a lot and best regards!

**Comment by xus** [comment]
Hi @klees, thanks for your help. Alex already fixed the tests and I will provide new unit tests for the aria-labels asap.

**Comment by xus** [comment]
Hi @klees, new unit tests have been added in this [commit](https://github.com/ILIAS-eLearning/ILIAS/commit/6dc5eab3fc60248cd3ab3d83ba650d85f952333f).  Notice that only the standard button template contains aria label attributes. If add this labels to the other buttons is considered, I can add the changes in the templates.

**Pull request merged**
