### PR TITLE
Inputs for the UI-Framework

### PR DESCRIPTION
**Pull request by klees**
This PR contains facilities to handle inputs in the ILIAS-UI-Framework. This PR intentionally contains no screenshots because the forms and input created by the new facilities should look exactly like the old ones. There still is a lot stuff in this PR that should be widely interesting, for non-technical user, but even more so for developers. The proposed changes not only contain kitchen sink information and code for creating and rendering the inputs as other components do. Moreover the changes define how developers will process input from the client side in the future.

We still start with the [basics](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-582b4a13a07bdfdfa5ecbec4caa1239b), the Kitchen Sink descriptions for [Containers](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-a5b0844daf7ef3c49988ca394af4e686), [Fields](https://github.com/klees/ILIAS/blob/trunk_inputs/src/UI/Component/Input/Field/Factory.php), [Forms](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-8ee0151567be6237c507291747111e5d), their [Standard Implementation](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-239223547575f8840330e9efc4ead806) and [different types of input fields](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-2d8571e3a451f51b51f9868081f6f7e8) are based on the texts in the first KS-version (at gdocs) and were enhanced to fit the current implementation.

To get an idea how inputs will work from a developers perspective have a look into the examples ([1](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-db1fd5263f382c109ccbb3f5c360294a),[2](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-8bdb8ace5e7a82aa4c6247d87915f9e5)). [The README](https://github.com/ILIAS-eLearning/ILIAS/pull/704/files#diff-ccb5d545fc6a7349bd235bd8b2d5639e) attempts to explain the mechanisms in detail. To really get to the meat of the mechanism, you might want to start with [Data/Result](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/Data/Result.php), [Validation](https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/src/Validation) and [Transformation](https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/src/Transformation) before you check the [basic implementation of the fields](https://github.com/klees/ILIAS/blob/trunk_inputs/src/UI/Implementation/Component/Input/Field/Input.php).

There most likely will be some dangling ends and missing stuff in this PR. We nevertheless propose this to the JF to hopefully document the agreement we had in the input-workshop and allow developers that could not attend to ask questions and voice their concerns. Please give feedback if you are not comfortable with the mechanisms we propose. Please check if the documentation is good enough to let you use the framework. Please point out if stuff is missing.

### CODE REVIEW

**Comment by matthiaskunkel** [comment]
Jour Fixe, NOV 06, 2017: We highly appreciate this suggestion in general. But we have different opinions about merging this PR to the trunk now or after having re-opened the trunk for new features. We kindly ask the Technical Board to discuss this problem and to decide how to proceed with pull request from the Kitchen Sink in future. On the next Jouf Fixe we also need to discuss how to handle new and existing offers for features that either implement new form fields or extend existing ones.

**Review by alex40724 — CHANGES_REQUESTED** [review]
I highly appreciate this development and think it is a very important step forward for our ui framework. 

Since this is a larger code extension including some smaller changes in the existing old form service, too, I highly recommend to respect our "only bug fixing during beta" rule and commit these changes after the creation of a new stable release branch.

I support an immediate creation of a stable release branch to enable both, stability for 5.3 and a fast start of further ui development for 5.4.

**Comment by klees** [comment]
The "only bug fixing during beta"-rule is not documented clearly anywhere and could also be doubted to exist implicitly (respectively being obeyed). The [rules for the UI-Framework](ILIAS/src/UI/docu/rules.md) on the other hand clearly state, that new UI-components must be proposed via PR against the trunk, which is what we have done here.

These changes here don't break any of the existing and clearly defined interfaces of the UI-framework. Thus, this PRs potential effects on the stability of the current trunk are a lot smaller than the effects of numerous bugfixes made in shared services without a clearly defined interface. This still doesn't stop these bugfixes during beta.

I still would be fine with the creation of a stable branch.

**Comment by alex40724** [comment]
The last picture on
https://www.ilias.de/docu/goto_docu_pg_211_42.html
makes this statement clearly imo. "Bug fixing only" after the 1st beta release mark.

**Comment by Amstutz** [comment]
@alex40724 : Since the decision about the UI-Framework was added later and specific rules usually beat the more general ones I would still say, that this case here is clear. However, I am not sure whether this is a fruitful discussion. I would go with the creation of a stable 5.3 branch and after that merge this into the trunk.

Further we work on a better and more explicit wording for the process described in (https://www.ilias.de/docu/goto_docu_pg_211_42.html) in the TB.

**Comment by Amstutz** [comment]
I propose the following agreement for the transition to the new forms:

1. Es gibt Bestandsschutz für bestehende Formulare bis zum Erscheinen des Release 5.4. D.h., wenn bis dahin bei einem existierenden Formular ein neues Feld eingefügt werden soll, kann die alte Abstraktion verwendet werden.
2. Ganz neue Formulare müssen ab 5.4 mit der neuen Abstraktion gebaut werden.
3. Auch kleinste Änderungen an bestehenden Formulare für ILIAs 5.5 und später erfordern die Umstellung des kompletten zu ändernden Formulars. 

There is currently some disagreement about how to deprecate the old forms implementation. There are 2 proposals around:
+ Ab Release XY werden die Formulare Depracated (aus dem System entfernt) Maintainer sind selber verantwortlich Features bis zum diesem Zeitpunkt auf die neuen Fomulare umzustellen.

VS

+ Die bestehenden Formularklassen werden erst deprected, wenn geprüft wurde, ob sie nirgendwo mehr verwendet werden. Diese Transition wird nicht durch SP's, sondern Featuers oder Funding für die Umstellung finanziert.

**Comment by alex40724** [comment]
There are roughly 550 forms in ILIAS. It will be important how much effort will be needed to migrate a form. Currently I doubt that this can be done purely automatically. If you need e.g. 2h per form you would end up with 140PD.

I think we should bring this part of the UI service to a certain stage of maturity first, getting some experience and focus on issues like separation of filters, before discussing how to migrate the complete set of existing form implementations.

**Comment by Amstutz** [comment]
> @alex40724: I think we should bring this part of the UI service to a certain stage of maturity first, getting some experience and focus on issues like separation of filters, before discussing how to migrate the complete set of existing form implementations.

I personally like this suggestion of first getting some experience and let everybody put their hands on the new implementation before we decide anything about a complete migration. I could live with something like, we agree on points one to three and postpone the migration decision for existing forms that are not to be changed by any FR for one release.

**Comment by klees** [comment]
@alex40724 I really wonder how you derive a rule from that picture. It is located under a headline "**Typical** Major Release Timeline" (emphasis mine). The text below the image says "Up to our first beta release - planned for end of August - all new features **should** be fully developed. After that we **focus on** testing and bugfixing." (emphasis mine again). Recent commits also show, that there happens more than bugfixing on the trunk atm.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 NOV 2017: There is a general preference of creating a 5.3 release branch asap and to accept this pull request for the trunk when the release branch is available.
Concering Timon's rules: we accept rule 1 to 3 and ask for the following additional rules:
4) These rule do only concern new features and not bug fixes. Technical and usability bug fixes of old form implementations can be done with 5.5 and later, too.
5) The rules are effective from today and exclude all offers for 5.4 features made before today.
There is no requirement that old form implementations have to be transformed to the new form service with a specific ILIAS version. Both implementation will co-exist.

**Comment by alex40724** [comment]
@klees: So there seems to be at least some "SHOULD" rule. I am fine with that. If there are constant violations against this (and no communication on exceptions), we have a severe problem imo.

**Comment by klees** [comment]
@alex40724 No. How would a "**Typical** Release Cycle" (emphasis mine again) be translated into a rule? Also, the *should* is about features. As you know, there is reasonable doubt that UI-components are to be subsummed under the term "features". Your original statement was : "only bug fixing during beta". This is actually contradicted by the statement in the text that says "After that we **focus on** testing and bugfixing." (emphasis mine again).

I'm glad you asked about "violations". This is only a sample collection:

https://github.com/ILIAS-eLearning/ILIAS/commit/bdd4617591eab9533d3a5a85da13cada55a4c3c2
https://github.com/ILIAS-eLearning/ILIAS/commit/1004057926ca84a94a8e3e5d7c4aaa30b545be2d
https://github.com/ILIAS-eLearning/ILIAS/commit/4d4d83ec1161e022a3ebacdf193a4492e9e09675
https://github.com/ILIAS-eLearning/ILIAS/commit/2c30a01349ab50cecedbe764460436dad1af2047
https://github.com/ILIAS-eLearning/ILIAS/commit/af771b67f80475510bd206e2a16596cda18cce41
https://github.com/ILIAS-eLearning/ILIAS/commit/b20175a6a1b522a978811016da906b20fdb27fa9

That said, **I'm not advocating uncontrolled addition of stuff to the trunk or stable branches.** On the contrary: I proposed this PR by following a well defined process we all talk about and agreed on in the JF. You try to argue for rejecting this request by quoting "rules" that are neither documented anywhere in the form you are quoting them nor followed in the way you are quoting them, even by yourself or your colleagues. This is a very bad foundation for cooperation in the community.

**Comment by alex40724** [comment]
Ok I just picked the first two of the list of "violations". You may consider this being not well documented in the commit messages, but these are all bug related.

The first commit is related to these bug reports:
https://www.ilias.de/mantis/view.php?id=21003
https://www.ilias.de/mantis/view.php?id=21081
https://www.ilias.de/mantis/view.php?id=21082
https://www.ilias.de/mantis/view.php?id=21088

The second commit is related this feature which has been finished, documented and approved in time:
https://www.ilias.de/docu/goto.php?target=wiki_1357_Media_Files_for_Working_Instructions 
It worked pretty well when using new exercise objects. However we realized later that it did not work work older existing exercises. So we fixed the file location, without reporting this as a bug, but of course this was a bug.

I do not comment on Stefans commits. For mine they all have a bug background, even if not explicitly stated in the commit message.

**Comment by mbecker-databay** [comment]
With bugs in numbers that we fail to make the planned release date (also decided upon on the 11/20 JF), everyone certainly needs extra merge efforts from branching off 5.3 early to obviously address this Kindergarten here. It's surely bearable in sum but ... smh ...

**Review by alex40724 — APPROVED** [review]

**Comment by Amstutz** [comment]
Hello this PR is not 100% finalised, some tests are yet missing and some slight changes in the less will follow. However, due to other PR's building up on this especially on PR to be discussed in the next JF, we decided to merge it into the trunk nevertheless. 

We appreciate to have a separate trunk that soon in the dev-process making this early merge possible. Thanks a lot to everybody involved. Feedback on this work is heavily appreciated.

**Pull request merged**
