### PR TITLE
try catch onload code of modules, services, plugins, ...

### PR DESCRIPTION
**Pull request by ghost**
ILIAS modules, services, plugins, ... (I call it components to mean all types) can add their JavaScript autoload code with `addOnLoadCode` on the main template

this codes will than executed consecutively in a single javascript function on jQuery read event

the case can be, if one code of a component will failed and throws an error, all following component codes will not be executed anymore, although they are actually independent of each other

this can be very irritating, if an other component has bug (not fixed yet) and it's own component will not be executed and it can not do anything because it has no influence on the order of `addOnLoadCode`

This PR improves this case and try catch each single onload code of components and logs it

So if an onload code should fail, the following codes will be executed

### CODE REVIEW

**Review by alex40724 — APPROVED** [review]
+1

**Comment by mjansenDatabay** [comment]
+1

**Review by klees — COMMENTED** [review]
Hi @sragfw,

thx for this proposal! Why do we need to add that code in the individual usage locations instead of adding it in [`il.Util.addOnLoadCode`](https://github.com/ILIAS-eLearning/ILIAS/blob/b8a2a3a203d8fb5bab988849ab43616be7379551/Services/JavaScript/js/Basic.js#L27) directly?

Best regards!

**Comment by klees** [comment]
Hi everyone.

I assigned the people that seem to be somehow involved here due to some maintainership or coordinatorship.

I, as LSO-maintainer and UI-coordinator, would prefer if the issue would be fixed in `addOnLoadCode` directly, if there are no good reasons against this move.

How should we go on here?

Best regards!

**Comment by bheyser** [comment]
+1 // Big Thx to handle this problem (!)

**Comment by matthiaskunkel** [comment]
Jour Fixe, 12 AUG 2019 : We prefer a centralised approach and would like to fix this in addOnLoadCode, as suggested by Richard. Accepted for trunk. Please modify the PR accordingly. Alexander will merge this PR after modification has been completed.

**Comment by ghost** [comment]
sorry that it took so long, but I didn't work in august

I also thinks it is better to fix directly in `addOnLoadCode` and not on each call, thanks

**Review by klees — APPROVED** [review]

**Comment by ghost** [comment]
I see, that directly do this in `addOnLoad` will not fix this issue, because all part of code will executed in the same `try-catch`, will fail one, the rest will not be executed

The template files still needs to be adpated like

new:
```
<!-- BEGIN on_load_code_inner -->
il.Util.addOnLoad(function() {
	{OLCODE}
});
<!-- END on_load_code_inner -->
```

before:
```
il.Util.addOnLoad(function() {
	<!-- BEGIN on_load_code_inner -->
		{OLCODE}
	<!-- END on_load_code_inner -->
});
```

@klees What do you think?

**Comment by alex40724** [comment]
Thanks!

**Pull request merged**
