### PR TITLE
UI Components, New Glyphs for il-icons fonts see #41767

### PR DESCRIPTION
**Pull request by Amstutz**
Addition of 6 new Glyphs with description and font changes, see https://mantis.ilias.de/view.php?id=41767 for details.

### CODE REVIEW

**Comment by yvseiler** [comment]
Hi @Amstutz 

Thank you a lot for contributing to ILIAS. This significantly improves the glyph database.

I just have one question according to the Files changed:

Please answer the following questions:
- [x] Why is there no entry in the language files [de](lang/ilias_de.lang) and [eng](lang/ilias_en.lang) for the preview glyph? Does it already exist?


kindly,
@yvseiler

**Comment by Amstutz** [comment]
_Why is there no entry in the language files [de](https://github.com/ILIAS-eLearning/ILIAS/pull/lang/ilias_de.lang) and [eng](https://github.com/ILIAS-eLearning/ILIAS/pull/lang/ilias_en.lang) for the preview glyph? Does it already exist?_

Because it already exists.

@klees and @thibsy , this is ready for review. If good, it would need to go to the JF. See mantis isssue above for details. Trunk only.

**Review by thibsy — CHANGES_REQUESTED** [review]
Hi @Amstutz and @yvseiler,

Thanks a lot for your contribution to the UI components!

The factory descriptions are plausible and can be presented at the next JF. There are some minor changes before we can merge this afterwards, but they are not important for JF.

Please implement the following changes:

- [x] Unit tests: the unit tests are currently failing. Please look into this.
- [x] `ilias_de.lang`: the german translation of `common#:#tile_view` is in english. Please translate this variable.
- [x] `@inheritDoc`: this PHPDoc annotation is obsolete and can be removed from the new methods in the `Glyph\Factory` implementation.

Kind regards,
@klees and @thibsy

**Comment by matthiaskunkel** [comment]
Jour Fixe, 30 SEP 2024: We highly appreciate this suggestion and accept the PR for ILIAS 10/trunk.

**Pull request closed without merging**
