### PR TITLE
add library ramsey/uuid

### PR DESCRIPTION
**Pull request by theodortruffer**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Thx @theodortruffer for this PR. Can you please add some more details in the PR's description why you plan to introduce this composer dependency? Of course I personally know the reason, but there may be many developers (or even non developers) who don't. Thx in advance.

**Comment by theodortruffer** [comment]
Sure! 

Ramsey/Uuid is probably the most popular library (= has the most downloads) for creating UUIDs: Universally Unique Identifiers. UUIDs can be used as primary keys for domain objects, instead of (or with) auto-incremented ids, which are currently used in ILIAS. 

UUIDs have some advantages (universal uniqueness, creatable before the actual storage, ..), but also some disadvantages (needs more storage/performance, not sortable, ..) over auto-incremented ids. So while it doesn't make sense in every context, the developer should still have the choice to use UUIDs in his/her components, if it seems appropriate.

Some reading (it's easy to find more articles via google): https://medium.com/@Mareks_082/auto-increment-keys-vs-uuid-a74d81f7476a

**Comment by mstuder** [comment]
We would like to use the library for
https://docu.ilias.de/goto_docu_wiki_wpage_4571_1357.html
"Question ID is composed randomly as UUID"

**Comment by mjansenDatabay** [comment]
Thx @mstuder  and @theodortruffer

**Comment by matthiaskunkel** [comment]
Jour Fixe, 15 JUL 2019: Introducing Ramsey library in ILIAS 6.0 is highly appreciated. Please offer also a wrapper for this library to ease the use of UUIDs for developers.

**Comment by mstuder** [comment]
@theodortruffer Please provide a wrapper under /src/data! Please assign this to Richard Klees for approval.

**Comment by theodortruffer** [comment]
@klees here's a very basic wrapper with only uuid4 as object or as string. Do we need more? 

https://github.com/ILIAS-eLearning/ILIAS/pull/1980/commits/3bc1f4ed217f31244ea2454d97793b94977ef085

**Review by mjansenDatabay — CHANGES_REQUESTED** [review]
Hi @theodortruffer 

Thank you a lot for the provided UUID factory.

Please implement the following changes:
- [x] Add `Return Type Declarations` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R35) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R43).
- [x] The consumers in the ILIAS code base should not rely on an `\Ramsey\Uuid\UuidInterface` [interface](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R32). Please add an additional `\ILIAS\Data\UuidInterface` interface used for contracts with the UUID data type.
- [x] Resolve all conflicts.

If you have any questions, don't hesitate to contact me.

Best regards,
@mjansenDatabay

**Comment by mjansenDatabay** [comment]
Please implement the following changes:
- [ ] Add `Return Type Declarations` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R35) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R43).
- [ ] The consumers in the ILIAS code base should not rely on an `\Ramsey\Uuid\UuidInterface` [interface](https://github.com/ILIAS-eLearning/ILIAS/pull/1980/files#diff-d7737a3081d066cec57193131f1c2ab1R32). Please add an additional `\ILIAS\Data\UuidInterface` interface used for contracts with the UUID data type.

If you have any questions, don't hesitate to contact me.

Best regards,
@mjansenDatabay

**Comment by mjansenDatabay** [comment]
Arghhhh, sorry

**Comment by theodortruffer** [comment]
Hey @mjansenDatabay 

Thanks for your feedback. I made a try at wrapping UuidInterface, but I realized that I'm not an experienced wrapper. Here's what I did:
* UuidInterface has almost all methods from Ramsey/UuidInterface, but it doesn't inherit from it to avoid coupling and because we don't need all methods - e.g. there are many methods only applicable to uuid version 1, which we currently won't use I guess. Maybe even call the interface Uuid4Interface?
* RamseyUuidWrapper takes a UuidInterface from the library and just wraps every method. compareTo and equals are a bit ugly, since they should actually accept only RamseyUuidWrapper and not UuidInterface as parameter, but I haven't found a better way yet.

I'm open for suggestions.

Thanks, Theo

**Comment by mjansenDatabay** [comment]
Thx @theodortruffer , LGTM!

Regarding your questions/remarks:

- For now `UuidInterface` is fine for me. Maybe we need a `Uuid4` successor in the future, so a generic name should be okay :-).
- I see the issue with `compareTo` and `equals` and indeed this is a valid point. The current implementation is okay for me. I doubt there will be multiple implementatons of the interface in future. What could be done: The concrete `RamseyUuidWrapper` **could** check if the passed `$other` instance is of the same type/class, and return a `false` (equals) or `-1/1` (compareTo) otherwise. Maybe throwing an exception if the class differs is even better.

Please resolve the remaining conflict. I will merge this afterwards.

Best regards,
Michael

**Review by mjansenDatabay — APPROVED** [review]

**Comment by theodortruffer** [comment]
@mjansenDatabay Thanks for your feedback! The conflicts have been resolved.

**Pull request merged**
