### PR TITLE
OrgU: Removal of MyStaff/EmployeeTalk

### PR DESCRIPTION
**Pull request by tbongers-cat**
This removes Modules/EmployeeTalk and Services/MyStaff including all references in other modules/services.

### CODE REVIEW

**Comment by klees** [comment]
Hi everyone!

To whom it may concern: This is not @tbongers-cat idea, I simply asked him to provide this PR (thanks!).

Product Manager and Technical Board will decide how this is handled. If there are any questions, feel free to contact me.

Best regards!

**Comment by matthiaskunkel** [comment]
Current maintainer of MyStaff would like to hand over maintainership to another developer. In case we do not find a new maintainer that takes over responsibilty for this component already for ILIAS 8 and fixes bugs to get component stable for 8.0 we have to remove the component with this pull request. Deadline for taking over maintainership is 22 JAN 2023.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 09 JAN 2023: Timon explained the reasons for creating this PR - in case we need to remove Services/MyStaff because we do not find a new maintainer (classic or coordinator) that takes over responsibility for this component, incl. bugfixing for ILIAS 8. We will discuss and decide upon this PR on the next JF at 23 JAN 2023. An additional FW article to abandon the feature will be created by the PM.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 23 JAN 2023: Decision postponed to Jour Fixe at 06 MAR 2023 when we know if the maintainership for MyStaff and EmployeeTalk has successfuly been taken over or not.

**Comment by klees** [comment]
I think this is not needed anymore. Thanks @tbongers-cat =)

**Pull request closed without merging**
