### PR TITLE
fix rector examples for newest code style

### PR DESCRIPTION
**Pull request by iszmais**
A bit picky but at least the header should be fixed imo.

The changes within the functions are just suggestions, if you may have a better approach to that take that.

### CODE REVIEW

**Comment by chfsx** [comment]
@iszmais thanks for the hint, i changed the code style and several other thing for the whole directory CI/Rector now and close this PR. The changes in `foo()`and `bar()` are not correct since we want here a ilUtil::sendXY since the rector `ReplaceUtilSendMessageRector` is meant to replace those with `setOnScreenMessage`, the Example Class is to try this rector.

**Comment by iszmais** [comment]
@chfsx Thanks for the response!

LGTM, but (i might be missing something) arent the `sendXY` function removed for ILIAS 8. Why would the example should call an invalid function?

Greetings,
@iszmais

**Comment by chfsx** [comment]
@iszmais the example is to show hoe the rector rewrites your code, you can try this with ```./libs/composer/vendor/bin/rector process --clear-cache --no-diffs --config ./CI/Rector/ilUtils/ilutil_rector.php CI/Rector/ilUtils/Example.php``` 
The rector can be used in plugins as well

**Comment by iszmais** [comment]
@chfsx thank for the explanation!

I assumed that this isnt productive code and i might be extra picky here but even as an example i would still expect this to be executable in some way. Imo that falls under extended documentations. :sweat_smile: 

Greetings,
@iszmais

**Pull request closed without merging**
