### PR TITLE
remove old class stub - > fixing a classname collision

### PR DESCRIPTION
**Pull request by colin-kiegel**
pretty sure this is not in use at all.

(one step closer to autoloading..)

### CODE REVIEW

**Comment by chfsx** [comment]
@alex40724 there are no includes of this class in the code base --> not used

**Comment by chfsx** [comment]
there's also a second class ilMetaDataImporter which doesn't appear in the code base: Services/MetaData/classes/class.ilMetaDataImporter.php

**Comment by alex40724** [comment]
Services/MetaData/classes/class.ilMetaDataImporter.php
is definitely used.

**Comment by chfsx** [comment]
my bad, didn't consider possible "dynamic" usage und include of this class.

**Pull request merged**
