### PR TITLE
[fix 0022897] Test-Creation failed in PostgreSQL

### PR DESCRIPTION
**Pull request by lbruening**
using `coalesce` instead of `ifnull` in sql

### CODE REVIEW

**Comment by bheyser** [comment]
thx for providing the improvement / fix (!)

**Comment by lbruening** [comment]
@bheyser have you merged this also to trunk?

**Comment by bheyser** [comment]
oooops, it seems like i did not. I will check all stable branches and ensure a merge ;-) Thx for pointing me on that fact (!)

**Comment by bheyser** [comment]
merged to trunk by now.

**Pull request merged**
