### PR TITLE
Registration: Prevent multiple assignments for same domain (ILIAS 7.x)

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=29273

### CODE REVIEW

**Comment by oliversamoila** [comment]
Hallo @pascalseeland 
könntest du hierzu noch eine Rückmeldung geben?
Besten Dank und viele Grüße.

**Comment by oliversamoila** [comment]
Hello @pascalseeland, please give us feedback on this PR.

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland, any objections to merge/pick this?

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland ,

the Technical Board regularly monitors PRs with no recent activities. This PR has been lying around for quite a while. Please merge as soon as you are ready or provide feedback.

Best regards,
@mjansenDatabay

**Comment by mjansenDatabay** [comment]
This PR has to be unfortunately closed because the ILIAS 7 branch is EOL.

**Pull request closed without merging**
