### PR TITLE
PHP 8 Code Review Services Cache

### PR DESCRIPTION
**Pull request by katringross**
Hello @alex40724 ,

I completed the review of the Services/Cache component.

Results:

- [x]  The code style is PSR-2 + X compliant
- [x]  No usage of $_GET / $_POST / $_REQUEST / $_SESSION
- [x]  There is a Unit Test Suite with at least one unit test
- [x]  The unit tests pass
- [x]  External libraries are compatible with PHP 8 (if relevant)
- [x]  There are no serious PhpStorm Code Inspection issues left
- [ ]  The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)

--

We fixed some trivial issues reported by our inspection profile.
1 return type was missing, see my change in code.

Actions needed:

no

Best regards,
@katringross

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
This PR also contains a review for the `Rating` component.

Cache: 
- [ ] A `: void` return type is missing in `\ilCacheTest::testSetExpires`

**Comment by katringross** [comment]
@alex40724 and @mjansenDatabay sorry, I overlooked it for Cache and Chart. By mistake we added the commit for rating here. Can you work with it? If not I will create a new PR.

**Comment by alex40724** [comment]
I can work with that! :-)

**Comment by alex40724** [comment]
I will take care of the PHP8-Review issues in the Rating service.

**Comment by alex40724** [comment]
Done

**Pull request merged**
