### PR TITLE
DataCollection: Application for Authorities

### PR DESCRIPTION
**Pull request by oliversamoila**
Dear @matthiaskunkel, @ILIAS-eLearning/technical-board, dear @pascalseeland, 
here is the PR in addition to my application to be responsible for the Data Collection.

Best regards
Oliver

### CODE REVIEW

**Comment by pascalseeland** [comment]
@oliversamoila Thanks for your application. I would vote for accepting Oliver for the requested authorities.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 13 MAY 2024:  Final decision will be taken by TB and PM tomorrow.

**Comment by matthiaskunkel** [comment]
Change of authorities has been accepted by product manager and @pascalseeland as authority to (de-)assign authorities. No veto by TB.

**Comment by matthiaskunkel** [comment]
Due to a merge conflict I close this report and cherry-pick the changes manually.

**Pull request closed without merging**
