### PR TITLE
Init/Login/Migration/Codes: Use UI framework for startup forms

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR introduces the UI framework forms to the `ilStartupGUI`.

Furthermore I did a little bit of "boy-scouting".

See: https://mantis.ilias.de/view.php?id=33816

**!!!Important!!!:** The `Code` and `Account Migration` forms do not provide a `Cancel` button anymore, just because the UI forms don't support further buttons.

### CODE REVIEW

**Comment by pascalseeland** [comment]
Thx for the PR. Do we have any guidelines in place for forms that don't have the cancel buttons any more. Does this require a JF decision? There are some more forms at least in the ECS code which have the some issue which the cancel button

**Comment by mjansenDatabay** [comment]
Hi @pascalseeland,

We don't have any guidelines for this. I am not sure if we need a JF decision here. Users can still use the browser back button of the linked glyph in the metabar (top right of the screen) to navigate back to the login form.

As far as I know, Oliver Samoila wanted to put the topic "Additional Form Buttons" up for discussion again.

Best regards,
@mjansenDatabay

**Comment by oliversamoila** [comment]
Hello @pascalseeland 
please give us feedback on this in a timely manner.
Do you need anything else?

**Comment by oliversamoila** [comment]
Hello @pascalseeland, please give us feedback on this PR.

**Comment by oliversamoila** [comment]
Dear @pascalseeland 
we need feedback by Thursday in order to integrate the changes into Release 9 before Coding Completed. 
In the meantime, we have to assume that if there is nothing else to remark on, we can merge this status.
Best regards.

**Pull request merged**
