### PR TITLE
Missing semicolons added.

### PR DESCRIPTION
**Pull request by d3r1w**
I added two missing semicolons to the CrawlerExceptionLogger.

### CODE REVIEW

**Review by dkloepfer — APPROVED** [review]
LGTM,
that's why we use pre-commit hooks now, to avoid this in the first place :/

**Comment by chfsx** [comment]
@dkloepfer how comes this never showed up in production? in which cases this CrawlerExceptionLogger is used?

**Comment by dkloepfer** [comment]
@chfsx It was intended to be used during unit tests of UI Factory interfaces, but obviously noone ever did actually bother to use it...

**Comment by klees** [comment]
Hi @dkloepfer, please remove the unused code. Thx!

**Pull request merged**
