### PR TITLE
Fixed scrolling behaviour of vertical ordering questions on mobile de…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…vices

This PR fixes scrolling issues during drag'n'drop events on mobile devices. It should be cherry-picked to v. 5.3.x and 5.2.x as well. The behaviour has been already fixed for ILIAS v. 5.1.x (see: https://www.ilias.de/mantis/view.php?id=20481).

TODO (before merging this PR):
- [ ] Instead of patching file *./libs/bower/bower_components/nestable/jquery.nestable.js* you should investigate if there is a proper patch solution for bower components.

### CODE REVIEW

**Comment by bheyser** [comment]
Hello Michael,

i do not understand the given todo. In the past there was referenced a fixed lib file, that was stored in the TestQuestionPool Folder. Some has added this lib to bower and refrenced it here.

I thought this is now the regular library?

Call me stupid please if i am wrong ;-)

BR, BJörn

**Comment by bheyser** [comment]
in general thx for this PR (!)

**Comment by mjansenDatabay** [comment]
Hi @bheyser,

@chfsx migrated the JavaScript library _Nestable_ as a dependent library to our JS dependency folder managed by [bower](https://bower.io/).

See: [./libs/bower/README.md](../blob/trunk/libs/bower/README.md)

Thus we just cannot apply a patch to these source code files. An update of the dependencies will lead to code conflicts or will just overwrite these changes. The PHP depenencies managed by composer support a patch mechanism. As long as we did not find a similar option for bower, we should leave this PR as 'on hold'. You can refer to this PR in Mantis issues. So there is already a solution, but it is not sustainable, yet.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 05 FEB 2018: Björn, please have a look at https://github.com/RamonSmit/Nestable2/commits/master and check if we could switch to this fork of Nestable2. This would allow us to keep the lib as a bower dependency.

**Comment by mjansenDatabay** [comment]
@bheyser Any update on this?

**Comment by chfsx** [comment]
@bheyser is there anything we could help you with? thanks for having again a look at this PR

**Comment by bheyser** [comment]
This PR does patch the nestable lib after installing with bower. I now tested the nestable2 library also provided with bower. new nestable2 lib does support scroll, so I will replace nestable with nestable2.

**Pull request closed without merging**
