### PR TITLE
UI Panel: Add optional Dropdowns for Standard/Sub Panels

### PR DESCRIPTION
**Pull request by alex40724**
This PR adds optional action Dropdowns for Standard and Sub Panels.

This is needed for the approved 5.3 feature "Competence Reporting Panels"
https://www.ilias.de/docu/goto_docu_wiki_wpage_4314_1357.html

Panel description/rules:
https://github.com/ILIAS-eLearning/ILIAS/pull/574/files#diff-0c3b34e8901a0a9c29aec05f17067584

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
Thx for the additional examples and tests.

**Comment by matthiaskunkel** [comment]
Jour Fixe, July 17, 2017: Highly appreciated. Please merge into trunk.

**Comment by Amstutz** [comment]
@alex40724 Should this be merged or can this be closed since it is part of an other feature that will be merged very soon?

**Comment by Amstutz** [comment]
Implemented in different PR.

**Pull request closed without merging**
