### PR TITLE
Legacy-UI refactoring of TestDetailedEvaluationStatisticsGUI

### PR DESCRIPTION
**Pull request by matheuszych**
These changes are part of the [Legacy-UI refactoring](https://docu.ilias.de/go/wiki/wpage_7320_1357).
The commit "Initializes LUI refactoring base" acts as the base for all further Legacy-UI refactorings.

### CODE REVIEW

**Comment by kergomard** [comment]
Hi @matheuszych and  @thojou 
Thank you very much for this PR! I'm very much looking forward to getting rid of this table!

Just one quick thing: I would like to discuss this at the next TechSquad as you are introducing an alternativ structuring in the src-folder. So I would ask you to wait with merging.
As you know I generally think this structure is a bad idea, but in any case we shouldn't have two parallel structures in the src-folder. So, we should discuss this. If we would decide to go with the structure in here, I would then ask you to restructure all other code currently in the src-folder, too.
My suggestion though would be to put all of this in a folder "Evaluation". To reiterate: In this way we would create a kind of "sub-module". This module could then have an internal structure that fits its needs, if necessary (here I don't think it is).

I have a few additional things, I would like to have a look at with you (e.g. why there is a questions-repo here), but this we can do, whenever you feel ready (we can also do it in the TechSquad, if you prefer).

I assume this PR is exactly for opening this discussion, but just to be sure.

Thanks again and best,
@kergomard

**Comment by matheuszych** [comment]
Hello @kergomard,

We can deffinetly discuss the alternative structuring in the src-folder. Since @thojou has developed the base structure used here i would suggest to wait for his input.

For now we will wait with the merging itself.

Best regards,
@matheuszych

**Comment by dsstrassner** [comment]
@thojou informed the TechSquad today, that he will review this PR first internally and change some things.

**Comment by kergomard** [comment]
Hi @matheuszych and @thojou 

Just on a side-note: I would suggest to push further work on this back in your schedule, as this table will disapear, if everything goes as planed (See: https://docu.ilias.de/go/wiki/wpage_8317_1357 ). Sorry, I didn't leave this comment earlier, it just didn't bubble over the awarness-threshold in my mind.

Best,
@kergomard

**Comment by dsstrassner** [comment]
@kergomard will close this one.

**Comment by kergomard** [comment]
We discussed this PR at the Tech Squad today. We close this PR for the time being, as this class will probably disappear with the restructuring of the tabs. @kergomard  will keep an eye on this.

**Pull request closed without merging**
