### PR TITLE
KS: new ui report listing component

### PR DESCRIPTION
**Pull request by bheyser**
This PR introduces a new ui component called report listing:
UI > Listing > Report > Standard / Mini

It is to be used to present listings of label-value doubles that need to be presented side by side.

It is more about presenting longer labels for short values than a short term that is described with a longer description. This is why we need this report listing as a rival to the descriptive listing.

*Standard Report Listing*

The Standard Report Listing is used for a regular presentation in the main content of a page as a major part of the ui.
```
function base()
{
    global $DIC; /* @var \ILIAS\DI\Container $DIC */
    $f = $DIC->ui()->factory();
    $r = $DIC->ui()->renderer();

    $items = [
        'Any Label for the First Item' => 'Item 1',
        'Another Label for the Second Item' => 'Item 2',
        'Third Item Comes as Component' => $f->legacy('Item 3'),
        'Fourth Item Comes as Component' => $f->legacy('Item 4')
    ];

    $standard = $f->listing()->report()->standard($items)->withDivider(
        $f->divider()->horizontal()
    );

    return $r->render($standard);
}
```
image

*Mini Report Listing*

The variant Mini Report Listing is to be used when presenting the information as a mariginal part of the ui, e.g. when using in the card of a reporting panel.
```
function base()
{
    global $DIC; /* @var \ILIAS\DI\Container $DIC */
    $f = $DIC->ui()->factory();
    $r = $DIC->ui()->renderer();

    $items = [
        'Any Label for the First Item' => 'Item 1',
        'Another Label for the Second Item' => 'Item 2',
        'Third Item Comes as Component' => $f->legacy('Item 3'),
        'Fourth Item Comes as Component' => $f->legacy('Item 4')
    ];

    $mini = $f->listing()->report()->mini($items);

    return $r->render($mini);
}
```
image

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @bheyser 

Thank you a lot for contributing to the UI Components.

To evaluate this a little better, it would help to know of some instances in ILIAS or upcoming features, where this will be used.

We see a strong rivalry of this proposed component to the existing panels, especially the listing panel and the report panel. 

Please answer the following questions:
- [ ] Taxonomy: Why do you propose this as a listing and not as a panel?


We are sceptical towards to proposed approach and recommend a solution with somewhat less overhead: Note that panels accept various input, also descriptive listing. What we could do, is just to improve the less for descriptive listing in panels a little to more or less match your mockups. Would that be a workable solution?

kindly,
@amstutz and @klees

**Comment by bheyser** [comment]
Thx for your Feedback @Amstutz !

First I want to answer your expicit question:

I did started up with a another kind of reporting panel in the beginning of the year called data panel, but you gave me the hint that we are not talking about a panel but more a listing and you adviced me to check wether the desctipive listing could be extended in any way.

Than I realized myself, that I do want to have a listing that can be shown in either any kind of panel or even within a card of a reporting panel. So I strongly consider the requirement to list item label/value doubles as a listing that can be used in any kind of panel and not a special panel that could'nt be combined with other panels in a flexible way.

When I evaluated the descriptive listing because of your hint to extend it in any way, I noticed that it makes use of the html elements DL, DT and DD. So correct me if I am wrong: The descriptive listing takes less long terms that are described by more long descriptions.

The label/value doubles I need to present behave the opposite, the labels are more long and the values are shorter in general.

Also the use of the sematics of a Descriptive Listing nesting Descriptive Terms and Descriptive Descriptions are not the right choice for presenting a kind of statistic imho as this is the requirement of the following features for which I need the new UI component. The screenshots shows label value doubles that are really not descriptive terms, but labeled values.

Continuous Testing Mode Usability Improvement
https://docu.ilias.de/goto_docu_wiki_wpage_5089_1357.html
image

Extended Test and Item Statistics
https://docu.ilias.de/goto_docu_wiki_wpage_3529_1357.html
image

Kind regards, Björn

**Comment by bheyser** [comment]
Please notice that my component does not render the panels I have shown in the screenshots, my component is rendered within a panel in the first screenshot and in the card of a reporting panel in the second screenshot. I am sorry, when my introduction did not made this clear.

**Comment by Amstutz** [comment]
Hi @bheyser 

Thanks a lot for you answer. You explanations and mockups did help a lot. We both (@Amstutz and @klees ) suspect now, that it might be just a naming issue. We both got it slightly wrong and your explanation makes sense to us. We believe best, if we have hold a short discussion to get any confusion out of the way. Ill send you a doodle. 

thx.

**Comment by Amstutz** [comment]
We (@bheyser , @klees , @Amstutz ) discussed the PR today in a skype meeting. We agreed on the following:
- [ ] The Title should be changed to: *Characteristic Value* with one child named *Text*.
- [ ] We do not need a *Mini* Version, we use CSS/Less instead for the Layout
- [ ] We do not want divider on the public interface

Note that the above examples from @bheyser will not be affected by those decision. The visual output will remain the same.

**Pull request closed without merging**
