### PR TITLE
UI/DateInput add current lang-key to config 

### PR DESCRIPTION
**Pull request by nhaagen**
...to display date-picker with user's language.

### CODE REVIEW

**Comment by Amstutz** [comment]
Thx, 

- [x] one minor detail, could you provide a unit test, making sure this will be kept in future refactorings. IMO this can regarded as part of the public API and should be tested.

**Review by klees — COMMENTED** [review]
As @Amstutz says.

**Review by klees — APPROVED** [review]
Thx @nhaagen.

**Comment by klees** [comment]
@Amstutz: Could you have a quick look here and greenlight this?

**Review by Amstutz — APPROVED** [review]

**Comment by Amstutz** [comment]
Thx for the test!

**Comment by klees** [comment]
Picked to release_7. Did not pick to release_6, there are conflicts and nobody complained till now.

**Pull request merged**
