### PR TITLE
PHP 8 Code Review Learning Module ILIAS

### PR DESCRIPTION
**Pull request by katringross**
Hi @alex40724 ,

I completed the review of the Module/LearningModule component.

Results:

- [x] The code style is PSR-2 + X compliant
- [x] No usage of $_GET / $_POST / $_REQUEST / $_SESSION
- [x] There is a Unit Test Suite with at least one unit test
- [x] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant)
- [ ] There are no serious PhpStorm Code Inspection issues left
- [ ] The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)
--
We fixed some trivial issues reported by our inspection profile. 
We marked some issues with comments, please search for PHP8-Review.

Actions needed:
- [ ] Please have a look at the types.

Best regards,

@katringross

### CODE REVIEW

**Comment by alex40724** [comment]
@katringross Thanks for the PR! Looks good. Is the review finished? I just saw that in the data collection https://docu.ilias.de/goto_docu_dcl_10296_209.html it is not marked as finished yet.

**Comment by katringross** [comment]
@alex40724 it's finished. I will update the datacollection, thanks for the reminder.

**Comment by alex40724** [comment]
I will take care of the comments.

**Comment by alex40724** [comment]
Done.

**Pull request merged**
