### PR TITLE
Fix strings being accessed with {} (PHP 7.4 deprecation: Array and st…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…ring offset access syntax with curly braces is deprecated)

### CODE REVIEW

**Review by bheyser — APPROVED** [review]
thx @mjansenDatabay - all fine for my file!

**Review by chfsx — APPROVED** [review]
Thanks a lot, LGTM for my files!

**Comment by mjansenDatabay** [comment]
@alex40724 / @smeyer-ilias / @klees Can you please have a look?

**Review by smeyer-ilias — APPROVED** [review]
Thanks, everything fine for my files.

**Review by alex40724 — APPROVED** [review]

**Review by klees — APPROVED** [review]

**Pull request merged**
