### PR TITLE
UI Symbol 

### PR DESCRIPTION
**Pull request by nhaagen**
This reorders and unifies Glyph and Icon.
As you can see [here](https://github.com/ILIAS-eLearning/ILIAS/compare/trunk...nhaagen:UI_Symbol?expand=1#diff-a561671ae5bc673294bb9277cd26b5c5), e.g., or [here](https://github.com/ILIAS-eLearning/ILIAS/compare/trunk...nhaagen:UI_Symbol?expand=1#diff-db35e3346a8382cbfe421d16f795dfed),  Icon and Glyph are quite close to each other and are actually being used as such.
Unification as [`Symbol`](https://github.com/ILIAS-eLearning/ILIAS/pull/1835/files#diff-0c3b34e8901a0a9c29aec05f17067584R762) lets us properly hint and describe this usage.

### CODE REVIEW

**Review by Amstutz — COMMENTED** [review]
HI @nhaagen 

Thx for the PR. 

To who it might concern: Note that it has been brought to us, that the term Glyph is in certain scenarios (like testrail cases) not such an ideal term to us, since it might be confused with the term Icon. In some scenarios, this might be exactly as intended in others (like testrail) it might cause necessary confusion. The suggestion was to use a term to bundle to two. I think symbol is a good choice.

I thought some time about making the description more precise, however, the quite open nature has some charm. If no better suggesions pops up, I can live with it.

Thx,
@Amstutz

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 MAY 2019 : We highly appreciate this PR and accept it for 6.0.

**Comment by klees** [comment]
@Amstutz Besides conflicts: Anything to do here?

**Comment by Amstutz** [comment]
Nope, this is ready to be merge, feel free to do so, as soon as conflicts are resolved to avoid further ones (IMO, this is prone to spawn new ones by the minute).

**Review by Amstutz — APPROVED** [review]

**Pull request merged**
