### PR TITLE
T&A: fix type of parameter of method roundtrip in interface ILIAS\UI\Component\Modal\Factory

### PR DESCRIPTION
**Pull request by malaja11**
While writing Unittests I noticed the inconsistency between the type and the doc comment and decided to provide a quick fix.

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @malaja11,

can we use `?array` here?

Kind regards!

**Comment by klees** [comment]
Ahh, sry. Did not notice the single `Component` there. So, can we use `|` and just enumerate the types in the parameter list?

Kind regards!

**Comment by klees** [comment]
Hi @malaja11,

I assigned you here to remove this from our list. Please assign back to me once you changed or answered.

Thanks!

**Comment by malaja11** [comment]
Hey @klees, I just changed the type the way you described :)

**Pull request merged**
