### PR TITLE
T&A Abandon ILIAS-specific TinyMCE Plugins latex, pastelatex, ilimgupload

### PR DESCRIPTION
**Pull request by fhelfer**
Abandon ILIAS-specific TinyMCE Plugins for T&A
See: https://docu.ilias.de/go/wiki/wpage_8337_1357

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much for the PR @fhelfer ! 

This looks really straight forward and right and I've just one question: Do we really need to actively remove 'ilimgupload'? There should be no plugin of this type anyway and thus we will need to remove it from the RTE. What am I missing?

Thanks again and best,
@kergomard

**Comment by dsstrassner** [comment]
@fhelfer will retest this. @mjansenDatabay stated, that actively removing 'ilimgupload' is needed. @kergomard will take care of it.

**Comment by fhelfer** [comment]
I retested and the changes work. At least for ILIAS 9 on trunk I cannot test tinymce, there seems to be other things broken.
@kergomard  Do i keep the line `removePlugin('ilimgupload')` and you remove this when you provide a PR for TinyMCE? Because if I take this out now, the feature is not complete.

Best @fhelfer

**Comment by kergomard** [comment]
Thank you very much @fhelfer for testing this.

I'm working on Tiny right now. I hopefully have a PR by tonight. I would suggest to keep this open until we are through with the other PR and then remove the line. I keep you posted.

Thanks again,
@kergomard

**Comment by fhelfer** [comment]
I will remove the changes regaring 'ilimgupload' as soon as https://github.com/ILIAS-eLearning/ILIAS/pull/8091 has been merged

**Comment by kergomard** [comment]
Just a ping, as I don't know, if you follow the whole repo: https://github.com/ILIAS-eLearning/ILIAS/pull/8091 has been merged.

**Comment by fhelfer** [comment]
Hey @kergomard, rebased and ready for merge
Best @fhelfer

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

Failing tests due to preexisting unsorted lang files.

**Pull request merged**
