### PR TITLE
Aria (Landmark) Roles + some more accessibility fixes

### PR DESCRIPTION
**Pull request by tfamula**
Hello all,
this PR improves/introduces [Aria Landmark Roles](https://docu.ilias.de/goto_docu_wiki_wpage_5879_1357.html) to make ILIAS more accessible. 

> Aria landmark roles allow identifying the organization and structure of ILIAS. They classify and label different sections of ILIAS, allowing screen readers to read out visually conveyed structural information. Screen readers provide keyboard navigation to landmark roles.

To make these changes more comprehensible, you find some explanations for each landmark role listed below. You will probably also need these references:

- [Landmark Roles by W3C](https://www.w3.org/TR/wai-aria-practices-1.1/#landmark-roles)

- [Landmark Roles by MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles) (less official, but more comprehensible)

Banner:
- `role="banner"` is added to the page template
- `<header>` tag cannot be used here because its context is not the `<body>` element and it is descendant of `<section>` element

Footer:
- `role="contentinfo"` is added to the page template
- `<footer>` tag cannot be used here because its context is not the `<body>` element and it is descendant of `<section>` element

Navigation:
1. The `<nav>` tag for main controls (Mainbar + Slates) is removed because Slates are not always used for navigation and can contain other content. Only the Mainbar gets the `<nav>` tag instead.
2. The UI Tree gets a `<nav>` tag.
3. The Legacy Tree gets a `<nav>` tag.
4. For Breadcrumbs, only the second level in the HTML gets the `<nav>` tag. In the first level, the tag is removed because the screen reader should not identify empty breadcrumbs as a landmark role and also not read it twice when breadcrumbs are shown.

- Because there are multiple navigation, each of them gets an `aria-label` to distinguish them.

Main:
- `<main>` tag is already used in page template, no changes needed here

Complementary:
- `<aside>` tag is added to the right page content

Form:
- Forms in ILIAS do not have `aria-labelledby`,` aria-label` or `title` element. That is why they must get `role="form"`. This is already given and no changes are needed.

Search:
- The Bulky Button for Search in the Metabar gets `role="search"`

Dialog (no landmark role):
- Slates in the Metabar get `role="dialog"`

Tab (no landmark role):
- First-level tabs already have `role="tablist"` respectively `role="tab"`, no changes needed here

A link to a test installation, where these changes are included, can be found [here](https://test72.leifos.com/60arialandmarkroles/). If you wish a user, please contact me or @atoedt.

kindly,
@tfamula

### CODE REVIEW

**Comment by tfamula** [comment]
TODO:

- [ ] Check and repair unit tests

**Comment by atoedt** [comment]
Thank you for combing through the role concept and applying it to ILIAS 6. 
I looked at this pull request for what I am worth and I think it is good. 

However I would like to get back to your offer of providing me and - more important - blind testers with an installation. This would allow consuming the aria role of this PR with a screen reader.  

Please provide me with an installation. That would be very helpful for me.

**Comment by tfamula** [comment]
A link to a test installation, where these changes are included, can be found [here](https://test72.leifos.com/60arialandmarkroles/). If you wish a user, please contact me or @atoedt.

**Review by alex40724 — APPROVED** [review]
Explorer changes are fine for me. Thanks.

**Review by klees — CHANGES_REQUESTED** [review]
Hi @tfamula,

thanks for working on the accessibility of the components in the UI framework (and of course the other components). Please note that our review is about the changes in the UI-framework only.

You presented a lot food for thought, as you could see in our answers, suggestions and change requests. When adding accessibility semantics the devil is in the details, it seems. It is worthwhile to look carefully into these details though, as the accessibility semantics we add to our HTML will be important means for some people to perceive our system. Or as W3C puts it: [No aria ist better then bad aria](https://www.w3.org/TR/wai-aria-practices-1.1/#no_aria_better_bad_aria). This should receive just as much attention and care as our visually perceptible user interface, if we want to take accessibility seriously.

As a general goal we should try to create semantically and correct HTML, as this will help all kinds of users, with or without assistive technology and save us the work of maintaining two diverging representations of the same things. Aria is intended to [stimulate the evolution of the host languages](https://www.w3.org/WAI/PF/aria/complete#co-evolution), where these should be used if they provide strong enough semantics. You mostly implemented that (by, e.g., using `<nav>` instead of the `navigation`-role), and we use some HTML 5 elements with stronger semantics in other places as well (`<button>`, `<header>`, `<main>`, ...). We still want to stress this point. There is some opportunity to do better, in this PR and in the future.

Please answer the following questions:
- [x] Banner vs. Header: As we understand the relation between the HTML-tag `<header>` and the landmark role "banner", [those two have an identical meaning unless header is wrapped in a section (and some other tags)](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role), which would make it the header of that section. This is indeed the case in our standard page template. But wouldn't it be a simpler move to just replace the [`<section>`](https://github.com/ILIAS-eLearning/ILIAS/blob/release_6/src/UI/templates/default/Layout/tpl.standardpage.html#L29) in our page template with a `<div>` or even remove it altogether instead of introducing that landmark role? Using a `<section>` to wrap the complete content of the page seems to be odd anyway, so by just removing or replacing that outer `<section>`-layer we would also improve the semantic clarity of our HTML.
- [x] Dialog Role: We wonder how the decision to use the dialog role for the Meta Bar slates was derived. The [description](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal) kind of matches the slates, but some of them more act like other dropdowns, e.g. "Actions". Does "dialog" really fit the dropdown below my avatar? Would we want to assign "dialog" to the action menus and other dropdowns as well? Why wouldn't we want to use the menu role or the `<nav>` tag for the options below my avatar? The [description for menu](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) also seems to fit well: "A menu is a widget that offers a list of choices to the user, such as a set of actions or functions. A menu is usually opened, or made visible, by activating a menu button, choosing an item in a menu that opens a sub menu, or by invoking a command, such as Shift + F10 in Windows, that opens a context specific menu."
- [ ] Metabar Label: Why did you introduce a label for the Main Bar but not for the Meta Bar?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [x] German Main Bar: We propose to use `Hauptleiste` as german name for the Main Bar.
- [ ] Tree Aria Label: The UI Tree component is intended to be used for a range of different trees, like the repository tree, the org-unit tree and the taxonomy tree. The current proposal just labels all the trees with "tree", which doesn't seem to be too helpful. Let's introduce a required `label`-property on the UI Tree and use it as the aria-label instead. This seems to be a good time for that move, because currently the UI Tree isn't used too much and it seems feasible to add these labels retroactively.

Please implement the following changes:
- [x] Footer: In parallel to our remarks on "Banner vs. Header", the `<footer>` seems to in an odd place as well. Semantically it belongs to the `<body>`, but we needed to place it inside `<main>` section to put in below the content and besides the Main Bar visually. So the landmark-role atm is the right way to say that this indeed the footer for the whole page. Please add a long term entry in our roadmap outlining that tension between semantics and optics to remind us to fix that issue and then also remove that (then duplicate) landmark role.
- [x] Tree Role: From our understanding, the [Tree View roles](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView) would be the right choice for the trees. Please add them and remove the `<nav>`-tag you added. Stick the aria-label to the `<ul>` node instead. TreeView seems to be the exact description of what out tree is doing. `<nav>` on the other hand seems to be wrong, because the tree is not a simple group of links for navigation. We think [this example from W3C](https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html) is exactly what we have.
- [x] Button::withLandmarkRole/search role: Remove the `Button::withLandmarkRole` and `Button::getLandmarkRole` completely. The only use case is to add the `search` role [here](https://github.com/ILIAS-eLearning/ILIAS/pull/2500/files?file-filters%5B%5D=.css&file-filters%5B%5D=.html&file-filters%5B%5D=.php#diff-1bf7a0dfe0d0af761e9b8cd484e3a951R290). This in turn seems to be a misunderstanding of the purpose of this role. [The W3C docu says](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_search) that a "search landmark contains a collection of items and objects [..]", which isn't the case for the button but instead for the form that opens when clicking that button. That form already has the role. So we should be alright here and do not need that additional code.
- [x] Slate::withLandmarkRole: Currently we would allow all strings here. Please narrow down the set of allowed landmark roles to the ones we require for slates by using constants for the roles and only allow arguments to `withLandmarkRole` compliant with these constants. Currently we would only have `dialog`, right? Depending on our question regarding "Dialog Role", we might want to move the usage of the methods out of the renderer to the locations where the slates are created.
- [ ] Main Bar: Using `<nav>` for the Main Bar seems to be wrong, because, contrary to the [description of `navigation`](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_navigation) the Main Bar does not contain links (mostly). Also, it is (mostly) intended to open slates instead of navigating the page content. Using the ["Menu Bar" roles](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) seem to match the functionality of the bar a lot better. Also, using that roles might already solve [this issue](https://mantis.ilias.de/view.php?id=27512). The description says, that "When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item." which seems to be the behavior requested in the issue. Depending on the answers in "Dialog Role", this role might also be what we would want for the Meta Bar, which for one would be a nice unification and second would remove the requirement to introduce `Slate::withLandmarkRole` altogether.
- [x] Type Hints: Use type hints where possible and remove doc-strings where they don't add any additional information.
- [x] Accessibility Rules: Add accessibility rules to the appropriate UI components that cover our decisions regarding labels, roles and use of HTML5 tags. We intend to test the UI components in the future via testrail, just as we do with other ILIAS components. The KS entries for the components then will be a major source for testers. By adding the accessibility rules we make sure that the desired accessibilty properties don't degrade in future ILIAS versions.
- [ ] Tests: If we keep any changes in the PHP of the UI components, please add tests to cover them.

Please get back to us if you need to discuss anything, be it our questions, suggestions and change requests or the next steps. We understand that you might be acting under some constraints that won't allow to implement everything that is desired, but we would at least like to understand how you would like to move on with that topic. We are all committed to provide accessible UI components to all our users, so let's find a way forward together.

Best regards!
@klees and @Amstutz

**Comment by tfamula** [comment]
Hello @klees and @Amstutz,
thanks for your extensive feedback! I really appreciate your effort here.
Next week, I will have a meeting with a disabled person and @atoedt, where we will also discuss Aria (Landmark) Roles. I believe this will be very informative. After that (and hopefully with many new impressions), you will get an answer of me.
Just wanted to inform you quickly about this waiting time ;)

Greetings
@tfamula

**Comment by Amstutz** [comment]
@tfamula , any update on this?

**Comment by tfamula** [comment]
@Amstutz You will get an answer in the coming days. Thank you for your patience!

**Comment by tfamula** [comment]
Hello @klees and @Amstutz,
the meeting with the disabled person was insightful and hard at the same time. We managed to talk about some of the problems. My answer to your feedback will be kind of a mix of my own opinion and real problems of the disabled person.

My general impression of your feedback is, that you want to find the best Aria Roles for the UI Components, while my target in this PR was to assign Aria **Landmark** Roles to suitable UI Components. Disabled persons respectively their screen readers should be able to identify the page structure of ILIAS with its different sections. Aria Landmark Roles should help these persons to skip sections of the page, so the persons can reach the desired element more quickly and do not have to tab around the page each time. The problem is, that this cannot be reached with every Aria Role, but only with Aria Landmark Roles which were made i.a. for this purpose. Maybe a compromise is needed here. I agree with you that "no aria is better than bad aria". I think we must try to find solutions which fulfill the need of Aria Landmark Roles in ILIAS and also do not break any accessibility semantics. And, most importantly, a disabled person must be able to control ILIAS with assistive technology in a proper way at the end of the day.

Your questions:
- Banner vs. Header: Thank you for this question! Actually, I really thought about getting rid of the `<section>` in the template. But I was afraid to mess up something if I simply remove it. I was wondering about the `<section>` element here and it seemed like it was chosen for a good reason. Additionally, I I think we still need the css-class within the element and it must be on exactly this level in the template to fulfill the expected design. That's why your second proposal to change it to `<div>` seems to be a good solution here.

- Dialog Role: To be honest, I don't remember exactly why we decided for the "dialog" role here.  I am not attached to the Dialog Role. Your proposal to change it to "menu" is very feasible to me.

- Metabar Label: I introduced an aria-label because of the Aria Landmark Role "navigation" I added here. The [description](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_navigation) says: "If a page includes more than one navigation landmark, each should have a unique label." This is currently the case in this PR when Mainbar and Breadcrumbs are on the same page. A disabled person must find out which exact navigation s/he is triggering. For the Metabar, this will be mandatory if we assign the role "menubar" to the whole Metabar. I would support this. What I am not sure about, are the labels for the Mainbar/Metabar entries (menuitem) and the Slates of the Mainbar/Metabar (menu). I think they must be added at least for the Slates to tell a person which Slate s/he currently uses. The Metabar entries (Buttons) maybe do not need them because the Glyphs already have `aria-label` and the screen reader reads them out. And the Mainbar entries have text under their icons which the screen reader notices as well.
Maybe we should even use `aria-labelledby` here to make the relation between Button and Slate clearer? You see I am very unsure here, I hope you have a suggestion for that. For now, I only implemented the `aria-label` for the whole Mainbar/Metabar (menubar).

Your suggestions: 
- German Main Bar: Thank you for this one! "Hauptleiste" sounds good to me. Is this the official translation, too? I was not sure if we have a german translation for "Mainbar" or if we use the English word. Is there also a german translation for "Metabar"?

- Tree Aria Label: This label was introduced by me because of the (wrong) Aria Landmark Role I added for the Tree. Then, this label became a requirement. My idea was also to use a label which tells the blind person what specific Tree s/he is triggering. But I thought that it is too late to implement such a label. And that was the reason why I chose the very general label "tree" here just to fit the requirement for the label, which I dislike myself. But if you say it is not too late because the UI Tree is not used too much yet, then I really support this! I added the label for the Tree and will fix the existing usages of the Tree in a second step shortly in consultation with the Maintainers (for now, I marked them with "Testlabel").

Your changes:
- Footer: I totally agree. And I see that you understand my intention by adding the (usually unnecessary) Landmark Role. I hoped to solve this problem therewith. But while testing the Landmark Roles with the blind person, I was told that the Footer was not found immediately. When it was found, it was only possible through the Landmark Role "main" because the screen reader (NVDA in this case) nests the "footer" one level under "main". This is very confusing. So yes, I support your idea to fix that issue, but I would not prefer to do it as a **long** term entry. There is already a [bug](https://mantis.ilias.de/view.php?id=27934), which concerns this problem. Let's continue the discussion there, because this could need a more detailed consideration and I expect some opposition. For now, we must get along with the current solution.
- Tree Role: Change accepted. I also added the other related Aria Roles for the Tree, as well as the aria-expanded attribute. By the way, I figured out that expanding/collapsing the nodes in the UI Tree is not possible with a keyboard, only with a mouse. Can you confirm? If yes, I would write a separate Mantis ticket for this.
- Button::withLandmarkRole/search role: I understand your argument here. The thing is, we badly need the `search` role for the button here, because otherwise a blind person will never spot the search in ILIAS with the help of Aria Landmark Roles. You are right when you say the search form has already the role. But the problem is that the search form is "hidden" inside the Slate. The Slate will only visible to the screen reader when triggering the Search Button in the Metabar. So either we still keep the (not really) correct `search` role or we make the role from the search form visible to screen readers, which would probably mean that we remove the search form from the Slate and put it directly in the Metabar somehow. Besides that, the mutator for the Aria Role is still needed here if we treat the entries in Mainbar and Metabar as "menuitem" now.
- Slate::withLandmarkRole: I hope I implemented your proposed changes correctly here.
- Main Bar: I totally understand your point here. But in reference to the testing experiences with our blind person I can say, that we absolutely need the `<nav`> tag respectively the Aria Landmark Role here. Otherwise, when the person is navigated e.g. to the Dashboard where also no Breadcrumbs are shown, s/he will have no idea how to navigate in ILIAS because the screen reader won't find the related Landmark Role. The Mainbar is actually understood as a navigational element. And also the description of the Mainbar in the Kitchensink says, that it forms "_the primary list of navigational options for the user and the usual starting point for the user to explore the system._".
If you look at my changed code, you will see that I tried to match both requirements, the Landmark Role "Navigation" and the menu stuff. I checked it with the screen reader and the output sounds good. For the Metabar, I also changed the `aria-role`s to hopefully fit the menu concept, but without the navigational aspect. 
I used [this example](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html) as kind of a pattern. But this example is much less complex because it uses simple links for the "menu" while our "menu", which would be the Slate, can store much more complex content. I'm afraid that there is much more conceptual work needed if my current proposal is not sufficient. 
Additionally and unfortunately, my current implementation also does not fix the [bug](https://mantis.ilias.de/view.php?id=27512) you mentioned regarding the tabbing order.
To answer your last sentence, I would not remove `Slate::withLandmarkRole` because this would mean that every Slate get `aria-role="menu"` and I believe that this is not the case now or in the future.
- Type Hints: Done, to the best of my knowledge and belief...
- Accessibility Rules: Done! I hope I covered everything at the right place.
- ~~Tests: I skipped this at first because I assumed there will be some changes after initial commit. I think we are still not finished, but I will start with the tests in the meantime.~~

Sorry for so much text. We absolutely have the same goal: to provide accessible UI components to all our users. And I am glad that you consider this topic very seriously. I give my best to extend my expertise more and more to make ILIAS accessible as much as possible. During my work, it is sometimes a little bit hard to stay motivated when I run out of ideas because ILIAS is not simply structured as you would wish after looking at some examples from the W3C docu :smile:  But I am still confident that we will make it together, you two, me and all the other colleagues who deal with accessibility in ILIAS :)


Greetings @tfamula

**Comment by tfamula** [comment]
@alex40724 I reverted the changes in the Explorer. Like @klees correctly mentioned, just the Tree View roles should be used here and the Aria Landmark Role "Navigation" at this place would be wrong. If other accessibility issues in the Explorer come up, we should address them in Mantis tickets.

**Comment by klees** [comment]
Hi @tfamula,

just to inform you about @Amstutz and my schedule: I need to prioritize this down a little and look into the Assessment Question Service first. I everything goes according to plan we'll give our feedback in the next week.

Best regards!

**Comment by klees** [comment]
Hi @tfamula,

I'm in here for about three hours now and I'm still not through. There is lot to digest here. I won't make it today, I have some other stuff on my agenda. I'll continue on monday and hopefully will finish then.

Happy Easter!

**Comment by klees** [comment]
Hi @tfamula,

I'm through now. @Amstutz and me now try to agree on a common statement, I hope we'll get there tomorrow.

Thanks for your patience!

**Review by klees — CHANGES_REQUESTED** [review]
Hi @tfamula

Thanks a lot for your energy. And don't be sorry for the amount of text. On the contrary, this is a very complex subject and we highly welcome insights and feedback.

Furthermore, we feel that this subject has such a high impact and so much underlying complexity, that we need to wave it much more tightly into our development processes. E.g. we need a champion that we can ask for feedback on concrete issues (e.g. as happened with letter avatar and other components). This champion needs technical background (as you do) and needs to be able to connect the user group having to deal with the result of our work with us (as you did bellow). If you are interested in further fostering this topic and extend your knowledge in this area, let us know.

Thank you very much for your detailed answers, here the response:

- Banner vs. Header: Thanks for looking into this and replacing the `section` with a `div` for more semantic clarity. We might remove the div in the future altogether, since it seems somehow redundant, and we do not really see how the class at this level gives any advantage over just starting with body. However, this must not be your concern.
- Dialog Role: Thanks.
- Meta Bar Label:  Thanks for adding the aria-label. The use of `aria-labelledby` to make a connection between the slates and the buttons seems to be a good way forward too. If you agree, we should proceed with that approach. Please make that move in a second PR after this one here is merged to keep the changes manageable here.
- German Main Bar: So we agree on "Hauptleiste", neat. How about "Metaleiste" for Metabar, to maintain the translation of "bar" to "Leiste" at least? There doesn't seem to be another good translation for "meta", though.
- Tree Aria Label: Thanks for going through this here. It's a big improvement.
- Footer: Thanks for the feedback. We are fine with your proposal of sourcing this out to the linked bug report to not block progress here. Any suggestion is highly appreciated. Please open a separate PR if you attempt to solve that problem, though.
- Tree Role: Thanks for improving this. Regarding usage via keyboard: Yes, this does not seem to work. However, note that there are probably two entries needed. One for the new implementation (which IMO partly works, however the expand css on the left seems to be an issue there, it never gets the focus) and the legacy tree. Also, this seems to a be a very good example why accessibility considerations should be a concern much earlier in the development of UI components.
- Search-Role for Button: We totally get the reasons why a `search`-role should be available in a way that is perceivable to screenreaders. But sticking it to the button seems to just not fit the [semantics of that role](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_search). "[S]earch landmark contains a collection of items and objects [..]" would imply that the Glyph/Button and the Slate should get the role. We have the technical difficulty that the slates triggerer (Glyph or Button of the Slate) and the slates other contents are rendered in different places. However, we are unsure what the effects would be if we place the Search Role on the Button. Would the slates content then also need this role? Would this already save the day or would additional work be needed for the screenreader to find the slates content? Would we need something like aria-haspopup? This might just be a case for the "no aria is better than bad aria"-rule. Still there might be alternatives, where you point one out ("remove the search form from the Slate"). Did you check if the current `search`-role on the form will be perceivable for the screenreader if the Slate gets an "aria-hidden=false" instead of "=true", even if it isn't displayed to sighted users? This even might be the way to go for other slates. That expanding/hiding-behaviour seems to be a way to cope with sparse space on the screen of sighted users, but screenreaders don't seem to have the same problems. So maybe we could try to make the slates (at least in the Meta Bar, but maybe in the Main Bar as well) visible for screenreaders. To move on with this PR: Maybe we could remove the according code and discussion from this PR altogether and move it to a new PR?
- Slate/Button::with(Aria|Landmark)Role: We might need a mutator for setting an aria role on Buttons and/or Slates for the implementation,
but we should not require our consumers to set these roles (labels, ...) via the public interface of our components, unless we absolutely have no other choice. Optimally, the correct aria-roles, labels, etc. should be derived internally in the UI-framework, i.e., our knowledge about how accessibility is achieved should be implemented in the UI-framework rather then being requested from our users. This might no be possible in every case (e.g. we surely can't derive alt-texts for images in the UI-framework) but these landmarks and roles introduced here don't seem to be such a case. E.g. the `menu-item`-role could just be set in the Renderer of the Main Bar. We will therefore neither require that `withAriaRole` on the public interface nor require our consumer `GlobalScreen` to call it to set the aria-role correctly. Instead we propose to just add the mutator on the implementation side only for other UI components to be used. We agree if you would like to make that change (removing `with(Aria|Landmark)Role` from the public interface) later on in a new PR.
- Main Bar: We are fine with your proposed way forward and trust your experience with the tests you did (thx a lot). We believe that further improvement is necessary but further think that the proposed solution has to suffice for this release. We further agree on keeping the landmark role for slate but would like to remove it from our public interface (see "Slate/Button::with(Aria/Landmark)Role" above).
- Type Hints:  Thanks so far, but please have a look again. There are some type hints missing [1](https://github.com/ILIAS-eLearning/ILIAS/pull/2500/files#diff-c82f14bc22fbf714fc74ffcec3f4d675R24), [2](https://github.com/ILIAS-eLearning/ILIAS/pull/2500/files#diff-4fb98be82c321f9af986b5d608ea0b09R88), [3](https://github.com/ILIAS-eLearning/ILIAS/pull/2500/files#diff-4fb98be82c321f9af986b5d608ea0b09R81), ...
- Form Accessibility Rule: Please remove it for now and maybe reopen this as a new PR. We also doubt that we really need this role in every case, so the `MUST` seems to be too strong. We currently use the TML-tag, which should be enough, in some cases we also might require the `search`-role for the form.
- Other Accessibility Rules: Thanks a lot. Note that they trigger a JF discussion. We attached the label accordingly.

So, we generated to following things left todo to wrap this up:
- [ ] Assign Role „Menubar“ to the Metabar.
- [ ] Follow up on the labelled-by option for the slates.
- [ ] Follow up on the maintainers to find the right replacements for the „Testlabels“
- [x] Follow up on the landmark-role-question, see Button::withLandmarkRole/search role above.
- [ ] Cases in Testrail: In the last JF we decided, that we also need a set of test cases in Testrail to reflect changes in the UI components. Can you create/link them? Maybe touch back with Fabian Kruse to find a good entry point to add them.
- [ ] Add/Fix Unit tests: When everything is decided upon.
- [x] Remove accessibility rule for form.
- [x] Add various type hints.

Please do not add any new changes to the PR, let's instead try to bring this to an end. Still, we are looking forward to our future discussions. Please get in touch if you want to discuss any of our requests, opinions or suggestions.

@amstutz and @klees

**Comment by tfamula** [comment]
Hi @klees and @Amstutz 

Thanks again for your constructive feedback! Here the response for the open points:

- Banner vs. Header: How do we want to document this insight to not forget about it? With a Mantis ticket? With a Roadmap entry?
- Meta Bar Label: I will put this on my to-do list, check this again if this is expedient and, if applicable, try to tackle this point in a separate PR.
- German Main Bar: I agree. 
- Tree Aria Label: I remove the part with the `aria-label` in this PR and create a separate PR when this one is merged. I do not want to confuse the maintainers with the other stuff here.
- Footer: I will follow-up this issue in a separate PR and already have a first idea (or at least I hope so).
- Tree Role: You are right, the legacy tree also needs some love here. But basically, the navigation with a keyboard works better than with the UI Tree. So yes, we should track these problems separately in tickets. I will do that. However, I'm not sure yet if I can solve them, too.
- Search-Role for Button: I see your point. Unfortunately, the way how the Slate triggerers and the Slates work, is not really suitable to implement the `search` role in a proper way. I'm sorry to say your proposal to use `aria-hidden=false` instead of `aria-hidden=true` for Slates will not work, too. The Slates use `display:none` and that's why they do not appear in the accessibility tree, even when we would use `aria-hidden=false`. Furthermore, no example comes into my mind, in which we could use `aria-hidden=false` for blind persons, but hide the same content at the same time for sighted persons. Please also note in this regard, that always identical or equivalent meaning and functionality must be exposed for sighted and blind persons. Back to the `search` role: I will remove it for now. I will put this on my list and try to find a way to make the role findable for screen readers and also fit the semantics.
- Slate/Button::with(Aria|Landmark)Role: Thanks for clarifying this point in our VC. I agree and implemented it like that.
- Main Bar: Also done.
- Type Hints: Thanks for the hints. I hope I found everything now.
- Form Accessibility Rule: Ok, I see your point. The `form` role would not fit in every case. But only the HTML-tag would not be sufficient to identify the form as a landmark region. The [documentation](https://www.w3.org/TR/wai-aria-practices-1.1/#html-techniques-1) says: "The HTML form element defines a form landmark when it has an accessible name (e.g. aria-labelledby, aria-label or title)." My proposal is to change the rule to: "Forms SHOULD bear the ARIA role 'form' if there is no good reason to use another ARIA role, like e.g. 'search'". But then, the next problem comes up. In the template, `role="form"` is [defined fixed](https://github.com/ILIAS-eLearning/ILIAS/blob/613535a1eb8f9778c704d54af613e73fdd3d6333/src/UI/templates/default/Input/tpl.standard.html#L1) (what was also the reason why I thought writing this down as a MUST-rule would be fine). If this shall be changeable, we would need a mutator `withAriaRole` like for the Bulky Button and Slate, correct? And, in contrast to the other components, we would need it in the public interface IMO, because we do not know which type of form the consumer creates. And that would again mean, that the consumer is responsible to set the correct ARIA role... Really not easy how to proceed here. Do you have an idea? For now, I remove the rule and leave the form as it is. If we decide for a solution here, I will create a separate PR.

> - [ ] Assign Role „Menubar“ to the Metabar.

Do you maybe mixed up something here? Because the Metabar already has this role.

> - [ ] Cases in Testrail

My main obstacle is that I simply have no Testrail account. I will ask the JF how we should proceed with such problems when there are changes in the UI components which needs to be considered in test cases.

Greetings 
@tfamula

**Comment by matthiaskunkel** [comment]
Jour Fixe, 27 APR 2020 : We highly appreciate this suggestion and accept the PR for trunk and release_6. Please merge.

**Comment by Amstutz** [comment]
Hi @tfamula 

What is the state here, is this in your opinion ready for merging? What is the state of the testrail cases. Thx for sticking around for so long with this, looks like we finally can bring some closure to this ;-).

Thx.

**Comment by tfamula** [comment]
Hi @amstutz, 
I guess I got something wrong here. I was expecting another feedback from you and Richard, especially for the remaining questions, and that's why I was waiting. But you are right, let's bring this PR to an end! Most of the questions, which are still open, should be tackled in separate PRs, anyway.
I fixed again the unit tests and added an entry to the roadmap. Today, or at the latest tomorrow, I will add the cases in Testrail, which cover the new rules in the UI Components. I already got a Testrail account from Fabian. Actually, the presence of the testcases is independent of this PR. IMO, you can already merge it. 

Greetings
@tfamula

**Comment by tfamula** [comment]
Testcases can be found here: [Click](https://testrail.ilias.de/index.php?/suites/view/390&group_by=cases:section_id&group_id=8016&group_order=asc)

**Review by Amstutz — APPROVED** [review]
@rklees, Feel free to merge as soon as ready.

**Comment by klees** [comment]
I will probably have time to look into this in the next week.

**Comment by Amstutz** [comment]
friendly ping @klees

**Comment by klees** [comment]
Hi @tfamula,

this looks fine, besides the merge issues. Please rebase this onto trunk, resolve conflicts and ping me immediately so I can push the button. Any idea when you'll be able to look into this?

Best regards!

**Comment by tfamula** [comment]
Hi @klees,
conflicts were solved, should be good now. Thanks!

**Comment by tfamula** [comment]
@klees These changes must also be implemented into Release 6 because they count as a bugfix. This is accepted from the JF, too. Shall I do it?

**Comment by klees** [comment]
@tfamula Yes.

**Comment by tfamula** [comment]
Done, see [here](https://github.com/ILIAS-eLearning/ILIAS/commit/967ddb4e4d0ecd5fbd5e2246c5be49bf86e0b422)

**Pull request merged**
