### PR TITLE
MainBar/Performance: Prevent DDoS-like HTTP requests when resizing wi…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
... ndow

Mantis Issue: https://mantis.ilias.de/view.php?id=30610

### CODE REVIEW

**Comment by Amstutz** [comment]
Nice one, looks good to me. @nhaagen can you look at this as well and give some feedback, if all lights green, we could merge this and push to 7 and trunk as well.

**Comment by nhaagen** [comment]
Thank you,  good finding. However, I do not really agree with the solution.
While it's certainly ok to be less exited about rendering, the actual issue is reloading of slate-content, triggered by renderer.engage via this.getElement().trigger('in_view');
Maybe better wrap this one into something like

if(!this.getElement().hasClass('gs_triggered')){
    this.getElement().trigger('in_view');
    this.getElement().addClass('gs_triggered');
}

**Comment by mjansenDatabay** [comment]
Even better if there is an easy fix like the one proposed by @nhaagen

**Comment by klees** [comment]
I think we could do this (for trunk at least) anyway, because, as @nhaagen says, we don't need to be that excited on rendering when resizing the window. But we should only add that complexity if there actually is any perfomance hit from the actual rendering (besides the requests).

I agree with @nhaagen that this does not seem to fix the root cause of the initial problem, though.

**Comment by Amstutz** [comment]
Thx a lot. See comment in #3610 for the explanation in the decision on this one.

**Pull request closed without merging**
