### PR TITLE
TinyMCE 3.5.11 Hungarian lang files

### PR DESCRIPTION
**Pull request by KissDaniGH**
It makes TinyMCE hungarian

### CODE REVIEW

**Comment by KissDaniGH** [comment]
Hi
is it possible and allowed to merge official TinyMCE hun files to merge into trunk?
If yes, I'll pull a new one, to keep off this conflict.
regards, Daniel

**Comment by chfsx** [comment]
I think this should be possible, did you find the hun files from the correct version?

**Comment by KissDaniGH** [comment]
sure. 3.4.7 and 3.5.11.

**Comment by KissDaniGH** [comment]
@chfsx 
hi Fabian,
could you please check & merge #191 ?
Thanks in advance, Daniel

**Pull request closed without merging**
