### PR TITLE
WIP: Fix/php8/modules/orgunit

### PR DESCRIPTION
**Pull request by mstuder**

### CODE REVIEW

**Comment by mstuder** [comment]
@chfsx 
i removed the Modules Orgunit ArHelper\DIC trait from several classes of you. Please check them

```
Modules/Bibliographic/classes/Admin/Library/class.ilBiblLibraryFormGUI.php
Modules/Bibliographic/classes/Admin/Library/class.ilBiblLibraryGUI.php
Modules/Bibliographic/classes/Admin/Library/class.ilBiblLibraryTableGUI.php Modules/Bibliographic/classes/Entry/class.ilBiblEntryDetailPresentationGUI.php
Modules/Bibliographic/classes/Entry/class.ilBiblEntryTableGUI.php
Modules/Bibliographic/classes/FieldFilter/class.ilBiblFieldFilterFormGUI.php
Modules/Bibliographic/classes/FieldFilter/class.ilBiblFieldFilterGUI.php
Modules/Bibliographic/classes/FieldFilter/class.ilBiblFieldFilterPresentationGUI.php
Modules/Bibliographic/classes/FieldFilter/class.ilBiblFieldFilterTableGUI.php
Modules/Bibliographic/classes/Translation/class.ilBiblTranslationGUI.php
Modules/Bibliographic/classes/Translation/class.ilBiblTranslationTableGUI.php
Modules/Bibliographic/classes/class.ilObjBibliographicGUI.php
Services/BackgroundTasks/classes/class.ilBTControllerGUI.php
Services/Form/classes/class.ilFileStandardDropzoneInputGUI.php
Services/MainMenu/classes/Administration/class.ilMMItemTranslationGUI.php
```

**Comment by mstuder** [comment]
@chfsx , @mjansenDatabay , @klees , @alex40724 , @smeyer-ilias , @Amstutz , @mbecker-databay 

with this pullrequest I will change and all dependend classes
ilAccess::_checkGoto(string $a_target): bool
ilObjectListGUI:getCommandLink(string $a_cmd) : string

currently the test fails because of ilias setup - i'll wait until the setup is fixed and the tests succed

```

> php setup/cli.php build-artifacts --yes

Building Static Artifacts for ILIAS
===================================

Build Services/Component/artifacts/component_data.php...                   [OK]
Build Services/Component/artifacts/plugin_data.php...                      [OK]
Build Services/GlobalScreen/artifacts/global_screen_providers.php...       [OK]
Build ./Services/Style/System/data/data.php...                             [OK]
Build ./Services/UICore/artifacts/ctrl_base_classes.php...                 [OK]
Build ./Services/UICore/artifacts/ctrl_structure.php...                    [FAILED]

Error: ] syntax error, unexpected token ":", expecting ";" or "{"               


Build ./Services/UICore/artifacts/ctrl_security.php...                     [OK]
In ObjectiveIterator.php line 125:
                                       
  Objective had failed preconditions.  
                                       

build-artifacts [-y|--yes] [--plugin PLUGIN] [--no-plugins] [--skip SKIP]

Script php setup/cli.php build-artifacts --yes handling the post-autoload-dump event returned with error code 1
Error: Process completed with exit code 1.
```

**Review by mjansenDatabay — APPROVED** [review]
Thx @mstuder , LGTM!

**Comment by klees** [comment]
@mstuder The setup does not fail in the trunk, so there is something else going on there...

Please run `php setup/cli.php build-artifacts --yes -vvv` for further insights....

**Comment by mstuder** [comment]
thanks @klees and thanks @mjansenDatabay 

meanwile i have in addtion some conflicted files. i will check them an commit during this week.

**Comment by daniwe4** [comment]
Hi @mstuder ,
a first check against https://docu.ilias.de/ilias.php?ref_id=10290&cmd=view&cmdClass=ilobjcontentpagegui&cmdNode=j1:j&baseClass=ilrepositorygui results in the following output. 
Please let us know if we should check again.

# Must-Package
### What must be the agreed minimum goal from the community?  - Whether developers, operators or users.

## Goals
 * [ ] ILIAS can be used with PHP 8 without producing PHP-specific errors.
 * [ ] Refactored code conforms to current coding styles
 * [ ] Elimination of all warnings and errors of the static code inspection (without weak | incl. undeclared variables)
   * 24 errors
   * 132 warnings
   * 140 weak warnings
 * [ ] Transfer of GET params into Constructor
   * 85 places where $_GET is used
 * [ ] Avoidance/reduction of POST accesses (e.g. through $form->getInput()) and switch to Request classes
   * 63 places where $_POST is used
 * [ ] Use of SESSION (session object, alternative assignment of static session in constructor member variables)
   * 5 places where $_SESSION is used 
 * [ ] Documentation of all existing typifications as typehints (of parameters, return values and properties)
   * There are some errors, because of using PHP8 features that not supported by PHP7.4, that belongs to type declarations.
 * [x] Creation of a unit test infrastructure in the component

## Requirements and analysis criteria
* [ ] Preserve unit test coverage even in refactoring.
* [ ]  Simple call of all tabs/screens (without e.g. delete and move actions) and fixing of the corresponding bugs
* [ ]  Checking of external libraries
* [ ]  Basis of the refactoring and the reviews is, among others, ILIAS Development Documentation.

# Should-Package
### What do we need to do in the mid-term to catch recurring large code revisions and to refactor more than the minimum?

 * [ ] Expansion of the unit test coverage
  * General and structural improvements and optimisations to the code base. For example ...
   * [ ]  ... in static functions and by removing static methods
   * [ ]  ... by introducing return type declarations
   * ... by typification of all variables
     * [ ] Input/output typing of methods
     * [ ] Typification of member variables
 * [ ]   Use of UI components from the UI framework "KitchenSink" that have been introduced and established in the meantime. Reduction of legacy UI and legacy code.

# Sustainability-Package
### he developer community has identified topics that would also improve the quality of ILIAS from the point of view of PHP and ILIAS in general. Ideally, these topics could be directly addressed in the process of systematic refactoring.

* [ ] Introduction and use of declarations of "strict_types" for data
* [ ]  Replace previous arrays with classes that enable ArrayAccess - in future also getter / setter
* [ ]  Switching previous arrays to generators/data objects

**Comment by mstuder** [comment]
Hi @daniwe4 

Please excuse. This was an old not merged pull request. The new one, already merged is
https://github.com/ILIAS-eLearning/ILIAS/pull/4486

I close pull request and transfer your feedback to the new one.

Best regards
Martin

**Pull request closed without merging**
