### PR TITLE
Capitalize first word letter in dropdown menu

### PR DESCRIPTION
**Pull request by ghost**
As https://docu.ilias.de/goto_docu_pg_1430_42.html it's declared, that texts in dropwown menus should be 
capitalized first letter in each word. ILIAS should this automatic do, like also the form titles are already uppercase

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM, thx!

@Amstutz Please merge if you agree with the change.

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @sragfw 

Thank you a lot for pointing towards this issue.

However, there are some issues with the current suggestions. 

The linked reference we should follow states, that we should use title case for:
- Menu options and pushbuttons
- Field, checkbox, and radio button labels
- Frame, screen, and dialog box titles
- Tab descriptions
- All hierachy nodes and folder names (roles and so on)
- Possible entries, options in drop-down lists
- Column and row headers
- Titles of reports and lists
- All technical short descriptions (names of programs, function groups, and so on)

Meaning, we should probably promote mechanism at least to buttons, not?

Further the exact wording in the linked page is: 

> Title case means that the first letter of each word is capitalized, except for certain small words, such as articles and short prepositions.

The proposed solution "Capitalize" in CSS will capitilize every word in the respective control, e.g. "this and that" becomes "This And That", see: https://developer.mozilla.org/de/docs/Web/CSS/text-transform.

So that will not work, unfortunately. Doing it on php side could be possible with some good transformation, however, could be very demanding to find a good language independent solution for this. This is why all we currently have is the rule for buttons: "Every word except articles, coordinating conjunctions and prepositions of four or fewer letters MUST be capitalized".

I am very open for further suggestions, on how to improve this situation.

**Comment by ghost** [comment]
@Amstutz Something like so?

**Comment by Amstutz** [comment]
@sragfw thx for the feedback.

In this direction, yes, but two things we would need to consider:

1. you would not provide an own thread, you would provide a transformation to achieve your goal. See: [Readme Transformations](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/Refinery/README.md#transformation), to see how they work. Note that Unit tests would need to be provided in src/tests. A good example, where you could copy much is e.g. [Split String](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/Refinery/String/SplitString.php ) with it's [Unit Tests](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/tests/Refinery/String/Transformation/SplitStringTest.php).

2. your implementation would need to consider different languages. This will be very complex. If limited to english, this is already not easy. I once tried to test this rule in a JS test, this was a list I came up with for english:

```
 conjunctions = [
            "after","although","and", "as far as","as how","as if",
            "as long as", "as soon as","as though", "as well as","as",
            "because","before","both","but",
            "either", "even if","even though",
            "for",
            "how","however",
            "if only","in case","in order that","if",
            "neither","nor",
            "once","only","or","now",
            "provided",
            "rather", "than",
            "since","so that","so",
            "than","that","though","till",
            "unless","until",
            "when","whenever","where as", "wherever","whether","while","where",
            "yet" ];
    }
   prepositions = [
            "about", "above", "according to", "across", "after", "against",  "along with","along", "among", "apart from",
            "around", "as for", "as", "at", "because of", "before", "behind", "below", "beneath", "beside", "between", "beyond",
            "but", "by means of","by",
            "concerning",
            "despite", "down", "during",  "except for", "excepting", "except","for", "from", "in addition to", "in back of",
            "in case of", "in front of", "in place of", "inside", "in spite of", "instead of", "into","in",
            "like",
            "near", "next",
             "off",  "onto", "on top of", "out out of", "outside", "over", "past", "regarding", "round","on","of",
            "since", "through", "throughout", "till",  "toward", "under", "underneath", "unlike", "until",  "upon", "up to","up","to",
            "with, within, without"];
    }
    articles = ["a", "an", "few", "some", "the", "one","this","that"]

```
I am sure this list is incomplete, but workable for a start.

**Comment by ghost** [comment]
TODO: I need to make it works with multiple words in a range like `event if` (Is in test case)

**Comment by ghost** [comment]
I think it needs also somthing like a method `withTitleCapitalization` (default is `true`) in buttons/dropdown, so in very rare cases it can switched off

**Comment by ghost** [comment]
I think, I made it work.
Wath do you think @Amstutz ?
And how we can adapt it to supports multi langual?

**Comment by ghost** [comment]
I close this PR and create a new one because it containts unvanted commited private informations, I dont't want in ILIAS repo

**Pull request closed without merging**
