### PR TITLE
Certificate: Fixed migration issue with SCORM objects (https://mantis…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
….ilias.de/view.php?id=25563)

https://mantis.ilias.de/view.php?id=25563

@qdittrich : We highly appreciate a review here. This PR fixes the related issue where SCORM certificates are issued **without** checking the user's learning progress **during migration**. Could you please review and test it locally and give us feedback? Thanks in advance.

### CODE REVIEW

**Comment by qdittrich** [comment]
At the first look, it seems fine to me 👍  I will test it locally and give you feedback

**Comment by legionth** [comment]
Hey @qdittrich,

thank you for your time. Do you have any feedback on this yet? Do you need some additional information to test this?

Let us know :+1:

**Comment by qdittrich** [comment]
@mjansenDatabay @legionth 
I finished my tests and everything works just fine.

Sorry for the delay...
The testing took so much time because when I ran the first tests, I got some strange issues at the migration process. And I had few problems to figure out how to reproduce it.
Meanwhile I could get the cause of the problem and it was an imported course, that seems to broke as it was imported. To be safe, I created an course manually, after presentation of the broken course and removed the old one from the database. Then everything worked like expected.

**Comment by legionth** [comment]
Sounds strange, indeed. Do you have further information what exactly went wrong there?
AFAIK in the domain of the migration, we only look on the file system and if there are any `certificate.xml` in the folders described in the implementations of `ilCertificateAdapter`.
So the chance that the migration is broken by a wrongly imported course (IMO) is very low. Just correct me if I'm wrong ;)

Did you test the Scorm specific part of this PR? If you say its ok, I would merge this PR.

**Comment by qdittrich** [comment]
Yes, I tested the SCORM specific migration. This worked fine.
From my sight you can merge it.

Im not fully sure what exactly went wrong at my tests, but I guess, I made any mistake with the import. I imported the course with scorm modules and also certificate files and db data from one test system to the other. The failure seemed to happen by parsing the files. I'm not that good in reading xml but I think that the problem came from this files.
After I created a new test structure with course, scorm and other files, I never got that problems again. 
On Wednesday, I also created a new export and import of the course, where I got the problems (this time without the files) and with new certificates. This time it worked. So it looks like I did something wrong by copying the files or anything broke the xml on that process.

**Comment by legionth** [comment]
Awesome, thank you! :+1:

**Pull request merged**
