### PR TITLE
Replacement of the legacy modal in assClozeTestGUI

### PR DESCRIPTION
**Pull request by matheuszych**
These changes are part of the [Legacy-UI refactoring](https://docu.ilias.de/go/wiki/wpage_7320_1357).
I replaced the legacy ilModalGUI with the newer Kitchen Sink interruptive Modal.

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @thojou I add you as reviewer in this and some other Removing LUI PRs. If the PR is ready to look into for @kergomard e.g. please ping me on discord or right here. Thanks!

**Comment by dsstrassner** [comment]
@kergomard will review, approve and merge.

**Comment by kergomard** [comment]
Thank you very much for the PR @matheuszych !

Having a second look at this, I would actually suggest to get rid of this modals completely. They are just plain redundant and we would be able to remove a bit of this convoluted javascript (and a very little bit of convoluted php ;-)). I also discussed this with @dsstrassner and we will add a Dev-Issue to the next JF.

Thanks and best,
@kergomard

**Comment by kergomard** [comment]
Thanks again @matheuszych !
We discussed our wish to remove the modal at todays JF ([see](https://docu.ilias.de/go/wiki/wpage_8470_1357#ilPageTocA2119)) and the proposal was accepted. Would it thus be possible for you @matheuszych  to provide a PR removing it?

I close this PR for the time being.

Thanks again and best,
@kergomard

**Comment by matheuszych** [comment]
Hey @kergomard,

This https://github.com/ILIAS-eLearning/ILIAS/pull/8137 PR should do the trick.

Kind regards,
@matheuszych

**Pull request closed without merging**
