### PR TITLE
0024769: Failed test: Orgunit-specific permissions in Individual Assessment

### PR DESCRIPTION
**Pull request by bseglias**
https://mantis.ilias.de/view.php?id=24769

### CODE REVIEW

**Comment by klees** [comment]
Thx, will have a look soon.

**Review by klees — COMMENTED** [review]
Hi @bseglias,

thanks for your efforts to fix this bug. I see why you made the first and third change, both are obvious problems. I do not understand, though, why you removed `userMayDownloadAttachment` and how this relates to the ticket you link. Could you elaborate on that change?

Thanks a lot!

**Comment by bseglias** [comment]
Hi @klees,

Thank you for your feedback. There was no function `userMayDownloadAttachment` in the current trunk version so I removed it in the condition. Without removing it I got the error message `Call to undefined method usermayDownloadAttachment`.

**Comment by klees** [comment]
Hi @bseglias,

the `userMayDownloadAttachment`-problem was solved in #1497 (by adding the missing method), the double `$$` was addressed in #1469, the missing `= null` was taken care of in 99937792ee4342ab543e5630c79fbae30abe3621.

I thus close this PR (and say thanks again for contributing).

**Pull request closed without merging**
