### PR TITLE
5 2 awareness settings

### PR DESCRIPTION
**Pull request by alex40724**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
In this PR the dbupdate_custom.php file is included ;-).

**Comment by alex40724** [comment]
@mjansenDatabay : Please have a short look at ilChatUserActionProvider. Basically it is a refactoring from "awareness feature" to "user action" and additionally two methods that provide the component id and the available actions types.

I would adopt the osc additions in the chat class before committing the changes.

**Comment by alex40724** [comment]
I would not merge this PR 1:1, I will cherry pick everything and take care of the conflicts, change your chat class and, of course, not include the custom update.

**Comment by alex40724** [comment]
Would these changes be ok for you?

**Comment by alex40724** [comment]
I got an ok from Michael. I will close this now and cherry pick.

**Pull request closed without merging**
