### PR TITLE
Cleanup ilAuthSession

### PR DESCRIPTION
**Pull request by klees**
When executing the unit tests for my StudyProgramme I once again got a  `Whoops\Exception\ErrorException: session_start(): Cannot send session cookie - headers already sent by (output started at phar:///Users/rklees/bin/phpunit/phpunit/Util/Printer.php:134)`.

`grep -r ilAuthSession .` in the ILIAS-folder reveals, that there are no locations in the source, where the `global $ilAuthSession` session is used. Thus the propose refactoring to DIC-only is possible.

The according adjustment to the unit test will be done afterwards.

### CODE REVIEW

**Comment by chfsx** [comment]
@klees this PR has currently conflicts

**Comment by klees** [comment]
Resolved Conflict.

**Comment by klees** [comment]
@smeyer-ilias Any chance you'll look into this before beta?

**Comment by smeyer-ilias** [comment]
Thanks I have commited most parts of this pull request in the trunk.

**Comment by klees** [comment]
Hi @smeyer-ilias,

I might be missing something but currently I cannot find any part of this in the trunk.

Regards!

**Comment by smeyer-ilias** [comment]
Sorry, forgot to push. 
It's commit 0fb351f7f1b4e756231221e73ce73dd718fe9175

**Comment by klees** [comment]
Hi @smeyer-ilias!

I'm just working on a presentation for the DevConf regarding Dependency Injection. Since this is PR contained one example for DI I had a look at it again. Doing that I noticed, that you actually commited a different version to what I originally proposed. While my proposal used `new` to initialize ilAuthSession in ilInitialisation, your version uses the singleton pattern to create an instance. Could you comment on why you retained the singleton pattern?

Thx and best regards!

**Comment by smeyer-ilias** [comment]
Hi @klees ,

in the current implementation the ilAuthSession class is strongly tied to the session handling (session_start(), ilSession->[sg]et). In the moment I do not see a use case for creating multiple instances of ilAuthSession, furthermore the class does not support the creation of multiple auth sessions in the moment. Choosing a singleton pattern does reflect this situation: you can only use the global ilAuthSession instance. The creation of multiple instances using a public constructor could destroy the current session. 

Does this approach produce problems for the DI integration?

**Comment by klees** [comment]
Not exactly problems, but some friction in the patterns and approaches.

In the DIC scenario it is the DIC rather then a static member that takes care that only one instance is created. Also it is the source for services that other objects use. I.e. we have a separation of concerns between the things that ilAuthSession really does vs. the creation patterns we use or means we use to resolve services.

I guess this is a good topic for a debate some time, since the singleton pattern is used in many other places as well. I was just curious about the reasons.

**Pull request closed without merging**
