### PR TITLE
Dynamically add css classes to body tag

### PR DESCRIPTION
**Pull request by pebosi**
See #11663

### CODE REVIEW

**Comment by colin-kiegel** [comment]
This should probably be a Jour Fixe decision. I recommend to put this on the agenda.
1. Be aware, that it will be possible to inject arbitrary css-classes into the body-tag by manipulating the URL. You could prevent it with additional prefixing (class="getParamX getParamY getParamZ") - or something similar.
2. The extra tags should be always be present - also if body_class != 'std' && not empty. Otherwise it would be inconsistent.

... Still it feels a bit weird to me. Do you know other web software, which does this?

**Comment by pebosi** [comment]
One example is drupal:
see the body classes of this urls:
https://www.drupal.org/
https://www.drupal.org/project/project_module
https://www.drupal.org/project/views

You could easily customize the colors, etc. on the last url using the unique class "page-node-38878" but drupal has a lot more classes like "logged-in", "front", etc.

1) Inject arbitrary css-classes? who cares, this is not security relevant.

2) i will update the code...

**Comment by otruffer** [comment]
Drupal does not seem to do that with the GET variables though. This would add lots of arbitrary and in most cases unused classes to the body (e.g. hw:i6 for some command node). Those may or may not activate some javascript handlers. While I don't think that adding context oriented classes to the body element is a bad idea in general, I still think doing so based on the $_GET variables is a bad approach as the set of possible classes is undefined.

Maybe => Use the controller to get the commandClass and add some prefix e.g. "contextCss_ilRepositoryGUI". Thus the set of possible css classes are {prefix + cmd | cmd ∈ commandClasses}.

**Comment by chfsx** [comment]
hi @pebosi 

thanks for your PR. we decided in the development-community that new features always  need a feature-request in the feature-wiki (feature.ilias.de), simply that we don't create a new procedure to accept new features in ILIAS core through pull requests. This PR isn't lost, it just needs the regular way of decisions which every feature has to go.  please open a new feature-request and put it to the jour-fixe-agenda, it'll be discussed and decided whether it's accepted or not. all information about feature-requests are listet at http://www.ilias.de/docu/goto.php?target=wiki_1357_How_to_suggest_a_new_feature

thanks a lot for you commitment to opensource software. i'll let this request open and hope you'll link it in you feature request. use this conversation if you have any questions concerning the request

**Comment by chfsx** [comment]
hi @pebosi 

please use the link to this pull-request when you open a feature-request. I close the PR, it's still available when filtering for closed PR.

thanks and best regards

**Pull request closed without merging**
