### PR TITLE
UICore/ilCtrl: Support classes without parents and children

### PR DESCRIPTION
**Pull request by mjansenDatabay**
Mantis Issue: https://mantis.ilias.de/view.php?id=31483

If a PR for ILIAS 8 is needed, I already fixed this in a hotfix branch: https://github.com/mjansenDatabay/ILIAS/commit/8dc514ee78195cbfbba9d4628c802dc9a55d3583

### CODE REVIEW

**Comment by thibsy** [comment]
Hi @mjansenDatabay, I actually fixed the issue in #3970, which hasn't been approved by @alex40724 yet. I don't think this is an ilCtrl issue. Classes without parents or children are considered a base class (for which I created an interface in ILIAS 8) and should either be treated as such or named properly.

**Comment by mjansenDatabay** [comment]
@thibsy The similar issue is also valid for `ilStartingPoint`, `ilTableTemplatesStorage` and `ilNotification`, according to @utesche

**Comment by thibsy** [comment]
@mjansenDatabay but a quick search did not find any references to these classes with `@ilctrl_iscalledby`, so they should not be considered by ilCtrl at all.

**Comment by thibsy** [comment]
I suggest we accept #3970 instead and close this PR (incl. #4151).

**Comment by alex40724** [comment]
@thibsy Please note that e.g. ilTablePropertiesStorage declares itself as base class (ILIAS 6)
```
	<baseclasses>
		<baseclass name="ilTablePropertiesStorage" dir="classes" />
	</baseclasses>
```
and contains a ilCtrl_Calls comment
```
* @ilCtrl_Calls ilTablePropertiesStorage:
```
This was ok to make it work as a base class in ILIAS 6. I did not check the cases mentioned by Uwe yet.

I will just check these cases. If they are all irrelevant, I will close again...

(1) ilTablePropertiesStorage works again in ILIAS 7 because of this change:

```
* @ilCtrl_Calls ilTablePropertiesStorage: ilTablePropertiesStorage
```

(2)
ilTableTemplatesStorage, ilNotification and ilStartingPoint contain ``@ilCtrl_Calls`` comments without having an executeCommand. I will remove these comments.

**Comment by thibsy** [comment]
Hi @alex40724, the class you mention should be called `ilTablePropertiesStorageGUI` instead of `ilTablePropertiesStorage`, otherwise ilCtrl will not treat this class as "necessary" for the control-structure. The convention is `class.il<name>GUI.php`. 

After renaming this class link-targets should work again (similar case as in #3970).

**Comment by alex40724** [comment]
@thibsy As written in (2) above the other cases are non-issues. 

ilTablePropertiesStorage works in ILIAS7 (its being called, if you hide/show a table filter, e.g. in the user administration). The class does not implement a UI hence it was not named this way, still works however.

**Comment by alex40724** [comment]
@thibsy There are 4 base classes in ILIAS 7 not ending on "GUI":

- ilAccordionPropertiesStorage (has been fixed the same way as ilTablePropertiesStorage in ILIAS 7, broken in trunk)
- ilContainerBlockPropertiesStorage (see PR)
- ilSearchController (has children, seems to work in 7, has been renamed to ilSearchControllerGUI in trunk)
- ilTablePropertiesStorage  (fixed in 7, broken in trunk)

**Comment by thibsy** [comment]
@alex40724 could you point me to the mantis-tickets if they exist, or create them if not? Thx!

**Pull request closed without merging**
