### PR TITLE
implemented new icons for administrative notifications

### PR DESCRIPTION
**Pull request by chfsx**

### CODE REVIEW

**Comment by chfsx** [comment]
Sorry I was a bit too late and imlemented the same as @swiniker in #3338 but additionally for Administrative Notifications. I'll update my PR accordingly

**Comment by chfsx** [comment]
strange that there are any conflicts?

**Comment by chfsx** [comment]
rabased and now only icons for ADN :-)

**Comment by Amstutz** [comment]
Hi @chfsx 

Thx. 

#3338 was already merged. With your PR you now define  WBDV twice. The unit tests catched this. 

Probably just remove the WBDV part.

Edit: @chfsx was a few seconds quicker ;-).

**Comment by Amstutz** [comment]
Thx a lot!

**Pull request merged**
