### PR TITLE
Do not show ghost objects in clipboard

### PR DESCRIPTION
**Pull request by padvincenzo**
This PR prevent the bug on mantis: https://mantis.ilias.de/view.php?id=31899 and could also be ported to release_7 and trunk.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@padvincenzo 

Thanks for your pull request.

- Could you please apply the `PSR-2 + X` Coding Standard (see: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/coding-style.md) to the changed file?

Best regards
Michael

**Comment by padvincenzo** [comment]
Hi @mjansenDatabay 
how is it now?

**Comment by mjansenDatabay** [comment]
> Hi @mjansenDatabay how is it now?

@padvincenzo LGTM

**Comment by alex40724** [comment]
Thanks for the PR.

This is fixed differently in ILIAS 6 +.

Moving will be available with ILIAS 8 in general:
https://docu.ilias.de/goto_docu_wiki_wpage_6192_1357.html

**Pull request closed without merging**
