### PR TITLE
UI Avatar: Initial Interfaces and Descriptions

### PR DESCRIPTION
**Pull request by chfsx**
These are the rules and interfaces for the new UI-component-namespace Avatar and it's children LetterAvatar and ImageAvatar.

Mockups and direct links will follow soon

### CODE REVIEW

**Comment by klees** [comment]
Hi @chfsx,

thank you very much for proposing this much needed component!

Some questions:
- [x] 2 Components: You propose 2 components, letter and image avatar. The description seems very similar. Could they but stuffed into one, maybe with something like a „withImage“ mutator? There is some cost in having two components (e.g. adding attributes needs to be done twice or by a trait), we wonder if there is enough gain to have the two here.
- [x] Abbreviation: Where and how will the abbreviation be transformed from the user name? Could this find a place in the refinery? 

Some change requests:
- [x] Limited scope: The currently proposed scope seems to miss some contexts. We believe this should also be extended to places like "Who is online" or the "Member Gallery", extend a little here.
- [x] Icon as rival: We believe that Icon is a further rival. Add it.
- [x] Abbreviation rule: The rule avatar.wording.2 seems to belong to the letter avatar and not the general avatar.
- [x] Missing getters: For the rendering you will probably need some getters for the image, username and/or abbreviation. Add them.

Thanks a lot, we are looking forward to the component. Contact us if you need to discuss anything.

@klees, @amstutz

**Comment by chfsx** [comment]
@klees thanks for this first feedback. 

> 2 Components: You propose 2 components, letter and image avatar. The description seems very similar. Could they but stuffed into one, maybe with something like a „withImage“ mutator? There is some cost in having two components (e.g. adding attributes needs to be done twice or by a trait), we wonder if there is enough gain to have the two here.

I'd suggest to stay with 2 components since a „withImage“ mutator would lead to questions as "what happens to the Abbreviation when using a image? Is there a way back to "Abbreviation-only"? 

> Abbreviation: Where and how will the abbreviation be transformed from the user name? Could this find a place in the refinery?

Hmm, yes, didn't think about refinery for this topic. But wouldn't this be a bit too specific? That would need something like a "LoginNameAbbreviationTransformation", right?

> Limited scope: The currently proposed scope seems to miss some contexts. We believe this should also be extended to places like "Who is online" or the "Member Gallery", extend a little here.

Yes, we should extend to that. But there is currently a problem: The old implementation can't be replaced with the UI-Component that easy. Have a look at `ilUserAvatarLetter`: All consumers of a ilUserAvatarLetter will need the string from `getUrl()` and they will stick that into a img-tag or something else. If we want to use the UI component here internally, then we would have to
a) also provide a kind of getURL in the UI component
b) in case of Letter Avatar (i.e. not as profile picture) work with a data URL (as before). It would be much easier to implement a LetterAvatar only as text/CSS

> Icon as rival: We believe that Icon is a further rival. Add it.

Of course!

> Abbreviation rule: The rule avatar.wording.2 seems to belong to the letter avatar and not the general avatar.

Will be done soon.

> Missing getters: For the rendering you will probably need some getters for the image, username and/or abbreviation. Add them.

I will. I was unsure, because I had to remove them at another PR (but I can't remember which one)

**Comment by chfsx** [comment]
this is the revised version of the pull request, which takes into account the last discussion.

An avatar represents a user in ILIAS. This representation can have two states:
- the user has uploaded and released his own profile picture
- the user does not have his own profile picture

the UI component itself cannot know about this state, but must offer both appearances.

the only thing these two states have in common is the user name. this is relevant for screenreaders and is taken into account in PR. 

ILIAS 5.4 (status quo) has an avatar implementation that requires the consuming components to use the avatar as an image url and not as a unit. Therefore this PR cannot directly replace the previous implementation.

the implementation of this PR will address the complete implementation of the UI component and its use in the metabar. 

open is the question whether the translation of a user name to an abbreviation should be done via the refinery. From my point of view yes, but not in the context of this UI component

**Comment by chfsx** [comment]
a short statement about 'Image' vs. 'Picture':
 in the first versions of the PRs there was talk about image avatars, various discussions in forums convinced me to mention this in this PR 'Picture'.I like to be convinced that it's not. :-)

**Comment by chfsx** [comment]
there is a review container to see the result of the implementation, some screenshots will follow: http://feature-6-ui-avatar-implementation.ilias-core.review.studer-raimann.ch/ (contact me for username/password)

**Comment by chfsx** [comment]
Bildschirmfoto 2020-01-17 um 19 07 58
Bildschirmfoto 2020-01-17 um 19 41 20

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @fschmid

Thx a lot for this revision. LGTM in general. Note, due to the time constraint, I leave an individual feedback, @klees might have additional feedback.

Just a few details, however, none of them would prevent a JF decision. Those changes can easily be adjusted during implementation if the JF accepts it:

- [x] Image vs Picture: I am fine with renaming the Image Avatar to Picture Avatar. However, there are some place that got missed:
  - factory method (still image)
  - Description text in Picture Interface (still image)
- [x] Image vs Picuture: There is one too much that got addapted:
  - Rivals of Icon, I believe, *Image* is still correct there (got changed to image)
- [x] Wording I, Aria Label: We have put this so far in Accessability, move to accessability rule. However, thx considiering the aria rule.
- [x] Wording II, Abbreviation: Since only letter avatars have abbreviation, move this to abbreviation.

Thx a lot for your effort during the weekend (yes friday late night is weekend) ;-). I highly value the big investement of yours in the ILIAS 6 PLR Project. thx. btw, love the mockup. Is this already part of some implementation. Would be neat, looking good ;-)

@klees, I put this on the agenda, hope this is fine with you.

Greetings
@amstutz

**Comment by chfsx** [comment]
Thanks @Amstutz ! I made some adjustments concerning your feedback

**Review by Amstutz — APPROVED** [review]
My points are taken care of.

**Review by klees — COMMENTED** [review]
Hi both,

there's currently too much on my agenda, so I will only have time to have a look here if strictly necessary.

@Amstutz Do you need/want my opinion as well? Or is it fine if I withdraw here?

Best regards!

**Comment by Amstutz** [comment]
Hi @klees 

Completely fine, you already left a review earlier. 

thx.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 20 JAN 2020 : We highly appreciate this PR and accept it for trunk and release_6 branch. We prefer to use this new UI component only for the Global Screen Service implementation and keep the old implementations in other components as they are (due to the getURL problem). We will tackle this with ILIAS 7. But to have always the same colour for both letter avatars (GSS and forum, membership list, comments etc.) we would like to modify the generation of the user colour in the legacy code according to the same procedure as used for the new implementation. This will prevent that a user's letter avatar has different colours.

**Comment by chfsx** [comment]
@Amstutz  may we merge that, so we can proceed with the implementation (and it's PR #2447)

**Comment by chfsx** [comment]
Ah I'll fix the CI error asap: 
Fatal error: Class ILIAS\UI\Implementation\Component\Symbol\Factory contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ILIAS\UI\Component\Symbol\Factory::avatar) in /home/travis/build/ILIAS-eLearning/ILIAS/src/UI/Implementation/Component/Symbol/Factory.php on line 10

**Comment by chfsx** [comment]
ready to rumble

**Pull request merged**
