### PR TITLE
#25007 Refactoring: removed ui-globals utility from non gui-objects

### PR DESCRIPTION
**Pull request by dkloepfer**

### CODE REVIEW

**Comment by klees** [comment]
Hi @dkloepfer!

I think I fixed this in https://github.com/ILIAS-eLearning/ILIAS/commit/09d7cb1c8ee83e33f401f626900c7fa974593f98 and
https://github.com/ILIAS-eLearning/ILIAS/commit/b88dfc74ffb4b043d59c6d8405367db20e376522. Please rebase your changes on trunk, they look better than what I did. I do not want to include this into release_5-4 this short before the release.

Best regards!

**Review by klees — CHANGES_REQUESTED** [review]
Hi @dkloepfer!

I think I fixed this in 09d7cb1 and b88dfc7. Please rebase your changes on trunk, they look better than what I did. I do not want to include this into release_5-4 this short before the release.

Best regards!

**Comment by dkloepfer** [comment]
@klees Please notice https://github.com/ILIAS-eLearning/ILIAS/pull/1670

**Comment by klees** [comment]
@dkloepfer I can just close this one, right?

**Comment by dkloepfer** [comment]
Was merged into trunk in #1670.

**Pull request closed without merging**
