### PR TITLE
[FIX] 0038254: ilResourceCollectionGUI is missing a Upload-Button

### PR DESCRIPTION
**Pull request by chfsx**
This is a proposal for a fix for https://mantis.ilias.de/view.php?id=38254

The Bulky Dropzone is currently missing a shy button to open the Modal to add files.

Thanks for your feedback!

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @chfsx 

Thx for adding/fixing this. Please:

- [ ] Unit Tests: Add one to make sure this keeps working in the future. Note that you can use str_contains or similar for rendering test to not stack up too much HTML code (which makes refactoring of DOM structures rather painful). 

thx a lot!

**Comment by chfsx** [comment]
@Amstutz Sorry, sometimes you can't see the forest for the trees. The dropzone already has the ability to display a button, so I undid the change and nothing changes in the rendering.

But I have adjusted the following:
- CSS: The button still needs an indent on the left: https://github.com/ILIAS-eLearning/ILIAS/pull/6461/files#diff-901cc5d430eaef8a9dfbb9c097b43845344ff94c50e037b25090059e51520b1aR25
- Added an example for a bulky dropzone

**Comment by Amstutz** [comment]
Thx a lot for improving the component!

The changes look fine. However, there are conflicts due to the component revision. If possible, please resolve the conflicts and directly merge (to avoid further conflicts). If possible, also pick to 9 or let me know if this needs picking from my side.

thx.

**Review by Amstutz — APPROVED** [review]

**Comment by chfsx** [comment]
Merged locally for trunk and release_9

**Pull request closed without merging**
