### PR TITLE
Major Spanish Translation for release 5.0

### PR DESCRIPTION
**Pull request by jrbalsas**
- Translated new entries added since release 4.4
- Deleted unused entries
- Reordered entries to match order on ilias_en.lang file
- Improved some previous translations
- Added new spanish translation team members

### CODE REVIEW

**Comment by jrbalsas** [comment]
I can keep the original entries order if requested. On the other hand, if pull request is finally accepted, I can prepare a new pull request for ilias_es.lang in MASTER branch with merged translated entries.

For your information, we have not started yet to translate 5.1 new entries, but we expect to begin it soon

**Comment by chfsx** [comment]
@matthiaskunkel can you have a look at the comments and give a feedback concerning the spanish translation. Please tell if we should provide write access to @jrbalsas so he could push it directly

**Comment by pitbulk** [comment]
any progress with that?

**Comment by jrbalsas** [comment]
Updated version uploaded to ILIAS 5.0 language maintenance http://lang50.ilias.de

**Pull request closed without merging**
