### PR TITLE
PHP 7.2 compatibility ILIAS 5.3

### PR DESCRIPTION
**Pull request by ManfredKellermann**
OK, second try, hope it works now :)
The setup and operation of the ILIAS 5.3 test instance works well in my test environment with these changes.

### CODE REVIEW

**Comment by klees** [comment]
Thx, this looks much better now =)

**Comment by klees** [comment]
Hi @chfsx,

most (?) of the changes seem to be in your code, thus I assigned you. I hope that is ok!

Best regards!

**Comment by chfsx** [comment]
Hi @klees!
class.ilAtomQueryBase.php and class.ilGlobalCache.php LGTM, the rest of the classes don't belong to me :-)

**Review by chfsx — APPROVED** [review]

**Comment by klees** [comment]
I think you "win" here if we consider that you are listed as implicit maintainer for ilUtil =)

**Review by klees — APPROVED** [review]
Fine for me regarding `ilErrorHandling`.

**Comment by chfsx** [comment]
what a win :) ilUtil seems to be good as well, thanks!

**Comment by ManfredKellermann** [comment]
Is it such a big effort to check these small code changes?

**Review by alex40724 — APPROVED** [review]

**Review by chfsx — APPROVED** [review]
@ManfredKellermann I still don‘t know why I have been assigned to this PR, no one seems to feel responsible. nevertheless i took a closer look at the changes now and like to merge them. thanks for your contribution and your patience!

**Comment by chfsx** [comment]
I‘ll try to cherry-pick the changes in my files to 5.4 and trunk as well

**Review by smeyer-ilias — APPROVED** [review]
ilSCTask and LoggerFactory is fine.

**Comment by alex40724** [comment]
@chfsx As far as I can tell nothing has been cherry-picked from the PR at least to the Database Service. Please have a look at the changes, the 5.4 fix for this is slightly different and I cannot tell, if this difference is somehow important for 5.3 as well.

**Pull request merged**
