### PR TITLE
Export: remove TargetRelese from exports

### PR DESCRIPTION
**Pull request by klees**
Hi everyone,

basically, the field `TargetRelase` in the export seems to be of no use, hence we might as well remove it.

Best regards!

### CODE REVIEW

**Comment by alex40724** [comment]
The target release is passed to all exporter classes through getXmlExportHeadDependencies/getXmlExportTailDependencies
e.g.:
$sequence = $exp->getXmlExportHeadDependencies($a_entity, $a_target_release, $a_id);

The derived schema version is passed to all Dataset classes.

The idea was, to enable exports to previous versions of ILIAS, e.g. through a "Release" dropdown in the main export screen. However this has never been finally implemented (missing funding). But the idea has not been abandonded (yet). If we abandon this idea completely a removal of this parameter would require changes in almost all Export and Dataset classes.

**Comment by alex40724** [comment]
@mjansenDatabay Not sure why this had a "bugfix" label, but there is no mantis ticket for this and this does not seem to be a bug at all. I removed the label.

**Comment by dsstrassner** [comment]
32821

**Comment by alex40724** [comment]
Removed from output, still passing it through the process now.

**Pull request closed without merging**
