### PR TITLE
Setup: add missing status objects in setups of components. (#40139)

### PR DESCRIPTION
**Pull request by lukastocker**
https://mantis.ilias.de/view.php?id=40139

This fix resolves the issue of database update steps not getting listed after using the command `setup.php status` before `setup.php update`.

### CODE REVIEW

**Comment by klees** [comment]
Hi @chfsx, @mjansenDatabay, @tfamula, @Uwe-Kohnle, @smeyer-ilias, @kergomard, @pascalseeland, @alex40724, @gvollbach and @jeph864!

This adds missing objectives to include your database update steps into the output of the setups `status`-command. We all did not add these. This points at the fact that the mechanism here might be improved, because basically this is mostly meaningless boilerplate. Still, it currently is what it is. If you don't object I will merge this sometime soon (for the same reason: boilerplate). Please, everyone, remind yourself to add your steps there in the future. I might improve the mechanism at some point, but there are more important things to do atm. PRs welcome (with a quick discussion before), though.

Kind regards!

**Review by mjansenDatabay — APPROVED** [review]
LGTM @lukastocker / @klees , thx a lot!

**Review by kergomard — APPROVED** [review]
Thank you very much @lukastocker and @klees !

**Comment by klees** [comment]
Picked to trunk.

**Pull request merged**
