### PR TITLE
get rid of final methods in ilPlugin

### PR DESCRIPTION
**Pull request by chfsx**

### CODE REVIEW

**Comment by alex40724** [comment]
Has anybody else an opinion on this?

**Comment by mjansenDatabay** [comment]
No objections

**Comment by chfsx** [comment]
I could live with only the txt-method non final :-) but I thought maybe other devs wish other methods to be non final. I see the idea behind the final methods in the base-ilPlugin-Class, to "protect" the devs of implement misbehavior of their plugins, otherwise I think the devs should have the possibility to handle some things in an other way. would be nice to have this request agreed, but it's not the end of the world if not ;-)

**Comment by bheyser** [comment]
No objections as well

Am 1. Juni 2015 14:04:20 MESZ, schrieb Michael Jansen notifications@github.com:

> No objections
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ILIAS-eLearning/ILIAS/pull/34#issuecomment-107416741

## 

Diese Nachricht wurde von meinem sPhone gesendet.

**Comment by Amstutz** [comment]
Even though final methods can have their uses if they act as promise for different implementations of classes i think it should be used with care. Especially defining the constructor or called methods of it as final can lead to difficulties if classes using the class with the final constructor via delegation or as global instance should be tested (hard to create easy mocks of it).

In short, I think most of the methods in ilPlugin should not be final.

**Comment by bheyser** [comment]
I agree with Fabian, non final methods lead to more flexibility as well
as more potential for buggy code, BUT occuring bugs should relate to the
plugin instead of the core, so this becomes the problem of plugin
developers, right?

> I could live with only the txt-method non final :-) but I thought
> maybe other devs wish other methods to be non final. I see the idea
> behind the final methods in the base-ilPlugin-Class, to "protect" the
> devs of implement misbehavior of their plugins, otherwise I think the
> devs should have the possibility to handle some things in an other
> way. would be nice to have this request agreed, but it's not the end
> of the world if not ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ILIAS-eLearning/ILIAS/pull/34#issuecomment-107417737.

## 

_Björn Heyser_
fon +49 (0) 24 05 / 40 83 70
fax +49 (0) 24 05 / 40 83 759
mail _bheyser@databay.de_ mailto:bheyser@databay.de

_Databay AG_
Jens-Otto-Krag-Straße 11
D-52146 Würselen
_www.databay.de_ http://www.databay.de

Sitz/Amtsgericht Aachen • HRB:8437 • USt-IdNr.: DE 210844202
Vorstand: Ralf Schenk, Dipl.-Ing. Jens Conze, Aresch Yavari, Dipl.-Kfm.
Philipp Hermanns
Aufsichtsratsvorsitzender: Klaus Scholzen (RA)

**Pull request merged**
