### PR TITLE
[HUN] OnlineHelp

### PR DESCRIPTION
**Pull request by KissDaniGH**
@chfsx 
Hi Fabian,
we are working on hun version of OH. HUN Tooltips are almost finished.
Could you please check & merge this one too?
Thanks, Daniel

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @KissDaniGH 
Please discuss this tipoc with @matthiaskunkel and Alexandra Tödt (Head of OnlineHelp). I'm not sure if this is a feature... Best regards, Fabian

**Comment by matthiaskunkel** [comment]
Hi Dani, please contact Alexandra Tödt (toedt@leifos.com) for additional information. 
Kind regards,
Matthias

**Comment by chfsx** [comment]
@matthiaskunkel and @KissDaniGH did you already get some feedback from Alexandra?

**Comment by KissDaniGH** [comment]
hi, no answer here.

**Comment by atoedt** [comment]
Hello, 

The hungarian tooltips are very much appreciated. Thank you for putting in the work. But I am alittle confused how this can at this point in time become a part of the trunk. 

Help content is centrally prepared in a learning module which is then imported to a specific installation. 
No help content sits with the tunk. The trunk contains the "player" if one can put it like that. 

Thus the hungarian tooltips must 
a) become a part of the central learning module
b) the trunk must be prepared to handle the learning module in different languages.  (Please see herehttp://www.ilias.de/docu/goto_docu_wiki_wpage_4428_1357.html)

The project b) is not funded or contracted. We are still raising funds. 

I do not see how this is not a patch until the groundwork is done. 

kind regards 

Alexandra

**Comment by matthiaskunkel** [comment]
Closed. Prerequisite for an Hungarian online help would be multilinguality support of the help.

**Pull request closed without merging**
