### PR TITLE
Event Handling: Added logging

### PR DESCRIPTION
**Pull request by mjansenDatabay**
This PR introduces logging for the ILIAS event service.

### CODE REVIEW

**Comment by mbecker-databay** [comment]
Looks good to me. Thank you!

**Comment by alex40724** [comment]
Thanks. Looks good to me. Please resolve the conflict and merge to 5.2 - trunk.

**Review by alex40724 — APPROVED** [review]
.

**Comment by mjansenDatabay** [comment]
@alex40724 I close this PR and create a new one for the trunk. I think the `print_r` of the event data could lead to **performance issues**, because it is executed even if the debug messages will not be logged because of the configured log level.

I will provide another approach (by using the optional `$context` parameter and an anonymous class to **lazy load** the `print_r`) for the **trunk**.

**Comment by mjansenDatabay** [comment]
New PR: #1043

**Pull request closed without merging**
