### PR TITLE
BT-29591: Fixed permissions for administration auth / self registrations

### PR DESCRIPTION
**Pull request by M-Barz**
Link to Mantis-Report:
https://mantis.ilias.de/view.php?id=29591

### CODE REVIEW

**Review by smeyer-ilias — COMMENTED** [review]
LGTM

**Comment by kergomard** [comment]
Hi @M-Barz  and @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
We wondered if this PR could be merged or closed?

Best regards!

**Comment by smeyer-ilias** [comment]
Maybe the responsibility was not clear. 
I changed the assignment to the shibboleth maintainer.

**Comment by chfsx** [comment]
Thanks a lot for the PR!

**Pull request merged**
