### PR TITLE
Import and export all file versions

### PR DESCRIPTION
**Pull request by ghost**
Import and export all file versions. Old file exports still can be imported.

### CODE REVIEW

**Comment by ghost** [comment]
Main changes are in `ilFileXMLParser::handlerBeginTag`, `ilFileXMLParser::handlerEndTag`, `ilFileXMLParser::setFileContents` and `ilFileXMLWriter::start`

**Comment by ghost** [comment]
Also created some protected variables in `ilFileXMLParser`.

**Comment by chfsx** [comment]
https://www.ilias.de/mantis/view.php?id=22395

**Comment by matthiaskunkel** [comment]
Jour Fixe, 12 MAR 2018: Please check if this PR has effects on the web service implementation and come back to next JF at March 26.

**Pull request closed without merging**
