### PR TITLE
19928: use lang translation from plugin if available

### PR DESCRIPTION
**Pull request by shecken**
This attempts to fix [#19928](https://www.ilias.de/mantis/view.php?id=19928).

### CODE REVIEW

**Comment by chfsx** [comment]
@smeyer-ilias at this, too. Thanks!

**Comment by shecken** [comment]
@smeyer-ilias
Please merge this to Release 5-2 as well. As i create this PR, half a year ago, Release 5-2 was trunk.

**Comment by klees** [comment]
Hi @smeyer-ilias,
any chance that this will be merged some time?
Regards!

**Comment by chfsx** [comment]
TB: We will discuss this PR during next JF

**Comment by smeyer-ilias** [comment]
Thanks, for providing a fix.

**Pull request merged**
