### PR TITLE
[FIX] Add Buttons and Modals separately to Footer

### PR DESCRIPTION
**Pull request by chfsx**
This PR changes the interface at the updated `Footer` component. Currently, it is not possible to add buttons with modals to a link group. The current method `withAdditionalModalAndTrigger` always inserts such buttons in a separate section (the same as `withAdditionalLink`).
Therefore, I suggest removing the specific method `withAdditionalModalAndTrigger` and only offering a method `withAdditionalModal`. This is only necessary until there is a general way to add modals to the final page in ILIAS.
Please note the following:
- In the case of an emrge, trunk would currently fail because GlobalScreen still uses the old method, so I would like to deliver a second commit that uses the new method before the merge. We are welcome to coordinate with each other on this.
- The changes also have to be picked in release_10.

image

### CODE REVIEW

**Comment by chfsx** [comment]
@klees I changes the tests concerning Modals in Footer. @mjansenDatabay I skipped two tests using the current method

**Comment by chfsx** [comment]
Unfortunately, there was no time to discuss this PR itself at the JF yesterday, but the associated Development Issue was discussed and accepted: 
image

**Comment by chfsx** [comment]
The related changes in LegacDocuments are prepared in #8396

**Comment by matthiaskunkel** [comment]
Jour Fixe, 25 NOV 2024: Pull Request accepted for 10 and trunk. PR will be merged by UI coordinators.

**Comment by klees** [comment]
Hi @chfsx,

would you please change the unit tests accordingly, I'll merge then.

Thanks!

**Comment by klees** [comment]
Hi @chfsx,

please ping me and assign back once the tests are adjusted.

Thanks!

**Comment by klees** [comment]
Thick thumb :sweat_smile:

**Comment by chfsx** [comment]
We need #8397 and it's sister PR to be merged first

**Comment by chfsx** [comment]
Something went wrong wile rebasing :/ I close the PR for the moment and reopen it after resolving the issue

**Comment by chfsx** [comment]
@klees I opened a new PR for this, see #8599

**Pull request closed without merging**
