### PR TITLE
Templating: local cache for file content and removal of unused feature

### PR DESCRIPTION
**Pull request by shecken**
This PR even similar to https://github.com/ILIAS-eLearning/ILIAS/pull/244.

But there is a small difference. As we looked how to implement the property own cache, we had a look on the callback to load files included in tpl files.

We found not a single tpl file including other files. So we would like to remove this.

### CODE REVIEW

**Comment by alex40724** [comment]
If you are currently looking into the details of the template engine: Caching the file is one step, but the template engine is also performing the same steps to setup the internal structur of block/variable arrays each time (findBlocks(); and buildBlockvariablelist(); calls). There is a seven years old starting code from me in ilTemplate that tries to achieve caching after these steps (search for il_use_cache). I never had the time to finish this. Maybe you have a quick look. You could try to set the $a_use_cache flag default to true and check if this brings any additional performance improvements.

**Comment by shecken** [comment]
I had a look at the existing caching in ilTemplate. It is a small bit faster then our first proposal. So we decide to activate the caching per default.

To determine the performance improvement i created a new ordered list sample in the kitchen sink documentation. This sample has about 3.300 entries. After several times of reloading the example page, i calculated the middle of loading times. The difference is quite minimal. Caching was about 0.02 seconds faster.
Our proposal was just 0.01 seconds faster.

**Comment by alex40724** [comment]
For pages in ILIAS that don't reuse templates a lot, the effect may be even negative, since they need to write the cache but don't get any hits and additionally you will consume more memory.

**Comment by klees** [comment]
Yes, indeed. How would we divide the cases? I became aware of the problem the first time when Timon reported about slow rendering of lists with a lot of entries when using the UI-Framework. Maybe we should introduce the cache-flag in the UI-framework.

**Comment by alex40724** [comment]
What are our preferences on this? Should we just activate it for the trunk (5.3) or introduce some more sophisticated control? I have the feeling that the majority of us assumes that even global activation will overall improve the situation since templates become more granular with each release.

**Comment by Amstutz** [comment]
@alex40724: Thank you for referencing the closed PR. If you have some idea, how a more sophisticated control could look like, you can contact me and I will search with the SIG Perf. for funding. I am sure we will find a solution.

Until we have a better solution, IMHO: I think we should activate the the caching for 5.3. At least on our Installations, memory is almost never an issue. Clock (speed) however is a big one. I also agree, that our templates have the tendency to get more granular. The performance monitoring might give us some hints about the impact of this measures.

**Comment by alex40724** [comment]
Changes are part of the trunk now. Thanks!

**Pull request closed without merging**
