### PR TITLE
Improvement/5 4/auth hook abstract class

### PR DESCRIPTION
**Pull request by chfsx**
This PR contains and replaces #1874 and provides some documentation and more readable AuthHook. This also fixes https://mantis.ilias.de/view.php?id=25508

### CODE REVIEW

**Comment by ghost** [comment]
@smeyer-ilias For my commits please also read my answers of your comments
https://github.com/ILIAS-eLearning/ILIAS/pull/1875

**Comment by ghost** [comment]
@smeyer-ilias Current status?

**Comment by chfsx** [comment]
@smeyer-ilias conflicts are resolved now, could you please have a look at it?

**Comment by mjansenDatabay** [comment]
@smeyer-ilias Any update on this? Please provide feedback/ask questions, close the PR, or merge it.

**Comment by klees** [comment]
Send reminder to @smeyer-ilias today.

**Pull request merged**
