### PR TITLE
Dicto: Proposals for additional ignore statements

### PR DESCRIPTION
**Pull request by Amstutz**
Some additional ignore statements for dicto, which prevented my local ILIAS installation from crashing while indexing. Note that this mostly affects plugins which might be running on some local installations. However they seem like a good addition to the base set to me.

### CODE REVIEW

**Comment by klees** [comment]
Just for curiosity: How is dicto-crashing?

**Review by klees — APPROVED** [review]
LGTM

**Comment by klees** [comment]
And also: Do I understand correctly that you actually run dicto locally? This is GREAT!

**Comment by Amstutz** [comment]
@klees , jop, works like a charm. OSX (no vagrant or other vm needed), PHP 7.2.6, Git 2.17.1. Takes a bit of time, an lot's of memory:
```
NOTICE: Analysis took 900.99474406242 seconds to run.
execution time:    1217.2701148987s
peak memory usage: 1.803.264.424 byte
```

However, this can be adjusted while developing by adding some more ignores for files outside the PoI. 

The problem have been the following:
- A PDF in the Customizing dir file let the indexer to some error in reading the file
- A huge XML file in Customizing (100MB+) somehow let to an immediate halt of the indexer without any feedback.
- A rather large vendor dir from a plugin using composer let to a memory overflow of the indexer.
- .git and pack files let to an error while indexing.

All those problem occur in the customizing dir. However, I believe it to be a big win to also run dicto in customizing, since all those rules are valid for plugins as well and most of the code I write is in this dir.

**Pull request merged**
