### PR TITLE
Docs/Coding Style: Add instructions how the ILIAS code style can be c…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…hecked/applied

### CODE REVIEW

**Review by gvollbach — APPROVED** [review]

**Review by alex40724 — APPROVED** [review]
Great, thanks!

**Comment by kergomard** [comment]
Thank you very much!

**Review by Amstutz — APPROVED** [review]
thx a lot

**Review by klees — APPROVED** [review]
Thx!

**Pull request merged**
