### PR TITLE
Fixed #22317

### PR DESCRIPTION
**Pull request by mjansenDatabay**
https://www.ilias.de/mantis/view.php?id=22317

### CODE REVIEW

**Comment by klees** [comment]
Try summoning @gpkvt: Any opinion here?

**Comment by gpkvt** [comment]
Sure, go ahead. If the intention is to hide the existence of .git completely you should also disable directory listings, otherwise you might be able to see that .git exists there (but still won't be able to access it).

**Comment by tmuellerdatabay** [comment]
Other possibility is to deny permission, so is not related to setting of directory listings:
RewriteRule \.git - [F]

I think the decision has to be fell on server side for directory listings.

**Comment by gpkvt** [comment]
Forbidden indicates that the directory exists, so it won't be suitable if the intention is to fully hide the existence (for whatever reason). If only the access should be denied I would go with 403 instead of 404.

**Comment by mjansenDatabay** [comment]
Thanks for your feedback.

I will go with a 404, because a 403 discloses the existence of the folder.

**Pull request merged**
