### PR TITLE
UI, #28062 - Fix missing and existing aria labels for Glyphs

### PR DESCRIPTION
**Pull request by tfamula**
https://mantis.ilias.de/view.php?id=28062
This PR adds some missing language variables for Glyphs. It also fixes some existing aria labels.

### CODE REVIEW

**Review by Amstutz — COMMENTED** [review]
Hi @tfamula ,

Thanks a lot! An issue in deed. Note that some unit tests need some love as well due to the changes in the language variables. Other than that, I am fine with it. Maybe pass the translations also through @atoedt hower, this can also happen after a merge.

- [x] Fix Unit Tests

thx.

**Comment by tfamula** [comment]
Shame on me I forgot the unit tests...thanks for the reminder, @Amstutz!
I asked @atoedt for the translations and she is okay with them.

**Review by Amstutz — APPROVED** [review]
All good, @klees, merge as soon as fine with the changes.

**Comment by Amstutz** [comment]
@tfamula thanks for improving this. @klees just gave green light for this by mail. So resolve conflicts in the language files, merge and also promote down to 6. thx a lot!

**Review by Amstutz — APPROVED** [review]

**Pull request merged**
