### PR TITLE
8 mantis ilias 37850

### PR DESCRIPTION
**Pull request by chlulei**
Link: https://mantis.ilias.de/view.php?id=37850

### CODE REVIEW

**Comment by nicoroeser** [comment]
Thank you for your contribution, @chlulei! I have assigned our two developers who are responsible for the affected code; you’ll hear from them.

**Review by kergomard — CHANGES_REQUESTED** [review]
Thank you very much @chlulei for this PR

I don't believe either of these two lines is ideal:
- https://github.com/ILIAS-eLearning/ILIAS/pull/7088/files#diff-a1167db18550ccc7298d14c244c09d3246b63e84090258df61b39901cc6fcce6R321
- https://github.com/ILIAS-eLearning/ILIAS/pull/7088/files#diff-8b93c41023facb740bc3e87e5bc8775e46e676126b5f0097e40a4d6bc91c9682R127
Shouldn't they rather be a `yield from $component_factory->getActivePluginsInSlot($blup)`?

Thank you very much and best,
@kergomard

**Comment by chlulei** [comment]
Thank you @kergomard for the feedback, I have adjusted the code as recommended.

**Review by kergomard — APPROVED** [review]
Thank you very much for the quick adaptations @chlulei !
The changes look good to me now, please merge and cherry-pick to ILIAS 9 and trunk @smeyer-ilias if you also agree.

I will deassign myself.

Thanks again and best,
@kergomard

**Review by smeyer-ilias — APPROVED** [review]
Thanks @chlulei

**Pull request merged**
