### PR TITLE
fix #0025377

### PR DESCRIPTION
**Pull request by nhaagen**
safety to avoid db-error in setup;
https://mantis.ilias.de/view.php?id=25377

### CODE REVIEW

**Comment by klees** [comment]
This is odd and will crash later on (when SP is used). The fields should exist after the previous steps. But it seems they don't. Same here: #1802. Why is that?

**Comment by nhaagen** [comment]
Yes, this is odd. The fields should definitely be there. 
However, I do not understand where this will crash - what is SP here?

**Comment by klees** [comment]
SP = Study Programme. Should have been LSO, though.

**Comment by klees** [comment]
Hi @chfsx,

do you know similar phenoma? Do you have any idea what happened here?

Best regards!

**Comment by chfsx** [comment]
@klees I have no idea what happened there. Is this reproducible with every installation of ILIAS? If so, what kind of DB (MySQL, MariaDB) in which version is used?

**Comment by klees** [comment]
I could not reproduce this so far, but I think this could happen if you update a 5-4-Installation to the point, where the fields are removed via hotfix and then later move to trunk, where the similar steps in dbupdate would run again. So this safety should be fine.

**Comment by chfsx** [comment]
@klees  that sounds plausible. the switching between trunk and branches can cause the behavior.

**Pull request merged**
