### PR TITLE
Optimize toolbar for responsive view. Implement possibility to add "p…

### PR DESCRIPTION
**Pull request by wanze**
…rimary items" to the toolbar. These items are always visible, also if the toolbar is collapsed. Add some less variables for the toolbar.

### CODE REVIEW

**Comment by chfsx** [comment]
@matthiaskunkel since the feature has been approved by JF we would like to merge it at the end of the week, is that ok? This request is to inform affected developers.

http://www.ilias.de/docu/goto_docu_wiki_wpage_3683_1357.html

**Comment by chfsx** [comment]
affected developers: @alex40724 @jluetzen-ilias

**Comment by alex40724** [comment]
Sorry, I currently do not approve the merge, since I am not understanding the resulting interface:

The class currently supports things like
- addInputItem
- addButtonInstance (comes with a primary flag)
- addSeparator
- addLink

Now addPrimaryItem() is added. As I understand this is works like addInputItem but puts InputItems into the "always visible" area.

How does this related to the primary flag of the button instances?
How are links added to the "always visible" area?

EDIT: And the parameter in addFormButton(..., $a_primary = false, ...) - is this respected if set to true? Does not seem to be the case. Even if deprecated, this is still widely used.

**Comment by wanze** [comment]
> Now addPrimaryItem() is added. As I understand this is works like addInputItem but puts InputItems into the "always visible" area.

That's correct.

> How does this related to the primary flag of the button instances?

There's no relation. Currently, the developer is responsible to set this flag on the button object passed as primary item. Thus, it is currently also possible to add "normal" buttons.

> How are links added to the "always visible" area?

Primary items must implement the interface `ilToolbarItem`. Links are currently not modeled as objects, therefore it's not possible to add links as primary items. Ideally, we model a link item as object implementing the `ilToolbarItem` interface. Then it would be possible. I can add this to this pull request if that's okay.

**Comment by alex40724** [comment]
If there is no relation, we should give it another name. Otherwise one term "Primary" refers to two different concepts. I would suggest "Sticky".

I think primary buttons (coming with the flag in the button instance) should go to the sticky section "per default". But this should be a Jour Fixe discussion.

**Comment by Amstutz** [comment]
Even though I proposed the naming "primary" I have to agree that sticky would be a better fit, since primary might lead to confusion as alex discribed.

@alex40724: Do you propose to do that on the client side? A similar solution was already proposed by @wanze, I argued that this would involve quite a bit of JS to juggle the items around in the dom. I would not like this solution. Also the JS would have to be aware at which point we turn into the "responsive view" and react to that.

This might also be handled on the server side, if a primary button is added, then it's added as sticky item. The main point here is, that sticky item would always appear first (before the other items), since they are placed on a different location in the DOM.

**Comment by jluetzen-ilias** [comment]
No, this can be done server-side. When a button instance is added to the toolbar a simple switch would react to a given primary property of the button and add the button as sticky.

**Comment by wanze** [comment]
I will rename the method to `ilToolbarGUI::addStickyItem()`.

> No, this can be done server-side. When a button instance is added to the toolbar a simple switch would react to a given primary property of the button and add the button as sticky.

This implies that all primary buttons are added as sticky elements. Other questions we asked ourself: 
- Can there be more than one primary Button? 
- If the toolbar consists of only one button (primary/non-primary), should this button be converted to a primary one and being added as sticky item per default? 

Maybe these questions should be discussed at the JF. :)

**Comment by jluetzen-ilias** [comment]
Yes, all primary buttons should be sticky.
Regarding the questions: no and no.
There may be only 1 primary button per screen (or at least visible at once). And each primary button has to be suggested/accepted by the JF, see:
http://www.ilias.de/docu/goto_docu_wiki_wpage_1441_1357.html

**Comment by chfsx** [comment]
After changing the "primary" to "sticky" and representating links as class, are there any other concerns which prevent from merging? 

after the JF-decision concerning the "auto-sticky" for primary buttons this new behavior can be implemented separately.

**Comment by Amstutz** [comment]
Are primary items always on the very left? They will be if we make them sticky with the current template. For me this is oke, I just want to double check. 

@jluetzen-ilias: Why can this not be done on the server side? There is the function isPrimary(), if true, place it and treat it like sticky items.

**Comment by jluetzen-ilias** [comment]
@Amstutz 
That's what I proposed above, seems to be lost in translation.

**Comment by Amstutz** [comment]
Sorry my bad, lost in translation is a very fitting term for this awkward comment of mine.

**Comment by alex40724** [comment]
No other concerns from my side.

**Comment by wanze** [comment]
@alex40724 Regarding the links as sticky items: There is the `ilLinkButton` object which can be used. If it still needs an additional object to represent links, how should I name the class? `ilLink` is already used, `ilLinkGUI`? If not necessary, could you merge the pull request? Thanks.

**Comment by alex40724** [comment]
Since this is a PR for the trunk:
Has the general implementation been approved by the funding party? Or do you want to have this in the trunk without approval?

**Comment by wanze** [comment]
The implementation is available in the edge branch/installation. @matthiaskunkel Can you take a look at it please? Thanks

**Comment by alex40724** [comment]
Ok, this is already merged?

**Comment by wanze** [comment]
@alex40724 Sorry I forgot to add a comment, Matthias has approved the current implementation today. We will add test cases and update the dev guide accordingly.

**Pull request merged**
