### PR TITLE
Feature/6/ui file input

### PR DESCRIPTION
**Pull request by chfsx**
@klees and @Amstutz this is the implementation of #2257 (which is accepted and can be merged).

Please feel free to ask any question concerning this PR you need!

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @chfsx

Thanks a lot for this important addition to the UI Framework. Special
thanks for improving some components along the way by adding some strict
typing. Note that it can be somewhat risky to put them in an unrelated
PR, since all the work could be lost, if the PR is declined. However,
here this risk is minimal. Thx for the added Roadmap entry. Thx for the
well documented examples. Thx for the nice set of tests. Thx for the
nicely wrapped js code.

Please answer the following Questions

- [x] Todos: There are still TODO’s (isClientSideValueOk,
getUpdateOnLoadCode), what is the story about them? Probably remove. If
thought for ILIAS 7, add an entry to the roadmap.


Please follow the listed suggestions or clearly indicate, why you prefer
otherwise.
- [x] Long Methods: We try to follow Uncle Bob suggestions, to keep
methods as short as possible. Obiously we do not succeed in various
cases. However, render in Field/Renderer is getting way out of hand,
kicking 100 lines. Please move the contents of your elseif to its own
method.
- [x] Handler Result: It looks as if `HandlerResult` rather belongs to
`src/FileUpload` than `src/UI`, because UI never uses it (right?). Move
it to `src/FileUpload`.

Please implement the following changes
- [x] File.php Class Description: There is some radio input comment
hanging around, fix.
- [x] file.js 1: Adjust comment in the head of the file. You are not Nils =)
- [x] file.js 2: Remove console.log in your js code.
- [x] Less Variables: Use the existing variables for padding horizontal
and vertical.
- [x] Add these to the Roadmap: use proper Glyphs from the KS in the
input; use `Data\DataSize` for file size info


Please give us a short nudge, as soon as done, so you can fast-track
merge this.

Thx
@klees and @amstutz

**Comment by chfsx** [comment]
Hi @klees and @Amstutz
Thanks for the feedback (again), I tried to address all the points you mentioned

**Review by Amstutz — APPROVED** [review]
Fine for me, @klees merge if fine for you as well.

**Comment by klees** [comment]
Hi @chfsx, the tests are failing. Please fix. Thanks for the other adjustments!

**Comment by chfsx** [comment]
@klees sorry, now they're fine!

**Pull request merged**
