### PR TITLE
Update Dependencies after Release v7.21

### PR DESCRIPTION
**Pull request by fwolf-ilias**
Dear @ILIAS-eLearning/technical-board,
This PR updates all dependencies after release v7.21.

**Composer Notices:**
```
Package imsglobal/lti is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/twig-configurable-i18n is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package technosophos/libris is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```

There is an issue if i run `composer update` with PHP 7.3, which has to be fixed. When running `composer update` with PHP7.4 some packages are not compatible with PHP7.3. I'll post the issue next week on mantis. 

```
In ModuleInstallerPlugin.php line 15:
                                                                                                             
  [ParseError]                                                                                               
  syntax error, unexpected 'ModuleInstaller' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 
  ```

### CODE REVIEW

**Comment by fwolf-ilias** [comment]
The issue appears in package `simplesamlphp/composer-module-installer`. The recent version of this package states, it is only compatible with PHP7.4, but it was updated automatically anyway.

**Comment by mjansenDatabay** [comment]
I'll check this ...

... @fwolf-ilias When I did a `composer upgrade` (with PHP 7.3), `simplesamlphp/composer-module-installe` was not affected (sticks on version: 1.1.9).

**Comment by fwolf-ilias** [comment]
Okay, I think I know what happened here. After the incompatible version of `simplesamlphp/composer-module-installer` was already loaded composer operated by PHP7.3 wasn't able to switch back anymore because it ran into the parsing error above. After i cleared the vendor folder and ran `composer upgrade` it went through and installed the correct version of this package.

**Comment by kergomard** [comment]
Thanks @fwolf-ilias  and @mjansenDatabay for creating this and looking into the problems. This now seems to work here and for us locally. I merge.
Best,
@kergomard

**Pull request merged**
