### PR TITLE
implement __toString() on UUID

### PR DESCRIPTION
**Pull request by Hadrian-II**
implement __toString() on UUID as this method is needed by php for some methods like array_diff

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @Hadrian-II,

LGTM in general, thanks a lot. I have one change request, though: Since virtually all code should depend on the interface `Uuid` rather then the implementation you are modifying, please add that method on the interface too.

Best regards!

**Comment by Hadrian-II** [comment]
i added the method to the interface, im not sure if adding magic methods to interfaces feels right

**Comment by klees** [comment]
Hi @Hadrian-II,

sounds interesting =) Why's that?

Best regards!

**Comment by mjansenDatabay** [comment]
@Hadrian-II / @klees `__toString` can be ensured by the `Stringable` interface in PHP 8, so it is not sooooo magic anymore. The `Uuid` interface could then be slightly changed by using `extends Stringable` and the added method could be removed, if we require `PHP >= 8.0`.

**Review by klees — APPROVED** [review]

**Pull request merged**
