### PR TITLE
Feature/shy implementation

### PR DESCRIPTION
**Pull request by iszmais**
Depends on https://github.com/ILIAS-eLearning/ILIAS/pull/3787

### CODE REVIEW

**Comment by iszmais** [comment]
Hi @klees 

Since the Item/Shy Component was accepted by the JS i would highly appreciate your review here and merge if all is to your satifsaction.
(Of course after https://github.com/ILIAS-eLearning/ILIAS/pull/3787 was merged.)

Greetings,
Ingmar

**Comment by klees** [comment]
Hi @iszmais,

I will only get to this on friday, maybe @Amstutz is a little quicker.

Best regards!

**Comment by klees** [comment]
No, seems as if he's not quicker than me =)

**Comment by klees** [comment]
@iszmais Could you rebase on trunk, please.

**Comment by iszmais** [comment]
> @iszmais Could you rebase on trunk, please.

@klees done

**Comment by Amstutz** [comment]
Hi @iszmais,

glad to see you becoming a regular contributor to the ILIAS UI framework =). Thx for the tests. Thx also for usage of flex in less.

As a general rule: Please only apply exactly the rules for the ILIAS coding style, nothing more, nothing less. This seems to contain changes (like [this](https://github.com/ILIAS-eLearning/ILIAS/pull/3793/files#diff-9cea1c2c884b55aedbfd2f900756f1e2f46c14228eede175c221ae62ae64cc60L27) and [that](https://github.com/ILIAS-eLearning/ILIAS/pull/3793/files#diff-9cea1c2c884b55aedbfd2f900756f1e2f46c14228eede175c221ae62ae64cc60L29)) which seem to be style only and unrelated to the initial goal of this PR. If there is some additional style you want to see being used (like shortened names), best thing would be that we find an agreement (and an automatism) for the complete community. We'll be glad to support here. If that's not possible, we might look for an agreement for the UI-framework or you could just make PRs that rectify things.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] Button\Shy: Please use `Button\Shy` instead of [`bShy`](https://github.com/ILIAS-eLearning/ILIAS/pull/3793/files#diff-9cea1c2c884b55aedbfd2f900756f1e2f46c14228eede175c221ae62ae64cc60R14). 

Please implement the following changes:
- [ ] ilUtil: Please do not introduce that hidden dependency to ilUtil. What's the reason for calls to `ilUtil::stripSlashes` after all? Is this to prevent injections? Why not use `htmlentities`?
- [ ] Less/CSS: You use numeric pixel values in the less file. Use an existing variable or introduce a new one. I am aware, that our system (if one can call it such) for calculating padding and margins is not where it should be. But using variables will help changing that at some point. e.g. `@il-padding-large-horizontal` or `@il-padding-base-horizontal` could do the trick.

Feel free to get in touch if there are any questions or points to be discussed, as always.

Best regards!

@klees and @Amstutz

**Comment by iszmais** [comment]
Hi @Amstutz ,
i applied all changes (optional & required)

i also added new variables for grid gaps in less since the usage of paddings for gaps could be missleading for futhure designs.

Greetings,
@iszmais

**Comment by Amstutz** [comment]
Hi @iszmais 

Thx for the improvements. IMO this is almost good to go. There remains one minor thing, the variables need to go into this file (the other is and should remain original bootstrap):  https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/templates/default/less/variables.less . Also see: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/templates#less-guideline . For some guidelines concerning the naming and placing of variables. E.g. apply the il- to make clear that this is an ilias custom variable (not from bootstrap). Also, if only used in your component, best place them in the buttons section.

Thx for all the work.

**Comment by iszmais** [comment]
Hi @Amstutz ,

i assume you meant the item section (not button) since this is an item component?

But of course this isnt supposed to be in bootstrap. Fixed it.

Greetings,
@iszmais

**Comment by iszmais** [comment]
Hi @Amstutz ,

do you have any more change requests here? As for as i assume the last change should made this ready for merge.

Greetings,
@iszmais

**Comment by Amstutz** [comment]
Hi @iszmais 

Sry, this went of my radar covored by all those PHP8 PRs. You are right this is good to go. Thx!

**Comment by iszmais** [comment]
Hi @Amstutz / @klees,

no problem, thanks for merging! [PR #3671](https://github.com/ILIAS-eLearning/ILIAS/pull/3671) would also needs a review to proceed further in the implementation of the actual feature.

I would appreciate your feedback on this.

Best regards,
@iszmais

**Comment by klees** [comment]
@iszmais I will look into both on monday. Have a nice weekend.

**Pull request merged**
