### PR TITLE
UI/Metabar, more button with aria-expanded (#37151, #38249)

### PR DESCRIPTION
**Pull request by nhaagen**
This reverts the down-pick of https://github.com/ILIAS-eLearning/ILIAS/pull/6318 and applies the actual change for ILIAS 8.
PR6318 has dependencies that are not present in 8; thus, re-rendering of JS was prevented.

### CODE REVIEW

**Comment by dsstrassner** [comment]
Mantis Issue in #6318: https://mantis.ilias.de/view.php?id=37151

**Review by klees — APPROVED** [review]
Hi @nhaagen,

LGTM in general, just one question:

- [ ] Why is there a change in src/UI/templates/js/MainControls/metabar.js? Looks unrelated to me...

Kind regards!

**Comment by nhaagen** [comment]
> * [ ]  Why is there a change in src/UI/templates/js/MainControls/metabar.js? Looks unrelated to me...

this is the actual fix; https://github.com/ILIAS-eLearning/ILIAS/pull/6846/commits/ce63f2ef8a9ef4e69204c37062d83c604e06abc8

**Comment by Amstutz** [comment]
thx a lot.

**Pull request merged**
