### PR TITLE
ilPlugin::afterDeactivation event missing

### PR DESCRIPTION
**Pull request by KamuiXenom**

### CODE REVIEW

**Comment by alex40724** [comment]
I think its not a good idea to put these different things into the same pull request, since Fabian might like to assign them to different maintainers.

**Comment by KamuiXenom** [comment]
Sorry the mime-mail change was not for the pull-request.

**Comment by chfsx** [comment]
hi @KamuiXenom 
thanks for your pull-request! we will discuss it today and see if we accept it as bugfix and if it will be merged to trunk or also to the release-branches.

**Comment by chfsx** [comment]
I opened a Bug-report for tracking purposes: http://www.ilias.de/mantis/view.php?id=16662

**Pull request merged**
