### PR TITLE
removed *unused* JSON-Emulator (no references to it anymore)

### PR DESCRIPTION
**Pull request by colin-kiegel**
If still needed, there is a perfect duplicate at this path './Services/JSON/include/json.php'.

This also removes a classname collision like PR #14

### CODE REVIEW

**Comment by chfsx** [comment]
hi @Uwe-Kohnle. did you have already time to have a look at it? seems to be unused code which can be deleted by accepting this PR

**Comment by chfsx** [comment]
@Uwe-Kohnle can you have a look at it and then merge the pull request? thanks a lot...

**Comment by chfsx** [comment]
@Uwe-Kohnle please have a look at this PR and merge/decline it

**Comment by matthiaskunkel** [comment]
Jour Fixe, August 15, 2016: Please remove file.

**Pull request merged**
