### PR TITLE
fixed missing info message for diabled pw assistance

### PR DESCRIPTION
**Pull request by smeyer-ilias**
Removes the force_login parameter otherwise info / error do not survive a redirect to the login page.

https://mantis.ilias.de/view.php?id=32290

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@smeyer-ilias [log4j 2.17.2](https://github.com/ILIAS-eLearning/ILIAS/pull/4183/commits/c15f177c28d98d3763650ec62dc7dc4e642b5862) ? ;-)

**Comment by smeyer-ilias** [comment]
@mjansen cherry-picked on a wrong branch :(

**Comment by pascalseeland** [comment]
@smeyer-ilias please force-push your branch to remove the commit of log4j2 and not add another commit reverting it

**Comment by mjansenDatabay** [comment]
@smeyer-ilias Can you please resolve the conflicts by rebasing your branch and then sqash your commits?

**Comment by kergomard** [comment]
Hi @smeyer-ilias  

As Technical Board, we regularly check for pull requests that have been open for a long time.
Can you please resolve the conflicts by rebasing your branch and then squash your commits?

Best regards!

**Comment by pascalseeland** [comment]
Superseeded by #6088

**Pull request closed without merging**
