### PR TITLE
[belongs to 22516] Bugfix for duplicate entry error in DB Update 5102

### PR DESCRIPTION
**Pull request by jheim2**

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @jheim2 thanks for your contribution. As outlined in https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-3/docs/documentation/contributing.md PRs with bugfixes should reference to a Mantis-Ticket. Is there already a ticket you could link or will you find some time to open one? Thanks in advance!

**Comment by jheim2** [comment]
sorry, indeed i have very little time at the moment. But I have just opened a Bug Report in Mantis: https://www.ilias.de/mantis/view.php?id=22516

**Comment by chfsx** [comment]
Thank you @jheim2 this helps other which may find the same bug, they will see that there is already work in progress

**Comment by smeyer-ilias** [comment]
@jheim2 thanks for for the fix!

**Pull request merged**
