### PR TITLE
Move Add New Item to Modal

### PR DESCRIPTION
**Pull request by kergomard**
This PR moves the creation of new items and the import of objects to a modal. It leads to changes in many components.
The corresponding Feature Request can be found [here](https://docu.ilias.de/goto_docu_wiki_wpage_6597_1357.html) .
There are two changes compared to the Feature Request:
The import doesn't need a dropdown to select the content type and it has moved to a modal:
grafik

I've split up the changes into component-specific commits. It would be very kind if you could have a look at your components until March 18th 23:59. The whole import/export structure here was rather convoluted and I'm sure I made one or the other mistake.
- @alex40724 your commits are: 7d6ce216f4b08cf22bb5877a0f8e13f334c4b349, 152c0ef5b1c9d2cc6b27cb6186620203450c8924, ce00cc83466a03e52dffe8db08b2fda218c94e98, 0b2c3487209c6e3dab66edbfae690172d43314db, 09ba937babddcf1b30fe8aa79bb8a231e4dda3e0, bf84fc509fc5fba9ba741a616da9c4de49bd68bb, a507c53d15528ce8c9a4dce8ba59adf67f6cc351, 82ce729420d93a61f2854c13583c8b92a07bde83, a44ec2b53dc94affd9e1896f5c5705d08f4891fa, 3671b4a618e6c92e0a701e1f79ab315a33813720
- @Uwe-Kohnle as the SCORM component did some non standard changes to the import, I would be glad for a good look into this commit:  f62c84050e8794a2606eb8da59d1472db0b3e79f
- @smeyer-ilias your commits are: 993faf3628e57373b5e42598531c88ee33a1d1e7, 9a07f403260f79a10372051a63c574b05c267c91
- @tschmitz your commit for the Employee Talks: 3d443f248d37ea9ae3d0919126ad35dd8e750c25 Addendum 21 Feb 2024: I had to switch things around a little in Employee Talks. Please also see: 877471c8094700841a4c150dabc60d943f1fbc52 
- @chfsx your commit for Files is: 96a1fe5c863faca5285c12c020e47ac742b6bf8e
- @klees your commits are: bd7dd4dda0b2ca437b294cd14ebe03034f24c28e, ac74ffb5aba859ad49dd7740790b37be1c295139 . Addendum 21 Feb 2024: I had to switch things around a little in the Org-Units. Please also see: 877471c8094700841a4c150dabc60d943f1fbc52 
- @maxbecker and @dsstrassner if you want to have a look at the changes in test they are here: bbb5f37c855a22cb32ca8b0b52f5e30f44a8657f, bb0e130db6c6ab27a753b1e1373b86c873fe75b3, 1b59b17070a89249d11e712499487cfdaa957bda . I did quite a few changes though as this was really topsy-turvy!

Thanks and best,
@kergomard

### CODE REVIEW

**Review by chfsx — APPROVED** [review]
Thanks @kergomard!

**Review by alex40724 — CHANGES_REQUESTED** [review]
Hi @kergomard ,

thanks for the PR. I just made a quick test (< 10 min) of the branch and run in lots of issues, e.g.

- Categories: All are named „NO TITLE“
- Item Group: Call to undefined method ILIAS\UI\Implementation\Component\Input\Container\Form\Standard::removeItemByPostVar()
- Wiki: Missing the whole creation form, sending the form brings it back with missing data (no title)
- Category/Course Links: Not Possible
- General: If no title is provided we get  „Error Trying to access array offset on value of type null“
- Files: Selecting no files gives a form without heading

**Comment by kergomard** [comment]
Thank you Alex for looking into this.

> Categories: All are named „NO TITLE“

I cannot reproduce this.
> Item Group: Call to undefined method ILIAS\UI\Implementation\Component\Input\Container\Form\Standard::removeItemByPostVar()

Fixed with  82392fbb45c0451f32221f4c80c70f050c773af6
> Wiki: Missing the whole creation form, sending the form brings it back with missing data (no title)

Fixed with 175096a10ce6ff404bda4f01d88b38a775d11bbd
> Category/Course Links: Not Possible

If you have the same issue I have (you cannot select the target), this has nothing to do with the changes: The javascript is missing in ilPropertyFormGUI
> General: If no title is provided we get „Error Trying to access array offset on value of type null“

Fixed with 5bef53e08267bd067a7e3478e41808137da795e1
Right now there is no Error Message and I don't know why yet: There is a required field that is not filled in and it still passes muster. Will investigate further.
> Files: Selecting no files gives a form without heading

Fixed with 38783b5c31aca8adf9f81a1c20fde14643cdc3ae

**Comment by matthiaskunkel** [comment]
Jour Fixe, 19 FEB 2024: Stephan notified us about the change of code to implement Add New Item as a modal. In addition, the import does no longer need a dropdown which is highly appreciated by the JF.

**Comment by klees** [comment]
> If you have the same issue I have (you cannot select the target), this has nothing to do with the changes: The javascript is missing in ilPropertyFormGUI

I'm on it in #7019!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 18 MAR 2024: Last reminder by @kergomard about the upcoming merge of this PR for trunk.

**Comment by schmitz-ilias** [comment]
Hi @kergomard,

thanks for the PR, and sorry that it took me so long to look at it.

I tested your changes, and it seems like newly created EmployeeTalks and OrgUnits all have the title 'NO TITLE' and no description, regardless of what was entered in the creation form. (There are currently also a few ilCtrl issues in EmployeeTalk, probably unrelated to your changes, so you might want to stick to OrgUnits for testing this.)

**Comment by kergomard** [comment]
Thank you @schmitz-ilias for your feedback and sorry it took me so long to look into it!

If I assume that by "EmployeeTalks" you mean "Employee Talk Template", I cannot reproduce it in either of the cases you mention. They are created just fine, but I will check this out again after the Drilldown-PR is merged and I've rebased this PR.

Best,
@kergomard

**Comment by kergomard** [comment]
Hi @alex40724 
There is one more change needed in `ilRepositoryGUI` to implement the JF decision that "Content" should come first (See: https://docu.ilias.de/goto_docu_wiki_wpage_6597_1357.html). You can find the very small change in [this commit](https://github.com/ILIAS-eLearning/ILIAS/pull/7068/commits/a743e9822e06d2ef6d65b452e75287d89de2044d).

Thanks and best,
@kergomard

**Comment by kergomard** [comment]
I merge this now after multiple announcements and the approval by the customer.

**Pull request merged**
