### PR TITLE
Feature/button/minimize implementation

### PR DESCRIPTION
**Pull request by iszmais**
Depends on https://github.com/ILIAS-eLearning/ILIAS/pull/3644

### CODE REVIEW

**Comment by klees** [comment]
Hi @iszmais,

is this ready for review?

Best regards!

**Comment by iszmais** [comment]
@klees Yes this is ready for review.

Pls take note that i also did a minor refactoring of the close buttons less/css here to make it independend from the bower component and centralized inside the components less like all other buttons.

Since the minimize and close buttons are very similar i think its rational to correct that parity here

**Comment by iszmais** [comment]
@amstutz / @klees Could one of you review this? If approved, @mjansenDatabay could merge https://github.com/ILIAS-eLearning/ILIAS/pull/3665 as well.

**Comment by klees** [comment]
@iszmais I'm on it.

**Comment by Amstutz** [comment]
Hi @iszmais 

We thx for the implementation. Special thanks for refactoring the less. Kudos.

There is just one thing missing:
- [ ] Unit Tests: Add them, e.g. the one for rendering.

After adding and making sure they pass, you may hit merge to avoid further delays.

**Comment by iszmais** [comment]
Hi @Amstutz ,

i added the requested test (and one more), but im not priviliged to merge.
Could you merge?

Thx.

**Comment by Amstutz** [comment]
Thx a lot!

**Pull request merged**
