### PR TITLE
Remove Dev-Dependencies

### PR DESCRIPTION
**Pull request by chfsx**
This PR
- removes and ignores dev dependencies
- added phpunit & php-code-coverage as dev-dependency

As discussed during the TB meeting today I think we should not deliver ILIAS with dev-dependencies to reduce package size and to prevent from using dev-dependencies for production.

All auto-generated files like autoload_classmap.php are delivered in the state after a "composer install" but directories added with "composer require --dev ..." should be ignored in libs/composer/.gitignore

Current painpoint to discuss: what if a non-dev-dependency requires a ignored dependency? In my opinion this will be detected soon , e.g. on ilias.de/testXX

Thanks for your opinions and discussion

### CODE REVIEW

**Comment by alex40724** [comment]
Sounds good to me. Thanks.

**Comment by colin-kiegel** [comment]
@chfsx regarding the painpoint you mentioned, this could be of relevance:
Wikipedia has a composer plugin which can merge multiple `composer.json` files at runtime.
https://github.com/wikimedia/composer-merge-plugin

This might be a starting point to split up the `composer.json` into seperate files for production and dev-dependencies and to establish independent workflows for installing/updating prod and dev-dependencies.

**Comment by chfsx** [comment]
@colin-kiegel can you describe how this would look like? the repo would have both .jons Files?

**Comment by colin-kiegel** [comment]
@chfsx OK, I was not aware there was a built-in flag to install without dev dependencies (`composer install --no-dev`). So splitting the json file would solve a non-existent problem. ^^

But I could imagine the following alternative workflow for pushing updates of dependencies:
- just put **all** composer dependencies in gitignore, i.e. don't try to distinguish between dev and non-dev, because there might be an intersection as you mentioned
- when updating: 1. purge all dependencies, 2. re-install with `no-dev` flag, 3. `git add -f` all installed dependencies, 4. push. DONE.

Just my two cents.

**Comment by chfsx** [comment]
thanks @colin-kiegel, your two cents lead to the idea of just define the workflows and add them as readme. 

Since we do not loose anything I merge this

**Comment by chfsx** [comment]
We do loose something, a running CI :-) http://ci.ilias.de/viewLog.html?buildId=3850&buildTypeId=Experimental_PullBuild_2&tab=buildLog

I check with @gvollbach if we can "composer install" before every run on the ci-server. If not, i'll change this PR from "Remove Dev-Dependencies" to "Add phpunit/phpunit as dev-dependency" and commit all files

**Comment by chfsx** [comment]
OK, TeamCity is now configured to run "composer install" for Tests. Thanks to @gvollbach and Tobias

**Pull request merged**
