### PR TITLE
orgunit zip Bug #24218

### PR DESCRIPTION
**Pull request by smeyer-ilias**
Hi Xus,

here is the PR for the orgunit permission fix.

Mantis https://mantis.ilias.de/view.php?id=24218

### CODE REVIEW

**Comment by xus** [comment]
I extracted the filter to his own class. Please feel free to merge if it works for you.
Thanks

**Comment by Amstutz** [comment]
Please add the nr of the bugfix to your description of the PR.

**Review by xus — APPROVED** [review]
Thank you @smeyer-ilias for this PR.

**Comment by smeyer-ilias** [comment]
Merged into trunk and 5.4

**Pull request merged**
