### PR TITLE
Disable checkbox for close/delete appraisees when the survey is closed

### PR DESCRIPTION
**Pull request by xus**
Creating/Editing survey 360, in appraisees tab we can select appraisees and then delete them or close their surveys. If one of the selected appraisees has the survey closed and we try to delete/close , appears the message 'Please
select one' and we can not see any change.

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks. I just tested this. If you click "select all" disabled checkboxes are still checked. Maybe showing no checkbox at all (and not deactivate them) would be the better option.

**Comment by xus** [comment]
You are right, with this **style='display:none' disabled** works fine.

**Comment by alex40724** [comment]
In general style attributes should be avoided whenever possible (style should be handled by css/less files in the skin). In this case we should simply not output the whole checkbox.

**Comment by alex40724** [comment]
See 853937c2e1aa384e2f3d6e468e69c6328b724d13

**Pull request closed without merging**
