### PR TITLE
UI, Footer

### PR DESCRIPTION
**Pull request by nhaagen**
This adds the [Footer](https://github.com/ILIAS-eLearning/ILIAS/pull/2051/files#diff-19b7a6034a22226f59300948731bc31f) to the page's Main Controls.

Bildschirmfoto_2019-08-08_15-46-00

Bildschirmfoto_2019-08-08_15-48-08

Bildschirmfoto_2019-08-08_15-34-43

### CODE REVIEW

**Comment by Amstutz** [comment]
Thx a lot @nhaagen I am fine with the interface. The only thing I miss are the "Goto Links" aka "Permanent Links" currently (5.4) in the footer. I guess the "Links" could play this role in your proposal. IMO, the Permanent Link is a special link that should also look a bit differently to be immediately visible. 

Somethig like:
`public function withPermanentLink(\ILIAS\UI\Component\Link\Standard $link): Footer;
`
We can discuss this tomorrow if @klees is also fine with putting that on the upcoming JF. @klees if so, please attach the label.

**Review by klees — CHANGES_REQUESTED** [review]
Hi @nhaagen,

I agree with Timon: The permanent link is required. Maybe the wording is confusing here. The permanent link is no "link" like the other links (not clickable), but that location where I can copy a link to the current page that will survive ctrl-structure-reload. Maybe you'll find a better name.

I put this on the JF for today.

Thx and best regards!

**Comment by matthiaskunkel** [comment]
Thanks @nhaagen for your proposal. Just a question: Maybe I am wrong but on the screenshot above it looks as if the footer is an element embedded in the content page (I assume the blue background element is the footer). But the footer is a "top-level" UI element like top bar or main bar. It need to be the final element on the bottom of the page with no element below it - like it is now in 5.4.

**Comment by ezenzen** [comment]
Thanks a lot @nhaagen. I understand the position of @matthiaskunkel. Perhaps the role/position of the footer becomes clearer if it does not consider the margin of the content page. On the Feature Wiki page "Page Layout Revision (Desktop)" there is a MockUp. I attach the file to this comment. 
Footer

**Comment by nhaagen** [comment]
Thanks, @matthiaskunkel , @ezenzen ; Currently, I indeed appended the footer to the content-section.
This can be changed easily, though. 
Where should I put it in mobile layout? Below the Mainbar?

**Review by klees — APPROVED** [review]
The kitchen sink entry LGTM, so I add the JF label. I think we need to work on the CSS before merging this, especially for mobile, right? Pinging @catkrahl...

**Comment by matthiaskunkel** [comment]
Jour Fixe, 26 AUG 2019 : We highly appreciate the suggested interface. Please add 'withPermanentURL' to the public interface.

**Comment by Amstutz** [comment]
Is this ready for the final review?

**Review by Amstutz — APPROVED** [review]
Hi @nhaagen 

Since we intend to adopt the whole UI Compoents to PSR2 as soon as @klees is back on track, Ill provide the final review on the current state. Merging will be tricky afterwards. IMO we should aim to merge this before. If there are further issues, we can tackle them afterwards.

- [ ] The only thing missing IMO are less variables for the text size (probably @font-size-base, or some variant of it)

@klees anything you ask todo before we merge this?

**Comment by klees** [comment]
@nhaagen: Do it!
@Amstutz: I'm fine.

**Comment by Amstutz** [comment]
Ill merge this due to the upcoming PSR2 migration.

**Pull request merged**
