### PR TITLE
WebDAV Cleanup: Removed the method isLocalPasswordInstructionRequired

### PR DESCRIPTION
**Pull request by rsheer**
The WebDAV Service has a lot of old code in it which affects different parts from other Services / Modules.

With this PR, I want to remove the `isLocalPasswordInstructionRequired`-Method. The method was implemented about 9 years ago. I wasn't really able to make any sense, why this method is needed and why it is implemented in the WebDAV Service.

If this method and it's usage is indeed not needed anymore, I suggest to remove it.

### CODE REVIEW

**Comment by rsheer** [comment]
@swiniker just gave me the hint, that there are more of this methods in `ilContainerGUI`.

I even found out, how to use this methods and probably also why they were implemented. It seems, as if it was at an earlier point important to have a password for the authentication locally stored in ILIAS.

If you want to try this functionality out, go to a container object in ILIAS (in the Browser, not over WebDAV) and add the GET-Parameter *cmd=showPasswordInstruction*. The loaded page will show you a form, where you can set a new password. If you are using ILIAS-Auth for your account, this will change your users password. Otherwise, your password remains the same.

**Review by alex40724 — APPROVED** [review]
Thanks. This is all fine for me. Stefan is on vacation currently, but I think he should comment on the password stuff.

**Review by kergomard — APPROVED** [review]
Thanks @rsheer ! Please check in with @smeyer-ilias after his holidays to see if he sees any problems.

**Comment by smeyer-ilias** [comment]
As far as I know this code was used for the following use case:

- User wants to use webdav-features via browser (Konqueror: webdavs://test54.ilias.de/webdav.php...) or cli (e.g cadaver). 
- The User account uses an external authentication method: e.g shibboleth or CAS.

Webdav uses Apache Basic Authentication which cannot be used for Shibboleth authentication.
In that case the option "Authentication -> Shibboleth -> Allow Local Authentication" needs to be enabled and the user can set or change a local password (stored in the ILIAS database) which is then used for WebDAV authentication. 

I approve these PR if this use case is not supported anymore. Your decision.

**Comment by rsheer** [comment]
Hey @smeyer-ilias,

thanks a lot for your response! Now it all makes sense to me.

This seems like a currently unused feature to me (I might be wrong though). So at first, I thought deleting it might be the best idea to clean up the code.

But I think the part with shibboleth and the EduID, which is coming soon in some Swiss universities, there might be a need for this feature in the future.

I'm leaving this PR open for discussions (if needed) till the 10th of January. If there is no discussion, I will close this PR and think about possible solutions.

Thanks a lot for your help!

**Comment by rsheer** [comment]
This feature seems to be still usefull for some use cases (like auth for shibboleth accounts etc.). But it definitely needs a revision. Therefore, I will close this PR and will think about other solutions.

**Pull request closed without merging**
