### PR TITLE
[FIX] 0023877: Setup broken: Uncaught ilCtrlException: ERROR: Can't f…

### PR DESCRIPTION
**Pull request by chfsx**
…ind target class ilachievementsgui

See https://mantis.ilias.de/view.php?id=23877

### CODE REVIEW

**Comment by klees** [comment]
Hi @alex40724 could you be so kind and have a look here as well?

**Comment by klees** [comment]
I'm not sure this really is the correct solution. As far as I know, the service/module.xml contain info about base classes as well. Are these missing when reloading the control structure?

**Comment by chfsx** [comment]
@klees I don't think this would be a problem:
the structure-reader (ilCtrl-structure) only collects information about the control-structure such as names and locations of GUI-classes and their relation to each other (paths from one cmd-node to another) and does – IMO – not need infos from the xml-files. moving the collection of the information from the xml-files after the collection of the control-structure should be the correct solution

**Comment by alex40724** [comment]
I think it is ok for now. But for the future I think we should avoid to instantiate and call classes of the application code whenever possible. The setup should not need to create links for the main menu. It would be better to pass/collect the necessary information via static xml imo. (I know that Jörg did something similar with the cron jobs)

**Comment by klees** [comment]
Thx you both.

**Pull request merged**
