### PR TITLE
fix 21583: View of Content-fields: Only 3 lines, then stop with ...

### PR DESCRIPTION
**Pull request by alex40724**
https://mantis.ilias.de/view.php?id=21583

### CODE REVIEW

**Review by klees — APPROVED** [review]
LGTM, thx!

**Comment by Amstutz** [comment]
Hi @alex40724 

Thanks a lot for going through the effort of working the line-cap CSS into a nice mixin. 

One minor thing I would like you to add:

- [ ] Write a small comment in the top of the less of what this mixin exactly does along maybe with a link back to the mantis ticket and a note, that this is used in the Listing Panels. I have a fair chance here to grasp and understand the less quickly, since I know the context. A future dev/designer might not be that lucky and wonder what this mixing exactly provides.

Other than that, thumbs up, big thanks.

As soon as commented, you may merge directly, since the CSS is really prone for conflicts.

**Comment by alex40724** [comment]
@Amstutz done

**Comment by Amstutz** [comment]
Thx again, promoted to 5.4 and trunk as well.

**Pull request merged**
