### PR TITLE
T&A Bugix #0038178: Random Question rules that cannot be implemented generate error when starting test.

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=38178
trunk as well

### CODE REVIEW

**Comment by dsstrassner** [comment]
@kergomard - maybe HJL wants this in his pretesting ;)

**Comment by kergomard** [comment]
Thank you very much @fhelfer !
Shouldn't we just remove the  `is_numeric()` check completely? The only reason for it to not be numeric, should be that it is null, but then the check does not help us at all. What am I missing?

Best,
@kergomard

**Comment by fhelfer** [comment]
> Shouldn't we just remove the `is_numeric()` check completely? The only reason for it to not be numeric, should be that it is null, but then the check does not help us at all. What am I missing?
> 

Thx @kergomard , you are right. We can completely remove the numeric check

Best, @fhelfer

**Comment by kergomard** [comment]
Thank you very much @fhelfer ! I think this should work. I will merge and cherry-pick to ILIAS 9 and trunk

**Pull request merged**
