### PR TITLE
T&A: 39719, Fixed Type Error in TestEvaluationUserData concerning login property

### PR DESCRIPTION
**Pull request by malaja11**
Will be taken care of by @mbecker-databay and @thojou 

Possible solution for Ticket https://mantis.ilias.de/view.php?id=39719 and https://mantis.ilias.de/view.php?id=40938

### CODE REVIEW

**Comment by matheuszych** [comment]
We could not reproduce the error but we think this is a possible solution when going by the error stacktrace.

**Comment by mbecker-databay** [comment]
I have to check and see how we can get Thomas on the list of assignees here.

**Comment by dsstrassner** [comment]
hi @mbecker-databay, I think we could assign @thojou if he at least provide one Pull Request to the ILIAS Repo. It was possible to assign @matheuszych / Adding as reviewer needs more rights I assume ;-)

**Comment by dsstrassner** [comment]
Hi all, I close this PR, as the linked mantis issues are also closed, since the error seems to be fixed meanwhile. 
This helps me not to lose track of things. Please reopen if certain changes are still needed.

**Pull request closed without merging**
