### PR TITLE
UI Repository Item Concept Proposal (ILIAS 9)

### PR DESCRIPTION
**Pull request by catenglaender**
# Concept for UI Repository Item

This project was presented at the DevConf 2023 in Bremen. You can [access the slides of the presentation here.](https://catenglaender.github.io/public-notes/ILIAS-development/Presentations/2023/DevConf_March-2023_Object-Properties/export/index.html)

## The Issue

Objects in the repository can display an overhelming amount of properties. Relevant information can get lost in a long list of details that are in many cases less relevant (or even irrelevant) to the user.

## The proposal

This PR [contains a concept](https://github.com/catenglaender/ILIAS/blob/ui/proposal-item-properties/src/UI/docu/UI-Repository-Item_proposal.md) of how properties for objects could be split into different Semantic Groups. Priority Areas offer a tool to highlight specific properties.

This will make objects in the repository more readable and enables users to see relevant information more quickly.

Here is an example for an overwhelming magazine object and a draft how an easier to read grouping of properties could look like below:

example-01

We propose to use the presented guidelines to implement a UI Repository Item that displays properties in an intuitive structure while highlighting the most important information for the average user.

This graphic depicts a possible structure of the Semantic Groups and the Priority Areas on the proposed UI Repository Item:

schema-complete

## Connected Feature Requests

We believe that the approach outlined in this proposal will help to move the following feature requests along:

* [Transfer Repository Objects to KS Items](https://docu.ilias.de/goto_docu_wiki_wpage_6409_1357.html)
* adresses some aspects of [Streamline Object Properties](https://docu.ilias.de/goto_docu_wiki_wpage_7399_1357.html)

## Credits & Participation

Funding for this project was provided by the University of Bern.

This is a follow up project of the [UX Guide: Best practices for properties and actions displayed on repository objects](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/docu/ux-guide-repository-objects-properties-and-actions.md)

The first version of this concept was created during a **two-day workshop** organized by CaT Concepts and Training GmbH and the University of Bern with participation from @catenglaender, @ezenzen, @yvseiler 

We continuously collected feedback over the course of weeks from colleagues (thanks to @klees, @nhaagen, @Amstutz), some object maintainers, the CSS Squad on the ILIAS Discord server and received helpful input and questions after a presentation at the 2023 DevConf in Bremen.

## Next steps

Since the Legacy Repository Item must be replaced by UI framework KS Items soon, we propose the following milestones:

* presentation and discussion at the Jour Fixe
* if necessary revising the concept until approved by the Jour Fixe
* finalizing the design for Delos
* implementing the UI Repository Item (CaT Concepts and Training GmbH and University of Bern are highly interested in doing this)
* FR [Transfer Repository Objects to KS Items](https://docu.ilias.de/goto_docu_wiki_wpage_6409_1357.html)

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @catenglaender 

Thx you, @yvseiler and everybody involved for this great work! @ezenzen seems to be missing in the Credits. Special thx to him for his contribution as well.

I am already familiar with the concept and like it, so I am looking forward to the opinion of other devs. 

Thx

**Comment by Amstutz** [comment]
I tagged this with the JF label, IMO this is in a state, where in can and should be presented / discussed at the jf.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 03 APR 2023: Yvonne and Ferdinand presented the concept of a new UI element for repository items and how the item's properties could be presented in an improved way. Yvonne explained why the concept knows two areas for availability properties and that the blocking conditions should be more prominent while other properties do not need to be highlighted. We discussed if the concept should be more generalised but prefer to focus on repository objects. Concept is highly appreciated and accepted for trunk.

**Comment by Amstutz** [comment]
thx a lot. However, we should remove the png images form the repo since binary file. If strictly needed, maybe link to external source. I close the PR, since we should not merge this, even if the binaries are removed (will create a large history). Once the binaries are removed, feel free to open an directly merge the PR without binaries (also in history).

**Comment by klees** [comment]
@tbongers-cat Could you please reopen this without binaries on top of the current trunk? Will press merge directly afterwards...

**Pull request closed without merging**
