### PR TITLE
Ui framework img card

### PR DESCRIPTION
**Pull request by mjansenDatabay**
UI framework interface changes according to ILIAS v. 5.3.x [feature request](http://www.ilias.de/docu/goto.php?target=wiki_1357_Highlight_Tutorial_Support_in_Member_Gallery)

These changes (required to migrate the members gallery to the ui framework) should be discussed by the Jour Fixe participants.

The final pull request will contain the full implementation and of course passed unit tests.

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
Thank you very much. This looks good to me.

**Review by klees — COMMENTED** [review]
LGTM

**Review by klees — APPROVED** [review]
LGTM

**Comment by matthiaskunkel** [comment]
Jour Fixe, Jan 09, 2017: Pull request is highly appreciated. We should get a guideline for using clickable images.

**Pull request merged**
