### PR TITLE
OrgU: Bugfixes for positions/authorities (release_8)

### PR DESCRIPTION
**Pull request by tbongers-cat**
This fixes [Mantis #35740](https://mantis.ilias.de/view.php?id=35740), [Mantis #35741](https://mantis.ilias.de/view.php?id=35741) and [Mantis #35742](https://mantis.ilias.de/view.php?id=35742) for release_8.

These fixes are also integrated in PR #5243 for trunk.

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @tbongers-cat,

actual changes LGTM. One minor request:

* [x] Early return: Please use that pattern [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5253/files#diff-a404117d49f23ad0f7f0a9ff8a972b78c34dcb70cb1a70c7caac60d4fb4a81e8R96).

And, like in the other PR, please rebase to make lang-checks pass.

Thanks!

**Comment by klees** [comment]
Thx =)

**Comment by klees** [comment]
Merged to trunk as well. I noticed that you already included the fix in the other branch, but the actual code would have been a little different. Please rebase #5243. Thanks!

**Comment by tbongers-cat** [comment]
> Please rebase #5243. Thanks!

Done :)

**Pull request merged**
