### PR TITLE
Notifications: Fix deactivation of Toasts aka. OSD-notifications

### PR DESCRIPTION
**Pull request by iszmais**
https://mantis.ilias.de/view.php?id=41656

### CODE REVIEW

**Review by mjansenDatabay — CHANGES_REQUESTED** [review]
Thx @iszmais , LGTM in general, but we should remove the linked PNG file from the `README` (and thus from our codebase).

**Comment by iszmais** [comment]
Thank you for your quick response @mjansenDatabay 

Pls have another look.

Greetings,
@iszmais

**Review by mjansenDatabay — APPROVED** [review]
LGTM!

**Comment by matthiaskunkel** [comment]
Jour Fixe, 08 JUL 2024: Ingmar notified us about a change in the toast handlings. PR is already merged.

**Pull request merged**
