### PR TITLE
Fix missing files for whoops

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
https://www.ilias.de/mantis/view.php?id=22502

**Comment by ghost** [comment]
Also merge to trunk

**Comment by ghost** [comment]
https://www.ilias.de/mantis/view.php?id=22474

**Comment by alex40724** [comment]
Thanks a lot. I think it's ok if you merge this. Richard is still on vacation and this should do no harm.

@chfsx: What do you think?

**Comment by chfsx** [comment]
Thank you @fwyss-srag, I picked to trunk as well.

**Comment by klees** [comment]
Thx!

**Comment by klees** [comment]
Did you include this in 5-2 as well?

**Comment by ghost** [comment]
In Ilias 5.2 it was already ok

**Pull request merged**
