### PR TITLE
Setup 29874: fix missing or wrong entries in cli status command

### PR DESCRIPTION
**Pull request by daniwe4**
https://mantis.ilias.de/view.php?id=29874

### CODE REVIEW

**Comment by klees** [comment]
Dear @smeyer-ilias, dear @chfsx,

please have a look into this, this touches code maintained by you. From my perspective this looks valid, though.

Feel free to ping me to merge and cherry-pick to trunk, though.

Best regards!

**Review by chfsx — APPROVED** [review]

**Comment by chfsx** [comment]
@smeyer-ilias you can merge this after your review

**Comment by mjansenDatabay** [comment]
Hi @smeyer-ilias 

we stumbled upon this PR in our TB meeting. Any updates on this or objections to merge this?

@daniwe4 Could you please resolved the conflict?

Best regards!

**Comment by daniwe4** [comment]
Hi @klees,
this pr can be closed because its obsolete. The changes are already in the code base of release_7.

**Pull request closed without merging**
