### PR TITLE
T&A Bugfix #0037975: Test derives a faulty dummy question pool with title error

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=37975
Not an issue in Ilias8 and up

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @fhelfer !

This for me didn't "feel" right/sufficient, so I tested it out. I'm still unable to derive question pools correctly.
When I export a test with random questions on ILIAS 7, then import it again, and then go to the Subtab "Selected Question Pools" the title is missing. The export file does contain the title.

May I kindly ask you to give this a second look @fhelfer ?

Thanks again and best,
@kergomard

**Comment by fhelfer** [comment]
> This for me didn't "feel" right/sufficient, so I tested it out. I'm still unable to derive question pools correctly. When I export a test with random questions on ILIAS 7, then import it again, and then go to the Subtab "Selected Question Pools" the title is missing. The export file does contain the title.

release_8 seems to be missing commit https://github.com/ILIAS-eLearning/ILIAS/commit/f385227c225659369280e7845c607139c138dec9 which should update title accordingly

@kergomard, Can you cherry-pick this one in release_8? Im pretty sure this works

**Comment by fhelfer** [comment]
The critical line is the missing isset in https://github.com/ILIAS-eLearning/ILIAS/commit/f385227c225659369280e7845c607139c138dec9#diff-0eae1e0f7fbefa5e2c1a56e4187457859fd31f4e21175d9cdbaa712dbdb0ab59R195

**Comment by kergomard** [comment]
Thank you very much @nhaagen for the rebase.

@nhaagen and @kergomard had a quick chat and decided to leave the constant in the separate class to make it easier to search for it.

Best,
@kergomard

**Comment by kergomard** [comment]
I was not 100% concentrated here and merged the wrong one, sorry! I will check up on this immediately and finalize this.

**Comment by kergomard** [comment]
Ok, I reverted this again, as far as I can see, we don't need it.

**Pull request merged**
