### PR TITLE
Feature/6/ui head info

### PR DESCRIPTION
**Pull request by chfsx**
This is a proposal for the UI-component HeadInfo which indicates a user sees ILIAS in a special mode such as Member-View or LTi. Please note there is a ongoing discussion here: https://docu.ilias.de/goto_docu_wiki_wpage_5979_1357.html

The proposed description and rules: https://github.com/ILIAS-eLearning/ILIAS/pull/2251/files#diff-19b7a6034a22226f59300948731bc31fR316

The proposed interface: https://github.com/ILIAS-eLearning/ILIAS/pull/2251/files#diff-cd550c325169e2bd54eb3649a292c6b2R11

please not that there is a ShyButton instead of the CloseButton in the FR. I suggest to have a button with text here (ans additionally with a "real" URL and not only JS-closing something).

A HeadInfo will be shown like this:

Bildschirmfoto vom 2019-10-11 um 16 49 36

or 

Bildschirmfoto vom 2019-10-11 um 16 50 19

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @chfsx

Thank you a lot for this PR. We believe this already on a quite advanced
state. We therefore squash the implementation and the interface review
into one to save some resources.

We think that a "mode" or "modality" is a very delicate UI-pattern that
should only be used with care. There are various general problems with
"modes" of application. They can easily irritate user, because suddenly
the application behaves differently or looks differently or both. The
application needs to clearly communicate that is in a(nother) mode, if
that is the case. And the user needs an easy way to exit that mode and
go back to normal, if he likes to. Still, we obviously have some "modes"
in ILIAS, and we won't or don't want to get rid of them anytime soon.
The UI-component you are proposing here reflects the current solution
for solving these visual problems.

However, there are some problems with this visuals which we think are
worth addressing in the future:

* Derived from the general considerations above, the mode is always
important. The proposed distinction between "important" or "not
important" might just go away if we find a better place for the info and
the Close-Button. Only using a color for that distinction is an
accessibility problem btw.
* On mobile, the bar as currently designed will have some problems: It
will take very precious screen real estate. The Close Button will be
very close to the Metabar Entries, maybe to close for some fat fingers.
The text on mobile will either be very small or end very soon.
* The PLR managed to clean up the layers on the top level of the
application. This reintroduces a new layer (that certainly also was
there before). For some features (PDF) we seem to require some more page
info (filename, date, ...). Adding this on top level will just introduce
another layer. So the general pattern of "adding new rows in the grid"
is not sustainable. Instead, we should try to coordinate and weigh the
importance of different things that want to be displayed on the first
level in the application instead of just showing them equally next to
each other.
* Is it really correct for all modes to be displayed underneath the
Meta-Bar? This would imply, that the Metabar Entries are not affected.
This is at least incorrect for the Kiosk-Mode in the Learning Sequence.
We are not sure if this is correct for LTI.

In general this might also imply, that we need different Pages (besides
the Standard Page). If we want to stick with the current model (Standard
Page + Mode Info), the current implementation and description will give
us enough wiggle space to work on the way the info and Close Button for
the mode are displayed.

Please consider the following suggestions. You do not need to follow
those, but but please indicate shortly why you prefer to do otherwise:
- [x] Close Button I: Please do not use a Shy Button instead of Close.
This is very clearly a case for a Close Button. If the Close Button
needs to be extended for this, go this way.
- [x] Close Button II: Let the component require a Close-Button via the
constructor. There should always a possibility for the user to leave a
mode he is in. We are not [vim](https://www.amazon.de/How-Exit-English-Chris-Worfolk-ebook/dp/B01N5M1U6W)
=)
- [x] Close Button III: What should happen if the Close Button is
pressed? Probably elaborate somewhat in the effect section.

Please implement the following changes:
- [x] Naming: Rename the component to "Mode Info" and use the wording
"(application wide) mode" instead of "state" in your description. After
all, this is what the component is about: show information about a mode
in which the user currently views the application and provide a way to
leave it.
- [x] Method Descriptions: Add descriptions to the methods of the Head
Info interface.
- [x] No CamelCase: Do not use Camel Case in the YAML descriptions
parsed and displayed in the UI  (HeadInfo -> becomes Head Info in
description for readabilities sake).
- [x] Importance: Add a description on importance in the composition
section. What does important do? When should it be used?
- [x] Less I: Do not introduce values for color and font outside from
the variables.less file. Use existing colors and fonts are declare new
ones that depend on existing ones in variables.less.
- [x] Less II: Replace padding-left: 15px with a variable. I suspect
this to be related to @il-logo-margin. If not introduce a new variable.
Similar case with margin-right. Look at the Header Variables.
- [x] Tests: Add the according Tests.
- [x] Example: Please provide an example for the Header Info. Nice to
have would also be to provide a second Standard Page example show casing
a Standard Page with Header Info.
- [x] Roadmap: Add an entry in the roadmap outlining the problems with
the visuals as noted above.

kindly,
@klees, @amstutz

**Comment by klees** [comment]
Hi @chfsx,

sorry, one suggestion somehow is missing in the text above. Due to the general problems with modality outlined above, we additionally like to suggest that we add a rule to the Mode Info that says: "All usages of the Mode Info MUST be approved by the JF.".

Best regards!

**Comment by chfsx** [comment]
I have adjusted the points above accordingly. 

More information:
- I removed the withImportance() completely. It was about a representation, which was known from ILIAS 5.4, but which is not important.
- CloseButtons have been adapted to accept URIs

**Comment by chfsx** [comment]
I had a very interesting discussion with @rklees today. Basically it was about whether the "mode info" gets a special place in the page, which it should have according to the current state of knowledge. However, there are some "elements" that should be understood rather than "information" that COULD be relevant when putting together a page. For example the title of the installation, the "permalink" and a "mode info". For the moment we want to go the way of seeing the "Mode Info" as part of a page. But we suggest to think about ILIAS 7 in the context of the following roadmap:

ILIAS components have to contribute various information to the presentation when they are executed. Currently they can do this - besides the content - already explicitly via the GlobalScreen service. Each of this information, like the installation title (see PR #2249) is very explicitly addressable. However, since we can assume that other "pages" than the "standard page" will be in the UI service in the longer term, we have to consider whether this information should be understood as information instead of UI components.

**Comment by klees** [comment]
@chfsx This is ready for final review, right?

**Comment by Amstutz** [comment]
AFAIK this is not WIP anymore, correct? If I am wrong plz just open a new PR with link back to this one here.

**Pull request closed without merging**
