### PR TITLE
remove obsolete class ilInitialisation

### PR DESCRIPTION
**Pull request by colin-kiegel**
not in use anymore since svn revision 52916 - previously used for scorm2004.

(one step closer to autoloading)

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Uwe, I did not find any usage of this class. Please remove this file (and the directory).

**Comment by chfsx** [comment]
@Uwe-Kohnle can you have a look at it and then merge the pull request? thanks a lot

**Comment by matthiaskunkel** [comment]
Please contact Uwe Kohnle to discuss if this class can be removed. @Uwe: please have a look at this PR. We keep the PR open.

**Review by Uwe-Kohnle — APPROVED** [review]
ok

**Comment by Uwe-Kohnle** [comment]
Thanks

**Pull request closed without merging**
