### PR TITLE
Data type "link"

### PR DESCRIPTION
**Pull request by nhaagen**
As @klees commented [here](https://github.com/ILIAS-eLearning/ILIAS/pull/544#discussion_r121111675), a data-type "link" would come in handy for several components.
There is also a lot of enhancements potential with a link, e.g. alter/retrieve only parts of the URL, add/get params, etc...

### CODE REVIEW

**Review by alex40724 — CHANGES_REQUESTED** [review]
- The commits seem to mix color and link related code.
- I am not convinced that link would be a data concept. First, this would be a UI concept to me. And a label might be a property of a text link. An image link may come with other properties. Maybe we end up with text links an more complex links which are containers in the UI.
- For me the strong data concept would be the URL, since it implements a specific string format. And URLs would be handy without labels imo, too.

I do not object this idea in general but would prefer to have a URL data object before having a Link data object. And I think we need a UI Link concept because of the reasons I listed here https://github.com/ILIAS-eLearning/ILIAS/pull/544#discussion_r121397943

**Comment by klees** [comment]
Hi @nhaagen,

please move the color related code to a separate PR. Please make the `label` optional for the link. I'll try to to address @alex40724 concerns tomorrow.

Regards!

**Comment by klees** [comment]
Hi @alex40724,
the idea that this is also a data concept is supported by the fact, that we have several locations in ILIAS where I enter a label/URL in a form. Also to me a link is a concept from hypertext, which definitely is not a thing concerning UI only. It moreover encodes the idea, that resources are linked together in a meaningful way. I agree with the idea to check the format of the URL part. We'll also make the label optional. Maybe we should model this completely according to the HTML-link tag and add a rel property and type property as well.
Regards!

**Comment by nhaagen** [comment]
With UI Link and Shy Button, I think this is obsolete.

**Pull request closed without merging**
