### PR TITLE
fix xml_style in ilCtrl::getFormAction

### PR DESCRIPTION
**Pull request by ghost**
The parameter `xml_style` of `getFormAction` is not working correct, because it not passed to `getLinkTargetByClass` in `getFormActionByClass`

### CODE REVIEW

**Comment by ghost** [comment]
The concrete problem is, that the `&` of  `getFormAction` self are correct handled with `$xml_style` (`fallbackCmd`, `rtoken`), but not the `&` of `getLinkTargetByClass` (`baseClass`, `cmdClass`, `cmd`, ...)

**Comment by ghost** [comment]
The following error occurs after send the formular
```
Could not find entry in modules.xml or services.xml for <br/>/ilias.php?ref_id=70
&amp;amp;cmd=post
&amp;amp;cmdClass=ilobjsrtableuigui
&amp;amp;cmdNode=w3:140
&amp;amp;baseClass=ilObjPluginDispatchGUI
&amp;fallbackCmd=showExampleTable
&amp;rtoken=xxx
&amp;cmdFilter=toggleOff
```

**Comment by ghost** [comment]
Auswahl_001
The formular is the toggle switch of the new FilterInput container

**Comment by ghost** [comment]
Strange is, that apply and reset working also without this fix

**Comment by alex40724** [comment]
I stumbled upon similar issues in the last weeks and wonder why this is the case.

But in general we can get rid of the xhtml style completely, right? I will put the issue on the JF agenda.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 01 JUL 2019 : We would like to abandon the xhtml style to solve the mentioned problem (as suggested Alex) instead of merging this PR.

**Comment by ghost** [comment]
Should I remove the xml style in this/or a seperate PR or only close this and someone other make this?

**Comment by ghost** [comment]
@matthiaskunkel Current status?

**Comment by ghost** [comment]
The problem still exists, even with ILIAS 5.4

**Comment by matthiaskunkel** [comment]
Jour Fixe, 23 SEP 2019 : The suggested change is necessary for 5.4 and not for trunk. Therefore, a  bug report is needed for this report. Once the report has been created, Alexander will merge the suggested extension of ilCtrl into the 5.4 release branch. No need to have this extension in trunk.

**Comment by ghost** [comment]
https://mantis.ilias.de/view.php?id=26155

**Comment by alex40724** [comment]
Thanks for the PR

**Pull request merged**
