### PR TITLE
fix empty values on non required input field numeric

### PR DESCRIPTION
**Pull request by ghost**
https://mantis.ilias.de/view.php?id=26219

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @sragfw,

LGTM in general. But: Please use `Validation\Factory::or` in `Numeric::__construct` to build a new constraint from `isNull` and `isNumeric` instead of introducing a new Constraint-class. If we would introduce a new Constraint-class everytime we want to connect two (or more) other constraints, we get an exploding amount of classes. That's what combinators like `or` prevent.

Best regards!

**Comment by mstuder** [comment]
Hi @klees, 

@sragfw is in vacation. We'll be taking a look at this next week.

Best regards
Martin

**Comment by ghost** [comment]
@klees Thanks for the hint using `or`

**Comment by klees** [comment]
@sragfw Thanks for taking care!

**Comment by klees** [comment]
Picked in trunk: https://github.com/ILIAS-eLearning/ILIAS/commit/9a22a6e6c598dd8cc78a8e1f27dad1411b74e446

**Pull request merged**
