### PR TITLE
UI Menu-Drilldown

### PR DESCRIPTION
**Pull request by nhaagen**
Description and looks are mainly taken from https://github.com/ILIAS-eLearning/ILIAS/pull/1620;
However, this introduces general interfaces for Menu/Labeled Menu and picks up a lot of comments from the former PR. Further, this will make it quite easy to adapt and extend existing Menus.
I feel that this version is way superior over #1620, and kindly ask you to have a look a this.

### CODE REVIEW

**Comment by Amstutz** [comment]
@nhaagen, I am unsure about the state of this. Is this ready for a review? Since there are changes in the interface, we need to discuss this during the upcoming JF, is this ready for this?

**Comment by nhaagen** [comment]
Hi @Amstutz ,
rhe rules for menu in the main factory are certainly a little weak, but otherwise I think this is ready for JF.
Main decision, imo, should be which of the pathes to follow, and I find this version way superior.
If you want (and find time), I'd be more than happy for your comments.
Cheers

**Comment by alex40724** [comment]
Thanks for the follow up. Is there any summary about what has changed?

**Comment by klees** [comment]
Yes: The old structure of the KS-namespace was:

* drilldown
    - menu
    - submenu

This proposes:

* menu
    - drilldown
    - sub

instead, which will allow to include `Dropdown Menu` in that same hierarchy.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 07 MAY 2019 : we highly appreciate this PR and accept it for 6.0

**Comment by klees** [comment]
@Amstutz Please ping us if we can merge this. Thx!

**Review by Amstutz — COMMENTED** [review]
Hi @nhaagen

Thank you a lot for refining the drilldown structure.

Note: Thx for fixing intendation issues in several places. However, best commit the directly or provide a seperate PR for such improvements. They might got lost if this would be declined/closed (which will not be the case here).

Please implement the following changes:
- [ ] Resolve Conflicts
- [ ] PHPDocs: Add to the following methods: Drilldown: __construct(), Renderer: renderMenu(), wrapMenuEntry(), maybeConvertLabelToShy(), Sub: __construct()



You may merge as soon as done, to avoid further conflicts.

kindly,
@amstutz

**Comment by nhaagen** [comment]
Hey @Amstutz ,
thanks, but I cannot merge (no permissions...). 
It's ready, though...

**Pull request merged**
