### PR TITLE
Use configured proxy by default in `ilCurlConnection`

### PR DESCRIPTION
**Pull request by ghost**
`ilCurlConnection` should set a configured proxy automatic

otherwise it always has to consider this yourself, which is easy to forget, especially with plugins

Thanks to @fneumann to hint this issue in https://github.com/studer-raimann/H5P/pull/17

### CODE REVIEW

**Comment by klees** [comment]
LGTM, thx!

**Comment by fneumann** [comment]
@sragfw Thanks for merging studer-raimann/H5P#17

I' m not sure if the automatic usage of a proxy in ilCurlConnection will work in all scenarios, e.g. if ILIAS calls the ilServer via RPC behind a firewall. In this case the automatic use of a proxy may not be wanted and the proxy should be reset in ilRpcClient.

**Comment by ghost** [comment]
@fneumann 
Thanks for your hint, I made it disable with a bool parameter and I disable it on the places, which not uses the proxy, like before

**Comment by ghost** [comment]
Or is it better to move it to a seperate function and call it only if desired?
```
$curl->initProxy();
```

**Comment by fneumann** [comment]
Both variants woud be fine. An init parameter has the benefit that the developers get a hint to think about whether the proxy should be used or not. Calls to the 'outside' should use it, 'internal' calls not. As far as I understand the ilBadgeBackpack case, it's an outside call and it would benefit from the proxy. The case of the ECSConnector is not so clear. If a local ECS is used to connect a campus management sytem it may be 'internal', if it is a remote E-Learning Hub, it may be 'outside'.

**Review by alex40724 — APPROVED** [review]
Badge and Media service related changes are fine for me. Thanks.

**Review by klees — APPROVED** [review]

**Comment by smeyer-ilias** [comment]
Thanks to all.

**Pull request merged**
