### PR TITLE
fix undefined array key for some nodes

### PR DESCRIPTION
**Pull request by ingoj**
Sometimes invalid objects are found when displaying object lists. This leads to "array key not found" errors. This PR shows a possible solution

### CODE REVIEW

**Comment by ingoj** [comment]
May apply to release_9 and trunk, too

**Comment by kergomard** [comment]
Thank you very much @ingoj for the PR!

I would have three little requests:
* Could you please provide an issue report in mantis? You don't have to reproduce this on test8, but so we have a reference.
* Could you please combine your changes with the ones in the next `if`-statement, so: `if (!isset($node["ref_id"]) || (int) $node["ref_id"] !== $item_ref_id) {`.
* Might you be so kind and fix the copyright headers as you have to touch this once more anyways?

Thanks again and best,
@kergomard

**Comment by ingoj** [comment]
if- statements are combined
mantis entry will follow in acouple of minutes (not the only one for today)
Sorry, I am not familiar about the changes wirth the copyright headers, do you have some instructions?

**Comment by kergomard** [comment]
Thank you very much @ingoj !

I will take care of the headers after merge, if you want. Sorry, I'm not finding the rules for the copyright, but basically they are that every code-file in ILIAS needs to start with the precise copyright at the top of the file. Nothing apart from the opening php-tag should be above. A correct example would be e.g. [here](https://github.com/ILIAS-eLearning/ILIAS/blob/b07e9d437baa61a5f4d245c981825006a0e33f6c/components/ILIAS/ILIASObject/classes/class.ilObjectActivation.php#L1).

And then I think you now introduced superfluous brackets `) || (` with your commit ;-).

Thanks and best, 
@kergomard

**Comment by ingoj** [comment]
Brackets are removed, and I tried to fix the copyright lines (it semms copyright must start alt line 3, was line 5)

**Comment by kergomard** [comment]
Don't worry about the Copyright. I will figure it out afterwards. The rest is ok now: I  just wait for the issue in Mantis and merge tomorrow.

**Comment by ingoj** [comment]
mantis 41486

**Comment by kergomard** [comment]
Merged and picked to ILIAS 9 and trunk.

You actually fixed the copyright alright, ...just in the wrong file ;-).

Best,
@kergomard

**Pull request merged**
