### PR TITLE
T&A Bugfix #0040634: Calling print view in question list of test leads to fatal type error

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=40634

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much for the PR @fhelfer ! Special thanks for typing this all a little more strictly.

I'm sorry to say though: I don't think this is the right solution:
- Why are asking for the reached points of a print preview?
- Why do we have an `active_id` here that also has a result?
- What feedback are we expecting to be shown here? Feedback for the right answer or the wrong one? (@dsstrassner : Maybe you have an answer for this.)

My feeling is: There is something fundamentally wrong here.
It would be very kind, if you could analyze this a little more deeply. Maybe we should also discuss this amongst @dsstrassner, @mbecker-databay, me, and you?

Thank you very much and best,
@kergomard

**Comment by dsstrassner** [comment]
I am sorry about the delay @fhelfer: 

ILIAS 7 only shows the correct answer(s) and no feedback in the Print View of the Question Tab. The review tab only shows the question.

 Please remove the link between the feedback setting of scoring and results and the print view on the questions tab. The Feedback setting in Scoring and Results should only be relevant for the viewing of answers in the test results. (ILIAS 8 only).

**Comment by dsstrassner** [comment]
I think this all came from the "Einstellungsüberarbeitungsworkshop" and the changes at the scoring and results sub tab ;-)

**Comment by fhelfer** [comment]
Hi @kergomard,

I disabled the calculation of feedback for the print view. There's still result calculations with an active_id = 0 (but most have been disabled with this PR), so there might still be something fundamentally wrong, but this seems to be a good enough fix IMO.

Please give the PR another review.

Best @fhelfer.

**Comment by kergomard** [comment]
Thank you very much again for the PR @fhelfer ! I cherry-picked your changes manually and added a few more of my own, thus I close this.
Best,
@kergomard

**Pull request closed without merging**
