### PR TITLE
Removing LUI: Allow UI Buttons in ilToolbarGUI

### PR DESCRIPTION
**Pull request by tfamula**
This is IMO a needed change to allow using UI Buttons in `ilToolbarGUI`.

### CODE REVIEW

**Comment by alex40724** [comment]
@tfamula Thanks for the PR. There is an existing addComponent() function that should allow to add KS buttons imo. Please check.

**Comment by mjansenDatabay** [comment]
Alex is right, the existing method is already widely used. The bigger problem is, that there is IMO no (non-hacky) way to replace instances of `ilSubmitButton` (means: a HTML button which is natively able to submit the toolbar form for state manipulating POST requests) in legacy toolbars.

**Comment by mbecker-databay** [comment]
I am good with this PR, thank you!

**Comment by tfamula** [comment]
Thanks for the hint, @alex40724! `addComponent()` already does the job. My bad!

**Comment by tfamula** [comment]
@mjansenDatabay Maybe you should put the mentioned problem on the agenda for the next "Removing LUI"-meeting!

**Pull request closed without merging**
