### PR TITLE
0023728: Updating LP Settings does not refresh Learning Progress corr…

### PR DESCRIPTION
**Pull request by theodortruffer**
…ectly

### CODE REVIEW

**Comment by theodortruffer** [comment]
@Uwe-Kohnle here's the mantis report to this bug: https://mantis.ilias.de/view.php?id=23728
I think this will have to be merged into 5.2, 5.4 and trunk, too.

**Comment by mjansenDatabay** [comment]
@Uwe-Kohnle : We stumbled upon this PR in our biweekly TB meeting. Could you please merge this PR or provide your objections?

**Comment by Amstutz** [comment]
@Uwe-Kohnle : We stumbled upon this PR in our biweekly TB meeting again. Could you please merge this PR or provide your objections?

**Comment by kergomard** [comment]
**@Uwe-Kohnle** : Sorry to bug you with this again, but looking at PRs that have been open for a long while the TB noticed that this PR is still open. Could you please merge this PR or provide your objections?

**Review by Uwe-Kohnle — APPROVED** [review]

**Pull request merged**
