### PR TITLE
PHP 7.2/Init: Fixed errors for initial HTTP request after completing setup

### PR DESCRIPTION
**Pull request by mjansenDatabay**
Mantis Tickets:
* https://mantis.ilias.de/view.php?id=24914
* https://mantis.ilias.de/view.php?id=24915

### CODE REVIEW

**Comment by shecken** [comment]
LGTM. I just have a question. Should we wrap [this](https://github.com/ILIAS-eLearning/ILIAS/blob/2a20e4c8571fe312e7ffe24ce46bc8b8ed93363b/Services/Logging/classes/error/class.ilLoggingErrorSettings.php#L85) with a check on an existing, none null gClientIniFile property?

**Comment by mjansenDatabay** [comment]
@shecken Yes, this would be more robust

**Review by alex40724 — APPROVED** [review]
Thanks. Looks fine to me. Can be merged anytime. Will you include more changes according to @shecken's comment or should I merge?

**Comment by mjansenDatabay** [comment]
@alex40724 Now you can merge and cherry-pick to `release_5-4` if you like.

**Comment by alex40724** [comment]
Merged and picked. Thanks!

**Pull request merged**
