### PR TITLE
#33552: setup now recognizes objectives that halt the program.

### PR DESCRIPTION
**Pull request by thibsy**
Hi all,

There currently is an issue with the setup, where an ILIAS-update (e.g. `php setup/cli.php update`) could abort when a certain objective is reached without any further information. In our case, this was due to a "bad" plugin which loaded some library in its constructor that contained an `exit` statement somewhere. 

We cannot prevent this from happening obviously, but we can offer some better information about why the setup aborted. This PR introduces a shutdown-function that recognizes if an objective halted the program and displays an according message in the terminal.

Best regards!

EDIT @klees:
The problematic behaviour is no described in [#33552](https://mantis.ilias.de/view.php?id=33552).

### CODE REVIEW

**Comment by thibsy** [comment]
@klees do you think I should just throw a RuntimeException all the time instead of printing the message nicely if possible?

**Comment by klees** [comment]
I would prefer a simple RuntimeException. This way, all errors will look the same.

**Comment by klees** [comment]
And Symfony will take care =)

**Review by klees — APPROVED** [review]
Neat fix, thx a lot @thibsy!

**Comment by klees** [comment]
Picked to trunk.

**Comment by thibsy** [comment]
Thx!

**Pull request merged**
