### PR TITLE
Several UI-Fixes

### PR DESCRIPTION
**Pull request by klees**
Hi @Amstutz, hi @nhaagen,

this fixes various issues in the UI framework:

* [#33704](https://mantis.ilias.de/view.php?id=33704)
* [#33831](https://mantis.ilias.de/view.php?id=33831)
* [#33832](https://mantis.ilias.de/view.php?id=33832)
* [#33581](https://mantis.ilias.de/view.php?id=33581)
* [#33778](https://mantis.ilias.de/view.php?id=33778)

Since I'm a little tired lately, I would appreciate you having look into my changes.

Thanks!

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @klees 

Thx a lot for the various fixes. I am not happy with the fix for the "for" label for the file input. However, atm, I do not see much room for improvements due to the ext. Deps at work here. It's certainly an improvement compared with the current state of this. However, it might be possible that this will become up again in a future audit/test.

thx,
@Amstutz

**Comment by jbraun-ilias** [comment]
Hi @Amstutz  the mantis ticket [#33581](https://mantis.ilias.de/view.php?id=33581) was for ILIAS 7...
When is the fix coming for this version?

**Comment by Amstutz** [comment]
@jbraun-ilias : thx for the feedback. 

Most of the linked issues are a11y issues. Atm I do not port a11y down to productive releases due to lack of resources and high risk of breaking changes (not obvious breaking changes for skins or JS due to DOM changes). Exceptions are possible, but my prio is to get as many a11y Tickets fix for the next release.

The Ticket you linked is differen however (being a UI Component issuen, not a11y). @klees do you see an option to provide a seperate PR containing only the fix for this individual ticket?

thx.

**Comment by klees** [comment]
@Amstutz We could simply pick [this commit](https://github.com/ILIAS-eLearning/ILIAS/pull/5148/commits/69927a8dbfa613a13d2605f43573398b054a1f85) I would assume...

@nhaagen Would you be so kind?

**Comment by klees** [comment]
Cherry-picked: https://github.com/ILIAS-eLearning/ILIAS/commit/74a06af00e744c39308729ef4335fba73fc2fadc

**Pull request merged**
