### PR TITLE
Feature/7/file storage service

### PR DESCRIPTION
**Pull request by chfsx**
This PR introduces the ResourceStorageService for ILIAS 7. 

Generally speaking, the service offers:
- The storage of files in a central location
- The possibility for components to store files without dealing with the FileSystem and the concrete file storage location
- The ability for the service to request components if files are still needed.

Please have a look at the README located here:

https://github.com/ILIAS-eLearning/ILIAS/compare/trunk...studer-raimann:feature/7/file-storage-service?short_path=3e6246f#diff-3e6246f6450e318be155b935e8b88a49

At TopLevel the service via the DIC offers two scopes:
- manage()
- consume()

via manage a component gets the following options: 
- Transfer user uploaded files to the storage. A unique ID will be displayed, which the component should store.
- Exchange an ID for the resource known to the StorageService with all its revisions
- Manage revisions (file versions)
- delete resources

via consume there is the possibility to output a revision of a resource, currently as
- Download
- Inline
- File stream

in a next step I'll propose how to migrate files (fileobject) by using the 'migrate' command in the setup.

### CODE REVIEW

**Comment by klees** [comment]
Hi @chfsx,

I assigned you because I think you are responsible for this =)

Best regards!

**Review by klees — APPROVED** [review]
Thanks Fabian! I'm really looking forward to use this.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 12 OCT 2020 : Fabian wants to merge this PR on Wednesday. If any developer has a comment or an objection, please contact Fabian until tomorrow.

**Comment by alex40724** [comment]
Hi @chfsx,

thanks for the PR. I think it would be good to have more examples in the readme file. It currently stops when retrieving the ID for the resource which I can store in the DB. But how to continue after that? E.g. how do I offer such a file for download?  This is currently no covered in the readme (or maybe this information is somewhere else or I am missing something)?

Thanks for your great work!

Alex

**Comment by chfsx** [comment]
Hi @alex40724 
Thanks, this was missing and I just appended this in the readme! feel free to ask anything else of there are more examples needed, I will update the readme accordingly.

Best regards Fabian

**Pull request merged**
