### PR TITLE
Feature/6 0/changelog service 2

### PR DESCRIPTION
**Pull request by theodortruffer**
@ILIAS-eLearning/technical-board 

This PR provides an alternative structure for the changelog service suggested in PR: https://github.com/ILIAS-eLearning/ILIAS/pull/1991

Please have a look at the README for general information on usage: src/Changelog/README.md

# Structural Change

Unlike in the previous PR, the structure uses a single database table for all events, including the following fields:

> 1. event_id (uuid)
> 2. actor_user_id (who did this?) - could be null
> 3. subject_user_id (which user concerns this?) - could be null
> 4. subject_obj_id (which object concerns this?) - could be null
> 5. event_name
> 6. ilias_component
> 7. additional_data (component-specific, json-formatted)
> 8. timestamp

By omitting component-specific tables, I was able to remove all "Handler" classes and simply rely on one repository to store and read change events: src/Changelog/Interfaces/EventRepository.php

The Query side was also immensely simplified: a QueryFactory delivers a Filter and Options, which are used to receive an array of EventDTOs (see README).

----
I tried to address all of your concerns from the last PR. Please consider this new structure and let me know if there are any questions/concerns. (*Edit:* I forgot the tests, I will deliver them later)

**One question from my side:** 
- [ ] Will the service be included in the DIC?

I'm asking this because the instantiation of the ChangeLog class uses dependency injection and therefore the consumers would need knowledge of the EventRepository / ilDBEventRepository (which is unpleasant IMO). This problem would be solved if the service is included in the DIC but else I would consider introducing some kind of factory for the service. 

I understand your _concerns about the relation to the ILIAS EventHandler_. I'm open for discussing if this service might be extendable to a global EventHandler - but at this moment we don't really have the ressources and time for a discussion of this size and therefore would like to limit this service's responsibilities to the original scope: logging changes.

I'm looking forward to your feedback,
Theo

### CODE REVIEW

**Comment by Amstutz** [comment]
I assigned this the Theo, since he is IMO responsible for the moment for this new service.

**Comment by theodortruffer** [comment]
@ILIAS-eLearning/technical-board will this PR be reviewed?

**Comment by Amstutz** [comment]
Dear @theodortruffer!

First of all: We are sorry it took us so long to give you an answer. The @-mention you used seem to have slipped out attention. We'll try to find out why that happened (and of course fix it).

Second, we feel that we need to clarify the role of the TB in this PR (and similar ones) a little. We feel responsible here regarding the introduction of a new service "Change Log", as this seems to be an issue of general architecture and structure of our application. From this perspective, we are happy that you asked proactively by mentioning us, instead of silently introducing a new folder and then seeing what happens.

As TB we do not feel responsible to perform an in-depth review of the PR. The concrete implementation of components, in accordance with our coding rules and guidelines, is the responsibility of the component's maintainer. For changes with huge importance we might deviate from this as we see fit, but we will try to do our best to be transparent when we plan to do so to not catch anyone by surprise. Individual members of the TB might look deeper into PRs just as every other developer may do. In both cases (feedback from TB, feedback from individual TB-member) we'll do our best to unambigiously communicate who is the originator of the feedback.

Now  to the proposed introduction of a "Change Log"-service:

Although we feel that **a** change log service could be a valuable service for our system, we currently would object to introduce **a** new "Change Log"-service as you propose in this PR. The reasons for this are:

* The relation of the proposed service to other services in the system needs to be designed in more carefully. Most notably: The name `Event` will be introduced a third time in this service (current ILIAS event system, event sourced architecture in assessment question service, maybe even more?). Why don't we use the current event system (or improve it) to fire the events? How is this different from the event sourced architecture in the assessment question service? How should someone that reads `Event` in the source code is supposed to know what is what? Furthermore: How is this related to the currently existing change log of the RBAC? Should that be migrated? How are the relations to XAPI? E.g. if someone has passed a course, will this need to be announced three times (once to the current event system, once to your log, once to XAPI)?
* The relation of the proposed service to its consumers need to be clarified. E.g.: The cronjob seems to need to know the [consumers](https://github.com/ILIAS-eLearning/ILIAS/pull/2115/files#diff-71d3d0d71c30d1faff6c2f7babee6f3cR119). The lang variables about consumers events reside in the events. The readme does not say anything about deletion of data (although the cronjob does). This should be simple to fix in general, but also is something that should be informed by input from other ILIAS developers (= possible consumers) of the service.
* From what we read in the description and the code in this PR and its predecessor, this aims to be **the** change log service of ILIAS. We feel that this would require a lot more consultation and discussion with other ILIAS developers as currently has happened. We would be glad to help to organize an according workshop with other developers. The former question most certainly are things that should be discussed on said workshop.

We hope you understand that we do not want to stop you for no good reason, but instead see that your proposal pokes into the middle of some very relevant and important questions regarding the architecture of our whole system. For the upcoming release in november, we recommend you to more or less transfer the service as is to the place it is use at the moment (probably membership, if the corresponding maintainer agrees). If other services for the moment also need to consume it, then we can live with the fact, that we have some slightly odd dep. there. However, this seems to serve as a good starting point for a discussion on how we want to design together a central log service for future releases. Also, since you kept the foot print in the persistence layer really slim (well done!) we expect it to be a rather low cost to transfer the existing log data to a (hopefully) upcoming new central log service.

If you have further question or if you have resources ready to discuss next step for a central log service for a future release, please contact us.

Best regards!
The TB

**Comment by kergomard** [comment]
@theodortruffer 
Thx for this contribution. I will close it though for now, as it has gathered some dust. Please create a new PR, if you think we would need to keep this open.
Best,
Stephan for the TB

**Pull request closed without merging**
