### PR TITLE
UI, Mainbar - add aria-labels to buttons and slates (fixes 27979)

### PR DESCRIPTION
**Pull request by nhaagen**

### CODE REVIEW

**Review by tfamula — APPROVED** [review]
Thanks for the PR! This fix can be merged IMO.

**Review by klees — APPROVED** [review]

**Review by Amstutz — APPROVED** [review]
Thanks a lot!

**Comment by Amstutz** [comment]
cherry-picked to 6 as well.

**Comment by Amstutz** [comment]
@tfamula thanks for pointing the right fix in mantis.

**Pull request merged**
