### PR TITLE
18206: store context in session, check for context, add supportPushMesssages…

### PR DESCRIPTION
**Pull request by alex40724**
… for contexts

This is a bugfix for 0018206

Björn, I assign this to you first. But I think there is not too much of your session code involved. I will it assign to Stefan and Jörg, if I have your ok for this change.

### CODE REVIEW

**Comment by bheyser** [comment]
Hi all,

no objections sincce the sessoin control make use of own type domain. ilcontext could be used in the long way, but currently it is not.

**Comment by alex40724** [comment]
@Stefan: Any objections?

**Comment by smeyer-ilias** [comment]
No objections.

**Comment by alex40724** [comment]
@Jörg: Please have a look at the code. There is one open issue, see

> ```
>           // todo: ask context $u["context"] if it supports pushMessages
>           if ($u["context"] == 1)
> ```

Problem: I have a given context and want to know, if it "supportsPushMessages".

**Comment by chfsx** [comment]
@alex40724 Is this PR still needed?

**Comment by alex40724** [comment]
Yes

**Comment by chfsx** [comment]
@alex40724 this PR has currently conflicts
@Uwe-Kohnle can you have a look at it after the conflicts have been resolved?

**Comment by alex40724** [comment]
Sorry, my bad I misread your comment. Uwe, there is a marginal change in the ScormContext class.

**Comment by Uwe-Kohnle** [comment]
It's okay for ScormContext class

**Pull request closed without merging**
