### PR TITLE
[HUN] Wiki link, cron, install->telepít (5.0)

### PR DESCRIPTION
**Pull request by KissDaniGH**

### CODE REVIEW

**Comment by chfsx** [comment]
@alex40724 can we merge language-pull-requests for stable releases? I thinks these are language bugs and can be merged, whats your opinion?

**Comment by KissDaniGH** [comment]
these are only minor changes, no new name for any object or somwething like that...
noone will be suprised if upgrade to 5.0.4

**Comment by alex40724** [comment]
Yes, of course the pull requests of language maintainers should be merged. You can forward these requests to Matthias, if you like, since he leads the translation process.

**Comment by chfsx** [comment]
Matthias delegated the language-pullrequest to me. thanks for the response!

**Pull request merged**
