### PR TITLE
Templates/Images: move images, adjust references and adjust...

### PR DESCRIPTION
**Pull request by lukastocker**
... implementation for UI > Symbols (#35768)

Mantis Ticket: https://mantis.ilias.de/view.php?id=35768

### CODE REVIEW

**Comment by Amstutz** [comment]
LGTM. However, we should test that throughly before merging, to not create major havock on trunk. @yvseiler can you look into this and give feedback if good and assign back to @klees .

@klees feel free to merge if the feedback of @yvseiler is all good. I accept that from a system styles maintainer POV. thx.

**Comment by yvseiler** [comment]
Hi @lukastocker 

Thank you a lot for your work on the new structure of the images folder. It works fine in most places, except for the following places, which I found:

Please implement the following changes:
- [x] **Communication > Mail > Mail Folders (Slate in Tools)**: Images are "broken". The source of these images is f.e. src="./templates/default/images/icon_inbox.svg" and should be src="./templates/default/images/standard/icon_inbox.svg" I think.
- [x] **Administration > Achievements > Competence Management > Edit a Competence Tree > Tab "Competences"**: Images in column "Typ" aren't visible. The source of these images is f.e. src="./templates/default/images/icon_skll.svg?vers=9-0_alpha" and should be src="./templates/default/images/standard/icon_skll.svg?vers=9-0_alpha" I think. I don't know what the "?vers=9-0_alpha" means in this case, it's also there on test9.ilias.de. Seems to be another issue.
- [x] **Administration > Layout and Navigation > Layout and Styles > Page Layouts**: Images in column "Active" aren't visible. The source of these images is f.e. src="./templates/default/images/icon_ok.svg" and should be src="./templates/default/images/standard/icon_ok.svg" I think. 
- [x] **Test > Participants > Column "Test started" and "Finished"** (f.e. here https://dev-server.cat-office.de/bern_icon/goto.php?target=tst_86&client_id=ilias). Also concerns the icon_ok.svg from the point above: Source is src="./templates/default/images/icon_ok.svg" and should be src="./templates/default/images/standard/icon_ok.svg"
- [x] **Lernmodul > Settings > Content > Chapters** (f.e. here http://dev-server.cat-office.de/bern_icon/goto.php?target=pg_3_92&client_id=ilias > Actions-Dropdown beside "Print View" button > Edit Chapters): Image of chapter is "broken". The source of this image is src="./templates/default/images/icon_st.svg" and should be src="./templates/default/images/standard/icon_st.svg"  I think.

While reviewing the new folder structure, I noticed three icons that should be in a different folder:
- [x] Could you move the following three icons from the "media" folder to the "object" folder? I'm sorry, but of course this will also result in path adjustments:
- marked.svg
- notification_off.svg
- notification_on.svg


Thanks
@yvseiler

**Comment by lukastocker** [comment]
> * icon_st.svg



> Hi @lukastocker
> 
> Thank you a lot for your work on the new structure of the images folder. It works fine in most places, except for the following places, which I found:
> 
> Please implement the following changes:
> 
>     * [x]  **Communication > Mail > Mail Folders (Slate in Tools)**: Images are "broken". The source of these images is f.e. src="./templates/default/images/icon_inbox.svg" and should be src="./templates/default/images/standard/icon_inbox.svg" I think.
> 
>     * [x]  **Administration > Achievements > Competence Management > Edit a Competence Tree > Tab "Competences"**: Images in column "Typ" aren't visible. The source of these images is f.e. src="./templates/default/images/icon_skll.svg?vers=9-0_alpha" and should be src="./templates/default/images/standard/icon_skll.svg?vers=9-0_alpha" I think. I don't know what the "?vers=9-0_alpha" means in this case, it's also there on test9.ilias.de. Seems to be another issue.
> 
>     * [x]  **Administration > Layout and Navigation > Layout and Styles > Page Layouts**: Images in column "Active" aren't visible. The source of these images is f.e. src="./templates/default/images/icon_ok.svg" and should be src="./templates/default/images/standard/icon_ok.svg" I think.
> 
>     * [x]  **Test > Participants > Column "Test started" and "Finished"** (f.e. here https://dev-server.cat-office.de/bern_icon/goto.php?target=tst_86&client_id=ilias). Also concerns the icon_ok.svg from the point above: Source is src="./templates/default/images/icon_ok.svg" and should be src="./templates/default/images/standard/icon_ok.svg"
> 
>     * [x]  **Lernmodul > Settings > Content > Chapters** (f.e. here http://dev-server.cat-office.de/bern_icon/goto.php?target=pg_3_92&client_id=ilias > Actions-Dropdown beside "Print View" button > Edit Chapters): Image of chapter is "broken". The source of this image is src="./templates/default/images/icon_st.svg" and should be src="./templates/default/images/standard/icon_st.svg"  I think.
> 
> 
> While reviewing the new folder structure, I noticed three icons that should be in a different folder:
> 
>     * [x]  Could you move the following three icons from the "media" folder to the "object" folder? I'm sorry, but of course this will also result in path adjustments:
> 
>     * marked.svg
> 
>     * notification_off.svg
> 
>     * notification_on.svg
> 
> 
> Thanks @yvseiler

Hi @yvseiler ,

I just fixed the issues above and pushed the commit to this PR and tested my implementation on my local instance. Please check if it's also working for your instance.

Best wishes
Luka

**Comment by yvseiler** [comment]
Thanks a lot @lukastocker ! It now looks good in those places too. I am therefore assigning this PR to you @klees  so that it can be merged.

**Pull request merged**
