### PR TITLE
PRG: 37941, fix placeholder in langvar

### PR DESCRIPTION
**Pull request by nhaagen**
https://mantis.ilias.de/view.php?id=37941

### CODE REVIEW

**Comment by dsstrassner** [comment]
Not sure, if @matthiaskunkel or @klees is the right contact person ;-)

**Comment by matthiaskunkel** [comment]
@nhaagen : what is the content of the (%s)? It is difficult to say if the wording is correct when one does not know the entire message. And the German version does not mention the "individual plan" but just says "Erfolgreich aktualisiert (%s)"

**Comment by nhaagen** [comment]
It's a technical placeholder and will be substituted by the amount of updated records.
Translation will read "Successfully updated individual plan (34)".

**Comment by matthiaskunkel** [comment]
Here comes the feedback from our master of English language. He suggest to write:
Individual plan (%s) successfully updated.

**Comment by nhaagen** [comment]
Hi @matthiaskunkel ,
changes are in. I removed the brackes, though, they don't make sense in mid-sentence

**Review by matthiaskunkel — APPROVED** [review]
LGTM

**Comment by matthiaskunkel** [comment]
Thanks for the fix.

**Pull request merged**
