### PR TITLE
UI Panel Secondary

### PR DESCRIPTION
**Pull request by xus**
This PR introduces a new UI component to be used when any kind of information has to be displayed and not located in the Center Section.

This component among other things will be a substitution for current marginal content blocks like the mini calendar.

This PR comes after these previous discussions/descriptions:

- https://docu.ilias.de/goto.php?target=wiki_1357_Streamlining_Blocks_as_Panels
- https://edupad.ch/p/ym7klsMeXz

### CODE REVIEW

**Comment by Amstutz** [comment]
@xus : Just to avoid a possible deadlock here, is the interface ready to be reviewed and then discussed in the JF?

**Comment by xus** [comment]
Yes, the interface is ready for the review. Thanks

**Review by klees — CHANGES_REQUESTED** [review]
Hi @xus!

Thank you a lot for contributing to the UI-Framework of ILIAS.

Your work looks very solid overall and we see your efforts to implement the points we agreed upon in the meeting. We see that these efforts need to be taken a little further, which we'll try to outline in the next sections. Besides that we have the usual questions and change requests and are looking forward for your answers and improvements.

Please answer the following questions:
- [x] Why can the Secondary Panel contain only one View Control? This seems to be very harsh. Why not have, e.g. Pagination and Sortation?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [x] Please change the wording at the rivals-section that delimits the Secondary Panel from the Slate. We do not see that referring to an "institution" is a good way to delimit the two. The visibility of slates is also the result of some configuration done by the institution, since the mainbar is configurable and the items in the metabar depend on configurations of the installation as well. We would suggest to use the following wording instead: "Other than the Slates in the Mainbar and the Metabar, the Secondary Panel always relates to some specific context indicated by the title of the current screen. Note that the slates in the tools of the Mainbar may have a very similar context-based characteristic. The difference between Slates, Tools and Secondary Panels currently is blurry and needs to be defined more rigorously in the future." After all, this was one core issue raised in our meeting, where the introduction of the Secondary Panel was the way forward to gather more data on this issue. We do not see that this issue is easily solvable by just referring to some "institution".

Please implement the following changes:
- [x] Use typehints on arguments and return values where possible.
- [x] Most probably you would have done so anyway, but: Please remove uncommented code.
- [x] Please do not capitalize "Center Section" and "Center Content". We feel that there is the convention that capitalized stuff hints at components in the UI-Framework, but we currently do not have these components.
- [x] Please introduce "Secondary Listing Panel" and "Secondary Legacy Panel" as children of "Secondary Panel", like we agreed upon in our meeting, instead of putting a Listing Panel (or a Legacy component) into the Secondary Panel. Although this might currently work on the technical level, we see issue on the conceptual level when binding the Listing Panel to the Secondary Panel in the way you propose. The issues we see are currently visible in the `title`-property that just duplicates in the Listing Panel and Secondary Panel. Currently, the `title` from the Listing Panel is silently dropped during rendering. Why do we use the one and not the other? The Secondary Panel, on the other hand, currently allows to add View Controls, while the Listing Panel can have actions in a Dropdown. What will happen when the Listing Panel should get View Controls? Or the Secondary Panel should get actions (like your rules already suggest)? Questions like these will lead to conceptual dependencies in the future we want to avoid. Both questions might even lead to problems on the technical level. Overall we see some more conceptual issues regarding the displaying of items (e.g. Deck of Cards/Listing Panel, Card/Item) and we see these problems to grow even larger if we accept the Secondary Panel in the way you propose. A duplication of the Listing Panel as Secondary Listing Panel will give us some more wiggle room on both. 

If you have questions or remarks about or feedback, feel free to ask or remark, here or personally, as always.

Note that this is only the review for the Interface TBD at the JF. We will perform a spererate review on the implementation as soon as the interface is accepted.

kindly,
@klees and @Amstutz

**Comment by xus** [comment]
Hi @klees and @Amstutz 

Thank you for this review. I will try to provide an answer to your points.
About the question above:
> Why can the Secondary Panel contain only one View Control? This seems to be very harsh. Why not have, e.g. Pagination and Sortation?

I used in the composition rules the following verbs:
"contain" to define parts inside the main content of the secondary panel. 
"have" to define elements outside the main content like the secondary panel title, actions, and sortation.
What the composition rule nº4 said inaccurately is that we are not allowed to "have" a Pagination plus a View Control at the same time in the main content.

I can change it to: Secondary Panels MUST NOT contain more than one UI ViewControl in the main content
But, maybe it can be good to introduce in the description the concepts of "main content" and "top content". What do you think?

I am completely fine with the suggested changes at the rivals-section and also with the required changes.

I remove the JF tag because changes in the interface are needed. I will reach you again when I finish to adopt these changes.

Thanks once again.

**Comment by xus** [comment]
Hi @klees @Amstutz 
I updated the PR with the requested and suggested changes.
Now we have the mentioned child panels "Secondary Listing Panel" and "Secondary Legacy Panel".

The Interfaces are ready for review. I will provide tests and examples of the implementation after approval.

Edit-> I made small changes in the interface minutes after this comment.
You can read them [here](https://github.com/ILIAS-eLearning/ILIAS/pull/1522/commits/f0b4b8582a03f1e02f87d386f660ee54fca31357). Sorry if I was late.

Thanks in advance.

**Review by klees — CHANGES_REQUESTED** [review]
Hi @xus!

Thanks for working on this! And sorry for the delay.

Two change requests from my last review haven't been incorporated completely yet:

- [x] Use typehints on arguments and return values where possible.
- [x] Most probably you would have done so anyway, but: Please remove uncommented code.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:

- [x] Use `withViewControls` like [Presentation Table does](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/Table/Presentation.php#L32) to add view controls to the `Secondary Panel` instead of using specific getters/setters for the different controls. A similar API will help our users. Also, there might be new view controls in the future and we would want to use these as well, right? Or is there a special reason that you don't want to use the `Mode View Control`.#

Kudos for the optional type hints!

Best regards!

**Comment by xus** [comment]
Thanks, @klees

No worries for the delay, looking at the pull requests and how the ILIAS UI components are growing it is completely understandable.

> A similar API will help our users. Also, there might be new view controls in the future and we would want to use these as well, right?

I knew I was breaking the Open-closed principle here but I didn't see an easy way to avoid it completely. Thanks to show me the withViewControls, I will propose something similar to avoid move the problem or add complexity to the renderer. 
In tables, the viewcontrols are located always in the same place, that's why with one loop over the result of getViewControls() we are finish, keeping the code closed for modification. Is not like this for secondary panels where "sortation" and "pagination" are located outside the main container, and the "section" is located inside the main container. 

I will propose methods like "getInnerViewControls" "getOuterViewControls"  ...

Thanks once again for the review and the helpful suggestion.

**Comment by klees** [comment]
>  Is not like this for secondary panels where "sortation" and "pagination" are located outside the main container, and the "section" is located inside the main container.

I wonder if we could push this to the styling/CSS-level completely. I mean: The viewcontrols ought to be identifiable by class in the CSS. The positioning (in my understanding) can be made very flexible via flex-box. IMO it would be best if the coder-consumer of the UI-framework could ignore that "inner"/"outer"-detail of how the view controls are displayed. I think you could very well contact @catkrahl about this issue, he is much better informed than I am, and I am almost sure he will come up with a solution that will render the distinction between "inner" and "outer" view controls unnecessary on the PHP-interface level.

> Thanks once again for the review and the helpful suggestion.

Thanks for this positive feedback =) It's a pleasure.

**Comment by Amstutz** [comment]
Hi @xus

Thank you lot for this contribution.

Important: All my remarks are of minor relevance. This is ready to be discussed during the next JF.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [x] Legacy Secondary Panel Context: The phrase „A good example of when use Secondary Legacy Panel is the current mini calendar block.“ rather belongs to Context, than purpose, move to Context.
- [ ] @klees Point concerning the View Controls: I agree with @klees, this is not something to be decide on the client level, but internally. CSS would be neat, however, the renderer could also take care of that. Maybe I am missing something.

Note that this is only the review for the interface. The review for the implementation follows as soon as this is accepted.

kindly,
@amstutz

**Comment by matthiaskunkel** [comment]
Jour Fixe, 24 APR 2019 : We highly appreciate this pull request and accept it for trunk.

**Comment by xus** [comment]
Hi @Amstutz, @klees 
I finished the implementation, created some tests and adapted the suggested changes.
Thanks @Amstutz , I moved this concept to Context.
> Legacy Secondary Panel Context: The phrase „A good example of when use Secondary Legacy Panel is the current mini calendar block.“ rather belongs to Context, than purpose, move to Context.

Thanks @klees , I tried my best using flex-box
> The positioning (in my understanding) can be made very flexible via flex-box. 

This is ready for the implementation review.

**Review by klees — APPROVED** [review]
LGTM, thx. @Amstutz please merge if you're fine with this too!

**Comment by alex40724** [comment]
@Amstutz Could you please provide feedback on this?

**Comment by Amstutz** [comment]
Hi @xus

Sorry for the delayed review. Thx for your patience and more importantly, the implementation of this component.

@akill, thx for the reminder. This indeed disappeared from my radar mid week.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [x] Flex Shorthand: I am not fond of the flex shorthand here. I always have to lookup which param stands for which. IMO better name them on separate lines. However, we do not have some guideline in place preventing this. This is only a suggestion

Please implement the following changes:
- [x] PHP-Docs: Please add PHP-Docs to the following methods: Listing: __construct(), Renderer: renderListing(), renderLegacy()
- [x] Less Line Wrap: Only define one property per line -> Move order to a new line.
- [x] Padding: Use @padding-base-horizontal for padding.
- [x] Fully Qualified Namespaces: Not really an issue of your code. However, currently we extract the placement from the folder with the namespace given in the return statement of the factories. We should fix that and I created a respective mantis-report. However, since you provide such nice examples, it would be a shame if one could not see the atm. So use fully qualified namespaces atm (e.g. @return \ILIAS\UI\Component\Panel\Secondary\Listing).
- [x] Type-Hint on View Control: There is no such thing as ViewControl to type hint for (there is no such interface). This is something @klees and @amstutz might have to look into. However atm, You can only type hint on component and work with your descriptions.

Since those are all points of minor gravity, you may directly merge, as soon as those are resolved, to avoid further conflicts. Thx a lot.

**Comment by xus** [comment]
Thanks @Amstutz 
I implemented the required and suggested changes. 

Thanks a lot.

**Pull request merged**
