### PR TITLE
UI: extend pagination-control with custom label for dropdown

### PR DESCRIPTION
**Pull request by nhaagen**
A customer wishes to display paginations like this, I think others might like that, too:

bildschirmfoto_2018-11-22_15-29-39

### CODE REVIEW

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @shecken ,

Thanks a lot for this request. First of all special thanks for making the component better by introducing strict typing in various places. Note, that you probably best do that in a separate PR, so your effort is not lost in case we would decline this. Neverthelesss, thanks!

There is one main question we should discuss in the JF. If possible, please answer
- I would prefer to make the "Page X of Y" the default label. What do you think?

Please improve the following points:
- [ ] You propose a good description on the withDropdownLabel. However, parts of it also belong to the composition section of the components description in the factory.  Please shortly hint the option of having a dropdown with a special label in this section there (e.g. "_When used with the "DropdownAt" option, a dropdown is rendered if  the number of chunks exceeds the option's value._ **Further you can adapt the the label of this dropdown if you are dealing with scenarios for which the default label is not working**".
- [ ] Please add a rule defining when to use label other than the default. (e.g. "You MUST use the default label if dealing with tables. You MAY use a different label, if the default one is not working for the use case.").

Thanks a lot, I am looking forward to the discussion in the JF.

**Comment by nhaagen** [comment]
Hi @Amstutz , 
thanks for keeping your eyes so close on the docs.
I'll hint in the composition-section; however, I kept the labeling-part on consumer side intentionally 
for not having to deal with i18n(-domains) within the component - or is there a standard way to do this?
If there is, I would second your opinion on making "Page X of Y" the default.

**Comment by Amstutz** [comment]
@nhaagen thanks for the prompt feedback. Concerning i18n, yes you do have access to the language dependency inside the renderer.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 03 DEC 2018 : We highly appreciate this PR incl. Timons suggestions. We would like to extend the suggested as follows:
You MUST use the default label if dealing with tables. You MAY use a different label, if the default one is not working for the use case. But indicating the total number of items (X of Y) MUST be kept anyway.

**Comment by nhaagen** [comment]
I incorparated the changes and (finally) resolved the conflicts - please, somebody hit merge before those lang-files get back at me ;)

**Pull request merged**
