### PR TITLE
fix_ilias-fr_some-encodings

### PR DESCRIPTION
**Pull request by mstuder**

### CODE REVIEW

**Comment by mstuder** [comment]
for release_7 @see https://github.com/ILIAS-eLearning/ILIAS/pull/5885

**Comment by ghost** [comment]
Seems to me, that this PR is simular to: https://github.com/ILIAS-eLearning/ILIAS/pull/5885

**Review by matthiaskunkel — APPROVED** [review]
Thanks for fixing the French language file!

**Comment by matthiaskunkel** [comment]
Approved and merged in ILIAS 8

**Pull request merged**
