### PR TITLE
KS: Sticky Panel (5.4 Proposal)

### PR DESCRIPTION
**Pull request by alex40724**
For rules see https://github.com/ILIAS-eLearning/ILIAS/pull/896/files
For mockups see https://www.ilias.de/docu/goto_docu_wiki_wpage_5104_1357.html
Scaffolded Exercise FR: https://www.ilias.de/docu/goto_docu_wiki_wpage_4333_1357.html

Use cases can/should be
- Online Help
- Exercise/Assignment Instructions
- Chat
- Page Editor

### CODE REVIEW

**Comment by klees** [comment]
I'm not a fan of this and would rather prefer to see these efforts and requirements merged with the Page Layout Revision. After all we are adding another top level component to the page. Why discuss this seperately?

**Comment by Amstutz** [comment]
I guess this is discussed seperately since time is pressing and use cases ready for this at the current point in time. however, we can not make any valid statement of when we will decide upon the page layout pr's. 

However, I think you have a good point there. @alex40724 do you see any option of working this in with the work for the page layout of richard?

**Comment by matthiaskunkel** [comment]
Jour Fixe, 26 FEB 2018: Due to the ongoing discussion about a Page Layout Revision for ILIAS we would like to postpone the decision about this PR to the Jour Fixe at July 02. Until this date it should be clear if the PLR will be realised for 5.4 or not. If not, this PR can be discussed and a decision can be taken. If the PLR has been accepted until this date, this feature request shall be realised with the according UI elements of this concept. We ask LEIFOS to bring the requirements of this PR into the PLR discussion as soon as possible.

**Comment by alex40724** [comment]
Kann geclosed werden. Kunde nutzt Plugin.

**Comment by Amstutz** [comment]
TB: This seems not to be needed anymore. There will be a plugin solving the issue. In future this is moved to the cockpit tools.

**Pull request closed without merging**
