### PR TITLE
UI Framework: Deleted MainControls\MainBar::withMoreButton and ::getMoreButton methods - ROADMAP.md updated

### PR DESCRIPTION
**Pull request by lukastocker**
https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/ROADMAP.md#remove-maincontrolmainbarwithmorebutton-and-getmorebutton-beginner-2h

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @lukastocker,

LGTM in general. Please remove [this commit](https://github.com/ILIAS-eLearning/ILIAS/pull/2817/commits/794d5415c7de41e70b3755805f34bbd5720edd7f), it does not seem to belong to the problem at hand.

I will still take this to the JF for approval of the interface change (if @Amstutz does not object).

Best regards!

**Comment by klees** [comment]
Hi JF,

we bring this to everybodys attention because a breaking change is contained here. We want to [remove the methods `MainBar::withMoreButton` and `MainBar::getMoreButton`](https://github.com/ILIAS-eLearning/ILIAS/pull/2817/files#diff-0386d22af43419b240ceabba9b0bf780L70) as already outlined in our roadmap. We do not seem to need this methods.

Best regards!

**Review by Amstutz — APPROVED** [review]
Hi @lukastocker and warmly welcome.

Very neat PR crossing an item from our roadmap. The change in the interface looks good to me.

Thx.

**Comment by lukastocker** [comment]
> Hi @lukastocker,
> 
> LGTM in general. Please remove [this commit](https://github.com/ILIAS-eLearning/ILIAS/pull/2817/commits/794d5415c7de41e70b3755805f34bbd5720edd7f), it does not seem to belong to the problem at hand.
> 
> I will still take this to the JF for approval of the interface change (if @Amstutz does not object).
> 
> Best regards!

That commit is deleted now.

**Comment by lukastocker** [comment]
> Hi @lukastocker and warmly welcome.
> 
> Very neat PR crossing an item from our roadmap. The change in the interface looks good to me.
> 
> Thx.

Hi @Amstutz,

thank you very much.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 03 AUG 2020 : We highly appreciate this suggestion and accept the PR for trunk (attention: it is currently made against the release_6 branch!).

**Comment by klees** [comment]
I have picked this to trunk manually: https://github.com/ILIAS-eLearning/ILIAS/commit/89681189bb1114201d2cf1aa2419e5f32ae13eeb

**Pull request closed without merging**
