### PR TITLE
Added slim rest library: #24162

### PR DESCRIPTION
**Pull request by smeyer-ilias**
As mentioned in the Jour Fixe on 2018-12-03 this is PR for a composer based replacement of the old "Services/WebServices/Rest/lib" library.

https://mantis.ilias.de/view.php?id=24162

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@smeyer-ilias Please merge, we highly appreciate this change.

**Comment by corro** [comment]
This PR broke `composer install`. The file `libs/composer/composer.lock` does not contain valid JSON anymore:
```
$ composer install -d libs/composer 

                                                 
  [Seld\JsonLint\ParsingException]               
  "./composer.lock" does not contain valid JSON  
  Parse error on line 875:                       
  ...2:40+00:00"        {            "name"      
  ---------------------^                         
  Expected one of: 'EOF', '}', ':', ',', ']'     
                                                 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by smeyer-ilias** [comment]
Cannot reproduce it in the current 5.3 branch. 

$ jsonlint-php composer.lock
Valid JSON

If there are still problems, please open a report in our bugtracker.

**Comment by corro** [comment]
@smeyer-ilias I meant branch `trunk`.

I just realized this PR is for branch `release_5-3`, but the commit message of the commit that introduced the problem (f0050795e4) mentioned this one. Sorry for the confusion.

**Comment by smeyer-ilias** [comment]
no problem. 
Summary: composer.lock in 5.4 and trunk is broken.

**Comment by smeyer-ilias** [comment]
Fixed in 5.4 and trunk

**Pull request merged**
