### PR TITLE
Test&Assessment LogicalAnswerCompare corrections

### PR DESCRIPTION
**Pull request by nicoroeser**
This pull request delivers a lot of fixes created _while_ working on [Mantis issue 35685](https://mantis.ilias.de/view.php?id=35685 "Mantis 35685: Failed test: Lösungsvergleich 1") (but not _for_ fixing that bug). It mostly contains
* fixes for bugs in the LogicalAnswerCompare code,
* dependency commits for these bugfixes,
* changes deemed uncritical to code stability (like API documentation additions or trivial code restructuring).

It is against the `release_8` branch, and I would suggest to put the commits on this branch and on trunk.

Important changes include addition of missing language strings for LAC error-handling, corrections for violation of strict typing, and a fix for incomplete detection of errors related to brackets in expression strings. See the individual commit messages for details.

The topmost 3 commits are enhancements. I have applied them to and used them on ILIAS 8, but if you decide to just apply them to trunk or not at all or just with changes, that’s fine, too.

I have tried to group the commits a bit according to topic. If you’d like me to change the order, split something out, explain something better, etc., please tell me. Thanks!

### CODE REVIEW

**Comment by dsstrassner** [comment]
Hi @nicoroeser!
What is the status of this PR? Do @mbecker-databay and @kergomard  just have to review this one, or does something happen beyond that?

**Comment by nicoroeser** [comment]
As far as I know, someone (who is not me) should “just” review this pull request and

1. decide on which branches it should be applied,
2. decide whether the topmost enhancement commits should be kept, and on which branch(es), and
3. tell me whether something needs further discussion.

Maybe there is unclarity because this pull request delivers bugfixes as well as contains some additional commits which do not _fix_, but _improve_ the code base.

**Comment by dsstrassner** [comment]
TechSquad 11.05.2023: @kergomard will review.

**Review by kergomard — CHANGES_REQUESTED** [review]
Thank you very much @nicoroeser for these improvements!
I'm not really into this LogicalAnswerCompare stuff. If I look at your changes it makes me feel like, we should get rid of this, as we are not really using it, or how could we live with these funky behaviors for so long? It also looks highly over engineered, for what we need. For me the changes look mostly correct, but there are things I either don't understand, or I think are a step back. As a word of caution: I didn't look into the usages.

* Please either type variables, parameters, and return values or define them in a Doc-Block, but not both. So, please remove the Doc-Blocks where you have added types, we don't want them to contradict each other with the next change ;-).
* Please remove the Class-Doc-Bloc, where they are wrong. E.g. [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5397/files#diff-f5b7488b5d6fb12b4d39ffd90d372250ce53e49f4d3fb669419b52606edfb21dR20) or [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5397/files#diff-1b77ef8949464ff7c2e58a441caa44a5c1c1e2e8bbd0fe13ffa02d8f78deee52R20) even after the change "Class" does still not contain anything useful as far as I can see. Am I missing something here?
* Could you maybe try to simplify a few of the conditions? This is a trivial case, but before this [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5397/files#diff-8b145f865e284d36f3157b3675a10f69f1e1219b54a4a8700c3557164727f116R140) was clearer, from where I stand. The last return is completely unconditional as you have filtered away al the rest, so the `else` is superfluous. 
* Do we need this Error [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5397/files#diff-1b77ef8949464ff7c2e58a441caa44a5c1c1e2e8bbd0fe13ffa02d8f78deee52R22) , if it has been broken for so long and nobody cared? Can't we just delete it?

Thanks again and best,
 @kergomard

**Comment by kergomard** [comment]
Hi @nicoroeser 

Do you think you will have a chance to look at this soon and to resolve the conflicts, so that we can merge this? Otherwise I would actually suggest to close it.

Thank you very much and best,
@kergomard

**Comment by nicoroeser** [comment]
I haven’t forgotten about this pull request :wink: , and hope to be able to invest some time soon(ish) to get it merged or otherwise bring it forward.

**Comment by kergomard** [comment]
Hi @nicoroeser 
As this PR does not fix a bug, but rather provides an improvement and hasn't seen a lot of movement in the last months. I close it, to keep my backlog short.

I kindly ask you to reopen, if you get around to it and feel it is important enough.

Thank you very much and best,
@kergomard

**Pull request closed without merging**
