### PR TITLE
UI, Viewcontrols as Inputs

### PR DESCRIPTION
**Pull request by nhaagen**
Viewcontrols are OKish on their own, but if you want to use more than one of them on the same visualization, their handling becomes somewhat clumsy. There is no standard or organized way to orchestrate parameters/values and (re-)apply the user's selections to both the data and the controls.

However, all this is very well thought of in Inputs/Form (or Filter, for that matter..), and there is 
certainly a lot in common for (View-)Controls and Inputs - in fact, VCs _are_ Inputs. 

This PR introduces a [ViewControl-Container](https://github.com/ILIAS-eLearning/ILIAS/pull/2540/files#diff-a5b0844daf7ef3c49988ca394af4e686) as the wrapper around [Controls](https://github.com/ILIAS-eLearning/ILIAS/pull/2540/files#diff-582b4a13a07bdfdfa5ecbec4caa1239b) and a new [FieldSelection-Control](https://github.com/ILIAS-eLearning/ILIAS/pull/2540/files#diff-3d7d6d8537916c29fac8afa9f3c9b428).

I left all known ViewControls untouched, since they are being used, but ultimately, [those should go](https://github.com/ILIAS-eLearning/ILIAS/pull/2540/files#diff-03187698ad133a5bd55a354aa296e112).

I also moved QueryParamsFromServerRequest up one level.

### CODE REVIEW

**Comment by klees** [comment]
Hi @Amstutz,

please have a look here, I discussed this with @nhaagen already and think this is the right way forward. We would like to take this to the JF if you are fine with this, or, of course, change stuff if requested.

Best regards!

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @nhaagen


Thanks a lot for proposing this important improvement. I agree with the general concept and push this towards the next JF. I am sure we get the following point sorted out until the upcoming JF:

Questions:
- [x] Accessibility: Do we need to consider any accessibility rules? E.g., do we have rules, that would apply for all View Controls (e.g. some Aria role or similar) other than the keyboard rule? Ist there more for the containers? I truly do not know. Maybe @atoedt can help out here.
- [x] Load More: For me to understand this better, would some „Load More“ button be a (View)-Control?
- [x] Existing View Controls: Can you sketch out somewhat, how sementicaly the existing View Controls would be migrated to the taxonomy here? E.g. what would happen with the „Mode View Control“? Would this be a „Mode (View) Control Input“ that then needs to be put into some „View Control Container Input“? Maybe shortly list for all existing and maybe even put into roadmap.
- [x] Usage Rule: "Controls MUST NOT be used standalone.“, does this mean, they need to reside in a View Control Container? If so, maybe clarify in the rule.

Maybe change or argue, why no change is neccessary:
- [x] Input Rival: For View Controls, you name „Inputs“ as rivals. However, View Controls are Inputs according to your proposal. Note that in the purpose description of inputs, there is not notion of data to be persistently stored. Maybe forms would be correct here?
- [x] Usage Rule: A usage rule would be neat for all View Control Container Inputs, when MUST/SHOULD we use this new control, when MUST/SHOULD we NOT? E.g. would this be the component to be used for a search dialog?
- [x] Naming „Control Input“: Why did you chose the generic name „Control" for the new Input type? Why not why not „View Control“ if there is (currently) according to the purpose description a 1:1 coupling. If we stick with „Control“ then remove the "(View-)" in the purpose description.

Please change to following:
- [x] Camel Case: In the desciption parts do not use CamelCase, e.g. „ViewControl" should be "View Control" to make this easier for humans to read. Other examples are FieldSelection, and MultiSelect.


Thanks 

@amstutz

**Comment by nhaagen** [comment]
Hi @amstutz,
thanks for your review. 

> * [ ]  Accessibility: Do we need to consider any accessibility rules? E.g., do we have rules, that would apply for all View Controls (e.g. some Aria role or similar) other than the keyboard rule? Ist there more for the containers? I truly do not know. Maybe @atoedt can help out here.

I definitely do not have any expertise on accessibility ore the usage of aria-attributes; so, any input will be much appreciated.
I think that also @tfamula is currently working on that?
I found "aria-controls", which seems to fit, but also found words against using it, see https://heydonworks.com/article/aria-controls-is-poop/, e.g.

> * [ ]  Load More: For me to understand this better, would some „Load More“ button be a (View)-Control?

Yes, I think so. A "Load More" button would need some intimate knowledge about the component it affects.
Also, it should work in conjunction with other View Controls.

> * [ ]  Existing View Controls: Can you sketch out somewhat, how sementicaly the existing View Controls would be migrated to the taxonomy here? E.g. what would happen with the „Mode View Control“? Would this be a „Mode (View) Control Input“ that then needs to be put into some „View Control Container Input“? Maybe shortly list for all existing and maybe even put into roadmap.

The existing View Controls will vanish, once they are migrated into Inputs and consumers are updated accordingly.
currently, these are
* Mode View Control Input 
* Pagination View Control Input 
* Section View Control Input 
* Sortation View Control Input 

They all (will) live in a "Standard View Control Container Input", e.g.
However, those containers again will be part of even more complex Components like a Table, e.g., since View Controls, or even their container, do not make any sense on their own.

> * [ ]  Usage Rule: "Controls MUST NOT be used standalone.“, does this mean, they need to reside in a View Control Container? If so, maybe clarify in the rule.

Will do.
 
> * [ ]  Input Rival: For View Controls, you name „Inputs“ as rivals. However, View Controls are Inputs according to your proposal. Note that in the purpose description of inputs, there is not notion of data to be persistently stored. Maybe forms would be correct here?

You are right, thanks. It's not Inputs, it's "Form". I'll change. 

> * [ ]  Usage Rule: A usage rule would be neat for all View Control Container Inputs, when MUST/SHOULD we use this new control, when MUST/SHOULD we NOT? E.g. would this be the component to be used for a search dialog?

Will the "same page"-rule answer that already? 
I can't think of anything much better rigth now, but I have the feeling that I did not touch this for the last time ;)

> * [ ]  Naming „Control Input“: Why did you chose the generic name „Control" for the new Input type? Why not why not „View Control“ if there is (currently) according to the purpose description a 1:1 coupling. If we stick with „Control“ then remove the "(View-)" in the purpose description.

I refrained from "View Controls" to better tell those two occurences apart in verbal communication. But you are right, it's "View Controls" after all.

Best regards!

**Comment by Amstutz** [comment]
@nhaagen ; thanks a lot for the answers and explanations. I am fine with those, and push this forward to the next JF. @klees feel free to intervene, if you feel there is more to be discussed before the upcoming jf.

Concerning your question:

> Will the "same page"-rule answer that already?

Yes, will do.

**Comment by matthiaskunkel** [comment]
Jour Fixe, 30 MAR 2020 : we highly appreciate this suggestion and accept the PR for trunk.

**Comment by klees** [comment]
In agreement with [our rules](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/docu/rules.md) and after consultation with @Amstutz I merge this PR without implementation to proceed with the discussion of more UI components for the Data Table soon. The implementation and examples will be delivered in a second PR.

**Pull request merged**
