### PR TITLE
VirusScanner: Temporary changed file permissions of files to enable c…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…lamd to scan temporary files according to group read/write

Ralf Schenk suggests this change to handle issues for the `ClamAV Daemon` when trying to scan files.

Mantis Ticket: https://mantis.ilias.de/view.php?id=22739

### CODE REVIEW

**Comment by alex40724** [comment]
So Ralf is listed as the author of this class. Who should merge this? :-)

**Comment by klees** [comment]
I'm no admin, have deep knowledge on filesystem-permissions or know the virus scanner in ILIAS well, but from the code this looks like asking for trouble imo. If something breaks in the middle (e.g. in exec because execution takes too long) we are left with changed permissions that are not changed back. Are there implications for security?

**Comment by mjansenDatabay** [comment]
@alex40724 Yes, but @chfsx is the maintainer of the folder (see: maintenance.json)

@klees I am also not sure about security implications other than or worse than: We cannot even scan a file.
I checked the usages and the virus scan is **not** only used for files in the `upload_tmp_dir`, but also when extracting ZIP archives or scanning the import directory for media pools (see: `\ilObjMediaPoolGUI::createMediaFromUploadDir`). So permission changes (we are left with when something breaks) within the data directories could be indeed an issue.

**Comment by klees** [comment]
@mjansenDatabay I'm not opting for "not scanning the file", but I wonder if there is a saner way to achieve that result. The main problem I see here is that this approach here is intransparent for the admins (that I consider the "owners" of the permissions).

The alternative I see is visibly and loudly tell admins that permissions of the files does not allow the scanner to open it. This would then give them the possibility to act on the problem themselves. This is where my lacking knowledge of unixy permission-systems comes into play: would there be a good way for the admin to somehow influence those permissions on the OS-level that covers new files? If so I would not modify permissions via code.

**Comment by smeyer-ilias** [comment]
@mjansenDatabay : I'm also not a fan of changing any permissions in the PHP code. 
Maybe it is a solution to put the user clamav (the clamav daemon runs with this privileges) to the www-data group.

**Comment by chfsx** [comment]
@mjansenDatabay I must say I'm not a fan of ILIAS setting the permissions of the files, too. AS I mentioned in the Mantis-Ticket I'd also put the ClamAV User to the www-data-group and the SysAdmin could set the permissions of the files or the mask accordingly. But I did not checked if it works, honestly. I see that the implementation of the FileSystem-Service lead to a more restrictive handling of file-permissions - which is good IMO. But that the Virus-Scanning is broken now is bad, indeed. The Virus-Scanning Implementation is quite old and a bit shaky from my point of view. I'm not even sure if I am the maintainer but I think since it's quite near the FileObject inherited that, too. My suggestion is to rethink the feature for ILIAS 6.0 and I will try to make the feature-wiki entry asap (at least before feature freeze)

**Comment by rschenk0** [comment]
The virus scanning of files is common requirement in many our instances. Since the virus scannning of all uploaded files might lead to enormous load if a virus-scanner is executed for each file (then loads its latest virus databases - scans file) it is really important to be able to use the daemonized versions of virus-engines like in my case clamd.
This and each other daemon in ILIAS context (i.e. chatserver etherpad-lite, ilserver) should run as a specific user itsself. So following these facts it is absolutely neccessary to give these daemon users a secondary group and let them read or write ILIAS configs, files or whatever is needed to get the job done.
In case of clamd it needs to be able to read and write (to delete !) uploaded ILIAS files.
@chfsx 
It's necessary but not sufficent to add the clamd-user to www-data (webserver primary group) since the files are **not** group readable/writeable.
For years it was possible to simply add the secondary group to clamd. But this has changed anywhere in php (since 7.0x ?) or ILIAS since 5.2.x. Uploaded files in "upload_tmp_dir" **now** have 0600 rw- --- ---. 
So the (im my opionion only) solution is to add group read/write for the virus-scanning and revert it afterwards.

**Comment by mbecker-databay** [comment]
From the perspective of a corporate privacy officer, the risk having no virus scan must be evaluated as a much bigger issue than a potential risk of leaving files group-rw'ed if the system doesn't complete the exec-call. Not doing that based on the reasoning here is a bit like leaving the door open because it may not fully close if a lightning strikes while it's in motion. Cheers, ~M.

**Pull request merged**
