### PR TITLE
Feature/7/migrate command interfaces

### PR DESCRIPTION
**Pull request by chfsx**
Hi @klees 

As discussed I suggest the "migrate" command in this PR! There are several changes to the last version you saw:
- feature complete
- list of available migrations
- --run <migration_name>
-  with optional --steps 
- explicityConfirm by retyping the key of a migration

feel free to contact me any time!

### CODE REVIEW

**Review by klees — APPROVED** [review]
Hi @chfsx,

thanks a lot for looking into this. I did a little cleanup and refactorings and squashed your commit into this one:

https://github.com/klees/ILIAS/commit/bda0c1c1d014c3f1835bfaff60407b575d9d76d3

I will still leave this open so we can gather feedback from other developers and will then merge the single commit from my repo. Depending on what happens with PR #2782 I will also rebase it on the current trunk.

Best regards!

**Comment by klees** [comment]
Hi @mjansenDatabay, @alex40724, @smeyer-ilias, @gvollbach, @rschenk0, @mstuder, @Amstutz,

we added a method `Agent::getMigrations` and thus needed to implement that method in a very uninteresting way in your components.

Please have a quick look here.

Best regards!

**Review by mjansenDatabay — APPROVED** [review]

**Comment by klees** [comment]
Since I now have merged #2782, I rebased the commit onto the current trunk:

https://github.com/klees/ILIAS/commit/7e3b224c966a257c64e4cdf272d0dcb28b63b623

**Comment by chfsx** [comment]
@klees after the rebasing I'm unable to run the `migrate` command for listing migrations, I'll do some further investigation and try to figure out whats going wrong

**Comment by klees** [comment]
@klees Huh? I hate that sentence, but: Works for me =)

Could you send me that error message? I bet you have other things to do currently.

**Comment by chfsx** [comment]
I was afraid of that :-) the problem is that the dummy migration defines preconditions, but these are not needed if a `prepare` is executed when listing the migrations. In my implementation I have e.g. in `prepare` a "$fs_config = $environment->getConfigFor("filesystem");", because this is needed. If the migration is started, this works. But I do not have this dependency at the moment, if I only want to list all migrations.

Besides that I currently have the problem that I always get a PluginAgent without specifying --no-plugins, why I don't know yet, but I'm trying to fix it, otherwise I won't get anywhere.

**Comment by klees** [comment]
Call me via Skype if I can be of any help!

**Comment by chfsx** [comment]
Same Problem while running one migration, there has something changed concerning preconditions

Config for 'filesystem' is not contained in the environment ----- #0 /var/www/html/Modules/File/classes/Setup/cl  
  ass.ilFileObjectToStorageMigration.php(76): ILIAS\Setup\ArrayEnvironment->getConfigFor('filesystem')

**Comment by klees** [comment]
I removed the configs as dependency to `update` in #2940. I think the same is correct for `migrate`. Can you just collect the required information from the ini? Call me if I can be of any help!

**Comment by chfsx** [comment]
@klees I updated the PR accordingly and now it works again, thanks for your help!

**Comment by chfsx** [comment]
Hi @Amstutz, @alex40724 , @gvollbach , @rschenk0 and @smeyer-ilias 
Are there any questions, concerns of feedback from your side?

**Review by Amstutz — APPROVED** [review]
Hi @chfsx 

Thank you very much! I did not perform a code review, but agree with the general approach. Therefore green light for pushing this further down the road.

**Review by gvollbach — APPROVED** [review]

**Review by smeyer-ilias — APPROVED** [review]

**Comment by chfsx** [comment]
@klees asked me to merge this PR during his absence next week, if there are no objections I'll merge it an tuesday morning. Thanks!

**Comment by mjansenDatabay** [comment]
@chfsx / @klees You don't have to wait for the approval of @rschenk0 . @gvollbach and @mjansenDatabay checked this ;-).

**Pull request merged**
