### PR TITLE
BT-28658: Made plugin.php accessible multiple times for parsing

### PR DESCRIPTION
**Pull request by M-Barz**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@mstuder We stumbled upon this old PR in our TB meeting. Do you have any objections to merge this?

**Comment by chfsx** [comment]
Hi @mstuder 

this came up again in our last TB meeting on the 06-04-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by chfsx** [comment]
Hi @mstuder

this came up again in our last TB meeting on the 06-04-2021. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

**Comment by klees** [comment]
Thanks @M-Barz!

**Pull request merged**
