### PR TITLE
PHP8: Code Review `User Service`

### PR DESCRIPTION
**Pull request by lscharmer**
Hi @alex40724,

sorry for the inconvenience, here is the last last part of the `Services/User` review.

### Results
- [ ] There are no serious `PHPStorm Code Inspection` issues left

### Changes made in this PR
- Added `// @TODO: PHP8 Review: Missing return type.`
- Added `// @TODO: PHP8 Review: Invalid argument.`
- Added `// @TODO: PHP8 Review: Undefined method.`
- Added `// @TODO: PHP8 Review: Undefined property.`
- Added `// @TODO: PHP8 Review: Void result used.`
- Added `// @TODO: PHP8 Review: Undefined constant.`
- Added `// @TODO: PHP8 Review: Wrong magic logger method called`
- Added `// @TODO: PHP8 Review: Variable is always false`
- Added `// @TODO: PHP8 Review: Variable is always true`
- Change `resource<xml>` to `resource` in doc blocks.

Best regards,
@lscharmer

### CODE REVIEW

**Comment by alex40724** [comment]
Thanks for the PR!

**Comment by alex40724** [comment]
@mjansenDatabay The logger user() should be correct, since it matches the service ID in the service.xml file.

**Comment by mjansenDatabay** [comment]
@alex40724 Okay, but then the usage in `\ilCronDeleteNeverLoggedInUserAccounts::run` is wrong.

**Comment by alex40724** [comment]
@mjansenDatabay Yes, at least as far as I know. I fixed the Todos.

**Pull request merged**
