### PR TITLE
User Field OrgUnits

### PR DESCRIPTION
**Pull request by theodortruffer**
new user field 'org_units', displayed/used in: 
- Administration > User > Edit
- Adminstration > User List (selectable columns)
- Personal Desktop > Personal Data
- Personal Desktop > Public Profile
- Personal Desktop > Import / Export
- Categories > Local User Administration
- Org Units > Local User Adminstration

### CODE REVIEW

**Comment by theodortruffer** [comment]
@smeyer-ilias ready to merge?

**Comment by colin-kiegel** [comment]
I like the idea to have a 'field' that reveals the org unit assignment in general.

But I am somewhat concerned about the cron-approach, which could lead to subtle unexpected behaviour. Of course I can see that this is also a performance tradeoff for bulk actions (searching, etc.).

This is also a precedence-case, isn't it? I don't think we have other fields which are updated via a cronjob. What is the general strategy of ILIAS here?

Are there any alternatives? Like a setting, whether this should be evaluated in real-time or not?

IMO this is worthy to be discussed by the JF first.

**Comment by colin-kiegel** [comment]
I have described my objections in a comment of this feature wiki ticket: http://www.ilias.de/docu/goto_docu_wiki_wpage_3564_1357.html

**Comment by chfsx** [comment]
@colin-kiegel Thanks for your inputs, we'll continue the discussion in FW: http://www.ilias.de/docu/goto_docu_wiki_wpage_3564_1357.html

**Pull request closed without merging**
