### PR TITLE
Deprecation/Removal in ILIAS 10: Services/FileSystem

### PR DESCRIPTION
**Pull request by chfsx**
ILIAS has since several releases modern and reliable services to work with files. These include the src/ResourceStorage, the src/FileUpload and the src/Filesystem.

Under "Services" there are several legacy implementations that were used in different places to work with files. These will be completely removed with ILIAS 10 - or maintained by the remaining maintainers. 

For the deprecations listed here in the PR, alternatives have existed for a long time with the above-mentioned services - for the storage and administration part - but these were not and only little used.

For the UI side (like e.g. the removal of ilFileSystemGUI/ilFileSystemTableGUI) new concepts have to be found for ILIAS 10 anyway, because these legacy UI things like the table will be removed with ILIAS 10 as well.

Enclosed is a list of the remaining uses of the classes. Please contact me regarding migration of the usages if the existing documentation (see Services/ResourceStorage/MIGRATIONS.md) is not sufficient. As said, for the UI side there is currently no direct replacement, here also suggestions from the using component maintainers are welcome, since I myself do not use them.

**ilFile**

- class.ilFileData.php
- class.ilFileDataCourse.php
- class.ilFileDataImport.php
- class.ilFileDataMail.php

already planed/prepared/done migrations for ILIAS 9:

- class.ilFileDataForum.php
- class.ilFileDataForumDrafts.php

**ilFileSystemAbstractionStorage**

- class.ilAssQuestionProcessLockFileStorage.php
- class.ilFSStorageBadge.php
- class.ilFSStorageBadgeImageTemplate.php
- class.ilFSStorageBlog.php
- class.ilFSStorageBooking.php
- class.ilFSStorageCourse.php
- class.ilFSStorageExercise.php
- class.ilFSStorageGroup.php
- class.ilFSStorageMail.php
- class.ilFSStoragePoll.php
- class.ilFSStoragePortfolio.php
- class.ilFSStorageSession.php
- class.ilFSWebStorageExercise.php
- class.ilIndividualAssessmentFileStorage.php
- class.ilLearningSequenceFilesystem.php
- class.ilRestFileStorage.php
- class.ilTestProcessLockFileStorage.php
- class.ilVerificationStorageFile.php

Planes migrations with ILIAS 9:
- class.ilFSStorageUserFolder.php

already planed/prepared/done migrations for ILIAS 9:
- class.ilFSStorageFile.php
- class.ilFSStoragePreview.php

**ilFileSystemGUI**

With Directories
- class.ilObjFileBasedLMGUI.php
- class.ilObjMediaObjectGUI.php
- class.ilObjSAHSLearningModuleGUI.php

Currently missing directory support in IRSS, please contact @chfsx if you need this.

Without Directories
- class.ilExAssignmentFileSystemGUI.php
- class.ilExerciseManagementGUI.php
- class.ilExPeerReviewGUI.php
- class.ilObjMediaPoolGUI.php

**ilFileSystemTableGUI**
Must be removed anyway since this is a legacy ui imlementation.

- class.ilFileSystemGUI.php
- class.ilExAssignmentFileSystemTableGUI.php

**ilUploadFiles**
No replacement suggested. This feature is only used in CmiXApi and SCORM and must be implemented there

- class.ilObjFileBasedLMGUI.php
- class.ilObjSAHSLearningModuleGUI.php
- class.ilObjCmiXapiGUI.php
- class.ilObjSCORMLearningModuleGUI.php

I am aware that some consumers of this code have unanswered questions. i am sure that we will find good solutions together, the necessary infr structure is in place and together we will find suitable solutions for this replacement.

### CODE REVIEW

**Comment by klees** [comment]
Hi @chfsx,

thanks a lot for going forward with the IRSS. I definitly support this move and will happily move my implementations away from deprecated file implementations. This has been on my agenda for quite some time and I appreciate being pushed a little by a deadline... =)

Best regards!

**Comment by alex40724** [comment]
@chfsx Thanks for the PR. What is currently the best way to perform zip/unzip processes in the src/Filesystem world?

**Comment by matthiaskunkel** [comment]
JourFixe, 31 OCT 2022 : We highly appreciate this suggestion. Please mark the mentioned classes as deprecated for ILIAS 10. All developers who have questions about using the IRSS should contact Fabian.

**Comment by chfsx** [comment]
Hi @alex40724 

Thanks for your question! 

> What is currently the best way to perform zip/unzip processes in the src/Filesystem world?

together with the [PR 5172](https://github.com/ILIAS-eLearning/ILIAS/pull/5172) I will make an appropriate proposal for zipping/unzipping files located in the IRSS or filesystem service. It makes sense that all files will eventually be in the IRSS, but there will definitely be cases where we continue to work with the filesystem service. The important thing is to get rid of all the posts that don't use either of these services and that's what PR is here for.

**Pull request merged**
