### PR TITLE
UI: set min-width to max-content for dropdowns. (#39053)

### PR DESCRIPTION
**Pull request by lukastocker**
https://mantis.ilias.de/view.php?id=39053

Note: If no label is set an aria-label will be set automatically.

Screenshot from 2024-07-24 11-24-27

### CODE REVIEW

**Review by klees — APPROVED** [review]
Changes in Study Programme LGTM.

**Comment by klees** [comment]
Hi @smeyer-ilias,

I added you because this contains marginal changes in `ILIAS\Membership`.

Kind regards!

**Review by Amstutz — APPROVED** [review]
Good from a CSS POV.

**Comment by smeyer-ilias** [comment]
Thanks @lukastocker LGTM

**Pull request merged**
