### PR TITLE
Setup/Style: move dbupdate_3136 into objective

### PR DESCRIPTION
**Pull request by daniwe4**

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @alex40724 

If I get this right, this is content styles, correct? 

thx @daniwe4

**Comment by alex40724** [comment]
@daniwe4 Thanks! This might be a stupid question. How would we use this objective? Would it be somehow part of a migration?

**Comment by daniwe4** [comment]
Hi @alex40724 ,

each of these objectives could be place into each SetupAgent. For testing purposes i put it into ilUICoreSetupAgent like this:
```php
public function getUpdateObjective(Config $config = null) : Objective
    {
        return new ObjectiveCollection(
            "",
            false,
            new ilDatabaseUpdateStepsExecutedObjective(
                new ilCtrlDatabaseUpdateSteps(),

            ),
            new ilStyleClassCopiedObjective(
                "ExtLink",
                "Extended",
                "link",
                "a"
            )
        );
    }
```

Feel free to ask further questions, of course.

Best regards, Daniel.

**Comment by alex40724** [comment]
@daniwe4 Ok, thanks a lot for the code and the explanation.

**Pull request merged**
