### PR TITLE
Trunk: Test: Use Launcher to Start the ILIAS Test

### PR DESCRIPTION
**Pull request by matheuszych**
Featurewiki-Link: https://docu.ilias.de/goto_docu_wiki_wpage_4925_1357.html

### CODE REVIEW

**Comment by matheuszych** [comment]
Will be reviewed by @mbecker-databay

**Review by mbecker-databay — CHANGES_REQUESTED** [review]
I had a look at this PR and got a few questions.
I will send you an email and we'll meet about that to sort things out.

**Comment by dsstrassner** [comment]
I also send an email with a first review ;)

**Review by mbecker-databay — APPROVED** [review]

**Comment by mbecker-databay** [comment]
I see we have the related PR 6355 still open and to my understanding, this is required for this PR... but I do not see this code calling it. Is there a plan here for a follow up PR taking advantage of the button labels or am I missing something?

**Comment by matheuszych** [comment]
Hey @mbecker-databay, when the PR #6355 is merged I plan on adding the button labels to this PR.

**Comment by dsstrassner** [comment]
Hi @mbecker-databay, from my point of view everything seems to look fine. @matheuszych said, you would do the review and merge? Could you click the button today, or is there anything left from your side?
FYI @kergomard

**Comment by kergomard** [comment]
Hi @matheuszych 

Thank you very much for your work on this.

One quick feedback: Please move all the dependencies on the `$DIC` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/6298/files#diff-401c39b3f3f94bf86318869e72faa5ae617bf3379c8488380b827f38c28ab3aeR59-R66) to the constructor. I know, this is not the ideal solution, but we will get there. I just spent a lot of time making sure the `$DIC` is centralized as best we could, to then be able to reduce the reliance on so many classes all over the place.

Thank you very much and best,
@kergomard

**Comment by matheuszych** [comment]
Hey @kergomard 

I have looked thru the `class.ilTestScreenGUI` but I don't see any usage of the `DIC` outside of the constructor. Could you maybe point out an example where that is the case?

Best regards,
@matheuszych

**Comment by kergomard** [comment]
Hi @matheuszych 

I do exactly mean the ones in the constructor. Inject them as parameters, please.

Thank you very much,
@kergomard

**Comment by matheuszych** [comment]
Hey @kergomard

All done :)

Best regards,
@matheuszych

**Comment by kergomard** [comment]
Thank you very much!

**Pull request merged**
