### PR TITLE
[FIX] 0041418: Setup routine does not verify required PHP version

### PR DESCRIPTION
**Pull request by chfsx**
See https://mantis.ilias.de/view.php?id=41418

### CODE REVIEW

**Comment by chfsx** [comment]
And we should introduce this in update objectives as well, I'll update the PR asap

**Comment by chfsx** [comment]
@klees hmm we have the following problem: these objectives do not cause an update to be canceled, do we have such a thing?

**Review by klees — CHANGES_REQUESTED** [review]
Hi @chfsx,

this would be a problem caused by a switch in execution logic of the Setup that we made at some point. The Setup stopped execution at the first unachievable objective before, but tried objectives from other branches in the DAG of objectives after. Hence, the `Conditions` currently do not stop the other objectives anymore. We had the same problem with admin-confirmations and solved it by introducing [`ILIAS\Setup\NotExecutableException`](https://github.com/ILIAS-eLearning/ILIAS/blob/release_8/src/Setup/NotExecutableException.php) that stops setup immediately. I think we can reuse this here:

* [x] Add a parameter `$block_setup = false` to the [`ExternalConditionObjective`](https://github.com/ILIAS-eLearning/ILIAS/blob/release_8/src/Setup/Condition/ExternalConditionObjective.php).
* [x] If this parameter is set, make the Objective throw a `NotExecutableException` instead of an [`UnachievableException`](https://github.com/ILIAS-eLearning/ILIAS/blob/release_8/src/Setup/Condition/ExternalConditionObjective.php#L97).
* [x] Write a test for that behaviour.
* [x] Also put this parameter on the constructor of `PHPVersionCondition`.
* [x] Set the parameter accordingly for our global PHP-constraint.

Also:

* [x] Please make the `$max_version`-parameter optional.

I think we should try not to break interface and behaviour of the general `PHPVersionCondition` class. It is not only useful to check PHP versions for all of ILIAS, but could also be a guard for functionality that only works with specific PHP versions. I don't really know if it is currently used in that way, but I can't rule it out either.

Finally:

* [x] Do you understand why the problem wasn't already caught by composer? We do specific PHP version constraints there...

Thanks for looking into this!

**Comment by klees** [comment]
Hi!

I could have answered my last question as well:

> Do you understand why the problem wasn't already caught by composer? We do specific PHP version constraints there...

The ticket says, that `composer install` was not executed, maybe user just updated the OS.

Kind regards!

**Comment by chfsx** [comment]
Hi @klees 
Thanks for the feedback, I implemented the changes and updated this PR.

> Do you understand why the problem wasn't already caught by composer? We do specific PHP version constraints there...

The problem is the following (and I never thought of this case myself): If you do not install ILIAS with Git and thus have to run composer install but install ILIAS from the bundled ZIP or Tar,  then you do not have to run composer install and thus the PHP version check never takes place there. the reporter of the issue therefore did everything right, we just didn't consider this case.

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Thanks a lot!

Picked to release_9 and trunk.

**Pull request merged**
