### PR TITLE
fixed bug #27734: Accessibility: Custom Icon

### PR DESCRIPTION
**Pull request by alex40724**
See https://mantis.ilias.de/view.php?id=27734

### CODE REVIEW

**Comment by Amstutz** [comment]
Hi @akill,

thanks for proposing this change. Note, we doubt that this change is what we really want, but see the need of some change, due to failing test tools. 

As far as we understand, the image in the Custom Icon is only decorative and not informative. Our [Guideline Text Alternatives](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/accessibility.md#guideline-text-alternatives) says that "If non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it SHOULD be implemented in a way that it can be ignored by assistive technology.".
[The internet](https://www.w3.org/WAI/tutorials/images/decorative/) says, that alt-text for purely decorative images should be set to empty, which seems to be the implementation of that abstract guideline requirement.

Also, this change violates rule [`symbol.icon.accessibility.1`](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/Symbol/Factory.php#L49) which requires the aria-label that you are about to remove. The rule might be outdated or require adjustment, however, if so, we need some proposal of a change. Maybe @atoedt can provide a such. As far as we understand, these rules are supposed to be tested on the actual KS elements by some humans some day (We think @fab-kru is working on this) and this would just lead to a new bug report then if we make this change without adjusting the rule.

However, we see the need to get ILIAS up to speed to pass the according test tool. So let’s tackle this:

Question:
- [ ] Aria-Label: Why did you remove it?
- [ ] Alt-Text: They are needed, since we use the img tag, correct? Is this a strict rule, that every img tag must also use an alt-text, that is followed by those test-tools?

Proposed changes, if you not agree, please explain why:
- [ ] Alt-Text II: Set the alt-text to "" on the image to signal that is is decorative.
- [ ] Aria-Label II: If removing is really the way we want to go, then we should adapt the written rules, if not, please re-add.

Best regards!
@Amstutz and @klees

**Comment by atoedt** [comment]
Zitat von Timon Amstutz <notifications@github.com>:

> Hi @akill,
>
> thanks for proposing this change. Note, we doubt that this change is  
> what we really want, but see the need of some change, due to failing  
> test tools.
>
> As far as we understand, the image in the Custom Icon is only  
> decorative and not informative. Our [Guideline Text  
> Alternatives](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/accessibility.md#guideline-text-alternatives) says that "If non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it SHOULD be implemented in a way that it can be ignored by assistive  
> technology.".
> [The internet](https://www.w3.org/WAI/tutorials/images/decorative/)  
> says, that alt-text for purely decorative images should be set to  
> empty, which seems to be the implementation of that abstract  
> guideline requirement.
>
> Also, this change violates rule  
> [`symbol.icon.accessibility.1`](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/Symbol/Factory.php#L49) which requires the aria-label that you are about to remove. The rule might be outdated or require adjustment, however, if so, we need some proposal of a change. Maybe @atoedt can provide a such. As far as we understand, these rules are supposed to be tested on the actual KS elements by some humans some day (We think @fab-kru is working on this) and this would just lead to a new bug report then if we make this change without adjusting the  
> rule.
>
> However, we see the need to get ILIAS up to speed to pass the  
> according test tool. So let’s tackle this:
>
> Question:
> - [ ] Aria-Label: Why did you remove it?
> - [ ] Alt-Text: They are needed, since we use the img tag, correct?  
> Is this a strict rule, that every img tag must also use an alt-text,  
> that is followed by those test-tools?
>
> Proposed changes, if you not agree, please explain why:
> - [ ] Alt-Text II: Set the alt-text to "" on the image to signal  
> that is is decorative.
> - [ ] Aria-Label II: If removing is really the way we want to go,  
> then we should adapt the written rules, if not, please re-add.
>
> Best regards!
> @Amstutz and @klees
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ILIAS-eLearning/ILIAS/pull/2518#issuecomment-591483952


-- 
leifos GmbH
Alexandra Tödt
Wilhelmstrasse 56-59, 50733 Köln
Tel: +49.221.12071890

toedt@leifos.com

Gesellschaft mit beschränkter Haftung
Sitz der Gesellschaft: Köln
Eingetragen beim Handelsregister Amtsgericht Köln (HRB 63686)

Geschäftsführer: Alexander Killing, Stefan Meyer, Alexandra Tödt

**Comment by atoedt** [comment]
Hello, 

the custom icon is an image and an image must have an alt-text and not an aria label. 
The normal icon is not image and is fine with the aria label. 

The custom image may be chosen for some specific decorative purposes but is should inherit the object type information. This way the important information "What is this? A Course? A Datacollection?" is kept. 
The approach to "harvest" the aria label vom the standard icon and make an alt text for the image of the customicon from it is great and very helpful.

**Comment by klees** [comment]
Hi @atoedt,

please give some arguments for your various propositions.

We do not propose to set no alt-text, but instead set the alt-text to "". This is completely in line with our [guidelines regarding decorative images](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/accessibility.md#guideline-text-alternatives) and the [tutorial from the w3 for decorative images](https://www.w3.org/WAI/tutorials/images/decorative/). We seem to agree that the image in the custom icon is indeed decorative.

From a non-technical perspective, it even seems to be potentially harmful if we use the aria-label for the alt-text of the image. On various occasions you argued that the interface as presented to sighted users should be similar to the one presented via assistive technology. Now imagine that some administrator changes his course's icon to be a planet for some styling reason. The icon still is (aria-)labeled as a course, although the icon now looks like a planet. With your proposal to just transfer the label to the alt-text of the image, the user with assistive technology would now be presented with an image of a course (what would that even be?), while the sighted user only sees a planet. With our proposal to set the alt-text to "", the surrounding div would still have the aria-label for a course, while the image would be understood to be decorative by the assistive technology (as of the source referenced above). We seem to agree, that the aria-label on icons is indeed the way to expose information about icon to assistive technology.

Best regards!

**Comment by alex40724** [comment]
The aria-label in the div is imo just a workaround for the **non-decorative** (type information) standard icons that are using background images. I basically moved the information to the alt text (for custom icons), because the image tag itself gives assistive technology a hint that some image is being used that may hold information.

I do not agree that the icons are decorative in both cases.

Of course admins can upload anything here, but if they are acting feasible, they try to include the same information (type) of the standard icons in their uploads. If not, I personally don't care.

But for users with assistive technology, my assumption is that an img with an alt text is better processible than a div with an aria label. Divs are not meant to hold non-decorative images as background-images (as the standard icons do).

Anyway, please close this if not acceptable.

**Comment by klees** [comment]
@alex40724 I see. Sorry that I'm so persistent here, but to me these this is not only about an acceptable solution, but about a coherent and comprehensible solution. And I just didn't understand why you introduced the alt-text to the custom icons but not the other icons.

Can you remember a specific reason why we used background images for the other icons in the first place? I'm pretty sure it's like this in the UI framework because it was like this before. Do you see any reason why we wouldn't want to use `` for the standard icons as well? Then we could move the aria-labels to alt-attributes altogether and change the according rule. I'll also ask @catkrahl about this.

Also I have a little budget left to work on accessibility issues, so if you have other things to do I can follow up here.

**Comment by alex40724** [comment]
@klees No, it wasn't this way before. The legacy icons in ILIAS are using img tags. Personally I was not so much involved in the KS Icon development, but afaik the main reason was that designers ask for backgroud images to be able to change the icons via CSS. I hope @Amstutz remembers.

**Comment by Amstutz** [comment]
@klees, @alex40724 is completely right, @nhaagen introduced standard icons as background in: https://github.com/ILIAS-eLearning/ILIAS/pull/547 

The reasoning was:

> This enables developers to use a default-icon with some text/abbreviation on it without actually creating an image. Designers can easily change icons via CSS.

I seem to recall that we agreed or even proposed that in the first place. Maybe @catkrahl can give some feedback, whether this reasoning still holds or whether we need to rethink that approach.

@alex40724 pointed in this discussion also towards the need of having custom icons with a path. He was right, and we introduced this second type. Therefore the two different implementation styles. 

Does this help?

**Comment by klees** [comment]
Yes, @alex40724 is right. I had a discussion with @catkrahl in the meantime, I'll summarize the results today. My initial confusion was caused by the different implementation styles, maybe we can (should?) align these. I'll be back soon.

**Comment by klees** [comment]
Hi everybody!

I did a lot of research and had some discussions with @catkrahl in the meantime and this is what I came up with.

To make sure where I came from: I was confused by this PR because it only adds `alt`-attributes to Custom Icons. While the Custom Icons use `` to implement the icon, Standard Icons use `<div>`s with `background-image`, where `alt` is not available and `aria-label` is used instead. As @alex40724 and @Amsutz correctly point out, the reason that Standard Icons use `background-image` instead of `` is that these indeed can be changed via CSS, while `` can't, and thus are easier changeblae for skin creators. I currently see no ultimate reason why we couldn't have implemented Custom Icons with the same `background-image` mechanism, but I might be missing something crucial.

Again: What appears to be odd (to me) is, that these two rather similar things are implemented in such different ways. This, however, may be visible to ordinary users as well. ConsidHi everybody!

I did a lot of research and had some discussions with @catkrahl in the meantime and this is what I came up with.

To make sure where I came from: I was confused by this PR because it only adds `alt`-attributes to Custom Icons. While the Custom Icons use `` to implement the icon, Standard Icons use `<div>`s with `background-image`, where `alt` is not available and `aria-label` is used instead. As @alex40724 and @Amsutz correctly point out, the reason that Standard Icons use `background-image` instead of `` is that these indeed can be changed via CSS, while `` can't, and thus are easier changeblae for skin creators. I currently see no ultimate reason why we couldn't have implemented Custom Icons with the same `background-image` mechanism, but I might be missing something crucial.

Again: What appears to be odd (to me) is, that these two rather similar things are implemented in such different ways. This, however, may be visible to ordinary users as well. Consider two courses in ILIAS, one with a Standard Icon and one with a Custom Icon some administrator uploaded. If for some reason the two images fail to load in a timely manner or at all, I would be presented with nothing for the Standard Icon but with an alternative text for the Custom Icon, without a way to tell why. Something similar might apply when using assitive technology, because accessibility information would be attached on different nodes in both cases. I think there are good reasons to **implement both, Standard and Custom Icon, with the same HTML structure and accessibility features**. This might also prevent some confusion in the future, be it for coordinators of UI frameworks or implementors of skins.

If one would want to follow the premise, we are left with two choices (if there are more, please say which): **We could use `` with `alt` for both Icons or we could use `background-image` with `aria-label` for both types of Icons.** So I did some research to find out if there is any way to alter the `src` of an image via CSS. There isn't. So if we would want to use `` we would need to set the `src` via rendering. I discussed the issue with @catkrahl and he seemed to be rather happy when I suggested to remove the images for the Icons from the CSS.

From another angle, the question whether we want to set the image via `src` in the HTML or the `background-image` in the CSS might be similar to the question *Does the icon convey information or is it purely decorative?*. At first I was in the *decorative* camp, but @alex40724 convinced me, that this is not the case. The icons might not add much in in the titles of a page, but they are an important information e.g. in the tree.

So I would suggest that we use `` with an `alt`-text for both Standard and Custom Icon. I can do the implementation if no one objects.

Best regards!


er two courses in ILIAS, one with a Standard Icon and one with a Custom Icon some administrator uploaded. If for some reason the two images fail to load in a timely manner or at all, I would be presented with nothing for the Standard Icon but with an alternative text for the Custom Icon, without a way to tell why. Something similar might apply when using assitive technology, because accessibility information would be attached on different nodes in both cases. I think there are good reasons to **implement both, Standard and Custom Icon, with the same HTML structure and accessibility features**. This might also prevent some confusion in the future, be it for coordinators of UI frameworks or implementors of skins.

If one would want to follow the premise, we are left with two choices (if there are more, please say which): **We could use `` with `alt` for both Icons or we could use `background-image` with `aria-label` for both types of Icons.** So I did some research to find out if there is any way to alter the `src` of an image via CSS. There isn't. So if we would want to use `` we would need to set the `src` via rendering. I discussed the issue with @catkrahl and he seemed to be rather happy when I suggested to remove the images for the Icons from the CSS.

From another angle, the question whether we want to set the image via `src` in the HTML or the `background-image` in the CSS might be similar to the question *Does the icon convey information or is it purely decorative?*. At first I was in the *decorative* camp, but @alex40724 convinced me, that this is not the case. The icons might not add much in in the titles of a page, but they are an important information e.g. in the tree.

So I would suggest that we use `` with an `alt`-text for both Standard and Custom Icon. I can do the implementation if no one objects.

Best regards!

**Comment by klees** [comment]
We implemented the "use -tag for all icons"-approach in #2639. So I think this can be closed.

Thanks @alex40724 for unearthing this problem.

**Pull request closed without merging**
