### PR TITLE
Refinery: include GreaterThanOrEqual to Refinery -> Integer. Add test…

### PR DESCRIPTION
**Pull request by lukastocker**
…s for constraint and new language variable for constraint message.

You could use GreaterThanOrEqual (instead of GreaterThan) in e.g. StudyProgramme to check if the input is greater than or equal 0 instead of "-1". See:
https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/Modules/StudyProgramme/classes/class.ilStudyProgrammeAssessmentSettings.php#L94

### CODE REVIEW

**Review by mjansenDatabay — CHANGES_REQUESTED** [review]
Hi @lukastocker 

thanks for your contribution to the ILIAS `Refinery`.

Please implement the following changes:
- [ ] PSR-2 Coding Style: Please use the`php-cs-fixer` to apply our coding style to the changed PHP files. There are at least two files with a missing linebreak at the end of the file.
- [ ] PHP Types: Please use the `void` return type declaration where appropriate.
- [ ] Strict PHP Types: Please use the `declare(strict_types=1);` directive in every PHP file.
- [ ] Translations: Please add a new translation for the `en` language file.

Best regards,
@mjansenDatabay

**Comment by lukastocker** [comment]
Hello @mjansenDatabay ,

thank you for your great review. I implemented your requested changes and included also the changes to the study programme module. 

Kind regards,
@lukastocker

**Review by mjansenDatabay — APPROVED** [review]
LGTM, thanks @lukastocker 

@klees I'll merge this, the change in the `StudyProgramme` is trivial, I hope this is okay.

**Comment by klees** [comment]
@mjansenDatabay Of course. Thx!

**Pull request merged**
