### PR TITLE
UI: This fixes the latest findings of PLR Tests

### PR DESCRIPTION
**Pull request by nhaagen**
- no more blank tools
- meta-more behavior
- equally distributed buttons in horizontal bar
- erroneous outlines for close tool
- reload on orientation change
- mobile locator arrow toggle
...

### CODE REVIEW

**Review by klees — COMMENTED** [review]
LGTM in general (and thx for the hard work on this). But: Please set the removal of this `for_ui_demo` stuff on the roadmap. I understand why we need it atm, but this is not good.

One other question: Why do we want the More-Button on the public interface of the Main Bar? Couldn't we just create it internally? Is there any need for consumers to set another?

**Comment by Amstutz** [comment]
Hi @nhaagen 

Thanks a LOT for the various fixes. Not that this includes some changes of the interface of page component. Technically we have to let that being approved by the JF before merging. However, due to the critical timeline of the Page Component, we can merge it. If there are objections by the JF towards one of the changes, we would need to revise this obviously.

@klees : Are you fine with that? If so, you may merge immediately, after resolving the conflicts and fix whatever @klees will point out additionally.

**Comment by nhaagen** [comment]
The idea behind the public more button is customization - you might like to change the symbol or text of the button.

**Comment by klees** [comment]
@Amstutz I'm fine with that.

@nhaagen Please remove the "More Button" from the public interface. Changing the text imo would need to be an issue of lng, the symbol of the CSS.

**Comment by klees** [comment]
This would also bring down the interface change for the JF to one method.

**Comment by Amstutz** [comment]
Since we just discussed this PR in the weekly, note; I am fine with merging, as soon Richards Comments are worked in and the conflicts are resolved.

**Comment by Amstutz** [comment]
I am looking forward to those changes ;-) any update?

**Comment by klees** [comment]
Nils is away atm, I will try to take care of this asap.

**Comment by klees** [comment]
Hoi @Amstutz, I adjusted this to the best of my knowledge. Please be so kind and look into this with due diligence again before merging. Don't want to be the one that breaks the prototype tomorrow =)

**Comment by klees** [comment]
Hmm, will fix the tests. Thx Travis.

**Comment by klees** [comment]
Done.

**Review by Amstutz — CHANGES_REQUESTED** [review]
Hi @klees 

Thanks for the effort. However, this currently breaks the layout in various places. Checkout just a few pages after login in, it will be obvious. However I was not able to track down what causes the various problem.

Needs some fixing

[Edit:] Recompiling the delos.less fixed most of the obvious issues. Please recompile and checkout if the results are as intended. Probably something got messed up while resolving issues in delos.css?

**Comment by klees** [comment]
Thx @Amstutz, I thought I did, but obviously didn't. Now delos.css is freshly compiled from delos.less.

**Comment by Amstutz** [comment]
Hi @klees , 

Much better. However, there are still two (probably related) issues, preventing this from merging:

- [ ] The "Tools Bulky Button" got Labeled "Moore"
- [ ] On small screens, if "Tools" (know labeled more) is active, the other Buttons are shifted so far to the right, that most of them disappear.

As soon as those two issues are fixed, feel free to merge. I am sure there are more things popping up. However, we will tackle them iteratively.

**Comment by klees** [comment]
Hmm, its labeled "More" for me (not "Moore"), its only labeled as such in the integration (not in the demo in the KS) and its also labeled as such ("More") in the trunk. I think we want to remove the possibility for KS-consumers to define their own "Tools"- and "More"-Buttons for the mainbar. I have already put the "More Button" on the ROADMAP.md. Should we do the same for the "Tool"-Button?

The shifting button is a similar problem: In the integration, the current content of the Tools is some panel (?) which seems to have some minimum width. We will have some constraints on the content of the slates and "having a defined width that fits on mobile screens in portrait" will be definitely one of them. If I remember correctly, @catkrahl said this will be something like 480px. I cannot see how we would deal with arbitrarily wide content in slates. Scrolling in the slates already causes enough pain in the vertical direction, from ux and technical perspective as well. I would rather think that we need to enforce constraints (be it hard via UI-components or soft via bug reports) on the content of the slate.

**Comment by Amstutz** [comment]
1. Oke, to your proposal, sry, moore was a typo of mine ;-)
2. Not sure if we talking about the same behaviour, I mean this (ignore my weird custom labels):

Inactive (i.O.):
image
Active:
image

**Comment by klees** [comment]
Yes. This screenshot is from the integration, right? The tools in the integration currently contain a wide text (I think its because it is preformatted) that defines the width of that mainbar div that in turn is used to calculate the placing of the buttons in the toolbar (via js). I think we could put a max-width somewhere in there, but we definitely also need content in the slates that can deal with a undefined width.

I need to go back to @catkrahl with that, so we are left with: merge this now with imperfection or wait until next weak.

**Comment by Amstutz** [comment]
thx for the feedback. I merge it, since it is overall a big improvement.

**Pull request merged**
