### PR TITLE
LDAP: Don't use an LDAP server as authentication mode if it is define…

### PR DESCRIPTION
**Pull request by mjansenDatabay**
…d as a data source

Mantis: https://mantis.ilias.de/view.php?id=31697

### CODE REVIEW

**Comment by smeyer-ilias** [comment]
@mjansen As mentioned in ticket mantis 31697, there are scenarios (SSO with Apache authentication), which - in my opinion should allow the LDAP authentication even if it used as "Data Source". 

I changed the assignment to the maintainer of authentication service.

**Comment by chfsx** [comment]
Hi @pascalseeland 

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the ressources to look into it in detail.

Best regards!

**Comment by klees** [comment]
Hi @pascalseeland

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the ressources to look into it in detail.

Best regards!

**Comment by oliversamoila** [comment]
Hello @pascalseeland, please give us feedback on this PR.

**Pull request closed without merging**
