### PR TITLE
Block: Fixed abstract static method declarations (E_STRICT error)

### PR DESCRIPTION
**Pull request by mjansenDatabay**
https://mantis.ilias.de/view.php?id=23673

### CODE REVIEW

**Comment by alex40724** [comment]
These notices should have been removed in PHP7
https://wiki.php.net/rfc/reclassify_e_strict ("Abstract static methods")

**Comment by mjansenDatabay** [comment]
Yes, the error message is only valid for PHP 5.x . Nevertheless, we should get rid of statics if it is possible in general (which is the case here).

**Comment by alex40724** [comment]
I agree, but this makes it an "improvement" instead of a "bugfix" imo.

**Comment by alex40724** [comment]
Thanks, you can merge the leifos code related changes anytime. I think @klees  is involved here,too (studyprogramme).

**Review by klees — APPROVED** [review]
LGTM for StudyProgramme.

**Pull request merged**
