### PR TITLE
Fixed lineendings for ui component progressmeter

### PR DESCRIPTION
**Pull request by qdittrich**
Changed lineendings for ui component "progressmeter" from CRLF to LF.

### CODE REVIEW

**Comment by qdittrich** [comment]
The remeining error is pointed to "ilTermsOfServiceTableDataProviderFactoryTest::testExceptionIsRaisedWhenAgreementByLanguageProviderIsRequestedWithoutCompleteFactoryConfiguration". This seems to come from the ilLanguage. On my local installation I also cannot run the phpunit tests because of errors in ilDB and ilLanguage classes.
Can anybody confirm this issues?

**Comment by klees** [comment]
Hi @qdittrich, yes, I can. I'll device a fix and pass it to @fneumann.

**Comment by klees** [comment]
Created a PR: https://github.com/ILIAS-eLearning/ILIAS/pull/1174

**Comment by klees** [comment]
Thx!

**Pull request merged**
