### PR TITLE
Default for online status after copying an object

### PR DESCRIPTION
**Pull request by fwolf-ilias**
This Pull-Request affects the following modules:
Bibliographic, BookingManager, Cloud, Course, DataCollection, Glossary, HTMLLearningModule, LearningModule, MediaCast, Poll, Scorm, Survey, SurveyQuestionPool, Test, TestQuestionPool and Wiki

For further informations visit the Feature Wiki Page http://www.ilias.de/docu/goto_docu_wiki_wpage_3515_1357.html
Discussed on JourFixe, Aug 31, 2015.

### CODE REVIEW

**Comment by alex40724** [comment]
Looks ok for my code. Thanks!

**Comment by bheyser** [comment]
Test / TestQuestionPool Changes Approved ;)

**Comment by chfsx** [comment]
looks ok for DataCollection, Bibliographic and Cloud

**Comment by jluetzen-ilias** [comment]
BookingManager, Poll, Survey, SurveyQuestionPool approved.

**Pull request merged**
