### PR TITLE
BT-28563: Removed link from images in search results

### PR DESCRIPTION
**Pull request by M-Barz**
Link to Mantis-Report:
https://mantis.ilias.de/view.php?id=28563

### CODE REVIEW

**Review by smeyer-ilias — COMMENTED** [review]
Have you checked the lucene search, too?

**Comment by M-Barz** [comment]
Both direct and Lucene search don't have Links in their images anymore with this change

**Review by smeyer-ilias — APPROVED** [review]

**Comment by smeyer-ilias** [comment]
Thanks Marvin. 
Please merge to the affected branches

**Comment by klees** [comment]
Hi @M-Barz,

could you be so kind and use a private fork of this repo to manage your bug fixing branches and open the PRs from there?

Thanks!

**Pull request merged**
