### PR TITLE
Update Dependencies after Release v7.25

### PR DESCRIPTION
**Pull request by fwolf-ilias**
Dear @ILIAS-eLearning/technical-board,
This PR updates all dependencies after release v7.25.

**Composer Notices:**
```
Could not apply patch! Skipping. The error was: Cannot apply patch ./libs/composer/patches/tcpdf.patch

Package imsglobal/lti is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/simplesamlphp-module-sanitycheck is abandoned, you should avoid using it. No replacement was suggested.
Package simplesamlphp/twig-configurable-i18n is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package technosophos/libris is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```

### CODE REVIEW

**Comment by fwolf-ilias** [comment]
!!! As this dependency update seems to break one of our composer patches I would suggest to wait until a fix is available.

Edit: I reported this issue to mantis [#37942](https://mantis.ilias.de/view.php?id=37942)

**Comment by mjansenDatabay** [comment]
The branch [fwolf-ilias:composer/release_7/v7.25](https://github.com/fwolf-ilias/ILIAS/tree/composer/release_7/v7.25) has to be rebased on `release_7`, the patch should work now.

**Comment by fwolf-ilias** [comment]
@mjansenDatabay Thank you very much.

**Comment by kergomard** [comment]
Thank you very much @fwolf-ilias  as always. The composer updates ran and I could access ILIAS after this, so I will merge.

**Pull request merged**
