### PR TITLE
[Docu] DevTutorial: Text Proposal UI Component

### PR DESCRIPTION
**Pull request by thibsy**
Hello future readers, 

This PR provides a text proposal for the dev-guide in form of a tutorial for contributing to the ILIAS UI framework.

@Amstutz and I have decided to keep the tutorial brief, giving merely an overview of the process, and keep the actual tutorial as close to the source code as possible. Thats why we have cross-referenced sections of the documentation between the development guide and the framework.

Kind regards,
@thibsy

### CODE REVIEW

**Review by Amstutz — APPROVED** [review]
looks good

**Comment by acgruber** [comment]
Hi @thibsy,

As promised in our last meeting, here’s the feedback to finalize this PR:
The tutorial’s directory has been created for trunk, including placeholder mds with the sorted numbering we’ve discussed. You can find the respective .md you should use for this PR here: docs/development/devguide/tutorial/05-contributing/03-ui-component.md
Please move your text to this file. I will then happily merge :)

Optional if possible: We’ve also defined a standardized naming for PRs concerning the tutorial: „[Docu] DevTutorial: Text Proposal (topic)“ - so in your case: „[Docu] DevTutorial: Text Proposal UI Component“. If it’s possible to rename this PR easily, please do as it would be a nice reference for future PRs. But no worries if not. Not mandatory for merging.

Thanks and cheers!
Ann-Christin

**Comment by dsstrassner** [comment]
Hi @acgruber, renaming a PR is easily possible in GitHub. You only need to click on the Edit Button besides the title:

image

**Comment by thibsy** [comment]
Thx @acgruber, this should be good to go now.

**Pull request merged**
