### PR TITLE
release_5-1: More obvious typos Excpetion vs Exception

### PR DESCRIPTION
**Pull request by level420**
Again detected via eclipse PDT during validation.

This time I'm omitting the PR for the release_5-2 branch

### CODE REVIEW

**Comment by level420** [comment]
@klees I'm just curious: why is this PR not labeled a bugfix but an improvement?

**Comment by Amstutz** [comment]
For a bugfix you need a mantis report with an particular ticket reference. See: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/documentation/contributing.md

> If your PR contains a bugfix please reference the number of the mantis ticket in the title 12345 - To many spaces, link the ticket in the description and label the ticket with bugfix. You may make one PR per affected branch.
> 
> Please label non-bugfix PRs as improvement.

Thanks for your contribution.

**Comment by level420** [comment]
I see. Thank you @Amstutz

**Review by chfsx — APPROVED** [review]
For my part ok, thanks a lot @level420! After @smeyer-ilias gave his ok we will merge it and patch to other supported versions of ILIAS.

**Comment by smeyer-ilias** [comment]
Thanks, merged.

**Pull request merged**
