### PR TITLE
T&A Bugfix #0037191: Errors in Formula Question

### PR DESCRIPTION
**Pull request by fhelfer**
https://mantis.ilias.de/view.php?id=37191
and some more errors

### CODE REVIEW

**Comment by kergomard** [comment]
Thank you very much @fhelfer for this PR!
Could you please do me a favor and replace this now really complicated checks with values from `$this->request`? I think we might simplify the code quite a bit.

Let me know, if I'm missing something.

Thanks again and best,
Stephan

**Review by kergomard — COMMENTED** [review]
Hi @fhelfer 
Thank you very much for adapting the PR!
- The `$_POST` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5836/files#diff-dbe5672777bfad9a1a05af97b082ba87fa5bf0ef626f38bf3ca0ed18e2ba90c3R183) seems to be wrong, or am I missing something?

Thanks again and best,
@kergomard

**Comment by fhelfer** [comment]
> Hi @fhelfer Thank you very much for adapting the PR!
> 
> * The `$_POST` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5836/files#diff-dbe5672777bfad9a1a05af97b082ba87fa5bf0ef626f38bf3ca0ed18e2ba90c3R183) seems to be wrong, or am I missing something?
> 
> Thanks again and best, @kergomard

Thanks fixed it

**Comment by kergomard** [comment]
Thank you very much @fhelfer ! I'll merge and cherry-pick zu 8.

**Pull request merged**
