### PR TITLE
Setup/Data: Fix minor version compare

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=38002

If approved, this has to be picked to `trunk`.

### CODE REVIEW

**Review by klees — CHANGES_REQUESTED** [review]
Hi @mjansenDatabay,

would you be so kind a write an automated test for the issue?

Thanks!

**Comment by mjansenDatabay** [comment]
@klees 

1) I fixed the license header
2) I added a new case in the data provider (and provided names for the cases as well)
3) I fixed the checks by adding negated assertions with the corresponding inverted method call.
4) I used `version_compare`, I did not see any reason why the versions are compared manually

**Comment by klees** [comment]
@mjansenDatabay I didn't use `version_compare` because it felt a little to obscure for me. But since all tests still pass I'm actually fine with it now =)

Thanks for the other improvements.

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Picked to trunk!

**Pull request merged**
