### PR TITLE
Timings/Activation: Properly transform object title in legacy form title

### PR DESCRIPTION
**Pull request by mjansenDatabay**
See: https://mantis.ilias.de/view.php?id=40996

If approved, this MUST be picked to `release_9` and `trunk` as well.

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Hi @smeyer-ilias , do you have any objections here? I highly recommend merging this (or providing another solution).

**Comment by smeyer-ilias** [comment]
LGTM, but I assign it to @kergomard, since this is a Services/Object related change.

**Comment by mjansenDatabay** [comment]
Thx for having a look @smeyer-ilias

**Comment by kergomard** [comment]
Thank you very much @mjansenDatabay for looking into this! This is not the the issue in the report, but it also is an issue! As far as I can see this is ILIAS 8 only.

**Pull request merged**
