### PR TITLE
Skill: Refactor deprecated update steps using Objectives

### PR DESCRIPTION
**Pull request by tfamula**
Follow-up of #5075
When approved, this needs to be cherry-picked to release 8.

### CODE REVIEW

**Review by klees — APPROVED** [review]
Hi @tfamula!

This looks good. The interfaces to the RBAC objectives definitely work now IMO, as demonstrated by your usage. I only have one change request:

- [x] Pass `$db` [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR76), [there](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR80) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR83).

I will assign this PR to @smeyer-ilias since he currently maintains Services/AccessControl, which this is mostly about.

Best regards!

**Comment by tfamula** [comment]
Hi @klees, thanks for your feedback!

> - [x] Pass $db [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR76), [there](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR80) and [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/files#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR83).

You mention a very interesting thing here. I found out that passing the database for the static methods of `ilRbacReview` and `ilObject` are **not** essential while they are called in the `achieve()` method of the Objective. The update command in the setup does not produce an error for me. It is different for the `isApplicable()` method of the Objective. When I would not pass the database (like [here](https://github.com/ILIAS-eLearning/ILIAS/pull/5123/commits/ab80fa14cf68accee667190dd815de0b77dfb16f#diff-fe0db81252e44d673286cdf327467046ded52727538ceff3e56c5864d3f951cfR86)), I would get errors which remind me that there is no database. Do you know why `achieve()` and `isApplicable()` act different here?

Nevertheless, I added the database at the places you mentioned, so we are on the safe side. Please also note that I found a few more places where this makes sense in this context, see https://github.com/ILIAS-eLearning/ILIAS/pull/5123/commits/e827aa07c19a5e01bc5f223dbd10b4163c5a4b0c.


Greetings
Thomas

**Review by smeyer-ilias — APPROVED** [review]
Thanks. The changes are fine for me.

**Comment by iszmais** [comment]
LGTM :+1:

**Review by iszmais — COMMENTED** [review]
LGTM :+1:

**Review by iszmais — COMMENTED** [review]
LGTM :+1:

**Comment by klees** [comment]
Hi @tfamula,

the behaviour you describe seems to be caused by lucky circumstances: Somehow the DIC or globals end up to contain `ilDB`, but the code it not explicitly arranged to guarantee that behavior. So passing `ilDB` explicitly will be much more robust.

Best regards!

**Comment by tfamula** [comment]
Hi @klees 
I see...thanks for the answer!

**Comment by tfamula** [comment]
@klees
One more information for you:
After merging this PR, I got quick feedback from two reporters in Mantis that there was another error regarding missing database in the update steps of the skill management. I detected the problem and used the `ilTreeAdminNodeAddedObjective` to fix it. By doing this, I found out that the Objective is faulty in some places. I changed the Hash which was not unique before and led to unexecuted Objectives. Moreover, I added a new (optional) parameter to the Objective, which must be provided IMO.
I have not created an extra PR for these changes and commited them directly to fix the bug for skills as fast as possible. Please check https://github.com/ILIAS-eLearning/ILIAS/commit/3339b9236c62f580420ff8a9626d5bca5dc62087 and https://github.com/ILIAS-eLearning/ILIAS/commit/532c07e9b470363d0d0fcbe43101b1d301ce24ea. If you have any objections, please let me know.

**Comment by klees** [comment]
Thx @tfamula, very nice =)

Pinging Tree-maintainer @smeyer-ilias as well...

**Comment by tfamula** [comment]
Stefan was already made aware of the changes by me ;)

**Pull request merged**
