### PR TITLE
Update maintenance.md

### PR DESCRIPTION
**Pull request by fab-kru**
AntoniaWeber is not working at Uni Cologne anymore. Testing is done by Alexander Baulig.

### CODE REVIEW

**Comment by fab-kru** [comment]
By the way, if this isn’t the proper way editing of this file should be done, please let me know how to proceed. I don’t want to interfere with "real" development.

I would also suggest to connect this md file here: http://www.ilias.de/docu/goto_docu_pg_9985_42.html - So we only have to update it at one place.

**Comment by klees** [comment]
Hi @chfsx,
did we lose the possibility to update that directly when introducing that script for the maintenance.json? Could you tell Fabian what to do instead?
Best regards!

**Comment by chfsx** [comment]
Hi @fab-kru and thanks for the changes. We are currently building up this new collection of information who maintains what. there is a Script for developers which can be used to automatically generate the maintenance.md based on information in every sub-directory of /Services and /Modules. 

You can try to use it, a description is written here: http://www.ilias.de/docu/goto_docu_frm_5386_4359.html

If it doesn't work or you do not find the time to set it up, I'll change it. 

We will have a look at the process how to propose changes in the future without using the script.

**Comment by fab-kru** [comment]
Hi @chfsx, unfortunately I didn’t find the time to learn using the script yet. That said, I’m afraid the automated process doesn’t quite cut it yet. Looking through maintenance.md, I encountered several issues. Some of them might reflect recent changes, some of them concern our manual list, but most of them seem to be real gaps here on GitHub.

My findings: [Maintainer GitHub versus Docu Mai 2017.xlsx](https://github.com/ILIAS-eLearning/ILIAS/files/1021969/Maintainer.GitHub.versus.Docu.Mai.2017.xlsx)

In the future, I would definitely be willing to learn using the script if that’s the best for you. If you believe that other people (apart from maintainers and PM) should be able to make fast changes, I’d also be open to an alternative change process of course.

EDIT:

One more thing: Matthias commented to me that another issue is the divergence of the official names of some of the components from the names of the directories. We would love to only use this single list in the future, but for that it would need to be at least clearly legible for community members and first-time visitors. The only alternative would be to keep maintaining multiple lists, which would cause even more trouble. 

Unfortunately I don’t have a great solution at hand, but it would be good if we could collaborate here in order to find a solution that also works for the /docu page I linked above.

**Comment by chfsx** [comment]
Hi @fab-kru 
Thanks for your lists with maintenance-infos and the differences to github (which are mainly related to the fact that not all maintainers have filled out the information at the moment).

I updated many of the maintenance.json file {maybe @smeyer-ilias, @alex40724 @mjansenDatabay  could have a loot at the latest version of the maintenance.md if I did wrong with some information): https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/documentation/maintenance.md

I also included the latest version of the maintenance.md in the Development Guide: http://www.ilias.de/docu/goto_docu_pg_9985_42.html

And I think it would be a good idea to have a look at some Component-names and also if there are more components that currently in the dev-guide. Feel free to contact me (e.g. via Skype) to coordinate our next steps.

I close this PR since the fix has been applied (Antonia Weber -> Alexander Baulig)

**Pull request closed without merging**
