### PR TITLE
WIP Feature/trunk/ilias with cqrs components

### PR DESCRIPTION
**Pull request by mstuder**
With this pull request I like to open a discussion about the _Internal API Alignment_, _cqrs/ddd_ and microservices. This request is WIP - I hope i will finish this conceptual work within the next two weeks.

See Readme:
https://github.com/studer-raimann/ILIAS/tree/feature/trunk/ilias_with_cqrs_components/vendor/ilias/IliasComponentCourse

### CODE REVIEW

**Comment by mbecker-databay** [comment]
Hello Martin!
I have to admit that I don't really get my head around this right now, but if you can prepare a few minutes to explain this concept, I'd be glad to give you proper airtime about this proposal in our Internal API Alignment workshop later today, 27 MAY 2019, 13:00-15:00. [Skype Conference](https://join.skype.com/nTFqPJGccWeI) Hope to see you there! Cheers, ~Max

**Comment by mstuder** [comment]
Thx Max! I will!

**Comment by alex40724** [comment]
@mstuder Thanks a lot for this. I especially like the idea of the command bus. I have the feeling that this might be the core of what we need.

**Comment by mstuder** [comment]
Indeed! Especially the concept that is possible to add n-middlewares globaly for all comand bus or whithin in addition in own contextes if you are the initator of the bus - e.g. in Dev-Mode a logging-Middleware / or in coorporate context an audit middlware which writes to a database table. 

But this work only perefect, if the mutual command call from one the another module is acting in each case per command bus. Like this you could integrate in one step new global guideline. You only has to integrate a new middlerware.


https://github.com/studer-raimann/IliasComponent/blob/dev_mst/src/Context/DomainModel/Event/AbstractEventBus.php

https://github.com/studer-raimann/IliasComponent/blob/dev_mst/src/Context/DomainModel/Event/EventBusMiddleware.php

**Comment by alex40724** [comment]
I am not sure if the "value vs. complexity" ratio of middlewares is high enough to include this in a first implementation. Of course logging is a use case, but not the most important issue to solve right now imo. More important parts like policy enforcement should not go to a middleware.

**Comment by mstuder** [comment]
Dear @alex40724 

You're probably right. I close this pull request because i made a concrete one for the Assessment Question Service
https://github.com/ILIAS-eLearning/ILIAS/pull/1931

There i will describe the concrete implementation of the cqrs and ddd pattern. For those concrete patterns it's a good way to connect a command with his command handler without the fear to get knocked out by the ctrl-flow (see also https://matthiasnoback.nl/2015/01/a-wave-of-command-buses/) of ILIAS. And it could a good way to have the possibility to use event buses for eventsourcing (
image.

But both use cases are the concrete usage to solve a concrete own problem in the developers own module. But it could a way to describe the usage of those patterns and to ensure, that when a developer go way of cqrs and ddd he uses the same tools.

**Pull request closed without merging**
