### PR TITLE
Implemented Avatar

### PR DESCRIPTION
**Pull request by chfsx**
this PR replaces #2447 after I recreated the branch and could not reopen the old PR (which seems to be a new behaviour in Github)

### CODE REVIEW

**Comment by chfsx** [comment]
Hi @Amstutz ! May I ask you to have a Look at this? Thanks in advance!

**Review by klees — CHANGES_REQUESTED** [review]
Hi @fschmid,

first, sorry for letting you waiting quite a bit with this. @Amstutz holidays did not help a speedy review here. Nevertheless, that took (too) long.

Then, thanks for throwing in some refactoring of the `ilObjUser` class by factoring out the Avatar Resolver stuff. You removed lines 3772 - 3841, that pretty much says it all. For future refactorings it would be really neat to move the DIC dependencies into the constructor to get rid of this dared global key word inline. However, kudos for factoring this out already, the rest here is for another day.

The points listed in https://github.com/ILIAS-eLearning/ILIAS/pull/2447 seem to have been taken care of. Thx for that. This looks nice and clean.

Still, please implement the following super minor changes:
- [x] smount_od: We might be missing some point here, but the variable name `$smount_od_colors` reads like a typo. Please change it =)
- [ ] JavaScriptBindable: Please implement `UI\Component\JavaScriptBindable` where you use `UI\Component\Implementation\JavaScriptBindable`. This `trait`/`interface` combination effectively acts as a way to implement something that might be called a `mixin` in some other languages.
- [x] `getRandom26StringsForAllColorVariants`: Make `AvatarTest::getRandom26StringsForAllColorVariants` a non-static method. Also: Why does it return a closure? Can't you remove that internal closure you return and `yield` the values from `getRandom26StringsForAllColorVariants` directly?

Concerning your feedback in https://github.com/ILIAS-eLearning/ILIAS/pull/2447:

>> Split tpl.avatar.html into two files. This is easier to read and customize. E.g. il-avatar-{MODE} is an issue for designers.

> Done. There is a new rule every time, which I don't know ;-)

We do not think that we really need, want or even could have a rule for everything. There has been much complaint about code quality in the ILIAS source. We try to make it better here by thoroughly vetting new code. Different opinions regarding specifics obviously might arise. This is just natural and even a good thing about detailed code reviews. Developers start to discuss patterns, styles and good practises, which makes the overall project more consistent. No one of us can be expected to think about or find everything anytime on their own, room for improvement is to be expected in every piece of code we write. A second pair of eyes just helps to uncover that potential and make our shared code base a little better. Coding here is more like an art form or craftmanship, where we can constantly improve and learn from our own experience and our fellows input instead of blindly following a fixed set of rules. Note, that people also will try to learn from code that we already have. So today's "Don't be nitpicky!" might be tomorrows "I thought this would be the recommended way to do it?".

> The PHPStorm Templates should be adjusted, so that you can use them. This is otherwise very annoying. I have now undo the changes manually.

Completely ack. @gvollback is working on that.

>> Rename AbstractAvatar to just Avatar. We don't use that Abstract` nomenclature in the UI framework.

> Done. Still find the PSR Naming Conventions the better ones: https://www.php-fig.org/bylaws/psr-naming-conventions/

Note that you point to the bylaws of the FIG. This is not a naming convention they propose for other peoples real code but instead a convention for the PSRs they write. These just have other requirements then the actual code that we are writing and thus naming conventions for PSRs are hardly applicable for us.

On the contrary: [Uncle Bob](https://cleancoders.com/) gives a really nice explanation why **not** to use `Interface` or `Abstract`-suffixes in it’s reasoning on the [Interface Segregation Principle](https://cleancoders.com/video-details/clean-code-episode-12). Unfortunately its behind a pay wall, contact @Amstutz if you want details, he really recommends watching it.

The reasoning is along the lines, that interfaces are basically a special form of abstract classes needed, due to the fact that we do not have multiple inheritance. They (both) should be named according their functionality and be tightly coupled with the class the have a tight logical binding. In his example he uses switch and light. The switch can turn on the light. He proposes to pass an interface to switch instead of passing the light directly, so we could switch other things on and off as well. If we use your prefered naming convention, it would be very tempting to name the interface `LightInterface`, since light will implement it in the first place. Over and done. However, he claims this (or `AbstractLight`) to be a bad name, and I can follow this reasoning. The interface has a tight logical coupling the the switch. A much better name is „Switchable“. `SwitchableInterface` or `InterfaceSwitchable` or `AbstractSwitchable` or `SwitchableAbstract` just add noise to that name. Is it much simpler to read `Light implements Switchable, Dimmarable, Colorable` than `Light implements SwitchableInterface, DimmarableInterface, ColorableInterface`. We already know that these are interfaces when reading `implements`. 

> But well, rules are rules :-). Done

Yes, some rules are anoying. We did not a agree on all the rules as well, but at some point, its just, pick one option and stick with it (e.g. number of lines etc.). Maybe some hero could provide some automatism that performs this formatting to remove the pain.

We hope this is valuable and helpful, thx for the feedback and most importantly, for the contribution. If you disagree with any of our more general points, we are very much interested to hear your opinion. Also, we might want to take these discussions elsewhere, as they are worthwhile to have and also should concern a greater audience than us three.

Best regards
@Amstutz and @klees

**Comment by chfsx** [comment]
Hi @klees and @Amstutz 

Thank you very much for the feedback and also your points on the off-topic discussion topics.

To get ahead with the Avatar, I can't go into it any further.

two of the three points above I could already do (push will follow soon).

> JavaScriptBindable

I'm afraid I'm lost on this one.

Currently, in `\ILIAS\UI\Implementation\Component\Symbol\Icon\Avatar`, the only place where I use `\ILIAS\UI\Implementation\Component\JavaScriptBindable`, I cannot implement the interface `\ILIAS\UI\Component\JavaScriptBindable` because it is implemented earlier. This is done through the inheritance of interfaces in `\ILIAS\UI\Component\Symbol\Symbol`. This passage was introduced by me, but even if I delete it, I think we have the following problem:

The UI component Avatar is defined via `\ILIAS\UI\Component\Symbol\Avatar\Avatar`. This interface inherits from `\ILIAS\UI\Component\Symbol\Symbol` and of course from `\ILIAS\UI\Component\Component`. M.E. belongs to `\ILIAS\UI\Component\Symbol\Avatar\Avatar`, so it also inherits from `\ILIAS\UI\Component\JavaScriptBindable`. This would look like this:

```
interface Avatar extends \ILIAS\UI\Component\Symbol\Symbol, JavaScriptBindable
```

But with this I could also implement `\ILIAS\UI\Implementation\Component\Symbol\Icon\Avatar` in the required place in `\ILIAS\UI\Component\JavaScriptBindable`.

``` 
abstract class Avatar implements C\Symbol\Avatar\Avatar, C\JavaScriptBindable
```

Would therefore not work and results in 

```
Class ILIAS\UI\Implementation\Component\Symbol\Icon\Avatar cannot implement previously implemented interface ILIAS\UI\Component\JavaScriptBindable
```

**Comment by chfsx** [comment]
Fun Fact: tests are running locally (???) I'll have a look at it again

-> did just run /tests

I fixed the Mock in LearningSequence-tests now

**Comment by klees** [comment]
>> JavaScriptBindable

> I'm afraid I'm lost on this one.

Your totally right, `JavaScriptBindable` is already implemented via `Symbol`.

Thanks @chfsx!

**Review by klees — APPROVED** [review]

**Comment by klees** [comment]
Hi @smeyer-ilias,

do you want to have a look into the changes in `Services/User`?

Otherwise i'll squash merge this.

Best regards!

**Comment by smeyer-ilias** [comment]
The changes in the User service are fine for me. 
I assigned @alex40724 since he is the author of the User/Avatar feature.

**Review by alex40724 — APPROVED** [review]
Hi @chfsx,

Thanks for taking care of this.

Well, we need a proper user service, but this is out of scope of this PR, of course.

Do you see an alternative to a consumer API like ilObjUser::_getAvatar($user_id)? E.g. by having an independent user avatar service that provides an API?

This is nice to have. I approve the current version, too.

kindly,
@alex40724

**Comment by klees** [comment]
Hi @chfsx,

I tried to cherry-pick this to trunk, but there seems to be stuff missing and tests fail. Maybe from the original Avatar-PR? I'll be in meetings for the rest of the day, so I won't have time to have a look today, if you could have a look sooner this would be much appreciated.

Best regards!

**Comment by chfsx** [comment]
yes I think the whole interface-stuff from the PR which has been accepted earlier is missing when you cherry-pick. I'll have a look at it and provide a PR for trunk as well

**Comment by Amstutz** [comment]
Hi @chfsx, No further PR needed, you may commit directly, since the complete implementation has been approved. just make sure all test pass and the set of commits is complete. thx a lot.

**Comment by chfsx** [comment]
Done for trunk: https://github.com/ILIAS-eLearning/ILIAS/commit/016077b60d4c4fa80f6b3f815b9be1c98c7c90b0

**Pull request merged**
