### PR TITLE
(bugfix#30156): delete the temporary html file after creation of PDF (PhantomJS and wkHTMLToPDF)

### PR DESCRIPTION
**Pull request by utesche**
Added unlink() after using the temporary file as input for PDF-Creation.
see mantis: https://mantis.ilias.de/view.php?id=30156

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
@gvollbach Any objections to merge this?

**Comment by kergomard** [comment]
Hi @gvollbach 

we stumbled upon this PR in our TB meeting. If you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by chfsx** [comment]
Hi @gvollbach 
As Technical Board, we regularly check for pull requests that have been open for a long time.
As the assignee, if you don't have any objections, please merge this PR or provide feedback otherwise.

Best regards!

**Comment by gvollbach** [comment]
@utesche Thanks!

**Pull request merged**
