### PR TITLE
Added 7.2 as PHP-Version on Travis

### PR DESCRIPTION
**Pull request by klees**
This will break tests because our code does contain PHP 7.2-related problems, but the tests run in general.

### CODE REVIEW

**Review by gvollbach — COMMENTED** [review]
@klees In general I support this change, but we will have broken builds until all problems will be fixed. It seems the most log lines come from the use of strings with assert(), which makes the log quite unreadable.

**Comment by klees** [comment]
I'm on it.

**Comment by klees** [comment]
The problems with `assert` are gone.

**Review by gvollbach — COMMENTED** [review]
@mjansenDatabay 
Seems like this are mostly "our" classes, I think we should fix this before we merge the pull request.

**Comment by mjansenDatabay** [comment]
@gvollbach @legionth I fixed the `Certificate` related issues.

**Comment by mjansenDatabay** [comment]
@gvollbach @klees WFLE and Certificate issues should be fixed (in `trunk` and `release_5-4`).

**Comment by mjansenDatabay** [comment]
PRs for `T&A` and `ActiveRecord` created ...

**Comment by klees** [comment]
@gvollbach Let's do this!

**Pull request merged**
