### PR TITLE
Forum: Tree in slate

### PR DESCRIPTION
**Pull request by legionth**
This PR will add the forum tree to the slate with its own implementation of the `TreeRecursion` so it is no longer dependent on the general implementation `ilTreeExplorerGUI`

### CODE REVIEW

**Comment by Amstutz** [comment]
Nice to see the new tools being used. :-)

Short note, why is there css, without corresponding less? Am I missing something?

**Comment by legionth** [comment]
@Amstutz this was rebased from a old development branch to the new trunk. I think this is not needed anymore. I'll check this.

**Comment by legionth** [comment]
Done. Ready for Review :)

**Comment by mjansenDatabay** [comment]
I think we should delete `./Modules/Forum/js/ilForumExplorer.js` because this will not be included anymore.

**Comment by Amstutz** [comment]
> I think we should delete `./Modules/Forum/js/ilForumExplorer.js` because this will not be included anymore.

Would be awsome, so we get a few lines closer to reducing LoCs with this refactoring, which is always neat:
image

:-) go go go.

**Pull request merged**
